### ISSUE TITLE
A parameter in body that is json has to be explicitly serialized

### ISSUE THREAD

**Issue by dwilson6** [swagger-api/swagger-js#1006]
I've noticed that if I have a POST endpoint with a parameter in the body that is of type object and I call that operation with the tags interface like client.apis.default.operation({param_name: {}}) (I explicitly set the Content-Type header to application/json), I get an error from my server: `unexpected token o in JSON at position 1...`

To get it to work, I have to serialize the value of the parameter explicitly `client.apis.default.operation({param_name: JSON.stringify({})})`.

Would it be reasonable to automatically convert an object to a string if the content type is application/json and it has an "in: body" parameter and the value of said parameter is an object?  

Also, if an api endpoint only has one parameter, what do you think about allowing you to call the operation with the interface `operation(value)` instead of `operation({param_name: value})`? If an operation only has one parameter, you could check if the argument passed to the operation is an object with a property matching the parameter name (existing behavior) and if not then just use the passed in argument as the value for the parameter (after validating the type).  Are there problems with that approach or does that make it too complicated?

**Comment by fehguy** [comment]
You are using the 3.x version I take it?  This is a regression

**Comment by dwilson6** [comment]
Yes, I am

**Comment by fehguy** [comment]
We'll get it addressed shortly

**Comment by buunguyen** [comment]
Fixed in https://github.com/swagger-api/swagger-js/pull/1034
