### ISSUE TITLE
missing tests against client over http

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#1007]
There are many tests taking in an object, but none that call a mock server and read specs via http

**Comment by webron** [comment]
@fehguy does #1008 close this one or more needs to be added?

**Comment by fehguy** [comment]
well, yes tons of tests are needed, and if you look, I've disabled many of them because the client actually fails.  So while there is _a_ test, there are probably 50 or so that should be ported from the old version into this class.  I suggest keeping this open

**Comment by shockey** [comment]
Closing as we're now only skipping five tests, and there are tests that set up a mock server (via `xmock`).
