### ISSUE TITLE
Unable to pass 'opts' for method invocation (swagger.js)?

### ISSUE THREAD

**Issue by cpedrinaci** [swagger-api/swagger-js#101]
Looking at the code it seems that things like choosing the response or request content types is specified by means of the 'opts' argument (SwaggerRequest).

The method 'SwaggerOperation.prototype["do"] = function(args, opts, callback, error)' does contemplate this parameter. It could thus be used directly via code, in principle.

However, the more convenient method 'this.resource[this.nickname] = function(args, callback, error)' seems to drop this parameter. 

Am I missing something? Is this the actual intended use or should the latter method be fixed to include the additional opts parameter?

**Comment by fehguy** [comment]
added along with tests
