### ISSUE TITLE
Default request Content-Type header and parameter in body as object

### ISSUE THREAD

**Issue by srihakum** [swagger-api/swagger-js#1010]
This issue is in further reference to https://github.com/swagger-api/swagger-js/issues/991

With version 3.0.5 a swagger client instance tries to make an API request the following issues are observed 
1. Content-Type header is not added in the request. 
2. If a parameter used in HTTP body is added to the request the client expects it to be in the string format.

However while using 2.0.32 there is no need to set these explicitly. So is there a way we can get back the old behaviour with latest version, like adding "application/json" as default content type and the adding body parameter as JSON object rather than string.

Code example:
```
var Swagger = require('swagger-client');
new Swagger({
    "url":"https://staging.cloud-elements.com/elements/api-v2/elements/44/docs"
})
    .then(function (client) {
        client.apis.zohocrm.createAccount({"Authorization":"...","body":{"Account Name":"XYZ1"}})
            .then(function(response){
                console.log(response);
            })
            .catch(function (error) {
                console.log(error);
            });
    }).catch(function (error) {
    console.log(error);
});
```

**Comment by dwilson6** [comment]
The content-type issue is documented in #995
The object serialization issue is captured by #1006

**Comment by camsjams** [comment]
Is 3.x stable? These issues create unexpected behavior and reduce the usefulness of this wrapper.

**Comment by webron** [comment]
Thanks @dwilson6. Closing this in favor of the other two tickets.
