### ISSUE TITLE
getOperationRaw() throw exception when `operationId` does not match

### ISSUE THREAD

**Issue by airmanx86** [swagger-api/swagger-js#1013]
```
// Get the operation, based on operationId ( just return the object, no inheritence )
export function getOperationRaw(spec, id) {
  if (!spec || !spec.paths) {
    return null
  }

  return findOperation(spec, ({pathName, method, operation}) => {
    if (!operation || typeof operation !== 'object') {
      return false
    }

    const {operationId} = operation

    if (operationId && operationId === id) {
      return true
    }

    const [_pathName, _method] = pathMethodFromId(id)
    return _pathName === pathName && toLower(_method) === toLower(method)
  })
}
```
When `operationId` does not match the `Id`, the above code assume `id` is in the format of `${method}-${path}`, then the regular expression in `pathMethodFromId()` return null which can't be destructed into `_pathName` and `_method`, which cause error.

Repo steps:
1. A spec which has more than one `paths` item with `operationId` set correctly
2. Use a valid `operationId` from the spec
3. Call `Swagger.buildRequest()` with the above

The existing test case only cover one item in `paths`, so it did not manage to pick up this problem.

**Comment by webron** [comment]
Which version of swagger-js do you use?

**Comment by airmanx86** [comment]
It's swagger-client 3.0.5.
The issue here is that the `for in` loop is not following the order of the keys on the object. So when we're lucky it will match and work, but if we're not lucky and when it won't match the above code will crash.

**Comment by shockey** [comment]
@airmanx86, the case you described (operationId that's valid, found in the spec explicitly) should be fixed.

We have coverage for explicitly provided operationIds in buildRequest [here](https://github.com/swagger-api/swagger-js/blob/master/test/execute.js#L14) now.

I just tried passing a nonexistent operationId to buildRequest, and got a `TypeError: Cannot read property 'operation' of undefined`. It's not a perfect error message, but IMO it's better than the object deconstruction error.

Feel free to make a PR, or comment here, if you'd like to see that error messaged differently.
