### ISSUE TITLE
Catch errors

### ISSUE THREAD

**Issue by Unsfer** [swagger-api/swagger-js#1014]
Seems like #1002

Trying to create a client, when swagger.json can't be loaded:

```
Swagger('/not.exist.api/swagger.json')
  .then((client) => {
    console.log('client', client);
  })
  .catch((error) => {
    console.log('error', error);
  });
```

But instead of catch 404 error, you get an client with spec like this
`
["H",
"T",
"T",
"P",
" ",
"4",
"0",
"4",
" ",
"N",
"o",
"t",
" ",
"F",
"o",
"u",
"n",
"d"]
`

**Comment by buunguyen** [comment]
https://github.com/swagger-api/swagger-js/pull/1015/files
