### ISSUE TITLE
allOf merges not only properties

### ISSUE THREAD

**Issue by lekoder** [swagger-api/swagger-js#1024]
Affected version: **3.0.6**

`allOf` implementation of `swagger-js` merges whole objects. While this is consistent with JSON Schema 1.0, for OpenApi it seems it should merge only `properties` of referenced models.

This behavior causes swagger-api/swagger-ui#2946

**Comment by shockey** [comment]
Closing as #2946 is resolved - if there's anything else around this that is still an issue, bump this thread and I'll reopen!
