### ISSUE TITLE
Cookies not sent when requesting $ref in swagger.json 

### ISSUE THREAD

**Issue by glipman** [swagger-api/swagger-js#1025]
Ticket #970 described a problem where cookies where not send because credentials: "same-origin" was missing.
In my model I have several $ref references to external files. The HTTP-request for these requests still don't send the ASPSESSIONID (or any) cookies.

My guess: makeFetchJSON in resolver.js needs to get the credentials: 'same-origin' as well.

(I do not have any experience with docker-based PHP development so I cannot create a PR)

**Comment by shockey** [comment]
This was solved in https://github.com/swagger-api/swagger-js/pull/1083.

Thanks for the report, @glipman!
