### ISSUE TITLE
swagger client authorization

### ISSUE THREAD

**Issue by boyandimitrov** [swagger-api/swagger-js#1033]
I'm using swagger-client npm through my client javascript. I have token based security but it must be applied to some of the functions in the api and must not for others (there is a public part of the api).

My problem is that these 2 types of api can hardly coexist in my ecosystem. The reason behind is that those methods with authorization fail when it's not supplied, but strangely enough when I supply authorization those that don't require it, stops. Part of the stack trace follows:

    swagger-client:613 Uncaught TypeError: p.forEach is not a function
        at p (swagger-client:613)
        at Object.u [as buildRequest] (swagger-client:564)

Maybe I have a general mistake in my swagger library initialization. I do it only onse and then I use my cached instance. Sample code follows:

    let run = function(config, callback)
    {
          // ???? problematic initialization happens here
          let options = {
                authorizations : {
                    "authorization": 'Bearer ' + config.token
                }
           };   
           Swagger(config.swagger_url, options).then(client =>
           {
                 window.client = client;
                 return callback()
           });
    }

I do it that way, because this code is under the Constructor section of the documentation but obviously I don't have a working code that way

So can anyone verified that I have to call the "constructor" for every api call choosing what kind of security to apply in the construction phase. Another approach could be to continue to use it my way, but to create 2 clients instead of one: One for authorized calls and the other for public calls.

**Comment by jpoutrin** [comment]
Hi @boyandimitrov,
I ran into the same issue:

1. The authorizations relate to the security element in the swagger.json
2. The error management in the swagger-client is poor which means it's hard to troubleshoot

ensure for each of your web method to have a security element such as:
`
"/users/{user_id}": {
            "get": {
                "operationId": "get_user",
                "parameters": [
                    {
                        "description": "An optional fields mask",
                        "format": "mask",
                        "in": "header",
                        "name": "X-Fields",
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "400": {
                        "description": "Validation Error"
                    }
                },
                "security": [
                    {
                        "Bearer": [
                            {
                                "in": "header",
                                "name": "Authorization",
                                "template": "Bearer {apiKey}",
                                "type": "apiKey"
                            }
                        ]
                    }
                ],
                "tags": [
                    "users"
                ]
            },
`

**Comment by boyandimitrov** [comment]
Ok let's deep in my swagger than

securityDefinitions:
 authorization:
  type: apiKey
  name: authorization
  in: header
..............................

Now I have private methods that does require security. For example:

  /login/user_info:
    x-swagger-router-controller: authentication
    post:
      tags:
        - private
      security:
        - authorization: []
      operationId: get_user_info
.............................

So these methods work. 

The problem is that I have another type of methods that are public:

  /login:
    x-swagger-router-controller: authentication
    post:
      tags:
        - public
      operationId: login

Now these methods produce an error, when I construct Swagger client in the way I pasted above.

**Comment by shockey** [comment]
I couldn't reproduce this, so I'm guessing it got fixed in a recent version.

I'm closing; please reply if this is still an issue and I'll reopen.
