### ISSUE TITLE
NPM package does not include umd module

### ISSUE THREAD

**Issue by mjkkirschner** [swagger-api/swagger-js#1035]
the NPM package for 3.0.8 does not seem to include any other minified files except for the commonjs module.

Is this intended? It looks like the repo has a webpack config for UMD in it.

**Comment by shockey** [comment]
Looks like the config changed here: https://github.com/swagger-api/swagger-js/commit/07ebd16eb3f83eb84994b30b25531784df1c573b, which would definitely make me think we'd export as a UMD module 😄 

PS: @ponelat, can you weigh in on this? @webron, can you prioritize?

**Comment by shockey** [comment]
Possibly coming from here: https://github.com/swagger-api/swagger-ui/blob/f85fdb78354ef14b64bab2c031722d57fa32640d/webpack-dist.config.js#L29

**Comment by ponelat** [comment]
So yeah... we'd just need to export the bundle and give it a UMD wrapper ( at least we're doing the latter ;) )

We've never really needed it, but that's not to say its not useful.

**Comment by shockey** [comment]
Closing; we're shipping with UMD now (not sure when it clicked over, though):

![Pasted Image 4.png](https://shipusercontent.com/e712bee3d0ae2fabd4ceae435f382df8/Pasted%20Image%204.png)
