### ISSUE TITLE
Support file:// urls

### ISSUE THREAD

**Issue by matthewadams** [swagger-api/swagger-js#1044]
Enhance `swagger-client` to support `file://` urls in order to allow the use of the package from Node.js server-side code.

The following code throws an error:
```
const Swagger = require('swagger-client')

Swagger(`file:///${__dirname}/swagger/spec/swagger.json`).then(client => {
  if (client.errors.length) {
    console.log('@@@@@@@@@@@@@@@@')
    console.log(client.errors)
    return
  }
  // ...use client...
}).catch(err => {
  console.log('!!!!!!!!!!!!!!!!!!!')
  console.log(err)
})
```
```
!!!!!!!!!!!!!!!!!!!
Error: only absolute urls are supported
    at /Users/matthew/dev/theservice-rest/node_modules/node-fetch/index.js:54:10
    at new Fetch (/Users/matthew/dev/theservice-rest/node_modules/node-fetch/index.js:49:9)
    at Fetch (/Users/matthew/dev/theservice-rest/node_modules/node-fetch/index.js:37:10)
    at module.exports (/Users/matthew/dev/theservice-rest/node_modules/isomorphic-fetch/fetch-npm-node.js:8:19)
    at a (/Users/matthew/dev/theservice-rest/node_modules/swagger-client/dist/index.js:1:3599)
    at /Users/matthew/dev/theservice-rest/node_modules/swagger-client/dist/index.js:1:17812
    at Function.i [as resolve] (/Users/matthew/dev/theservice-rest/node_modules/swagger-client/dist/index.js:1:18339)
    at Object.resolve (/Users/matthew/dev/theservice-rest/node_modules/swagger-client/dist/index.js:1:11515)
    at Object.a (/Users/matthew/dev/theservice-rest/node_modules/swagger-client/dist/index.js:1:10734)
    at a (/Users/matthew/dev/theservice-rest/node_modules/swagger-client/dist/index.js:1:10692)
```
I do see https://github.com/bitinn/node-fetch/blob/master/LIMITS.md, which appears to be the underlying problem.  This issue, then, is dependent on the removal of that limitation.  I've [commented](https://github.com/bitinn/node-fetch/issues/75#issuecomment-299526013) on https://github.com/bitinn/node-fetch/issues/75 in hopes that this will be resolved.

**Comment by matthewadams** [comment]
In the meantime, is there a workaround for being able to use `swagger-js` with a service that requires separate, manual download of its spec?

I was looking into it, and from a naive understanding of the code & dependencies, I'd have to fork & enhance `node-fetch` to support `file://` urls, then fork & enhance `isomorphic-fetch` to use the forked `node-fetch`, then fork `swagger-js` to use the enhanced `isomorphic-fetch`.  I could try some `proxyquire` trickery, but it all seems like a lot of work for little gain if there's another way to work around this.

**Comment by shockey** [comment]
@matthewadams, by this:

> Is there a workaround for being able to use swagger-js with a service that requires separate, manual download of its spec

do you mean that you already have your spec downloaded, and want to provide it directly to the library?

**Comment by matthewadams** [comment]
Yes

**Comment by boblauer** [comment]
A simpler alternative might be to allow a resolved spec to be passed into the client.  For example:

```js
const spec = require('./swagger-spec.json');
Swagger(spec).then(client => ...);
```

It seems silly to try to make a request of any sort to read a local file.

**Comment by matthewadams** [comment]
@boblauer I agree

**Comment by tcosentino** [comment]
@boblauer @matthewadams you can do this (found [here](https://github.com/swagger-api/swagger-ui/issues/1110)

```
import SpecFile from '../spec.json';
Swagger({ spec: SpecFile }).then((client) => {
  console.log(client);
});
```

**Comment by matthewadams** [comment]
Oooh I'll have to give that a try!

**Comment by c4milo** [comment]
@tcosentino I'm curious, why the need for the thenable call when providing the JSON already loaded?

**Comment by tcosentino** [comment]
@c4milo Just the way they've set up the constructor. I assume with the spec option it isn't doing anything async, but the pattern remains the same. There may be a way to do it without, i.e. the constructor may return the client? Just haven't tried that

**Comment by shockey** [comment]
@matthewadams, did @tcosentino's solution solve your use case?

**Comment by c4milo** [comment]
for new people landing here, this is how I did it with a Nuxt plugin: 

```
import Vue from 'vue';
import Swagger from 'swagger-client';
import APISpec from '~assets/identity.swagger.json';

const APIClient = {
	install (Vue, options) {
		Swagger({ spec: APISpec }).then((client) => {
			Vue.prototype.$client = client;
			Vue.prototype.$api = client.apis;
		}, (error) => {
			console.error('failed to load api spec: %o', error);
		});
	}
};

Vue.use(APIClient);
```

**Comment by shockey** [comment]
I'm going to close this one out, here's why:

`file://` URLs are not really useful, since they're very difficult to use in browsers due to Same-Origin Policy and very few Node request libraries support them.

As for loading in a definition that you already have in memory, @c4milo is correct: you can pass your definition as a JS object under the `spec` key.

Feel free to reply if you disagree with any of this, and I'll consider reopening. Thanks everyone!

**Comment by matthewadams** [comment]
@tcosentino: Just getting back to this.  Your comment (https://github.com/swagger-api/swagger-js/issues/1044#issuecomment-311481686) worked out nicely, and motivated me to add #1292.  Thanks!

**Comment by bcomnes** [comment]
Its unfortunate the io of fetching the spec has been so tightly coupled to the constructor of the resulting client.  Seems like that complicates the default path, and gets in the way (purposeless async) if you have the spec already.

**Comment by shockey** [comment]
@bcomnes, it's not completely purposeless, IMO.

We see definitions that are multiple megabytes of JSON - certainly, having the building of a client instance for that definition on the event loop is nicer than it locking up your main thread for a while.
