### ISSUE TITLE
overriding host

### ISSUE THREAD

**Issue by vivilian-git** [swagger-api/swagger-js#1045]
In the old version of UI, i can override the host using window.swaggerUi.api.setHost(url), as explained in swagger-api/swagger-js#532.

How could achieve the same with the latest version?

**Comment by hareeqi** [comment]
this worked for me but it's not official nor elegant 

https://gist.github.com/hareeqi/c9496288cfccf52342930874ac9670d3

**Comment by zhimoda** [comment]
This is actually very important for many scenarios, simplest being one spec and executing against test systems. How to achieve the same without the ability to switch? I can only think of multiple specs, one for each target system. In case only the host differs this does not make much sense. Hence, this feature should be considered important.

**Comment by webron** [comment]
It is considered important, but we still have to prioritize based on our resources. As with anything else, PRs are welcome.

@zhimoda in general, if you don't specify a host at all, and load it from the environment that you want to run against, that would work as well.

**Comment by alkrauss48** [comment]
Wanted to comment here with a semi-workaround. For me, I wanted to showcase a production URL in the docs, but have the "Try it out" button fire requests to a staging URL instead. I'm sure I'm not alone in this desire.

What I did was just set the host in my Swagger conf file to my staging URL so that the "Try it out" button would use that, but I just changed the `.base-url` DOM element to my production URL using the very-browser-supported document#querySelector method on page load. That element is the main place where the user sees the base URL:

```
document.querySelector('.base-url').textContent = '[ Base url: api.prod.com/ ]';
```

**Comment by xeranas** [comment]
Please consider include ability to override `basePath` as well.

**Comment by melanke** [comment]
+1

**Comment by joeherwig** [comment]
+1

**Comment by shockey** [comment]
Folks, please note that OpenAPI 3.0 allows you to [specify multiple URLs for your API, and use variables in server hostnames and paths](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#server-object). Support for this is in Swagger-UI :smile:

**Comment by AdrieanKhisbe** [comment]
My team and I are very interested on this feature, and I consider to volonteer to implement it.
Would it be possible to have some guidance? @shockey @webron :)
(gitter session for instance)

**Comment by shockey** [comment]
@AdrieanKhisbe, we don't have a gitter (#3544!), send me an email if you need guidance!

**Comment by cancan101** [comment]
Any updates on the ability to override the Host?

**Comment by dark-reiser** [comment]
I need this feature too

**Comment by zhoumeina** [comment]
I need this feature too.

**Comment by AdrieanKhisbe** [comment]
@cancan101,
Sorry we went an other way at my company, so I shifted subject and did not took care of it. :/
So no updates on my side

**Comment by Rmannn** [comment]
2 years and still no way to override host at init ?

**Comment by Niondir** [comment]
I'm also looking for this. Sounds like easily solvable inside the app.

**Comment by char0n** [comment]
I've explained [here](https://github.com/swagger-api/swagger-js/issues/1095#issuecomment-621818963) why there is no need for `swagger-js` to support these mutators.

Addressing this issue should now be possible purely from `swagger-ui` by [UrlMutatorPlugin](https://github.com/swagger-api/swagger-ui/issues/5981). 

Closing in favor of https://github.com/swagger-api/swagger-ui/issues/5981
