### ISSUE TITLE
Fix compatibility with React Native

### ISSUE THREAD

**Issue by jpoutrin** [swagger-api/swagger-js#1047]
The library does not work with react native for some reason.
when I disable swagger-js or move back to version 2 my app works again...

**Comment by ponelat** [comment]
So the issue was `Failed to print error: regeneratorRuntime.async is not a function` when loading this lib into a react-native app.

I think its because we're missing the regenerator runtime... all apps up to date have included `babel-polyfill` and so this was mostly hidden from us. (@webron in theory this should affect any browser that didn't include its own babel-polyfill )

@jpoutrin a possible workaround is to just include [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) 

But we'd need to find a fuller solution to swagger-js, as we _shouldn't_ be mutating globals in a lib. Its just bad :)

**Comment by jpoutrin** [comment]
@ponelat it might be one of the issue indeed. but didn't make it work at the end.
 
I moved back to v2 and also discover that the http connector had to be re-implemented as the XMLHttpRequest seem to behave in a different way.
everything was working except POST messages...
v2 is easier as plain javascript which makes it easier to debug ;)

see the [gist](https://gist.github.com/jpoutrin/20d6236d9dc1b4cb52cff6960d834078)

**Comment by adamski** [comment]
I just hit this issue trying to upgrade a react-native module to v3, manifesting as a "self is not defined" error which seems to come from the `fetch` library.

**Comment by piranna** [comment]
Any update on this? What's the current solution, or what we should be doing?

**Comment by shockey** [comment]
@piranna, some information on how `swagger-client` is breaking for you would be helpful.

We've removed babel-polyfill, so that shouldn't be an issue. Are you having the same fetch problem as @adamski?

**Comment by piranna** [comment]
I haven't used the library yet, but was heavily interested on. I was just asking to know if it would work or should I use fetch instead.

**Comment by WhoseSomebody** [comment]
Currently faced the same trouble.
Eventually `client` object has empty `apis` parameter. 

After debugging this error was found (in isomorphic-fetch lib):
![image](https://user-images.githubusercontent.com/5785260/29618741-c59fed38-8821-11e7-93e7-65f9e9f38662.png)
(as @adamski noticed)

So now I am stuck at this point. 
I would be happy to understand the workaround of @jpoutrin, but I don't exactly understand how it works.

I use `"swagger-client": "^3.0.20"`.

So, I now don't know what to do. Using fetch with swagger server interface doesn't look so sweet :'(

P.S. I am wondered but I cannot find any information about using RN and Swagger client. So, either everything works great everywhere, either no one use it. No glue.

**Comment by shockey** [comment]
Thanks for the insights, everyone.

It looks like this is a known issue with `isomorphic-fetch`:
- https://github.com/matthew-andrews/isomorphic-fetch/issues/125
- https://github.com/matthew-andrews/isomorphic-fetch/issues/59

Unfortunately, it appears that the library is no longer maintained, so this is unlikely to change from their end.

In the second issue I linked, I noticed someone pointing to the [`fetch-everywhere`])(https://www.npmjs.com/package/fetch-everywhere) as an API-compatible replacement for `isomorphic-fetch`. The best fix for this may be to move Swagger-Client over to `fetch-everywhere` internally.

**Comment by shockey** [comment]
We've just switched from `isomorphic-fetch` to `cross-fetch`, which claims to be React Native compatible 😄

**Comment by shockey** [comment]
Fix released in `swagger-client@3.3.2`.

Closing! Thanks everyone.

**Comment by jtn-d** [comment]
I have version 3.3.4 and facing this. 
```
Swagger('http://petstore.swagger.io/v2/swagger.json')
  .then(client => {
    console.log(client.errors)
  })

[ { [TypeError: undefined is not a function (evaluating '$.default.apply(e, [t])')]
```
Am I missing something?

**Comment by shockey** [comment]
@jtn-d, that's an odd error. Is it still a problem? Can you give some more context?
