### ISSUE TITLE
If I specify `multipart/form-data`, it should use that. Right?

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-js#1063]
If I explicitly specify the `consumes: multipart/form-data`, I'd expect that to take precedence over the default `application/x-www-form-urlencoded`, when there is a `in: formData` present.

ping @webron @bodnia 

Version: `Object {swaggerEditor: "3.0.10/gb2e3da6-dirty", swaggerUi: "3.0.9/ga068f78"}`

```yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: title
  description: description
  termsOfService: terms
  
host: httpbin.org

schemes:
- http

paths:
  /post: 
    post: 
      summary: ...
      description: ...
      consumes: 
      - multipart/form-data
      parameters: 
      - in: formData
        type: string
        name: one
      responses: 
        200:
          description: OK
```

**Comment by bodnia** [comment]
@ponelat yes, correct, it's a bug

**Comment by bodnia** [comment]
Closing as this is not an issue in swagger-js.

**Comment by ponelat** [comment]
@bodnia
How are you testing? With swagger-ui only? Since when I test with swagger-editor, it still fails..
![image](https://user-images.githubusercontent.com/8438485/26867185-96375350-4b64-11e7-8356-f90586e68491.png)

I can't recall if there is another issue ( in another repo ) where this is tracked. Could you link, if there is?

**Comment by bodnia** [comment]
There must be a drop-down to choose content-type for formData, but this is not implemented yet.
@ponelat so you'd like to set first `consumes` value if it didn't come from `swagger-ui` as chosen one?

**Comment by ponelat** [comment]
@bodnia, so there won't be a dropdown for formData yet ( its a known thing, and won't be implemented right now ).

Here we default to `application/x-www-form-urlencoded`, instead we should default to `multipart/form-data` since its in the list of `consumes`. Not necessarily the first item in `consumes`.

**Comment by ponelat** [comment]
@bodnia, so there won't be a dropdown for formData yet ( its a known thing, and won't be implemented right now ).

Here we default to `application/x-www-form-urlencoded`, instead we should default to `multipart/form-data` since its in the list of `consumes`. Not necessarily the first item in `consumes`.

Let me know if you have too much on your plate for this.

**Comment by tim-lai** [comment]
Closing issue. I believe already implemented
