### ISSUE TITLE
run npm build fail

### ISSUE THREAD

**Issue by SimCordy** [swagger-api/swagger-js#1066]
Hi,
I've downloaded the swagger-js zip, and I have modified some file, so I need to rebuild it. The command _npm install_ works correctly, but when I run the command _npm run build_ it fail and return me some errors, this is the content of the npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle swagger-client@3.0.11~prebuild: swagger-client@3.0.11
6 silly lifecycle swagger-client@3.0.11~prebuild: no script for prebuild, continuing
7 info lifecycle swagger-client@3.0.11~build: swagger-client@3.0.11
8 verbose lifecycle swagger-client@3.0.11~build: unsafe-perm in lifecycle true
9 verbose lifecycle swagger-client@3.0.11~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Sibo\Desktop\swagger-ui\swagger-js-master\swagger-js-master\node_modules\.bin;C:\Python27;C:\PCI Geomatics\Geomatica 2017\exe;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\MATLAB\R2016b\bin;C:\Program Files (x86)\Brackets\command;C:\Program Files\nodejs\;C:\Users\Sibo\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\Sibo\AppData\Roaming\npm
10 verbose lifecycle swagger-client@3.0.11~build: CWD: C:\Users\Sibo\Desktop\swagger-ui\swagger-js-master\swagger-js-master
11 silly lifecycle swagger-client@3.0.11~build: Args: [ '/d /s /c',
11 silly lifecycle   'NODE_ENV=production webpack -p --config ./webpack.config.js' ]
12 silly lifecycle swagger-client@3.0.11~build: Returned: code: 1  signal: null
13 info lifecycle swagger-client@3.0.11~build: Failed to exec build script
14 verbose stack Error: swagger-client@3.0.11 build: `NODE_ENV=production webpack -p --config ./webpack.config.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid swagger-client@3.0.11
16 verbose cwd C:\Users\Sibo\Desktop\swagger-ui\swagger-js-master\swagger-js-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error swagger-client@3.0.11 build: `NODE_ENV=production webpack -p --config ./webpack.config.js`
22 error Exit status 1
23 error Failed at the swagger-client@3.0.11 build script 'NODE_ENV=production webpack -p --config ./webpack.config.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the swagger-client package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=production webpack -p --config ./webpack.config.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs swagger-client
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls swagger-client
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

How I can solve the problem?

I'm using windows 10
nodejs version:  6.10.3
npm versione: 3.10.10

**Comment by shockey** [comment]
Strange... I have a couple ideas on what could be going on here.

What happens when you run `NODE_ENV=production webpack -p --config ./webpack.config.js` from the swagger-js directory?

**Comment by SimCordy** [comment]
Hi,
When I execute the command, NODE_ENV=production webpack -p --config ./webpack.config.js it return me the error :
_"NODE_ENV" is not recognized as an internal or external command, operable command or batch file._

**Comment by shockey** [comment]
Gotcha.

So yeah, that's coming from the command we have in our npm scripts - it assumes a unix shell.

The Windows equivalent of `NODE_ENV=production webpack -p --config ./webpack.config.js` should be `SET NODE_ENV=production & webpack -p --config ./webpack.config.js`. Can you tell me if that works for you?

**Comment by SimCordy** [comment]
Thank you, unfortunately it don't work, now the problem seems to be webpack, when I execute SET NODE_ENV=production & webpack -p --config ./webpack.config.js it return me:

"webpack" is not recognized as an internal or external command, operable command or batch file

I run the command npm install webpack but it still don't work.

**Comment by shockey** [comment]
Can you `npm install -g webpack` and try again?

**Comment by SimCordy** [comment]
Thank you vey much!!!!!
It works and the dist folder with the index.js file has appeared! Thank you!

**Comment by shockey** [comment]
🎉 

Glad I could help. I'm going to close this ticket, but I'll keep my eyes open for any more Windows users having issues. If this is a recurring issue, we'll open a ticket for the functionality.

To anyone reading this: if you'd like to open a PR for Windows support in our npm scripts, [`cross-env`](https://www.npmjs.com/package/cross-env) looks like a good option.
