### ISSUE TITLE
Correct way to update authorizations token

### ISSUE THREAD

**Issue by yoihito** [swagger-api/swagger-js#1090]
Hey guys!

What is the correct way to update access token for V3?

Thanks, Vadim

**Comment by webron** [comment]
What do you mean?

**Comment by yoihito** [comment]
hi @webron,

Small introduction. I'm implementing a single-page application. Swagger is used to implement API.  API's authentication is implemented using OAuth 2. Access token for API is short lived. I need to update it every 5 minutes. 

Swagger-js is used as api client for SPA. I found out how to initialize swagger-js with access token.
```
import Swagger from 'swagger-client';

...

const swaggerPromise = Swagger(specUrl, {
  authorizations: { jwtToken: { token: { access_token: 'SOME ACCESS TOKEN GENERATED BY API' } } },
});
```
I have to update access token every 5 minutes. What is the correct way to implement this?

**Comment by Robbilie** [comment]
Have you tried creating an authorizations object, storing it and passing it to the initialization and modifying the field in the object when needed? Not the nicest way but at least try it as temp workaround :)

**Comment by yoihito** [comment]
@Robbilie thanks :) I implemented your approach and it works. 
```
swaggerPromise = Swagger(url, {
    authorizations: { OauthSecurity: { token: { access_token: '' } } },
});

...

swaggerPromise.then(client => {
    client.authorizations.OauthSecurity.token.access_token = accessToken;
    ...
})

```

**Comment by shockey** [comment]
This looks solved - closing!
