### ISSUE TITLE
BasePath ignored when schema and host aren't set

### ISSUE THREAD

**Issue by JohnRowleySEL** [swagger-api/swagger-js#1091]
Currently if a spec doesn't have a schema and host set then the basepath is not used when executing an operation.

The source responsible for this can be found here. https://github.com/swagger-api/swagger-js/blob/master/src/execute.js#L212-L227

I have a fix on my own fork where I pretty much do the same thing that line 224 does but with the *computedPath*. I will create a pull request hopefully later this week.

**Comment by ereOn** [comment]
Any news on this ?

**Comment by shockey** [comment]
Fixed by #1166!
