### ISSUE TITLE
Request builder not including values of (int) 0

### ISSUE THREAD

**Issue by seamoss** [swagger-api/swagger-js#1103]
In the spec I'm consuming:

```json
...
{
  "in": "query",
  "name": "offset",
  "required": true,
  "description": "number of records to skip for pagination",
  "type": "integer",
  "format": "int32",
  "minimum": 0,
  "default": 0,
  "x-example": 0
}
...
```

When the request is built, it's ignoring the `0` when passed either by parameter injection or using the default.

Expected: `/1.0/menu?offset=0&limit=10`

Actual: `/1.0/menu?limit=10`

I know this is standard across the board to make `0` assumptions, but the API I'm consuming is designed to require this parameter in the `GET` request.  Faster to resolve in my end than assume they will update with a correction.

Any thoughts?

Disclosure:  I couldn't find any dupes of this.  Sorry if I missed any hidden gems.

**Comment by seamoss** [comment]
The request compiles correctly when changing the `type` of offset to `string`, but it requires me to augment the hosted spec and that probably isn't scalable long-term.

**Comment by shockey** [comment]
This is probably a bug in our request builder implementation - `0` is falsy in JS, but `"0"` is truthy. 

What version are you using?

**Comment by seamoss** [comment]
Oops, sorry. 

swagger-client@3.0.17

**Comment by seamoss** [comment]
Thanks for the quick attention.  Would it be advantageous to include `boolean` in this check, too?

**Comment by shockey** [comment]
@seamoss, this should be fixed in the next version 👍

**Comment by shockey** [comment]
thanks for reporting this!

**Comment by seamoss** [comment]
No, thank you!
