### ISSUE TITLE
3.x faq link is wrong

### ISSUE THREAD

**Issue by srl295** [swagger-api/swagger-js#1111]
in README.md

> want to learn more? check out our FAQ

looks like the link should be https://github.com/swagger-api/swagger-js/blob/master/docs/MIGRATION_2_X.md

(I found this via https://github.com/swagger-api/swagger-js/releases/tag/v3.0.1  which also has helpful info )

**Comment by srl295** [comment]
if i can tag onto this (ha) also, while 3.x does not seem to support custom authenticators, they can be done with `requestInterceptor`. I was able to do that pretty easily, will include a link once I push the commit…

**Comment by webron** [comment]
It actually links to the ended location, but I'll change it as that link is more useful. Thanks.
