### ISSUE TITLE
QUESTION: how to generate js code from spec?

### ISSUE THREAD

**Issue by poppinlp** [swagger-api/swagger-js#1119]
I wanna use the spec to send request in browser.
In the readme i found a way which is load the swagger-client.js to browser and use it to parse the spec.
It may cost too much...so i wanna know could i generate js code by spec directly?
Thanks.

**Comment by webron** [comment]
If you're looking for a generated JS client, take a look at [swagger-codegen](https://github.com/swagger-api/swagger-codegen).

**Comment by poppinlp** [comment]
@webron  Thanks.
A little more question. Why not a npm package to generate js code since there's such a js in this repo could parse spec and use it? Seems npm package is easier to use in node and to put in front-end build flow. No offense. :)

**Comment by webron** [comment]
The codegen is written in Java. We don't have the capacity to write a generator in each language. There are multiple ways to get it running, even through JS code.

**Comment by poppinlp** [comment]
Yes, i find you have a online generator which could call by curl.
Thanks.
And a little more (sorry just a little)...Which spec do you recommend 2.0 or 3.0.0? I found the the recommend spec on your website is 3.0.0 but swaggerhub and that online generator are using 2.0 (or maybe your update plan) :)

**Comment by webron** [comment]
If you'd like to take advantage of the full ecosystem, stick with 2.0 for now. It'll take time for tooling to catch up, even though we work on those.

What in our website gave the impression that 3.0.0 is the recommended spec?

**Comment by poppinlp** [comment]
Well..I get to the [specification page](https://swagger.io/specification/) and the default is 3.0.0 (just a little link to 2.0) which makes me feel 3.0.0 is the recommended spec version (like what other libs always do to show a recommended version as default and give a link to older. )
So...dose i feel wrong?
