### ISSUE TITLE
requestInterceptor not modifing headers on initial request for json

### ISSUE THREAD

**Issue by patrickml** [swagger-api/swagger-js#1124]
I am trying to modify the headers when requesting the initial spec json file from our server. However, I am a not seeing these changes reflected in the outbound request even though `requestInterceptor` is being fired.

```js
Swagger.http({
  requestInterceptor: (req) => {
    req.headers.Authorization = 'Token b9e1a4bfb5221f728572a095f2c39f9360eedf8b';
    req.headers.Accept = '*/*';
    return req;
  },
});

export default Swagger({
  url,
}).then((client) => {
  // eslint-disable-next-line no-param-reassign
  client.http.withCredentials = true;
  return client;
});
```

```
accept:application/json
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Host:localhost:8000
Origin:http://localhost:3000
Referer:http://localhost:3000/
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
```

**Comment by patrickml** [comment]
I guess my real problem here is I need to be able to modify the headers when you call Swagger to include an authorization token. I also need to modify the headers when a normal call is made

**Comment by srl295** [comment]
Working for me when we upgraddd from 2.x to 3.x https://github.com/IBM-Bluemix/gp-js-client/pull/86 (more precise link later- look for gaashmac.js )

**Comment by srl295** [comment]
https://github.com/IBM-Bluemix/gp-js-client/pull/86/files#diff-38aee4b3886a621f8daddb4104803472

**Comment by webron** [comment]
@patrickml which version of swagger-js do you use?

**Comment by patrickml** [comment]
I had upgraded from 2 to 3, but it still didn't work. @srl295 can you post an example? I ended up writing my own swagger client creator for now, but im curious how you were able to do it?

**Comment by srl295** [comment]
@patrickml it's in the link above , but i'm working on a blog post also

**Comment by srl295** [comment]
@patrickml did you get it to work?

**Comment by patrickml** [comment]
@srl295 not with this library, I ended up writing another swagger client that's really light weight and serves our needs, at least for now. thanks for checking in tho!

**Comment by bowbahdoe** [comment]
It's not a perfect solution, but in my code I ended up doing the request for the spec with fetch and just passing it in to the client as a data url. Here is the full file, if it will help anyone else work around the issue.

https://gist.github.com/bowbahdoe/d63d6468a20fcf289c278938de6fc7fa

**Comment by prees1** [comment]
I am seeing the same issue as the original.

I have this set of options:

```
  const ui = SwaggerUIBundle({
    url: "https://" + window.location.hostname + "/docs",
    dom_id: '#swagger-ui',
    deepLinking: true,
    requestInterceptor:
    (request) => {
      console.log('[Swagger] intercept try-it-out request');
      request.headers.Authorization = "Bearer testtoken";
      console.log(request.headers);
      request.mode = 'no-cors';
      return request;
    },
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })
```

When I view the request made to fetch the spec there is no `Authorization` header.
Viewing the console I can see the `request.headers` print out as expected and the header is there.

I am using the latest swagger-ui, v3.10.0, from here - https://github.com/swagger-api/swagger-ui

**Comment by shockey** [comment]
Hi folks!

I was just toying with this, and _thought_ I was reproducing the problem... then I realized I was inspecting a OPTIONS preflight request, not the actual GET for my definition. I haven't been able to coerce my GET request into not attaching the Authorization header.

If you're stuck on this, can you provide a screenshot of the request you were expecting to have an `Authorization` header on but don't, as shown in your browser's devtools? I'd like to make sure we're all on the same page with this bug.

Thanks in advance!

**Comment by shockey** [comment]
I'm pretty sure this is a server issue: if you aren't sending a `Access-Control-Allow-Headers: authorization` header back to the browser in your OPTIONS request, the Authorization header is not allowed in your actual request.

Can anyone confirm that this fixes (or doesn't fix) this problem?

**Comment by prees1** [comment]
Yes it was actually a CORS issue for me. Once I resolved the CORS issue (can't recall the exact header I had to correct) it worked as expected.

**Comment by tnpradeep** [comment]
Is it possible to return promise object from requestInterceptor, will swagger client wait for the promise returned to resolve before invoking actual http call ?

**Comment by shockey** [comment]
@tnpradeep yes, if you return a promise it will await the resolution of that promise! Beware that the promise will need to return a request object similar to the one provided to the interceptor.
