### ISSUE TITLE
POST values in tags interface aren't sent

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#1136]
When using the tags interface like [this](https://github.com/swagger-api/swagger-js#tags-interface), content in POST values is _not_ sent to the server.  Sample PR with test on the way...

**Comment by fehguy** [comment]
@shockey ping on this?

**Comment by shockey** [comment]
@fehguy 👋 

I changed the test you wrote in #1137 to the following:
```js
client.apis.Testing.tryMe({
  theBody: {
    name: 'tony'
  }
})
```

and the test passed. This is how I imagine the interface should work, but I may be missing something.

Should we be matching parameter values to body parameter schema properties (i.e. `name => body.name`)? Is this something we were doing in 2.x?

**Comment by fehguy** [comment]
oh! I think that what you put is the right behavior.  I'll retest and report back...

**Comment by shockey** [comment]
@fehguy bump 😄

**Comment by CameronAckermanSEL** [comment]
Hey guys. I'm seeing something similar.

Given this spec:

```
"/projects/{projectKey}/containers/{containerKey}/stuffs":{  
   "parameters":[  
      {  
         "in":"path",
         "name":"projectKey",
         "required":true,
         "type":"string"
      },
      {  
         "in":"path",
         "name":"containerKey",
         "required":true,
         "type":"string"
      }
   ],
   "post":{  
      "description":"Inserts a new `Stuff` for the `Container`.",
      "operationId":"insertStuff",
      "parameters":[  
         {  
            "in":"body",
            "name":"stuff",
            "required":true,
            "schema":{  
               "$ref":"#/definitions/StuffParameters"
            }
         }
      ],
      "responses":{  
         "201":{  
            "description":"successfully added stuff.",
            "schema":{  
               "$ref":"#/definitions/Stuff"
            }
         },
         "404":{  
            "$ref":"#/responses/NotFound"
         },
         "500":{  
            "$ref":"#/responses/Error"
         }
      },
      "tags":[  
         "stuff"
      ]
   }
}
```

And this method of calling the client:

```

```

I have two cases where swagger-client will fail to validate the request parameters and issue the request with no body.

1. If I pass in an explicitly defined object for the stuff argument


2. If I pass in an anonymous object that has extra parameters



I understand that the validation is useful. But my expectations are:

1. If there's a validation error, a descriptive exception is thrown and the request is NOT sent.
2. OR The client ignores the extra stuff.
3. Regardless, the client allows explicit objects to be passed into the object parameters.

**Comment by shockey** [comment]
Hey @CameronAckermanSEL! Sorry you're having problems. Some samples of how you're actually calling Swagger-Client would be helpful :smile:

**Comment by CameronAckermanSEL** [comment]
@shockey haha yeah sorry I was working on it. Should be up now!

**Comment by fehguy** [comment]
@shockey I’ll get back to thisnover the weekend. I got lost in Java land for a bit and am doing a detox

**Comment by webron** [comment]
But you don't do Java...

**Comment by fehguy** [comment]
WOW all this time I thought you didn’t read issues anymore...

**Comment by webron** [comment]
Mostly trying to ignore yours...

**Comment by shockey** [comment]
@fehguy bump

![](https://media.giphy.com/media/IP30yHlCkN8ha/giphy.gif)

**Comment by fehguy** [comment]
OK I've re-tested and things seem happy :D . It is a bit more picky about response headers when parsing but that's life

**Comment by shockey** [comment]
👍

Closing this one out 🎉
