### ISSUE TITLE
need help with ApiKeyAuthorization and adding authorizations

### ISSUE THREAD

**Issue by iamakimmer** [swagger-api/swagger-js#1138]
Tried looking at all the docs but couldn't get too far..I'm trying to add an ApiKeyAuthorization but it's undefined..

```
const Swagger = require('swagger-client'); //"swagger-client": "3.1.1",
const config = require('../config/config');

Swagger(myfiel.yaml)
.then(client => {
	
var auth = client.ApiKeyAuthorization('api_key', 'abc123', 'query'); //there is no ApiKeyAuthorization
	artix = client.apis;
	resolve(artix);					
}).catch(err => {
console.log('err', err);
});

```
The yaml file is loaded correctly and comes back but I can't find any ApiKeyAuthorization function anywhere.  the client object comes back with:

<img width="646" alt="screen shot 2017-09-22 at 5 30 12 pm" src="https://user-images.githubusercontent.com/335105/30765199-6c6a80cc-9fbc-11e7-8ebb-3d7f3deff18c.png">

What am I doing incorrectly?

**Comment by shockey** [comment]
Hi @iamakimmer, 

`ApiKeyAuthorization` is from the 2.0 version of `swagger-client`. See the migration guide for instructions on how to provide authorizations to `swagger-client` 3.0: https://github.com/swagger-api/swagger-js/blob/903569948d5a5c718d7b87d6832a672de4e76afc/docs/MIGRATION_2_X.md#authorizations

**Comment by iamakimmer** [comment]
That did the trick thanks!

**Comment by shockey** [comment]
Awesome! Glad I could help.

**Comment by nikarc** [comment]
Omg, @iamakimmer thanks so much! You've saved me hours of work

**Comment by biggianteye** [comment]
How does the suggested migration work?

From the doc linked:

```javascript
Swagger('http://petstore.swagger.io/v2/swagger.json', {
  authorizations: {
    // Type of auth, is inferred from the specification provided 
    my_basic_auth: { username: 'foo', password: 'bar' },
    my_query_auth: 'foo', 
    my_header_auth: 'foo', 
    my_oauth2_token: { token: { access_token: 'abcabc' } },
    cookie_auth: null, // !!Not implemented
  }
}).then( client => ... )
```

If you are going from this:

```javascript
my_header_auth: new ApiKeyAuthorization('My-Header', 'bar', 'header'),
```

to this:

```javascript
my_header_auth: 'foo', 
```

you are losing two piece of information: the name of the header and the fact that it's in the header rather than the query.

Am I missing something?

These two examples have identical content. How can it possibly infer that one is a query auth and one is a header auth?

```javascript
    my_query_auth: 'foo', 
    my_header_auth: 'foo', 
```

**Comment by gpineda-dev** [comment]
> 
> 
> How does the suggested migration work?
> 
> From the doc linked:
> 
> ```js
> Swagger('http://petstore.swagger.io/v2/swagger.json', {
>   authorizations: {
>     // Type of auth, is inferred from the specification provided 
>     my_basic_auth: { username: 'foo', password: 'bar' },
>     my_query_auth: 'foo', 
>     my_header_auth: 'foo', 
>     my_oauth2_token: { token: { access_token: 'abcabc' } },
>     cookie_auth: null, // !!Not implemented
>   }
> }).then( client => ... )
> ```
> 
> If you are going from this:
> 
> ```js
> my_header_auth: new ApiKeyAuthorization('My-Header', 'bar', 'header'),
> ```
> 
> to this:
> 
> ```js
> my_header_auth: 'foo', 
> ```
> 
> you are losing two piece of information: the name of the header and the fact that it's in the header rather than the query.
> 
> Am I missing something?
> 
> These two examples have identical content. How can it possibly infer that one is a query auth and one is a header auth?
> 
> ```js
>     my_query_auth: 'foo', 
>     my_header_auth: 'foo', 
> ```

Hello, 
     I guess I found a tips to solve your problem with the new version of Swagger-client and token access
```node
Swagger(SWAGGER_ENDPOINT,{
    authorizations: {
        accessTokenAuth: `Bearer ${SWAGGER_TOKEN}`
        //accessTokenAuth: {token: {access_token: SWAGGER_TOKEN}}
    }
})
```
It works but not really clean ..

I hope it might help you
