### ISSUE TITLE
Limiting DFS in `createKeyBasedPlugin`

### ISSUE THREAD

**Issue by dballance** [swagger-api/swagger-js#1150]
I'm struggling with some absolutely massive OAS documents in swagger-js (~3.5MB on disk). They contain many JSON pointers ($ref plugin produces ~28000 patches). They're also _potentially_ highly graphical - they're OData based and the OData `$expand` query param can be used to request related entities. Typically this is depth limited by the API, but as far as the OData metadata / OAS 2.0 metadata they're simply references that could repeat. This leads to lots of revisiting in `createKeyBasedPlugin`'s `traverse` method.

To the best of my knowledge, as patches are applied, `traverse` will revisit the same referenced path over and over, even if they are the same underlying type - here `#/responses/400` and `#/responses/401` both reference `#/definitions/OData.Error`. The underlying reference is the same, but we traverse the entire tree for both patches, because we don't know that we've already visited the  `#/definitions/OData.Error` node in search for additional modifications. (Note: I think is is what is occurring, but I'm not sure here) I believe the second traversal is redundant, as are any future traversals of `#/definitions/OData.Error`.

![image](https://user-images.githubusercontent.com/1234523/31450162-5792c41e-ae6e-11e7-977a-98d772137056.png)

The paths contain the results of logging the path argument to traverse
```js
        function* traverse(obj, path, patch, depth) {
          console.log(path.join('.'))
```

Since I have a limited knowledge of the design / intent behind the implementation - I wanted to ask - **Is there any reason NOT keep a reference to this node and simply skip traversal once we've already traversed a particular JSON pointer's referenced node?** This would be on a 'per-plugin' basis - one lookaside for each plugin. That means once a pointer is visited once in the `$ref` plugin, it wouldn't be visited again as patches are evaluated.

I've implemented a lookaside that utilizes the `allowMetaPatches` option - and the results in speed are astounding. Previously, spec resolution would take a long time - in the multi-hour range. I don't have an exact number because I never got it to complete. After adding the lookaside it resolves the specs within 10-20 seconds. I'm unsure of the completeness - as the resulting JSON is massive and I cannot get a swagger-ui utilizing this patched version of swagger-js to load - but wanted to ask about the intent here before I write some tests....

Result of traversal with look aside. 
![image](https://user-images.githubusercontent.com/1234523/31450929-5b4a63e4-ae70-11e7-958e-dcae78abd379.png)

#1117

**Comment by shockey** [comment]
Hey @dballance, sorry for the delay here! I was looking into a related issue and realized you never got a reply. Thanks for the writeup!

I don't see any reason to not cache the traversal. Would you be able to put this change into a PR?

**Comment by dballance** [comment]
@shockey Awesome - always amazed by how small the world is. 😃 

I'll look into getting a PR today - need to go back and look at what I did. When I left it, I believe that I only applied the lookaside for `$ref` patches. It seemed to cause issues with the model when I applied it for all patches. 

I think the solution is something along the lines of the lookaside for `$refs` and the `defaultModelExpandDepth` mentioned [in your comment](https://github.com/swagger-api/swagger-editor/issues/1546).

**Comment by dballance** [comment]
@shockey - Played around with this most of the day today. Hope to have a small PR tomorrow that adds mitigates this issue (DFS revisit) and I will potentially submit another to resolve an issue with `allOf` separately.

As a note on the spec I'm trying to resolve - it's ~140k lines formatted JSON. Limiting DFS solves half the problem - the other half is the potential in `allOf` resolutions to contain a massive tree due to the graphical nature of OData expansion. A url similar to this is not uncommon `http://services.odata.org/TripPinRESTierService/(S(hv5ozawv3rg0kxkskshwnr5h))/People('russellwhyte')/Friends('ronaldmundy')/Trips(5)/PlanItems` - and with this particulary model, relationships at some levels can be in the 10s to 100s, which leaves a massive amount of data to merge. Still not sure what can be done here - so I'm open to any suggestions.
