### ISSUE TITLE
IE11 not supported due to ECMA 6 call using 'startsWith'

### ISSUE THREAD

**Issue by srb-qlik** [swagger-api/swagger-js#1152]
@fehguy checked in some code back in April that calls applyDefaults() (in index.js) that uses startsWith().  This is not supported in IE11.  Should probably change this to `indexOf('http') === 0`.
I also see it is added in helpers.js isOAS3() and isSwagger2() calls too (added by @shockey ).  

I'm trying to use "npm run build-bundle" and that outputted swagger-client.js file in my environment and it's failing to work in IE11.

**Comment by shockey** [comment]
Fixed; should be released shortly.

Thanks for the report, @srb-qlik!
