### ISSUE TITLE
Issue with application/x-www-form-urlencoded 

### ISSUE THREAD

**Issue by cpedrinaci** [swagger-api/swagger-js#118]
Hi,
I'm trying to invoke the Boxcar API from a node.js script, based on a [swagger description](https://www.dropbox.com/s/vbx5dqvvoti77dr/boxcar.zip?dl=0) I've made.

The interesting thing is that while I can use swagger-ui directly for invoking the API, when I try to do so from a script it won't work. The code I'm using is the following:

```javascript
var client = require("swagger-client");

var responseFunction = function(response) {
    var resp;
    if (response === undefined || response.status >= 400 ) {
        console.log("Error invoking the API: Status - %s", response.status);
    } else {
        console.log("Successful invocation: Status - %s", response.status);
        console.log("Result: %s", response.data);
    }
};

var errorFunction = function(response) {
    console.error({status: response.status, payload:"API invocation error: " + response.data});
};

var swagger = new client.SwaggerApi({
    url: "http://localhost:8000/boxcar/api-docs",
    success: function() {
        console.log("Successfully obtained the API description from %s", this.url);

        if (swagger.ready === true) {
            swagger.apisArray[0].operationsArray[0]["do"]({"user_credentials": "XXXXXXX", "notification[title]": "Title", "notification[long_message]": "msg", "commit": "Try it out!"}, {"requestContentType":null, "responseContentType":"application/json"}, responseFunction, errorFunction);
        }
    },

    // define failure function
    failure: function() {
        console.error("Unable to obtain API description from " + this.url );
    }
});
```

Indeed, in order to test this you will have to replace the user_credentials with valid ones. You can get one if you install the boxcar app in your phone.

After much digging around I've spotted that the request made to Shred is not correct in this case.
Looking into swagger.js it seems that the issue occurs when generating the SwaggerRequest function.

Notably around line 1117
```javascript
if(headers["Content-Type"].indexOf("application/x-www-form-urlencoded") === 0) { ... }
```

the script proceeds to encode all the values and set the body to the resulting string.

Taking away of all the pre-processing of the parameters, for example replacing the if block with:

```javascript
if(headers["Content-Type"].indexOf("application/x-www-form-urlencoded") === 0) {
        body = params;
}
```

does the job for me and I can get that particular API to be executed without any problem. I am sure though that the existing code is there for a reason ...

I was wondering if you could have a look at this and see if I'm doing something wrong, or whether the handling of x-www-form-urlencoded does actually not deal properly with this particular case...

**Comment by fehguy** [comment]
Addressed and tested here:

https://github.com/swagger-api/swagger-js/blob/develop_2.0/src/js/swagger.js#L567-L580

**Comment by cpedrinaci** [comment]
Yes, I can confirm I'm not facing the issue anymore. Thanks!

**Comment by cpedrinaci** [comment]
Actually, I don't know what happened (maybe I had my trailing fix in the code I was running) but in my current tests this still gives problems I'm afraid. At least with the latest npm (swagger-client@2.1.4-M1).

I asked Shred to log its request as curl and indeed it does not send any data:
curl -X POST https://new.boxcar.io:443/api/notifications -H "user-agent: Shred" -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: application/json" -H "Content-Length: 0" -d ''

Any ideas? Should I be using some earlier bundle? has this not been released yet?

**Comment by fehguy** [comment]
we're on 2.1.9-M1.  Can you please try that?

**Comment by cpedrinaci** [comment]
Just tried and got the same result I'm afraid. No data is passed through:

curl -X POST https://new.boxcar.io:443/api/notifications -H "user-agent: Shred" -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: application/json" -H "Content-Length: 0" -d ''

**Comment by xhh** [comment]
I'm having the same issue that form parameters are not sent. I tried the `updatePetWithForm` endpoint from petstore example as well and got he same problem:

```javascript
var client = require("swagger-client");

var swagger = new client.SwaggerClient({
  url: 'http://petstore.swagger.io/v2/swagger.json',
  success: function() {
    swagger.apis.pet.updatePetWithForm({petId: 123, name: 'new-name', status: 'new-status'});
  }
});
```

But from the result of tcpdump, no post data is sent:

```
POST /v2/pet/123 HTTP/1.1
user-agent: Shred
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Content-Length: 0
Host: petstore.swagger.io
Connection: keep-alive
```

However, `asCurl` seems to work:

```
> console.log(swagger.apis.pet.updatePetWithForm.asCurl({petId: 123, name: 'new name', status: 'new status'}));

curl -X POST --header "Content-Type: application/x-www-form-urlencoded" --header "Accept: application/json" -d "name=new%20name&status=new%20status" "http://petstore.swagger.io/v2/pet/123"
```

Running the above curl command does send the data as expected:

```
POST /v2/pet/123 HTTP/1.1
User-Agent: curl/7.37.1
Host: petstore.swagger.io
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Content-Length: 31
name=new-name&status=new-status
```

**Comment by whitlockjc** [comment]
When was the last time you tried it?  It seems you're using an old version as the `User-Agent` should no longer be `Shred`.  Can you do a fresh build of the `develop_2.0` branch and try that?

**Comment by xhh** [comment]
@whitlockjc I tried just before I posted that comment, using swagger-client installed via `npm install swagger-client`, i.e. version 2.1.10-M1.

I'll have a look how to build and try it with develop_2.0.

**Comment by xhh** [comment]
fyi, tested with the latest swagger-client in node.js and browser, both work with form params now
