### ISSUE TITLE
Use of the "$ref" and "allOf" keywords outside of their place, throw errors

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-js#1196]
Use of the `$ref` and `allOf` keywords in _freely-namable-areas_, such as Model names, property names, etc - will throw an error.

This is taken from https://github.com/swagger-api/swagger-editor/issues/1343

Steps:
(I created a failing test case here: https://github.com/swagger-api/swagger-js/pull/1195 )

**Comment by ponelat** [comment]
A possible "workaround" is to simply ignore the error messages. But that isn't exactly desirable.

**Comment by RHackrid** [comment]
I have the same problem for a API with a implementation of the SCIM specification [http://www.simplecloud.info/].

> By convention, a reference is commonly represented as a "$ref"
   sub-attribute in complex or multi-valued attributes; however, this is
   OPTIONAL. [https://tools.ietf.org/html/rfc7643#section-2.3.7].

JSON-Example (User Representation):
`{
  "schemas": ["urn:ietf:params:scim:schemas:core:2.0:User"],
  "id": "2819c223-7f76-453a-919d-413861904646",
  "userName": "bjensen@example.com",
  "groups": [
    {
      "value": "e9e30dba-f08f-4109-8486-d5c6a331660a",
      "$ref":
"https://example.com/v2/Groups/e9e30dba-f08f-4109-8486-d5c6a331660a",
      "display": "Tour Guides"
    }
  ],
  "meta": {
    "resourceType": "User",
    "created": "2010-01-23T04:56:22Z",
    "lastModified": "2011-05-13T04:42:34Z",
    "version": "W\/\"3694e05e9dff590\"",
    "location":
     "https://example.com/v2/Users/2819c223-7f76-453a-919d-413861904646"
  }
}`

Our customers won´t understand why our 'official' API documentation shows error messages. It´s impossible to hide error messages by default, isn´t it?

**Comment by ponelat** [comment]
@RHackrid  how are you showing the errors? Via swagger-editor/swagger-ui, or custom?

**Comment by shockey** [comment]
This should have been fixed in https://github.com/swagger-api/swagger-js/pull/1195 :thinking:

**Comment by RHackrid** [comment]
We are showing errors via swagger-editor. I can confirm the fix. I didn't notice the fix on the 8. Feb. 2018. Thanks! :)

**Comment by shockey** [comment]
Seems like this is handled; closing!
