### ISSUE TITLE
POST going with content type as json instead of url encoded string

### ISSUE THREAD

**Issue by deostroll** [swagger-api/swagger-js#1199]
We are still on loopback 3.x. We have created a remoteMethod with the following signature:

```
  MyModel.getInfo = function(name, options, cb) {
    MyModel.findOne({ where: { name }} , options, (err, result) => {
      if (err) {
        cb(err);
      }
      else {
        cb(null, result);
      }
    });
  };

  MyModel.remoteMethod('getInfo', {
    description: 'Gets info about service',
    accepts: [
      {
        arg: 'name',
        type: 'string',
        required: true,
        description: 'name of the service'
      }
    ],
    returns : {
      arg: 'response',
      type: 'object',
      root: true
    },
    http: {
      verb: 'POST',
      path: '/getInfo'
    }
  })
```
This renders find in the swagger-ui as shown below:

![image](https://user-images.githubusercontent.com/415336/33595147-e22b0aea-d9bc-11e7-8ae6-150937f3cc63.png)

However, on execute the request that gets issued with content-type 'json':

![image](https://user-images.githubusercontent.com/415336/33595268-62372764-d9bd-11e7-920d-d99bf8d509d3.png)

However, the problem doesn't stop there. 

What would one do in a situation where the payload has some string parameter and something else...like a json body? Ultimately yes, the swagger-client must be clever enough to figure out.. 

>oh dear...this looks like a HTTP POST request where one argument is `formData`,  and one of the the other argument content-type `json`...so I shall convert the first one to a json format and perform this request.

Honestly I don't know if this is the best course of action. I am not sure if this problem is with the swagger-client either. Perhaps there is a correct way of handling this in the front-end. Please advise.

**Comment by webron** [comment]
Which version of swagger-ui have you tested this with? We'd also need to see your API definition.

**Comment by deostroll** [comment]
Whatever swagger-ui version in petstore app. I'll need some time to manufacture a minimal swagger json example pertinent to this issue.

**Comment by deostroll** [comment]
Hi. Sorry for the long gap.

Swagger.json: https://gist.github.com/deostroll/851e3f604ab9c66fbb64ce91d97642a7

Code for remote method:

```
'use strict';

module.exports = function(Person) {
  Person.getWithLimit = function(limit, options, cb) {
    Person.find({}, function(err, result) {
      if (err) {
        cb(err)
      }
      else {
        cb(null, result.slice(-limit))
      }
    });
  };

  Person.remoteMethod('fetch', {
    accepts: {
      arg: 'limit',
      type: 'number',
    },
    returns: {
      arg: 'response',
      type: 'object',
      root: true
    },
    http: {
      verb: 'post',
      path: '/fetch'
    }
  })
};
```

**Comment by deostroll** [comment]
any update on this?

**Comment by shockey** [comment]
Hi @deostroll!

I'm looking at the definition that you provided - which operation should I be playing with to see this happening?

**Comment by char0n** [comment]
Hi @deostroll,

I'll just re-iterate @shockey question: *which operation should I be playing with to see this happening?*

**Comment by char0n** [comment]
Closing for insufficient information.
