### ISSUE TITLE
possible to disable urlencoding of url paths swagger-js 2.x

### ISSUE THREAD

**Issue by mjkkirschner** [swagger-api/swagger-js#1210]
I have a path which includes `:`s - is it possible to not url encode this when the value is added to a path like:

base.com/api/project/:id

**Comment by mjkkirschner** [comment]
just wanted to report that I am using a `request interceptor` to decode the url path before sending it, incase anyone else ran into this.

**Comment by shockey** [comment]
We're encoding `:` by default since it's an [RFC 3986 Reserved character](https://tools.ietf.org/html/rfc3986#section-2.2).

Using a request interceptor is the best move if you want to override this :smile: 

Closing as resolved, feel free to comment if there are any other thoughts.

**Comment by AyoAlfonso** [comment]
@shockey this is an old issue but  how did you use the request interceptor

**Comment by char0n** [comment]
@AyoAlfonso please have a look at [requestInterceptor documentation](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md#request-interceptor). You can intercept request URL and modify it before it's being used.
