### ISSUE TITLE
Can't set 'Authorization' header on requests

### ISSUE THREAD

**Issue by robotoer** [swagger-api/swagger-js#1226]
Hi swagger-js team!

I've been trying to use swagger-js to make queries against an API that I maintain but haven't been able to successfully make a request that has the `'Authorization'` header set. I am currently using swagger 2.0 with swagger-js v3.4.4. I am using the browser client.

I have tried the following methods:
- Adding a `securityDefinitions` object to the api spec with the `"oauth2"` type and adding a corresponding authorizations entry on swagger-js initialization.
- Adding a `securityDefinitions` object to the api spec with the `"apiKey"` type and adding a corresponding authorizations entry on swagger-js initialization.
- Implementing a `requestInterceptor` method that adds the `'Authorization'` header to all requests. I have verified that the method correctly mutates the `header` object with no resulting change to the actual request.

All requests were checked using chrome devtools and verified to not contain the `'Authorization'` header. How am I supposed to set the `'Authorization'` header on requests without re-implementing the userFetch method?

**Comment by robotoer** [comment]
Oh, also, while poking around trying to figure out why the authorization header wasn't showing up, I found that the userFetch method is receiving the correct authorization header while using an `"apiKey"` type `securityDefinition`. This header still never makes it into the actual request.

**Comment by robotoer** [comment]
Ah, I figured it out. I had incorrectly implemented CORS requests in my server and wasn't accepting the OPTIONS request which was correctly being sent without any of my headers.

Once fixed, requests work as expected.

**Comment by prees1** [comment]
Had the same issue and can confirm that setting CORS for the requests, the header modification works.
