### ISSUE TITLE
Docs Need Major Update

### ISSUE THREAD

**Issue by leafoflegend** [swagger-api/swagger-js#1228]
The docs for this repo include one Migration Doc, and one Graveyard doc. There is less then a page of explanation of how to use this library. This is an awesome library and deserves a thorough documentation revamp.

**Comment by dleistn1** [comment]
Definitely + 1, I start using the lib a few days ago and ended up reading the source code to decrypt the possible options and the interfaces of the different properties are (especially auth is a fu****g pain)

**Comment by char0n** [comment]
Created first [PR](https://github.com/swagger-api/swagger-js/pull/1506) that should increase the documentation coverage and quality of our documentation. I've started with a `Swagger specification resolver`.

**Comment by char0n** [comment]
Documentation has been consolidated into [docs/](https://github.com/swagger-api/swagger-js/tree/master/docs) directory.
