### ISSUE TITLE
Configure xhr.responseType on request for binary data

### ISSUE THREAD

**Issue by mrhanlon** [swagger-api/swagger-js#123]
I have an API returning binary data. I'm trying to figure out how to set the `xhr.responseType='arraybuffer'` so I don't get content encoding errors.

``` javascript
/* swagger api... */
myApi.download({filePath: '/path/to/file.txt.gz'}, function(resp) {
  /* here resp.data is the binary data, but full of Unicode error/replacement characters */
});

/* alternatively... */
var xhr = new XMLHttpRequest();
xhr.open('GET', 'http://api.example.com/download//path/to/file.txt.gz');
xhr.responseType = 'arraybuffer';
xhr.onload = function(resp) {
  if (resp.target.readyState === 4) {
    var arraybuffer = xhr.response;
    // do stuff with arraybuffer...
  }
};
xhr.send();
```

I've tried passing in `{responseType: 'arraybuffer'}` with the options but without luck. Digging in the source I'm not seeing anything on how to get access to the underlying XHR object.

Thanks in advance for looking!

Regards,
Matt.

**Comment by vivex** [comment]
still not fixed. ?

**Comment by codler** [comment]
I have the same issue as @vivex 
@fehguy could you reopen this?

**Comment by dthorpe** [comment]
+1

**Comment by fehguy** [comment]
added long ago
