### ISSUE TITLE
Allow client API to perform OPTIONS requests as its request method

### ISSUE THREAD

**Issue by lduros** [swagger-api/swagger-js#1256]
I'm using the django-rest-framework for my API in the backend as well as django-rest-swagger.
It all works very well with swagger-js and I'm able to get my apis object from the client with a number of methods for each endpoint. However, I would like to perform an OPTIONS request to dynamically generate my form. Django Rest Framework provides information as JSON on the structure of the data that is expected to be sent, helper text, labels, etc, that I use to generate a form dynamically.
An example of the type of response an OPTIONS request providers in the Django Rest Framework:

```
{
    "name": "Register",
    "description": "",
    "renders": [
        "application/json",
        "text/html"
    ],
    "parses": [
        "application/json",
        "application/x-www-form-urlencoded",
        "multipart/form-data"
    ],
    "actions": {
        "POST": {
            "username": {
                "type": "string",
                "required": true,
                "read_only": false,
                "label": "Username",
                "min_length": 1,
                "max_length": 150
            },
            "email": {
                "type": "email",
                "required": true,
                "read_only": false,
                "label": "Email"
            },
            "password1": {
                "type": "string",
                "required": true,
                "read_only": false,
                "label": "Password1"
            },
            "password2": {
                "type": "string",
                "required": true,
                "read_only": false,
                "label": "Password2"
            }
        }
    }
}
```
You can see in this JSON response that useful information is provided to create a form that will then be used to send a POST request.
Currently, swagger-js appears to not offer any way to perform an OPTIONS request using the methods provided through client.apis.myapi.[methodname].

If you can think of a workaround I could do to get the OPTIONS without having to rely on a plain fetch and hardcoding the path to the endpoint, this could be a temporary solution to this issue. Otherwise, an optional parameter to override the method in the api methods would be really ideal. I'm trying to find a way to override swagger-js in order to do this, so any suggestion is welcome.

Thank you,

**Comment by lduros** [comment]
Thank you for your answer. As I'm using django-rest-swagger to automate this, I'm not sure if there's a way to get control of this. I will ask the django-rest-swagger repo. Many thanks for the pointer!

**Comment by lduros** [comment]
Closing issue. Thanks.

**Comment by llund** [comment]
@lduros Were you able to find an answer to this? My google-foo fails to find anything in django-rest-swagger.
