### ISSUE TITLE
Securities are clunky and unintuitive to use 

### ISSUE THREAD

**Issue by eropple** [swagger-api/swagger-js#1258]
Hey there--

As per conversation on IRC, @webron pointed me towards filing a ticket for a curious issue I'm running into. Or, rather, *was* running into; I solved it in the course of writing this bug report. Given that the documentation is thin on the ground, I figured I'd file a bug for anybody else who might be running into the problem I solved here but also to perhaps (as I'm [getting invested into the OAS3 ecosystem](https://github.com/modern-project/modern-ruby)) have a discussion about user-friendliness and predictability.

I'm using swagger-js 3.5.1 with a nothing-special specification, which you can find [here](https://gist.github.com/eropple/2ffa0dbefc97a8db37abd82053b989d5) My document specifies `apiKeyDealConvertV1`, a header API key parameter. But, when working with `swagger-js`, there be (usability) dragons.

Consider an account invoked with a method like this:

```js
import Swagger from 'swagger-client';

export async function buildClient(openapiUrl, userToken = null, attachToWindow = true) {
  console.debug(`Loading OpenAPI spec from ${openapiUrl}. Has token: ${!!userToken}`);

  const securities = {};
  if (userToken) {
    securities.apiKeyDealConvertV1 = userToken
  };

  const requestContentType = "application/json";
  const responseContentType = "application/json";

  const client = await Swagger(openapiUrl, { securities, requestContentType, responseContentType });

  if (window && attachToWindow) {
    window.apiClient = client;
  }

  return client;
}
```

Not rocket surgery, but when I wrote this I was very much YOLOing it, as doc is thin on the ground. Anyway, non-secured methods work fine, everything's peachy, I can log in and get the magic token that goes _back_ into that method to create a secured client. (I assume, though I never tested, that I could update the client object itself instead of generating a new one. True? False? I'm using React and injecting this as a context object, so I'd rather create a new one instead of mutating an old one, but it'd be good to know.)

The tricky part comes when trying to actually _use_ the client. Forgive the clunky pastes below, but it's all out of the Chrome console.

```
console.log(apiClient.securities)
=> {apiKeyDealConvertV1: "O2MDC_98CA3FA75ABB56D2BFED34FF2E"}
```

(This is a test key in a test environment, so I don't care about pasting it!)

OK, so let's try to use it.

```
resp = await apiClient.execute({ operationId: "get_current_user", parameters: { studio_code: "turnstyle" } })
=> GET http://localhost:11800/dealconvert/turnstyle/auth/me 401 (Unauthorized)
```

That's weird. I know my security is correct. Checking the Network tab's request headers:

```
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9
Connection:keep-alive
DNT:1
Host:localhost:11800
Origin:http://localhost:3000
Referer:http://localhost:3000/?d=turnstyle
User-Agent:Mozilla/5.0 (Linux; Android 5.1.1; Nexus 6 Build/LYZ28E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Mobile Safari/537.3
```

No bueno. Let's be explicit:

```
resp = await apiClient.execute({ operationId: "get_current_user", parameters: { studio_code: "turnstyle" }, securities: apiClient.securities })
=> GET http://localhost:11800/dealconvert/turnstyle/auth/me 401 (Unauthorized)
```

Into the tests I go, and I end up solving the problem by wrapping the authorizations inside an `authorized` object, so we have:

```js
{ securities: { authorized: apiClient.securities } }
```

This also works for the tags interface, which was the _original_ thing I was writing this issue about.

*This is pretty undesirable* and, from outside swagger-js, seems like typing for the sake of typing. So, being a programmer, let's figure out how another smart programmer made it so I don't have to copy-paste forever. But when I try:

```
apiClient.securities
=> {authorized: { apiKeyDealConvertV1: "O2MDC_98CA3FA75ABB56D2BFED34FF2E" }}

resp = await apiClient.execute({ operationId: "get_current_user", parameters: { studio_code: "turnstyle" } })
=> GET http://localhost:11800/dealconvert/turnstyle/auth/me 401 (Unauthorized)
```

I'm sure you've already found the issue, because now I have too: it's `authorizations` in the opts hash for a Swagger client, but `securities.authorized` when executing. This _poleaxed_ me, and I was mislead by `.execute` being on my _returned_ Swagger object when it appears to be trying to return it, and you pass `securities` to `.execute`!

So, to sum up, some things that are really confusing and might be worth discussing:
- Should `Swagger` and the objects yielded from `Swagger()` have a prototype relationship? You can also call `.resolve` on a client, and that seems really weird. It makes `applyDefaults` feel very spooky-action-at-a-distance, especially being called _within_ `.execute`.
- The authorizations/securities confusion is real and it's a thing. I wonder if there isn't an API-consistent way to allow for either.
- If you're defaulting securities...maybe swagger-js should default parameters too? The way this API is structured is that every user interacts with only a single `studio_code`, being able to default that in my requests seems obvious?

I really like OAS3 a lot (I wrote a web framework for it and I'm elbow-deep in a Ruby OAS3 client, I had _better_ like it!), but this has been a frustrating afternoon of grinding over code to understand what something I could've just _written_ can do, so I'd like to hope that some positive value can be realized from it. Happy to help where I can.

Thanks!

**Comment by shockey** [comment]
@eropple, thank you for the feedback!

You're right - the authorization is one of the more awkward parts of Swagger-Client. Some of the points you raised can only be fixed with breaking changes, so they aren't likely to change in the short-term, but when we move beyond 3.x I hope to make the various client APIs more harmonious 😄

**Comment by andylockran** [comment]
Thanks for the write up. I was getting confused with this earlier and now it all makes sense

**Comment by levisegal** [comment]
Want to add to this issue, at least some documentation stating that the securities object on the buildRequest method need to be nested under an "authorization" key would have saved me a few hours of time.

**Comment by devth** [comment]
I spent hours trying to get authorizations to work until I found this issue! Thanks @eropple.

**Comment by GreGosPhaTos** [comment]
Yes thanks @eropple that was helpful ! 
@shockey any progress on documenting this part ? 

Thanks guys !

**Comment by char0n** [comment]
Hello everybody,

Yes securities are pretty "clunky" in current version. As @shockey pointed out we will have opportunity to make API more harmonious in next major release.

For now, we've documented how to use securities with current 3.x API:


[Securities](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/try-it-out-executor.md#tryitout-executor) with concrete examples.

When using `execute` method on Swagger client instance, the API is slightly [different](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/try-it-out-executor.md#alternate-api).

[Passing securities to Tags Interface](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/tags-interface.md).

Related issue to this one: https://github.com/swagger-api/swagger-js/issues/1476

If you feel me missing something in the current documentation about how to use securities, please let us know.
