### ISSUE TITLE
Feature request : registering response interceptors

### ISSUE THREAD

**Issue by laurentperez** [swagger-api/swagger-js#126]
Hi
I'd like to feature request the ability to register a response interceptor, much like you can register request "interceptors" by populating window.authorizations with custom parameters.
I know this can somehow break the stateless nature of a call, given that I could reuse parts of the response to alter future requests. But it'd be the sole caller responsibility.
My use case is : I call a login service, it gives me a security token, and I have to use the token for other api requests.
I hacked swagger.js to retain the response object in localStorage, but it's ugly.
Objections ?

**Comment by fehguy** [comment]
hi, i think this is a good feature but we need to be careful about both the signature and nature of the calls.  For instance, it's fine if it's a synchronous interceptor but doing something that chains the response in a callback will certainly break the clients.

I'd like to push this into a future release but keep the feature request open so we can work through first the ideal behavior, and next the signature for the interceptor.

**Comment by whitlockjc** [comment]
I think we should work on this when we [make SwaggerHttp pluggable](https://github.com/swagger-api/swagger-js/issues/239).

**Comment by fehguy** [comment]
now that [SwaggerHttp is pluggable](https://github.com/swagger-api/swagger-js/pull/428), this poses another challenge.  Should the interceptor be handled in the pluggable client?  Looking into this more.
