### ISSUE TITLE
Basic auth on initial schema fetch request

### ISSUE THREAD

**Issue by lduros** [swagger-api/swagger-js#1260]
I instantiate a Swagger client as follows:

```
Swagger(`${url}schema/`, {
        authorizations: {
          basic: {username: username, password: password}
        }
      }).then(client => { ...});
```

This works just fine as my schema endpoint does not require basic auth, but not being authenticated only yields a subset of all the API endpoints available. I would like to perform a basic auth for the initial schema fetch. I expected the authorizations object as above to do the trick, however, it does not. Adding other params in there results in a silent error, I get no traceback as to what the error and no request is performed at all.
Could someone point toward the right way of doing this from the client? I do not have full control of the server.

I should also mention that basic is indeed a defined security, as what I'm getting back from the client in javascript shows the following:
```
securityDefinitions : {
  basic: {type: "basic"}
}
```

But this shouldn't even really matter, because I want to perform a basic auth before the schema is even received or parsed.
In the end all I'm trying to get is something that looks like this in the request headers:
authorization:Basic [base64 encode user:pass]=

Many thanks,

**Comment by lduros** [comment]
I should also mention that basic is indeed a defined security, as what I'm getting back from the client in javascript shows the following:
```
securityDefinitions : {
  basic: {type: "basic"}
}
```

**Comment by shockey** [comment]
Hi @lduros!

> But this shouldn't even really matter, because I want to perform a basic auth before the schema is even received or parsed.

Your intuition is correct: the security definitions in your document don't affect the initial request for the document, because Swagger-Client doesn't have the information yet 😄 

You can use the `requestInterceptor` option to attach information to the initial request:

```js
const swaggerClient = require("swagger-client");

const swaggerUrl = 'https://petstore.swagger.io/v2/swagger.json'

swaggerClient(swaggerUrl, {
  requestInterceptor: req => {
    if(req.url === swaggerUrl) {
      // we're fetching the definition
      req.headers.Authorization = "Bearer Asdf1234ThisIsMyToken"
    }

    return req
  }
})
```

Note that this request interceptor is used for _all_ requests, so you need the `if(req.url === swaggerUrl)` bit to make sure the request you're modifying is the document request.

Hope this helps!

**Comment by lduros** [comment]
Awesome, I had used requestInterceptor before, but then thought there was another way.
Great to know and thank you for your prompt answer and help!
