### ISSUE TITLE
Set request headers dynamically & Use functions

### ISSUE THREAD

**Issue by karllson** [swagger-api/swagger-js#1263]
Hey guys,

I'm working on a react application and set up my SwaggerClient like this: `Swagger('myschema.json')`.
I do this on app start, so that I can share the clients instance for the apps lifetime. I also can use the provided functions (e.g. `client.apis.pet.addPet`) this way.

Now i'm facing the problem, that I need an authorization header, but only for some endpoints. Is there a possibility to add headers dynamically without calling the json schema url (and getting the client) on every request. In that case I could instantiate a new Client with requestInterceptors on every request, if I understood the docs correctly.

Can I use `http()`for this **and** also use the provided functions (don't use the url as a string)?

Hope you get my problem,

thanks in advance!

**Comment by karllson** [comment]
I think I solved my problem.

If you instantiate your client before and then hit a route like this: `client.apis.pet.addPet` it's also possible to pass a second parameter, which also "accepts" interceptors.

So I ended up doing this: `client.apis.pet.addPet(myPayload, {requestInterceptor: () => ...});`

Is this the way to solve this problem/a correct approach? If yes, are you guys open for doc update PRs?

Thanks in advance

**Comment by shockey** [comment]
Hey @karllson! Yeah, the second argument to a tag interface method is `opts` (see the second function signature [here](https://github.com/swagger-api/swagger-js/blob/master/src/interfaces.js#L18], which is `(parameters, opts = {})`). Using opts is one  way to do this on a per-endpoint basis; the other  way is to define a global requestInterceptor but decide whether to modify the request based on the request metadata.

As for the GET operation: even if you aren't defining any parameters, Swagger-Client expects the first argument to be a parameter object - so you should call it like this: `client.apis.whatever.myGetStuff({}, {requestInterceptor: r => ...})`

---

FYI, defining your authorization header in your OpenAPI document is better than using requestInterceptor at all. OpenAPI supports describing a lot of common authorization schemes out of the box, here's some information on that: https://swagger.io/docs/specification/authentication/

**Comment by karllson** [comment]
Good morning @shockey,

thank you so much for clarify things a bit. I think this issue can be closed. 
I maybe will write a blog post about the different approaches. 

If I do so, I will definitely send you the link!

Have a good day !

**Comment by webron** [comment]
Thanks, @karllson!

**Comment by notyoyoma** [comment]
Hey @karllson, did you ever write that blog post? I'm working on a similar setup, and would love to hear how things went for you.
