### ISSUE TITLE
Name generation changes

### ISSUE THREAD

**Issue by djMax** [swagger-api/swagger-js#1269]
It seems that 3.0 changes the way names are generated from URLs. This causes major headaches for us - GET /foo/{bar}/baz used to be get_foo_bar_baz and now it's get__foo__bar_baz, and in addition to the extremely problematic task of updating everything, it ends up creating non-lint-passing identifiers in a bunch of cases, such as /foo/{bar} being get_foo__bar_, which airbnb's linter does not like.

1. This should probably be fairly prominent in the migration guide, I probably wouldn't even have tried had I known
2. It would be nice to be able to turn this off - is there a switch for that?

**Comment by djMax** [comment]
This logic seems gone:
https://github.com/swagger-api/swagger-js/blob/2.x/lib/client.js#L661

**Comment by shockey** [comment]
Hmm... I agree with you that the new format is less intuitive, but we wouldn't be able to change this without a breaking change.

We _could_ add an option to provide a custom method name generation function, and even build in an option for 2.x compatible names.

**Comment by webron** [comment]
@shockey that's an interesting option. @djMax would that help with your case?

**Comment by djMax** [comment]
So I have a module between swagger-client and our applications: https://github.com/gas-buddy/configured-swagger-client

I do a variety of unholy things in there now to try and make the transition from 2 to 3 less painful.

* I munge names like they used to be
* I add an obj property to the response that throws an error in dev but works silently in prod
* I modify the passed in swagger spec to include a "consumes" property if there isn't one
* I delete the url property when a spec is passed, because if I don't, swagger-client fetches that URL even if it has the content in the spec property
* I make more useful stack traces than "process._tick"
* I add the contents of "apis" back to the root client object
* I proxy all methods to enable header insertion that includes a cross-service correlation id.

So I don't like having to do all these things, but I don't need new workarounds in swagger-js.

**Comment by djMax** [comment]
I think perhaps what would've been easier is two majors for some of the changes. Throwing errors instead of objects - universally a good thing and a reasonable thing to break in a major. Changing "obj" to "body" - stylistic and would've been just as easy to do both for a version and then move away. And then I think the other point I've been trying to make is that the migration guide is not especially complete, so that'd be good to update I think.

**Comment by webron** [comment]
Yeah, the migration guide is challenging for other reasons. Feedback like yours definitely helps us focusing on the missing pieces though, so thanks for pointing those out.

**Comment by shockey** [comment]
No promises on a fix, but I will put eyes on this issue this week 😄

**Comment by shockey** [comment]
@djMax, `v2OperationIdCompatibilityMode` has been added to Swagger-Client, and will be available as part of our release tomorrow night.

I ported the generator logic directly from the 2.x code, and added your example as a test case.

**Comment by shockey** [comment]
@RdeWilde, this is just for the tags interface (`clients.apis`). 

Duplicate operationIds within the same Swagger/OpenAPI document are still invalid, even if they don't share tags or methods:

> **`operationId`**: Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.
> 
> [Swagger/OpenAPI 2.0 Specification: Operation Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object)

&nbsp;

> **`operationId`**: Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is RECOMMENDED to follow common programming naming conventions.
>
> [OpenAPI 3.0 Specification: Operation Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#operation-object)
