### ISSUE TITLE
Strange behavior of authorizations

### ISSUE THREAD

**Issue by aurelienlt** [swagger-api/swagger-js#127]
Hi

I'm trying to play with authorizations, and I'm a bit puzzled about its behavior.

First, line 1197 `status = e.authorizations.apply(obj, this.operation.authorizations);`, the absence of `var status` somewhere gives a strange behavior (the status is turned into string, I don't know why but make it fail). I notice that if `status === false`, the request is translated (sounds logical).

Second, the specification says 

> If multiple authorization schemes are described, they are **all required** to perform the operations listed.

So why in `SwaggerAuthorizations.prototype.apply` I can see everywhere:

    if (result === true)
      status = true;

Shouldn't be the contrary ?

Finally, I'm a little puzzled about where authorizations are required, and why there are so many calls to `window.authorizations`. As I read the spec, looks like
* authorizations must be declared in the resource listing (but it's only a declaration), so why calling it line 165 : 

> Provides information about the authorization schemes allowed on this API.

* authorizations might be referenced in ressources, only to inform that they will be required in every operation of this resource (unless said otherwise in the operation), so why calling it line 385 (moreover without any argument) : 

> A list of authorizations schemes required **for the operations listed in this API declaration**.

* authorizations might be referenced in the operations, and it overrides the ressource's authorizations, so why an operation does not inherit from its ressource's authorizations, and why `SwaggerAuthorizations.prototype.apply` called with an empty object does assume that every authorization is required: 

> A list of authorizations required to execute this operation. While not mandatory, if used, it overrides the value given at the API Declaration's authorizations. **In order to completely remove API Declaration's authorizations completely, an empty object ({}) may be applied**.

I hope I have been clear enough, thank you.

**Comment by fehguy** [comment]
this should be addressed in develop_2.0
