### ISSUE TITLE
GET requests not work at all with cookies

### ISSUE THREAD

**Issue by psy21d** [swagger-api/swagger-js#1279]
swagger does not send cookie to get requests! At all!
But in post requests all done. Why?

Now i add 2 strings to generated js code (lines 19, 20)
` 
config = config || {};
config.withCredentials = true;
`
and make headers on server.

I searched problem carefully, and i realized that the cookies  are not sent again in GET requests

**Comment by shockey** [comment]
@psy21d what Swagger-Client version are you using?

**Comment by psy21d** [comment]
`YAML = require('yamljs');
 
// Load yaml file using YAML.load 
nativeObject = YAML.load('swagger.yaml');

const swaggerGen = require('swagger-vue')
const jsonData = nativeObject
const fs = require('fs')
const path = require('path')

let opt = {
  swagger: jsonData,
  moduleName: 'api',
  className: 'api'
}
const codeResult = swaggerGen(opt)
fs.writeFileSync(path.join(__dirname, './dist/api.js'), codeResult)`

I use https://www.npmjs.com/package/swagger-vue

I guess I'm a little confused. I see it is not original swagger. Sorry, if not at the address.
Is it possible to use the original latest version of the swagger generator to get api js? 
Where can you find information about this?

**Comment by shockey** [comment]
`swagger-vue` is a different project 😄 here's their GitHub, maybe you can find help there: https://open.spotify.com/track/6d8MHAb3LSuAz42yyDM4q1?si=qwducChPTD-TM1b0npveyg

**Comment by shockey** [comment]
`swagger-vue` is a different project 😄 here's their GitHub, maybe you can find some help there: https://github.com/chenweiqun/swagger-vue/issues
