### ISSUE TITLE
Wrong repository name for kyleshockey/object-assign-deep@^0.4.0

### ISSUE THREAD

**Issue by nknol** [swagger-api/swagger-js#1319]
```
npm ERR! code E404
npm ERR! 404 Not Found: @kyleshockey/object-assign-deep@^0.4.0
```

https://github.com/swagger-api/swagger-js/commit/f328f47d7b0dc87b74f929e162a204118eea2704

**Comment by shockey** [comment]
@nkol, what package manager (and version) are you using?

**Comment by nknol** [comment]
npm 3.10.10

**Comment by shockey** [comment]
@nknol, I can install the project with npm 3 just fine:

```sh
➜  js git:(master) node -v
v6.14.2
➜  js git:(master) npm -v
3.10.10
➜  js git:(master) npm install
[output removed, it was a regular successful install]
➜  js git:(master) npm ls | grep object-assign-deep
├── @kyleshockey/object-assign-deep@0.4.1
```

**Comment by nknol** [comment]
Will try that in a bit, I do know that two other of my coworkers had the same problem, but it might be our environment. Will let you know.

**Comment by shockey** [comment]
@nknol great, thanks.

Also check that you're not using a private registry or npm proxy:

```sh
➜  ~ npm config get registry
https://registry.npmjs.org/
➜  ~ npm config get proxy   
null
```

If you're on a corporate network, be aware that you might be behind a network-wide proxy that's causing these issues.

**Comment by nknol** [comment]
We are definitely behind a proxy that is supposed to act as a pass-through for npm packages that we don't publish ourselves, which could definitely be the culprit. If you don't hear back from me soon it's probably safe to assume the fault is on our end.

**Comment by nknol** [comment]
Apparently it's a problem with our Sinopia server, switched to Verdaccio at the advice of another dev (which I guess we already for the exact same reason) and everything installed fine.  Sorry for the bother.

**Comment by shockey** [comment]
@nknol no problem! glad you got it sorted out 😄
