### ISSUE TITLE
Create OAS compatibility section in the README

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-js#1329]
It would be nice to have a note or two on which OAS versions this project supports.
Similar to https://github.com/swagger-api/swagger-ui/#compatibility

cc @webron

**Comment by char0n** [comment]
@ponelat I can do that, but would appreciate help reconstructing this information. I can see two major version of swagger-client: 2.x and 3.x. In order for me to reconstruct this information I'd need to go through the releases and commit messages and not sure if time invested into reconstructing this is worth the compatibility table.

What I can do now is to create compatibility table and mention OAS 2.0 and OAD 3.0.z only, and not go to deeper history.

**Comment by ponelat** [comment]
@char0n I've honestly forgotten about this issue :D 
The table should be simple. What version(s) of OAS does swagger-client 2.x support and what version(s) of OAS does swagger-client 3.x support? Do not need deeper than that.

**Comment by char0n** [comment]
@ponelat implemented in https://github.com/swagger-api/swagger-js/pull/1622. Let me know via code review if it's OK with you. 

Thanks!

**Comment by char0n** [comment]
I'm going to go ahead and merge this PR. @ponelat please let me know if there is something I should change ex-post.

**Comment by ponelat** [comment]
all good, thanks @char0n
