### ISSUE TITLE
Resolving issues in minified builds

### ISSUE THREAD

**Issue by drschulz** [swagger-api/swagger-js#1344]
### Q&A (please complete the following information)
 - OS: macOS
 - Environment: Chrome 67.0.3396.99, Node.js v8.9.1
 - Method of installation: npm
 - Swagger-Client version: 3.8.8
 - Swagger/OpenAPI version: Swagger 2.0

Swagger-Client usage:
```js
Swagger.resolve({url})
```

### Describe the bug you're encountering
It seems that with the latest patch (3.8.8), I'm seeing some issues with resolving between different builds in my project. In my development builds resolving works just fine, all refs are correctly replaced. But in prod builds (which are minified and optimized), no ref replacement or allOf replacement happens at all. I tracked down why, `isGeneratorFunction` is returning false in my prod builds for all the wrapped plugins, so none are getting run.

### To reproduce...
Still trying to figure this out myself, but it may have to do with minification. Because that is the only difference between my production webpack config and development webpack config.

1. Build a project with Webpack and use the UglifyJsPlugin (`uglifyjs-webpack-plugin`)
2. Try to resolve a Swagger 2.0 json file with refs.

### Expected behavior
The resolution should have been the same regardless of the build, especially because it was working just fine in v3.8.6.

### Additional context or thoughts
I think this may be related to changes made in this patch: https://github.com/swagger-api/swagger-js/pull/1203. Version 3.8.6 works perfectly for me in both builds. I've tested on multiple projects. It looks like swapping libraries may have caused this, a possible fix may be to use the library that babel-runtime is using under the hood? (https://www.npmjs.com/package/regenerator-runtime). I haven't tried this myself.

**Comment by shockey** [comment]
Thanks for the report, @drschulz - there's a sibling issue over at Swagger UI for this: https://github.com/swagger-api/swagger-ui/issues/4720
