### ISSUE TITLE
Resolver error - Cannot read property '0' of undefined (it's is back)

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-js#1362]
_From @ofavre on August 3, 2018 11:54_

### Q&A (please complete the following information)
 - OS: Linux
 - Browser: Chrome
 - Version: 67.0.3396.99
 - Method of installation: https://editor.swagger.io
 - Swagger-UI version: Probably the latest, 3.17.6 as of this writing
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
swagger: '2.0'
info:
  title: Test
  version: '1.0'
basePath: /
schemes:
  - https
paths:
  /get:
    get:
      summary: Gets things
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/A'
definitions:
  D:
    type: object
    properties:
      z:
        type: string
        description: Some Z string
  C:
    type: object
    properties:
      d:
        title: D
        allOf:
          - description: Some D
          - $ref: '#/definitions/D'
  B:
    type: object
    properties:
      c:
        title: C
        allOf:
          - description: Some C
          - $ref: '#/definitions/C'
  A:
    type: object
    properties:
      b:
        title: B
        allOf:
          - $ref: '#/definitions/B'
          - description: Some B
```

Swagger-UI configuration options:
No idea, I'm testing on editor.swagger.io.

### Describe the bug you're encountering

In essence, #3366 is back, or had only been partially fixed.

### To reproduce...

1. Go to https://editor.swagger.io/
2. Enter the Swagger above
3. Expand anything you will until you reach the definition of A under the models.
   Check that you see no error (in your console or the top of the document.
3. Now expand `A` in the models list
4. Scroll top and you'll see 4 time the error: `Resolver error - Cannot read property '0' of undefined`.

### Expected behavior

The visual output is fine in this example, however there are javascript errors emitted (and the online editor shows them).

### Screenshots

![image](https://user-images.githubusercontent.com/95129/43641478-2776feae-9724-11e8-8e3f-45ebf7c0b756.png)

### Additional context or thoughts

I found this while investigating why some other properties do not show their description, so these JavaScript errors may (or may not) be actually hurting more than it seems in this contrived example.

As suggested in #3366, if you move the A entry under definitions above B (right above or up higher) the problem disappears.
If you remove one level of nesting (remove A and make the end-point reference B directly), you get no issue.
However putting the definitions above the paths changes nothing.

_Copied from original issue: swagger-api/swagger-ui#4787_

**Comment by DavidBiesack** [comment]
In case this helps, debugger shows for me when I see 8 of these errors on my OpenAPI 3.0.2 API def.
```
index.js:2247 TypeError: Cannot read property '0' of undefined
    at l (core.js:244)
    at Object.p [as applyPatch] (core.js:277)
    at Object.applyPatch (index.js:940)
    at e.value (index.js:2258)
    at index.js:2242
    at Array.forEach (<anonymous>)
    at e.value (index.js:2214)
    at a (index.js:2412)
    at index.js:2390
    at e.value (index.js:2380)
(anonymous) @ index.js:2247
value @ index.js:2214
a @ index.js:2412
(anonymous) @ index.js:2390
value @ index.js:2380
(anonymous) @ index.js:2406
value @ index.js:2380
(anonymous) @ index.js:2406
value @ index.js:2380
(anonymous) @ index.js:2406
value @ index.js:2380
(anonymous) @ index.js:2406
value @ index.js:2380
(anonymous) @ index.js:2376
Promise.then (async)
value @ index.js:2376
(anonymous) @ index.js:2406
value @ index.js:2380
(anonymous) @ index.js:2376
Promise.then (async)
value @ index.js:2376
(anonymous) @ index.js:2406
value @ index.js:2380
(anonymous) @ index.js:2376
Promise.then (async)
value @ index.js:2376
(anonymous) @ index.js:2406
value @ index.js:2380
(anonymous) @ index.js:2376
Promise.then (async)
value @ index.js:2376
(anonymous) @ index.js:2406
value @ index.js:2380
v @ index.js:2419
Rt @ index.js:2707
(anonymous) @ index.js:2802
c @ runtime.js:45
(anonymous) @ runtime.js:271
e.<computed> @ runtime.js:97
o @ asyncToGenerator.js:5
s @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:23
Ft @ index.js:2813
In.resolveSubtree @ index.js:2777
resolveSubtree @ index.js:22
(anonymous) @ actions.js:178
c @ runtime.js:45
(anonymous) @ runtime.js:271
e.<computed> @ runtime.js:97
o @ asyncToGenerator.js:5
s @ asyncToGenerator.js:27
Promise.then (async)
o @ asyncToGenerator.js:15
s @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:23
(anonymous) @ actions.js:176
(anonymous) @ actions.js:176
c @ runtime.js:45
(anonymous) @ runtime.js:271
e.<computed> @ runtime.js:97
o @ asyncToGenerator.js:5
s @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:23
b @ debounce.js:95
x @ debounce.js:144
w @ debounce.js:132
setTimeout (async)
w @ debounce.js:135
setTimeout (async)
(anonymous) @ debounce.js:103
E @ debounce.js:172
(anonymous) @ actions.js:243
(anonymous) @ utils.js:134
(anonymous) @ bindActionCreators.js:3
(anonymous) @ OperationContainer.jsx:155
value @ OperationContainer.jsx:89
e.notifyAll @ CallbackQueue.js:74
close @ ReactReconcileTransaction.js:78
closeAll @ Transaction.js:207
perform @ Transaction.js:154
perform @ Transaction.js:141
perform @ ReactUpdates.js:87
w @ ReactUpdates.js:170
closeAll @ Transaction.js:207
perform @ Transaction.js:154
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
e @ ReactUpdates.js:198
a @ ReactUpdateQueue.js:22
enqueueSetState @ ReactUpdateQueue.js:216
s.setState @ ReactBaseClasses.js:62
i.handleChange @ connect.js:302
f @ createStore.js:172
(anonymous) @ utils.js:137
(anonymous) @ bindActionCreators.js:3
(anonymous) @ wrap-actions.js:9
r @ system.js:174
(anonymous) @ system.js:461
(anonymous) @ index.js:22
r @ system.js:174
(anonymous) @ system.js:461
(anonymous) @ actions.js:77
(anonymous) @ utils.js:134
(anonymous) @ bindActionCreators.js:3
(anonymous) @ wrap-actions.js:5
r @ system.js:174
(anonymous) @ system.js:461
(anonymous) @ index.js:11
r @ system.js:174
(anonymous) @ system.js:461
p @ download-url.js:37
Promise.then (async)
(anonymous) @ download-url.js:26
(anonymous) @ utils.js:134
(anonymous) @ bindActionCreators.js:3
h @ index.js:153
Hn @ index.js:180
window.onload @ (index):41
load (async)
(anonymous) @ (index):39
Show 41 more frames
system.js:464 TypeError: Cannot read property 'every' of undefined
    at actions.js:191
    at reducers.js:93
    at immutable.js:3084
    at ft.__iterate (immutable.js:2206)
    at o.__iterateUncached (immutable.js:3083)
    at ce (immutable.js:604)
    at o.K.__iterate (immutable.js:320)
    at o.forEach (immutable.js:4381)
    at immutable.js:2069
    at ft.Ue.withMutations (immutable.js:1353)
(anonymous) @ system.js:464
t.<computed> @ system.js:443
(anonymous) @ combineReducers.js:37
(anonymous) @ combineReducers.js:36
Ue.withMutations @ immutable.js:1353
(anonymous) @ combineReducers.js:35
f @ createStore.js:165
(anonymous) @ utils.js:137
(anonymous) @ bindActionCreators.js:3
(anonymous) @ actions.js:187
c @ runtime.js:45
(anonymous) @ runtime.js:271
e.<computed> @ runtime.js:97
o @ asyncToGenerator.js:5
s @ asyncToGenerator.js:27
Promise.then (async)
o @ asyncToGenerator.js:15
s @ asyncToGenerator.js:27
Promise.then (async)
o @ asyncToGenerator.js:15
s @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:23
(anonymous) @ actions.js:176
(anonymous) @ actions.js:176
c @ runtime.js:45
(anonymous) @ runtime.js:271
e.<computed> @ runtime.js:97
o @ asyncToGenerator.js:5
s @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:34
t @ _export.js:36
(anonymous) @ asyncToGenerator.js:23
b @ debounce.js:95
x @ debounce.js:144
w @ debounce.js:132
setTimeout (async)
w @ debounce.js:135
setTimeout (async)
(anonymous) @ debounce.js:103
E @ debounce.js:172
(anonymous) @ actions.js:243
(anonymous) @ utils.js:134
(anonymous) @ bindActionCreators.js:3
(anonymous) @ OperationContainer.jsx:155
value @ OperationContainer.jsx:89
e.notifyAll @ CallbackQueue.js:74
close @ ReactReconcileTransaction.js:78
closeAll @ Transaction.js:207
perform @ Transaction.js:154
perform @ Transaction.js:141
perform @ ReactUpdates.js:87
w @ ReactUpdates.js:170
closeAll @ Transaction.js:207
perform @ Transaction.js:154
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
e @ ReactUpdates.js:198
a @ ReactUpdateQueue.js:22
enqueueSetState @ ReactUpdateQueue.js:216
s.setState @ ReactBaseClasses.js:62
i.handleChange @ connect.js:302
f @ createStore.js:172
(anonymous) @ utils.js:137
(anonymous) @ bindActionCreators.js:3
(anonymous) @ wrap-actions.js:9
r @ system.js:174
(anonymous) @ system.js:461
(anonymous) @ index.js:22
r @ system.js:174
(anonymous) @ system.js:461
(anonymous) @ actions.js:77
(anonymous) @ utils.js:134
(anonymous) @ bindActionCreators.js:3
(anonymous) @ wrap-actions.js:5
r @ system.js:174
(anonymous) @ system.js:461
(anonymous) @ index.js:11
r @ system.js:174
(anonymous) @ system.js:461
p @ download-url.js:37
Promise.then (async)
(anonymous) @ download-url.js:26
(anonymous) @ utils.js:134
(anonymous) @ bindActionCreators.js:3
h @ index.js:153
Hn @ index.js:180
window.onload @ (index):41
load (async)
(anonymous) @ (index):39
Show 41 more frames
system.js:464 RangeError: Maximum call stack size exceeded
    at a (immutable.js:2327)
    at _t (immutable.js:2325)
    at ft.__iterate (immutable.js:2203)
    at Tt.__iterate (immutable.js:2698)
    at r.__iterateUncached (immutable.js:3015)
    at ce (immutable.js:604)
    at r.J.__iterate (immutable.js:274)
    at r.forEach (immutable.js:4381)
    at immutable.js:2651
    at Tt.Ue.withMutations (immutable.js:1353)
```
In my case, the API has several schemas in external files accessed via http:// (on the same host:port where the openapi.yaml file is and where swagger-ui is running -- i.e. localhost:8080/).
If I inline those schemas, the errors go away.

**Comment by unchase** [comment]
The same problem for my swagger spec:

{
  "openapi": "3.0.1",
  "info": {
    "title": "My API",
    "version": "v1"
  },
  "paths": {
    "/api/Todo/complicated": {
      "get": {
        "tags": [
          "Todo"
        ],
        "summary": "Complicated action.",
        "responses": {
          "200": {
            "description": "Returns a complicated class.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ComplicatedClass"
                }
              }
            }
          }
        }
      }
    },
    "/api/Todo/{id}": {
      "delete": {
        "tags": [
          "Todo"
        ],
        "summary": "Deletes a specific TodoItem.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/Todo": {
      "post": {
        "tags": [
          "Todo"
        ],
        "summary": "Creates a TodoItem.",
        "description": "Sample request:\r\n            \r\n    POST /Todo\r\n    {\r\n       \"id\": 1,\r\n       \"name\": \"Item1\",\r\n       \"isComplete\": true,\r\n       \"tag\": 0\r\n    }",
        "requestBody": {
          "description": "TodoItem.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TodoItem"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/TodoItem"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/TodoItem"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Returns the newly created item.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoItem"
                }
              }
            }
          },
          "400": {
            "description": "If the item is null.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Tag": {
        "enum": [
          0,
          1,
          2
        ],
        "type": "integer",
        "description": "Tag for TodoItem.<br>0 = None (Default tag)<br>1 = Task (Some task)<br>2 = Workout (Periodical job)",
        "format": "int32",
        "x-enumNames": [
          "None",
          "Task",
          "Workout"
        ],
        "x-enumDescriptions": [
          "Default tag",
          "Some task",
          "Periodical job"
        ]
      },
      "InnerEnum": {
        "enum": [
          1
        ],
        "type": "integer",
        "description": "Inner enum.<br>1 = Value ()",
        "format": "int32",
        "x-enumNames": [
          "Value"
        ],
        "x-enumDescriptions": [
          ""
        ]
      },
      "SecondInnerEnum": {
        "enum": [
          0
        ],
        "type": "integer",
        "description": "Second inner enum.<br>0 = Value ()",
        "format": "int32",
        "x-enumNames": [
          "Value"
        ],
        "x-enumDescriptions": [
          ""
        ]
      },
      "SecondInnerEnumSecondInnerClass": {
        "type": "object",
        "properties": {
          "innerEnum": {
            "allOf": [
              {
                "$ref": "#/components/schemas/SecondInnerEnum"
              }
            ],
            "description": "Second inner enum.<br>0 = Value ()",
            "x-enumNames": [
              "Value"
            ],
            "x-enumDescriptions": [
              ""
            ]
          }
        },
        "additionalProperties": false,
        "description": "Second inner class."
      },
      "InnerClass": {
        "type": "object",
        "properties": {
          "innerEnum": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/InnerEnum"
            },
            "description": "List of inner enums.",
            "nullable": true
          },
          "secondInnerClass": {
            "allOf": [
              {
                "$ref": "#/components/schemas/SecondInnerEnumSecondInnerClass"
              }
            ],
            "description": "Second inner class.",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Inner class."
      },
      "ComplicatedClass": {
        "type": "object",
        "properties": {
          "tag": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Tag"
              }
            ],
            "description": "Tag.<br>0 = None (Default tag)<br>1 = Task (Some task)<br>2 = Workout (Periodical job)"
          },
          "innerClass": {
            "allOf": [
              {
                "$ref": "#/components/schemas/InnerClass"
              }
            ],
            "description": "Inner class.",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Complicated class for testing enums."
      },
      "TodoItem": {
        "required": [
          "name"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Id.",
            "format": "int64"
          },
          "name": {
            "type": "string",
            "description": "Name."
          },
          "isComplete": {
            "type": "boolean",
            "description": "Is complete.",
            "default": false
          },
          "tag": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Tag"
              }
            ],
            "description": "Tag.<br>0 = None (Default tag)<br>1 = Task (Some task)<br>2 = Workout (Periodical job)"
          }
        },
        "additionalProperties": false,
        "description": "Todo item."
      },
      "ProblemDetails": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "detail": {
            "type": "string",
            "nullable": true
          },
          "instance": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": {
          "type": "object",
          "additionalProperties": false
        },
        "description": ""
      }
    }
  },
  "tags": [
    {
      "name": "Hided",
      "description": "Hided controller"
    },
    {
      "name": "Todo",
      "description": "Controller for todo (action count: 3)"
    }
  ]
}

**Comment by realsenseme** [comment]
Any update on this one? Though it doesn't seem to hurt the functionality, a list of errors on the page is no good.

**Comment by SourceCode** [comment]
It seems like being able to extend like this should be common place and deeply tested.  Almost all programming disciplines rely on a level of DRY and this should be no exception, deep nesting/complex inclusion scenarios.

**Comment by sarndt** [comment]
It seems that allOf in general has some issues.
I'll see if I can build up a minimal working example, but for me it also shows a bunch of resolver errors like this:

```
Resolver error
can't access property 0 of undefined
```

In a file where I use a lot of `allOf` inclusions.

**Comment by alexzuev** [comment]
Any updates with this issue? I still this error in v3.27.0

**Comment by char0n** [comment]
Looking into it

**Comment by char0n** [comment]
@Rutix no progress yet. Would anybody be able to give us a hand with this? We welcome any community contribution.

**Comment by Rutix** [comment]
@char0n any idea where the problem lies? I might have some time soon to look into this but I have no clue where to start.

**Comment by char0n** [comment]
@Rutix,

Sure I'll prepare some onboarding for you related to this problem. Should be done during tommorow.

Thanks!

**Comment by char0n** [comment]
Fix introduced in https://github.com/swagger-api/swagger-js/pull/1783

**Comment by Rutix** [comment]
@char0n Thanks for fixing the issue! Any idea on when this will come in a release? And will this automatically bubble into swagger-ui? After that it's done I can PR the update to the swashbuckle repository. If I can be of any assistance please let me know.

**Comment by char0n** [comment]
@Rutix we usually release during Thursdays. It will not automatically re-buble into swagger-ui because we use [exact version match](https://github.com/swagger-api/swagger-ui/blob/master/package.json#L95) for swagger-client. We'll release swagger-ui along with swagger-client.

**Comment by Rutix** [comment]
@char0n thanks for the information! I will keep an eye on the releases :). Thanks for all the effort

**Comment by char0n** [comment]
Fixed and released in https://github.com/swagger-api/swagger-js/releases/tag/v3.12.0
