### ISSUE TITLE
How to File-Upload without `transfer-encoding: chunked`

### ISSUE THREAD

**Issue by thilo-maurer** [swagger-api/swagger-js#1373]
Uploading a file using a Swagger-js-3.x nodejs client works well with the code shown down below, if the server accepts `transfer-encoding: chunked`, but what if it does not?

**Current Status:**
The code down below will HTTP POST a request with
```
Content-Type: multipart/form-data; boundary=--------------------------761773270080086352885963
Transfer-Encoding: chunked
body:
----------------------------761773270080086352885963
Content-Disposition: form-data; name="data"; filename="mypdffile.pdf"
Content-Type: application/pdf

%PDF-1.4
[.....]
----------------------------761773270080086352885963--
```

However, _how to send without using transfer-encoding chunked?_, but instead sending the file in once piece as
```
Content-Type: multipart/form-data; boundary=--------------------------761773270080086352885963
Content-Length: 1212324
body:
----------------------------761773270080086352885963
Content-Disposition: form-data; name="data"; filename="mypdffile.pdf"
Content-Type: application/pdf

%PDF-1.4
[.....]
----------------------------761773270080086352885963--
```

Reading #231, I experimented with creating the file object passed to swagger-js using `fs.readFileSync()` which creates a `Buffer`, instead of `fs.createReadStream()` which creates a `fs.ReadStream`. In this case, neither the Buffer is uploaded in one piece (wrong length! and empty! payload), and the filename is also omitted from the request (fine, a Buffer cannot carry a filename):
```
content-type : multipart/form-data; boundary=--------------------------495874774419912423270821
content-length: 159
body:
---------------------------495874774419912423270821
Content-Disposition: form-data; name="data"


----------------------------495874774419912423270821--
```

Here's the code
```
const fs = require('fs')
const path = require('path')
const Swagger = require('swagger-client')
const pathname = path.normalize(__dirname + '/myPet.jpg')

const myPetImage = fs.readFileSync(pathname)
const myPetImageStream = fs.createReadStream(pathname)

Swagger({
    url: 'http://petstore.swagger.io/v2/swagger.json'
}).then(client => {
    client.apis.pet.uploadFile({
      petId: 256256,
      file:myPetImageStream
    }).then(res => console.log(res))
})
```

**Comment by tim-lai** [comment]
@thilo-maurer PR#1527 changes dependency that should work better with node.js. I don't think that `transfer-encoding:chunked` is a requirement. Given the age of this ticket, if this issue is still relevant/needed, and not resolved with PR#1527, please feel free to re-open this issue.
