### ISSUE TITLE
React Native TypeError Object is not a function

### ISSUE THREAD

**Issue by npalethorpe** [swagger-api/swagger-js#1397]
### Q&A (please complete the following information)
 - OS: macOS
 - Environment: React Native
 - Method of installation: npm
 - Swagger-Client version: 3.8.21
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

Weird exception within a React Native project (iOS) - Everything runs fine in debug mode, however when I flick over to Release mode on iOS I get the following error:
```
TypeError: e is not a function. (in 'e({url:t,loadSpec:!0,requestInterceptor:r,responseInterceptor:n,headers:{Accept:"application/json"},credentials:a}}','e' is an instance of Object)
```
As this has been minified I stopped the minification and got the following: "TypeError: Object is not a function (near '...e...')".

Below is a summed up version of my code, however it isn't reaching the stage of actually attempting to make a call so I'm not sure its much use - and just to emphasise on the point; this works 100% in debug mode.
```
import Swagger from 'swagger-client';

Swagger({
    url: SWAGGER_URL,
    requestInterceptor: function (req) {
        req.headers.appVersion = 1;
        req.headers.authorization = USER_AUTH_TOKEN;
    },
    responseInterceptor: function (res){
    }
 }).then((client) => {
    resolve(client);
}).catch((err) => {
    reject(err);
});
```

**Comment by npalethorpe** [comment]
I managed to resolve this issue by doing a download of the project and including it as a local npm package. The only thing I had to change was that Package.json in the npm project had...
`"main": "dist/index.js"` 
which I had to change to... 
`"main": "src/index.js"`.

**Comment by marcosmartinez7** [comment]
Exactly the same problem, also with the assembleRelease. 

React Native. 57.3

Any ideas of why this could be happening? 


The @npalethorpe solution does the trick.

**Comment by shockey** [comment]
@npalethorpe, what do you see fi you do this:

```js
import Swagger from 'swagger-client';

console.log(Swagger)
```

**Comment by shockey** [comment]
(If anyone else can do this, it would be helpful to see your output as well)

**Comment by joh-klein** [comment]
with v3.8.22 the output is:
```js
function s(t){var n=this,o=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};if("string"==typeof t?o.url=t:o=t,!(this instanceof s))return new s(o);(0,c.default)(this,o);var u=this.resolve().then(function(){return n.disableInterfaces||(0,c.default)(n,s.makeApisTagOperation(n)),n});return u.client=this,u}
```

**Comment by joh-klein** [comment]
What I did to get my react-native project to work again: I took the un-minified output from `npm run build:umd:dev` and replaced everything in `dist/index.js` with it. This can be done with https://www.npmjs.com/package/patch-package in an orderly fashion and without to much hassle in a CI/CD workflow.

I also tried to upgrade `swagger-client` to webpack 4. It looked promising, but I didn't have the time to continue investigating.

**Comment by devth** [comment]
This is breaking me too. Kind of a nasty bug since it **only** shows up in production.

**Comment by shortcarver** [comment]
I started working back through the versions, and this appears to have been introduced in v3.6.0. 
v3.5.2 works for me.

**Comment by KeyBusiness1204** [comment]
New version (v3.9.0) does not work too. it does not work only in production.
Any solution?

**Comment by char0n** [comment]
I'm not very familiar with how react-native bundler works, but is it possible to configure the bundler to to prioritize on package.json mappings? This is what we do in webpack with [resolve.fields](https://webpack.js.org/configuration/resolve/#resolvemainfields). 

Anyway in next release of `swagger-client` we completely [changed](https://github.com/swagger-api/swagger-js/issues/1542) how we build and distribute build artifacts. `swagger-client` will come with ES5 compatible code with ES6 imports mapped to package.json `module` field. And I assume that something that react-native prioritize before `main` field.

**Comment by char0n** [comment]
Closing as resolved.
