### ISSUE TITLE
Incorrect parsing of cookie headers with node-fetch

### ISSUE THREAD

**Issue by simoami** [swagger-api/swagger-js#1398]
### Environment
 - OS: macOS
 - Environment: Node.js v8.11
 - Method of installation: npm
 - Swagger-Client version: 3.8.20
 - Swagger/OpenAPI version: Swagger 2.0

### Describe the bug you're encountering

In [http.js](https://github.com/swagger-api/swagger-js/blob/master/src/http.js#L128), the `serializeHeaders()` method doesn't property parse set-cookie headers with multiple values. 
with node-fetch, headers['set-cookie'] will now return a string like`foo=bar; path=/; secure; HttpOnly, baz=qix; path=/; secure; HttpOnly` instead of an array of cookie entries like `['foo=bar; path=/; secure; HttpOnly', 'baz=qix; path=/; secure; HttpOnly']`.

When you call `obj[header] = headerValue` for 'set-cookie', the headerValue is a string. The workaround is to pass the raw headers `headers: serializeHeaders(oriRes.headers.raw())`, which preserve the set-cookie header is its array form. Please see this thread for the node-fetch related issue: https://github.com/bitinn/node-fetch/issues/251

### To reproduce...

1. Mock a response to return:
```
headers": [
  "Content-Type", "application/json",
  "Set-Cookie", "foo=bar; path=/; secure; HttpOnly",
  "Set-Cookie", "baz=qix; path=/; secure; HttpOnly"
]
```
2. Then call 
``` 
Swagger.http(request)
  .then((res) => {
    console.log(res.headers['set-cookie')
  });
```
Log output:
```
foo=bar; path=/; secure; HttpOnly, baz=qix; path=/; secure; HttpOnly
```

### Expected behavior
The `set-cookie` response headers are supposed to hold multiple values in an array as show below:
```
[
  'foo=bar; path=/; secure; HttpOnly',
  'baz=qix; path=/; secure; HttpOnly'
]
```

### Additional context or thoughts

Moreover the `responseInterceptor` doesn't get passed the original response object in order to get around the issue by calling the `origRes.headers.raw()` method or to access other props you deemed unnecessary in your custom response.

**Comment by simoami** [comment]
FYI, this issue is with node-fetch. The native fetch behaves fine as it doesn't join header arrays.

**Comment by shockey** [comment]
Thanks for filing this, @simoami. Any chance you could make a PR that solves the issue? 😄

**Comment by char0n** [comment]
Thanks for reporting this; closing in favor of https://github.com/swagger-api/swagger-js/issues/1508
