### ISSUE TITLE
🐱 as API key

### ISSUE THREAD

**Issue by pracj3am** [swagger-api/swagger-js#1400]
### Q&A (please complete the following information)
 - OS: Linux
 - Browser: Chrome
 - Version: 70.0.3538.54
 - Method of installation: https://petstore.swagger.io

### Describe the bug you're encountering

I am not able to use emoji cat face as API key.

### To reproduce...

1. Go to https://petstore.swagger.io
2. Click on Authorize
3. Enter cat face 🐱 as `api_key`
4. Click on Authorize and Close
5. Click on GET /pet/{petId}
6. Click on Try it out
7. Enter `petId` 1
8. Click on Execute
9. See error
```
TypeError: Failed to execute 'fetch' on 'Window': Value is not a valid ByteString.
```

### Expected behavior

Successful API call.

### Screenshots

![image](https://user-images.githubusercontent.com/191928/47855542-2d2d6880-dde5-11e8-946a-96ac45aa4e66.png)

### Additional context or thoughts

The `fetch` method uses for headers `ByteString` that uses UTF-8 encoding, while Javascript strings uses UTF-16 encoding. I was able to fix it by
```js
          result[inType][schema.name] = unescape(encodeURIComponent(value))
```
here https://github.com/swagger-api/swagger-js/blob/f282ec5774199e2defe45b5346e2d75cd12b352c/src/execute/swagger2/build-request.js#L84

**Comment by char0n** [comment]
@pracj3am thank you for bringing this up!

I see two options how to handle this:

### 1.) Maintain the status quo

This requires us to do nothing and let `fetch` handle that for us as it currently does.
 
### 2.) Encode UTF-16 TO UTF-8 while building the request

Doing exactly what you suggested - converting UTF-16 to UTF-8 explicitly and making sure we're scope this to header keys and values as only those could be affected by this issue.


--- 

Having said that, I'm currently inclined for option 1.). My reasoning it following: Doing hidden explicit conversion for the user creates an **exception problem**. User expect 🐱 to be send as header key or header value. Instead we send some obscure characters that have no meaning and server receives something that user did not intended to send. IMHO warning him explicitly that the request cannot be event send is better and more expected.

@pracj3am what is your opinion on that?

**Comment by pracj3am** [comment]
I did a small testing and found that the `ByteString` rejects any javascript string that contains "char code" > 255, which means it expects the first byte of UTF-16 code unit to be always zero byte.

So if a server expects a header with UTF-8 encoded string, you have to create a javascript string representing UTF-8 bytes, in case of a 🐱 it would be
```
ð±
```

Because there is no standardized character encoding for HTTP headers, I agree with **1.)**

**Comment by char0n** [comment]
Cool thank you for your opinion. Let's stick with **1.)** for now and warn users explicitly about characters their allowed to use.
