### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by joshua-barnett** [swagger-api/swagger-js#1409]
I would really appreciate some API Docs for this library I've had to go through and read the source in order to know what options can be supplied to the `Swagger` client factory.

**Comment by bestmike007** [comment]
@shockey how about adding typescript definition for this module? I wonder if there's someone already working on this.

**Comment by shockey** [comment]
@bestmike007, I don't know of any efforts to do this, but if it's something that's testable (assert: do the TS definitions match what we're exporting at any given time?) it sounds like a great enhancement 😄

**Comment by bestmike007** [comment]
I think there are two ways of doing this:

1. Add a TS definition file: need more work to ensure it's consistent with what's exported, and additional tests for that
2. Translate the code into typescript: generated definitions from code, one source of truth, but everything will be changed

I prefer the latter option if it's okay with the team and planned in a new release.

**Comment by shockey** [comment]
@bestmike007, we aren't in a position to accept a TypeScript rewrite at this time, but a definition file would be great.

We may explore a TS rewrite at a later time - feel free to email me and we can chat further about it.

**Comment by cspotcode** [comment]
Typescript 3.7 allows generating `.d.ts` files directly from `.js`.  This means you can annotate your `.js` with comments to declare types, and `tsc` can create `.d.ts` declarations from there.

Then you can gradually port the codebase to `.ts` proper, which has a better syntax for describing types.

TypeScript 3.7 is currently in beta and a stable release is scheduled for November.

**Comment by char0n** [comment]
Created first [PR](https://github.com/swagger-api/swagger-js/pull/1506) that should increase the documentation coverage and quality of our documentation. I've started with a `Swagger specification resolver`.

**Comment by char0n** [comment]
Documentation has been consolidated into [docs/](https://github.com/swagger-api/swagger-js/tree/master/docs) directory.

If you wish to provide a TypeScript typings for this library, please create a separate issue for that.
