### ISSUE TITLE
Feature Request: set default error callback

### ISSUE THREAD

**Issue by lflobo** [swagger-api/swagger-js#141]
Would be great if, instead of passing the 3rd argument to each SwaggerApi invocation to an endpoint, you could set the default error callback function - something like:
```javascript
SeaggerApi api = new SwaggerApi({
	url: "/api",
	success: function() { /* do stuff */ },
	defaultErrorCallback: function(errorResponse) {
		/* do default stuff with errorResponse.obj */
	}
});
```
I'm sorry if this is already possible, but it's not clear in the documentation or in the source code.

Regards,
Keep up the excellent work,
LL

**Comment by fehguy** [comment]
you can now pass `defaultSuccessCallback` and `defaultErrorCallback` in the `opts` when creating the swagger client.  See:

https://github.com/swagger-api/swagger-js/blob/master/test/defaultCallbacks.js#L9

and 

https://github.com/swagger-api/swagger-js/blob/master/test/defaultCallbacks.js#L35
