### ISSUE TITLE
Can swagger-client support local files

### ISSUE THREAD

**Issue by dodtsair** [swagger-api/swagger-js#1410]
Can swagger-client import API Docs via a file instead of an http url.

Something like:

    const swaggerClient = require('swagger-client');

    const devZone = swaggerClient('file://api-doc.json');

We want to use swagger-client to exercise our rest apis where the rest apis are sitting in the repo next to the code that uses swagger-client.  In particular we have some integration test cases that we use to test our rest apis.

**Comment by bestmike007** [comment]
Swagger client uses fetch (or cross-fetch/polyfill) as the default client to load doc from url; it does not support file url (data url neither).

However, you can use a temporary server in your scenario:

https://gist.github.com/bestmike007/a63ea5b21a24fdd34508164a85dc1e4b

**Comment by shockey** [comment]
Quoting myself from #1044:

> I'm going to close this one out, here's why:
> 
> file:// URLs are not really useful, since they're very difficult to use in browsers due to Same-Origin Policy and very few Node request libraries support them.
> 
> As for loading in a definition that you already have in memory: you can pass your definition as a JS object under the spec key.
> 
> Feel free to reply if you disagree with any of this, and I'll consider reopening. Thanks everyone!

As mentioned, the best approach is to pull your local file in manually and pass it as an object to Swagger Client.

Closing!

**Comment by shockey** [comment]
@mm-gmbd, I worded it poorly! you'd actually want to do it like `Swagger({ spec: spec })`.

I'm going to edit your comment so Googlers get the right snippet, but for any historians out there, the line was originally `Swagger(spec)`.

**Comment by mm-gmbd** [comment]
@shockey - thanks for the clarification! Also, thanks for your work on this particular module, it's very helpful! I'd love a little more documentation / examples here and there, but this beggar won't try and be a chooser :smile: (best case scenario - maybe I'll actually get some time to contribute!)
