### ISSUE TITLE
How to pass headers to Swagger json

### ISSUE THREAD

**Issue by sandeep-paliwal** [swagger-api/swagger-js#1411]
### Q&A (please complete the following information)
 - OS: e.g. macOS
 - Environment: Node.js v8
 - Method of installation: npm
 - Swagger-Client version: 3.8.0
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
I need to pass header which will be bustome headers along with auth header. How can I do this with new client?

Swagger-Client usage:
```js
Swagger('http://petstore.swagger.io/v2/swagger.json')
  .then( client => {
      // Tags interface
      client.apis.pet.addPet({id: 1, name: "bobby"}).then(...)
      // TryItOut Executor, with the `spec` already provided
      client.execute({operationId: 'addPet', parameters: {id: 1, name: "bobby") }).then(...)
   })
```

### How can we help?
How do I pass headers to above sample code to call the addPet API?

**Comment by vvanpo** [comment]
@sandeep-paliwal It looks like you need to use the `requestInterceptor` property. Take a look at https://github.com/swagger-api/swagger-js/blob/master/docs/MIGRATION_2_X.md#default-content-type-values for an example of passing a header value.

**Comment by vvanpo** [comment]
@shockey can you comment on why the tags interface does not set a `Content-Type` header when the output is clearly going to be JSON?

https://github.com/swagger-api/swagger-js/blob/master/src/execute/index.js#L82
Here you can see that the client is explicitly outputting JSON, but does not touch any headers. So it is up to the consumer to set up a `requestInterceptor`. But you can't easily chain interceptors without some kind of abstraction, so complex applications that need to modify the request in multiple places get messy real quick.

The link from my last comment implies this behaviour used to be different, why was it changed?

**Comment by shockey** [comment]
@vvanpo we stopped assuming `Content-Type` based on payload content in an effort to more closely follow what a user's OpenAPI 2.0 document calls for. If you specify a `consumes` value for the operation, we'll use it... if not, we'll omit the header entirely.

Conversely, setting `Content-Type` when a document doesn't call for it through a `consumes` value ends up with our tool exposing functionality that isn't described in the underlying document, which makes interoperability between OpenAPI-ecosystem tools less likely, and more confusing to end users.

**Comment by char0n** [comment]
Hi @sandeep-paliwal,

As mentioned before, `requestInterceptor` is the answer.

Here is [documentation](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/tags-interface.md#options-override) how to achieve what you want with [Tags Interface](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/tags-interface.md).

```js
import SwaggerClient from 'swagger-client';

const interfaceLevelRequestInterceptor = (req) => {
  req.headers.CustomHeader = 'custom header value';
  return req;
};

new SwaggerClient({
  url: 'http://petstore.swagger.io/v2/swagger.json'
}).then((client) =>
  client.apis.user.getUserByName(
    { username: 'username' },
    {
      requestInterceptor: interfaceLevelRequestInterceptor,
    }
  )
);
```
And here is [documentation](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/try-it-out-executor.md) how to use requestInterceptor in [Try It Out Executor](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/try-it-out-executor.md).

```js
import SwaggerClient from 'swagger-client';

const interfaceLevelRequestInterceptor = (req) => {
  req.headers.CustomHeader = 'custom header value';
  return req;
};

new SwaggerClient({ spec: pojoDefinition, authorizations: { BearerAuth: "3492342948239482398" } })
  .then(
    client => client.execute({
      operationId: 'getUserList',
      parameters: { q: 'search string' },
      requestInterceptor: interfaceLevelRequestInterceptor,
    })
  ); // => Promise.<Response>
```
