### ISSUE TITLE
Access raw request and response

### ISSUE THREAD

**Issue by devth** [swagger-api/swagger-js#1415]
### Q&A (please complete the following information)

 - OS: macOS
 - Environment: Node.js v10.11.0
 - Method of installation: homebrew
 - Swagger-Client version: 3.8.22
 - Swagger/OpenAPI version: Swagger 2.0

### How can we help?

When using the [tags interface](https://github.com/swagger-api/swagger-js#tags-interface) is it possible to view the raw request and response? I can see the response for non-error responses but if the server errors it throws an error instead of letting me get at the response.

**Comment by devth** [comment]
Answering my own question:

Use `requestInterceptor` and `responseInterceptor` to log the request and response:

```javascript
    requestInterceptor: function (req) {
        console.log(req);
        return req;
    },
    responseInterceptor: function (res){
       // ...
    }
```

**Comment by shockey** [comment]
@devth thanks for leaving a solution! 😄

**Comment by nmaoez** [comment]
The problem with the interceptors is, that those are only accessable at the time when I initialize the swagger client. But I want to load the specification and generate the client only once and reuse it though out the whole project. And if my server throws an error with a detailed error message, it would be wonderful if I could access the response body.

So is there a chance to access the error response or is there a way to access the interceptors after the promise was rejected?

**Comment by kguelzau** [comment]
why did you close this issue?

**Comment by shockey** [comment]
> If the backend throws an error, it would be good to get the details of the response directly on the highest layer

@nmaoez I have a pull request open for this (https://github.com/swagger-api/swagger-js/pull/1281), but as you can see there are some concerns around it being a breaking change. Can't say whether it will make it into master in the future.

> why did you close this issue?

@kguelzau this ticket was a support request from @devth, who ended up solving their own problem. If you're having a problem, feel free to open your own issue 🙂
