### ISSUE TITLE
Add custom header to all calls

### ISSUE THREAD

**Issue by nishant-udgaonkar** [swagger-api/swagger-js#1416]
I am using swagger-ui, and am trying to add a custom header to each call that is made. The server needs to read this header and do something based on it's value. How do I do this?

**Comment by mm-gmbd** [comment]
Hey @nishant-udgaonkar, you can find an example of this in the [2.X Migration Guide](https://github.com/swagger-api/swagger-js/blob/master/docs/MIGRATION_2_X.md#default-content-type-values).

Using the `requestInterceptor` argument to Swagger Client constructor, you can define an interceptor function where you can do whatever you want with the request object, including adding a custom header to each call.

```javascript
Swagger({
  url: "http://petstore.swagger.io/v2/swagger.json",
  requestInterceptor: req => {
    if(req.body && !req.headers["Content-Type"]) {
      req.headers["Content-Type"] = "application/json"
    }
  }
})
```

**Comment by mm-gmbd** [comment]
Actually, I thought that this worked, but I just tried it and it did not work as expected...

**Comment by nishant-udgaonkar** [comment]
Apologies for leaving this stagnant for so long. Using the requestInterceptor worked for me:

```
requestInterceptor: (req) => {
    req.headers["my_header"] = "my_value";
    return req;
},
```
