### ISSUE TITLE
status or statusCode?

### ISSUE THREAD

**Issue by benirose** [swagger-api/swagger-js#1420]
### Q&A (please complete the following information)
 - OS: macOS
 - Environment: Chrome 71
 - Method of installation: npm
 - Swagger-Client version: 3.5.0
 - Swagger/OpenAPI version: Swagger 2.0

### How can we help?
The documentation says that the response to http calls uses a "fetch-link interface", but includes `res.statusCode` as opposed to `res.status`. However, when I make an api call using tags and operationIds, I get `res.status` (which actually matches a fetch-like interface). Which is correct?

**Comment by char0n** [comment]
Hi @benirose,

Here is an up-to-date [documentation](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md#response) about the Response type that should answer your qustion.

In short: `Number(res.status)`, `String(res.statusText)`.
