### ISSUE TITLE
Accept header is hardcoded to "application/json"

### ISSUE THREAD

**Issue by ZhouHansen** [swagger-api/swagger-js#1430]
### The bug I am encountering

https://github.com/swagger-api/swagger-ui/issues/447 

> Hi, this is ONLY the case(application/json) when fetching the Resource Listing or Api Declarations.

[django-rest-swagger](https://github.com/marcgibbons/django-rest-swagger)

> `Content-Type: application/openapi+json` is specified in the headers.

So, server returns `406 Not Acceptable` when 

```
swagger('http://some_django_rest_swagger_domain/schema/?format=openapi')
```

 - OS: [macOS]
 - Environment: [Chrome 59, Node.js v11.0.0]
 - Method of installation: [npm]
 - Swagger-Client version: [3.8.25]
 - Swaggerversion: [Swagger 2.0]

![image](https://user-images.githubusercontent.com/8222181/55224833-492a1e80-524c-11e9-9b7a-b7d638c51e0a.png)

**Comment by shockey** [comment]
@ZhouHansen, this seems like a problem with django-rest-swagger.

Per https://github.com/OAI/OpenAPI-Specification/issues/110: `application/openapi+json` is not recognized by the OAI, nor is it a [valid IANA media type](https://www.iana.org/assignments/media-types/media-types.xhtml#application). django-rest-swagger, IMO, shouldn't be requiring clients to ask for invalid media types.

Closing!
