### ISSUE TITLE
npm artifacts are minified only

### ISSUE THREAD

**Issue by nmccready** [swagger-api/swagger-js#1431]
Can we please publish non minified artifacts and leave it to the consuming application to decide how and when they will minify the codebase. 

If not can both be published? This would help immensely in debugging and understanding how things are generated.

**Comment by nmccready** [comment]
ping

**Comment by char0n** [comment]
@nmccready thank you for bringing this up!

This has been already architected and implemented in master. See https://github.com/swagger-api/swagger-js/issues/1542 for more details. Next version of swagger-client will have all this available. The release will come probably during today.
