### ISSUE TITLE
Adding headers before checks are ran

### ISSUE THREAD

**Issue by rnmalone** [swagger-api/swagger-js#1436]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Environment: Chrome 74, Node.js v10.15.1
 - Method of installation: npm
 - Swagger-Client version: 3.8.25
 - Swagger/OpenAPI version: Swagger 2.0

### Swagger/OpenAPI definition:
     ``` "get": {
        "tags": [
          "Agent"
        ],
        "summary": "Get list of agents",
        "operationId": "getAgentListUsingGET",
        "produces": [
          "application/json;charset=UTF-8"
        ],
        "parameters": [
          {
            "name": "my-uuid",
            "in": "header",
            "description": "Correlation ID",
            "required": true,
            "type": "string",
            "format": "uuid",
            "x-example": "2fabae89-a7d1-4e79-89b5-680ee7f545a9"
          },
          {
            "name": "page",
            "in": "query",
            "description": "page",
            "required": false,
            "type": "integer",
            "default": 0,
            "format": "int32",
            "allowEmptyValue": false,
            "x-example": 0
          },
          {
            "name": "size",
            "in": "query",
            "description": "size",
            "required": false,
            "type": "integer",
            "default": 20,
            "format": "int32",
            "allowEmptyValue": false,
            "x-example": 20
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Agent"
              }
            }
          },
          "400": {
            "description": "Bad request. Check error message for details."
          }
        },
        "deprecated": false
      }```

Swagger-Client usage:
```import Swagger from 'swagger-client';
import spec from '../schema/swagger';

const uuid = require('uuid/v4');

export function createPortalConnector() {

	const headers = {
		'my-uuid': uuid()
	};

	return Swagger(
	  {
			url: 'localhost:3006',
			spec,
			requestInterceptor: (req) => {
			  req.headers = Object.assign({}, { ...headers, ...req.headers });
			}
		}

	)
		.then(client => client)
		.catch((error) => { throw new Error(error); });
}
```

### How can we help?

When i try and make a call on that route for the schema snapshot, it returns an error saying the my-uuid header is not present. It looks like the `requestInterceptor` is called after the preflight checks are performed. Is there a way of appending default headers to the swagger client. This uuid is needed for all reuqests.

**Comment by char0n** [comment]
Hi @rnmalone, 

Yes in browser environment we have no control over prefligh requests. As [MDN documentation](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) states:

> A preflight request is automatically issued by a browser and in normal cases, front-end developers don't need to craft such requests themselves.

If you're using swagger-client in browser environment, unfortunately there is nothing you can do. If you're using swagger-client in backend-like environment (node.js), it should be possible for you to write you own implementation of our [HTTP Client](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md) and pass it to swagger-client during instantionation:

```js
import SwaggerClient from 'swagger-client';

const http = ...custom implementation with full control over preflight checks...;

new SwaggerClient({
  http,
  spec,
});
```

Sorry I did not have better news ;[
