### ISSUE TITLE
Requests are cancelled: "TypeError: Failed to fetch"

### ISSUE THREAD

**Issue by rnmalone** [swagger-api/swagger-js#1446]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Environment: [Chrome 75, Node.js v10.15.1]
 - Method of installation: npm
 - Swagger-Client version: 3.8.25
 - Swagger/OpenAPI version: OpenAPI 2.0

### Content & configuration
``` 
createConnector() {
		Swagger.http.withCredentials = true;
		return Swagger(
			{
				spec: this.schema,
				v2OperationIdCompatibilityMode: true,
				requestInterceptor: (req) => {
				  req.headers = Object.assign({}, req.headers, this.headers);
				  req.credentials = 'omit';

				  console.log(JSON.stringify(req));
				}
			}
		).then((client) => {
		  const { apis } = client;

		  // Iterate over every method provided by the api client so we can set default options on requests.
		  Object.entries(apis).forEach(([apiRealm, requests]) => {
		    this[apiRealm] = {};
		    Object.keys(requests).forEach((request) => {
		      this[apiRealm][request] =
              async(requestOptions) => {
		            try {
              		const response = await apis[apiRealm][request]({ ...this.defaultOptions, ...requestOptions });
              		this.emit('response', response);
              	} catch (error) {
              		this.emit('error', error);
              	}
              };
				});
			});
		}).catch((error) => { throw new Error(error); });
	}
```

The above method is part of a class I wrote to inject boiler-plate settings on every request provided by the client. An example of a request send by the client is :

```
await apiConnector['Agent Authentication'].loginUsingPOST({
			loginReqDTO: agent
		});
```

### How can we help?

Every request sent from the client gets cancelled and throws an error in the browser "TypeError: Failed to fetch". Preflight requests are sent and receive a 204.

We've definitely allowed CORS on our server and preflight request asserts the correct cors headers are present on the response, and taken all the steps recommended in documentation to allow for CORS.

We can't seem to find a way of getting a more verbose error out of the client. The basic error message yields no insight into the cause of the request being cancelled. Any suggestions will be highly appreciated.

**Comment by rnmalone** [comment]
* FIXED *

The form submission that was calling the login request was did not contain ```event.preventDefault()``` and so the form submission was cancelling the request.

**Comment by Krenabothu** [comment]
Simple fix event.preventDefault(), thanks
