### ISSUE TITLE
Tests fail with Node.js >8

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-js#1447]
Our unit tests don't work on versions of Node.js above 8 -- looks like there are some issues around HTTP mocking. (Could just be a need to bump the versions of our mocking libraries so they work with newer versions of Node.)

With Node.js v10.15.3:

<img width="916" alt="image" src="https://user-images.githubusercontent.com/680248/59226527-0491fc00-8b88-11e9-8843-1e17095bc4a8.png">

Node.js 8 will be EOL in January, so we should address this sometime in the coming months:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/680248/59226390-baa91600-8b87-11e9-8510-a18ad16f4df8.png">

**Comment by char0n** [comment]
Closed by #1511
