### ISSUE TITLE
Feature: request level authorization

### ISSUE THREAD

**Issue by mauron85** [swagger-api/swagger-js#146]
Request level authorization will enable to reuse same swagger-client for diferrent callers.

So something like this will be possible.
``` javascript
var swagger = new client.SwaggerApi({
    url: 'http://petstore.swagger.wordnik.com/api/api-docs',
    success: function () {
        if (swagger.ready === true) {
            var apiKey = new client.ApiKeyAuthorization('apiKey', 'secretkey', 'query');
            swagger.apis.pet.getPetById({petId:1}, { auth: { apiKey: apikey } });
        }
    }
});
```

Currently apikey is shared within client so per request authorization is not possible

**Comment by whitlockjc** [comment]
With recent refactorings, `authorizations` are no longer a global object so you can have per-SwaggerClient authorizations.  You can pass them into the `SwaggerClient` constructor using the `authorizations` option and you can alter an existing client's authorizations using `client.clientAuthorizations`.

Feel free to open an new issue with what you find.

**Comment by slidenerd** [comment]
Cannot read property 'add' of undefined , I am getting this error in my node.js code because clientAuthorizations is undefined. It is a standard sample by Microsoft that isnt working [HERE](https://github.com/Microsoft/BotBuilder-Samples/blob/master/Node/core-DirectLine/DirectLineClient/app.js)
