### ISSUE TITLE
How do I run update swagger.js locally and test against swagger-ui

### ISSUE THREAD

**Issue by markdemich** [swagger-api/swagger-js#1461]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Environment: N/A
 - Method of installation: NPM
 - Swagger-Client version: Latest
 - Swagger/OpenAPI version: OpenAPI 3.0

### Question
This question is more about updating the swagger.js.  I found a bug in swagger.js that causes external yaml references to not work.

The problem is in the file src/resolver.js in the function makeFetchJSON, we need to add application/yaml to the accept header of the request.

I've done this locally, but I can't figure out how to test this against a local installation of swagger-ui.  I tried npm link but that gives errors when I try to run swagger-ui in dev mode.

I searched online but can't seem to find instructions on how to do this.  Can anyone share how they accomplish something like this?

**Comment by char0n** [comment]
Hi @markdemich,

As this is rather common question, I've prepared a [PR](https://github.com/swagger-api/swagger-js/pull/1630) with documentation how to do local testing of `swagger-client` in `swagger-ui`.
