### ISSUE TITLE
add array schema support

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#147]
per

https://github.com/wordnik/swagger-ui/issues/653#issuecomment-58562198

**Comment by carlosrdrz** [comment]
Why was this closed? was it fixed?
It says that the progress for this issue should be tracked here but I can't see any PR / commit fixing this :/
Am I missing something?

**Comment by fehguy** [comment]
yes, if you follow the links, this was a duplicate issue of https://github.com/swagger-api/swagger-ui/pull/765 and it was closed 2 years ago.

**Comment by abchandra** [comment]
It seems there might be a circular reference between the issue 765 and 147. I tried this on the web client, and arrays are not valid.

**Comment by Download** [comment]
A pointer to the docs on array would help. Google brings me here when searching for 'swagger schema array of'. Apparently GitHub Issues has a lot of Google juice. Bad side effect of it is that it's much easier to find years old issues than it is to find the actual documentation...
