### ISSUE TITLE
Encoding style not respected for requestBody

### ISSUE THREAD

**Issue by sm-Fifteen** [swagger-api/swagger-js#1470]
### Q&A (please complete the following information)
 - OS: Arch Linux
 - Environment: Firefox 68
 - Method of installation: swagger-editor
 - Swagger-Client version: 3.9.4
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
openapi: "3.0.2"
info:
  version: "1.0.0"
  title: "Swagger Petstore"
servers:
  - url: "https://petstore.swagger.io/"
paths:
  /pet:
    post:
      tags:
      - "pet"
      summary: "Add a new pet to the store"
      description: ""
      operationId: "addPet"
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                list:
                  type: array
                  items:
                    type: string
                hashmap:
                  # complex types are stringified to support RFC 1866
                  type: object
                  properties:
                    foo:
                      type: string
                    bar:
                      type: integer
            encoding:
              list:
                style: spaceDelimited
                explode: false
              hashmap:
                style: deepObject
                explode: true
                  
      responses:
        default:
          description: 'Nothing to see here'
```

Swagger-Client usage:
```js
// Run via swagger-editor
```

### Describe the bug you're encountering
swagger-client does not respect encoding style for complex parameters when inside `requestBody`. [As per the OpenAPI 3.0 specification][2], complex parameter encoding should follow the `encoding` parameter and work pretty much the same way as query parameter encoding.

### To reproduce...
When submitting a POST request via `addPet` with the following content:

```json
{
    "id": 1,
    "list": ["a", "b,c"],
    "hashmap": {"foo": "string", "bar": 0}
}
```

...a request with the following body is sent:

```
id=1&list=a%2Cb%2Cc&hashmap=%7B%0A%20%20%22foo%22%3A%20%22string%22%2C%0A%20%20%22bar%22%3A%200%0A%7D
```

[This corresponds to `hashmap` being json-encoded and `list` in a comma-separated format][1]. No further escaping of the contents will be performed, so if any of the elements in `list` contain commas, those will be indistinguisable from the element separators. This is despite the `encoding` field specifying that `list` should be space-delimited and that `hashmap` should be rendered as a deep-object.

### Expected behavior
For the example given above, the correct serialization method should result in this being sent as the request body:

```
id=1&list=a%20b%2Cc&hashmap[foo]=string&hashmap[bar]=0
```

[1]: https://github.com/swagger-api/swagger-js/blob/f8fccb45107c76c0dd45d9d0e4583087b97ef6b3/src/execute/oas3/build-request.js#L74-L81
[2]: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#encoding-object

**Comment by tim-lai** [comment]
Re-opening. Reason: OAS3 x-www-form-urlencoded not addressed in #1527. #1500 is relevant PR in-progress to resolve.
