### ISSUE TITLE
how can I use a spec file which only available local

### ISSUE THREAD

**Issue by jinchenbravo** [swagger-api/swagger-js#1471]
### Q&A
 - OS: [macOS]
 - Environment: [Node.js v10.0.0]
 - Method of installation: [npm]
 - Swagger-Client version: [3.9.4]
 - Swagger/OpenAPI version: [OpenAPI 3.0]

### How can we help?

For some authentication reason , the spec file can only be downloaded from somewhere to local, 
and I need to use Swagger-Client to read the spec file and send the request to a remote host. 
Looks like I must use url : http.... to get the client
```
Swagger({ url: "http://petstore.swagger.io/v2/swagger.json" }).then((client) => { ...
```
so the question is there a solution to read the spec from local ?

**Comment by jonathan-meyer** [comment]
I tired  building a url with the node.js [URL object](https://nodejs.org/dist/latest-v10.x/docs/api/url.html#url_url_pathtofileurl_path).
```
const bitBucketSpecUrl = url.pathToFileURL(path.resolve(__dirname, "..", "lib", "bit-bucket-api.yaml"));
debug(bitBucketSpecUrl);
SwaggerClient({ url: bitBucketSpecUrl.toString() })
  .then(client => {
    debug(client.spec); 
    debug(client.originalSpec); 
    debug(client.errors); 
  })
  .catch(err => debug(err));
```
But it didn't work. 😩

According to the code it looks like only `http` urls are accepted. 
https://github.com/swagger-api/swagger-js/blob/7ca4c00dfff7e4e31905c0d48bc78c1bea4f9624/src/index.js#L89

**Comment by shockey** [comment]
Quoting myself from https://github.com/swagger-api/swagger-js/issues/1044#issuecomment-369746672:

> file:// URLs are not really useful, since they're very difficult to use in browsers due to Same-Origin Policy and very few Node request libraries support them.
> 
> As for loading in a definition that you already have in memory, @c4milo is correct: you can pass your definition as a JS object under the spec key.

There's a workaround, though: https://github.com/swagger-api/swagger-js/issues/1410#issuecomment-488325332. Essentially, if you're using a local file, it's your responsibility to provide your data to Swagger Client as a JavaScript object.
