### ISSUE TITLE
send the request to a remote host with custom port and base_path

### ISSUE THREAD

**Issue by jinchenbravo** [swagger-api/swagger-js#1472]
### Q&A
 - OS: [macOS]
 - Environment: [Node.js v10.0.0]
 - Method of installation: [npm]
 - Swagger-Client version: [3.9.4]
 - Swagger/OpenAPI version: [OpenAPI 3.0]

### How can we help?
use the spec as a JSON obj which is read from a local file (swagger-spec.json)
however, I need to send the request to a remote host with custom port and base_path. ( The host ,port, base_path info is NOT available in the spec)
ex:
https://my-remote-host:8080/base/api/v1

```
Swagger({ spec: spec, url: "https://my-remote-host:8080/base/api/v1" }).then((client) => { ...
```
How can I make the request ?

**Comment by shockey** [comment]
@jinchenbravo, you should be able to use `baseDoc` to achieve this:

```js
Swagger({
  spec: spec,
  baseDoc: "https://my-remote-host:8080/base/api/v1"
})
```

**Comment by jinchenbravo** [comment]
@shockey , I tried your baseDoc thing, however it is still NOT working. I got below err msg.
Error!
Error: only absolute urls are supported

**Comment by shockey** [comment]
@jinchenbravo, what does the URL you're providing look like?

**Comment by jinchenbravo** [comment]
@shockey , As you suggested, I did NOT use the url property but just the baseDoc.
```
Swagger({
  spec: spec,
  baseDoc: "https://my-remote-host/jinchenbravo/api/v1"
}).then((client) => { ...
```

**Comment by arjamizo** [comment]
I have achieved this with a request interceptor
```
const swaggerClient = new SwaggerClient(swaggerSpec || '/swagger.json').then(client => {
  client.spec.basePath = '/'
  client.spec.host = 'https://localhost:4450'
  client.requestInterceptor = (r) => {
    r.url = client.spec.host + r.url;
    return r
  }

```

Have fun while hacking `swagger-js`

**Comment by jinchenbravo** [comment]
@arjamizo 
Can you please share more code ? including pathName, method and Params ?
Thanks a lot

**Comment by arjamizo** [comment]
@jinchenbravo it will be applied to literally every swagger request, are you able to execute swagger requests or you are also looking for help in executing first request?

**Comment by jinchenbravo** [comment]
@arjamizo 
Yes , If possible , please provide me the whole example which includes pathName, method and Params
in your example above, you don't have those things, Thank you for your help

**Comment by char0n** [comment]
```

**Comment by char0n** [comment]
@jinchenbravo proper thing to do here is to use [requestInterceptor](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md#request-interceptor). Your code have to look like this in order to achieve what you want.

```js
const requestInterceptor = (request) => {
  if (request.loadSpec) { return request; }

  // original request.url == 'http://petstore.swagger.io/v2/pet/1'
  const url = new URL(request.url);
  url.host = 'www.google.com';
  url.pathname = url.pathname.replace('/v2/', '/v3/');
  url.port = 8081;

  // new request.url == 'http://www.google.com:8081/v3/pet/1'
  request.url = String(url);

  return request;
};

SwaggerClient({
  spec: petstore,
  requestInterceptor,
})
  .then(client => client
    .execute({
      requestInterceptor,
      pathName: '/pet/{petId}',
      method: 'get',
      parameters: {
        petId: 1,
      },
    })
  );
```
