### ISSUE TITLE
Unexpected double dollar signs in resolved OAS 3 definition

### ISSUE THREAD

**Issue by tmkasun** [swagger-api/swagger-js#1481]
### Q&A (please complete the following information)
 - OS: macOS
 - Environment: Chrome 77
 - Method of installation: npm
 - Swagger-Client version: 3.9.4
 - Swagger/OpenAPI version: OpenAPI 3.0.0

### Content & configuration

Swagger/OpenAPI definition:

Example yaml in [OpenAPI-Specification/examples](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml)

Swagger-Client usage:
```js
SwaggerClient.resolve({ spec: rawSpec }).then(({ spec, errors }) => {
            ...
        });
```

### To reproduce...

1. Download the sample OpenAPI 3 definition given in [OAI/examples](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml)
2. Use `SwaggerClient.resolve()` method to resolve the specification
3. Examine the resolved schema references
```yaml
content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Pets"
```
4. It contains 
```json
$$ref:"#/components/schemas/Pets"
```

### Expected behavior

- Should not contain double dollar signs ($$) in resolved `ref`, the expected value is `$ref`

### Screenshots
note the 

```json
$$ref:"#/components/schemas/Error"
```
![image](https://user-images.githubusercontent.com/3313885/67261900-56487c80-f4c0-11e9-8af8-a2093cf3d926.png)

### Additional context or thoughts

- As per https://github.com/swagger-api/swagger-ui/issues/4021#issuecomment-351206840 comment, `$$ref` is used internally only. Should not return in resolved spec

**Comment by shockey** [comment]
@tmkasun, `$$ref` is internal in the context of the UI, but it is part of Swagger Client's API.

If you'd like to resolve without getting `$$ref` trace keys back, set `allowMetaPatches` to `false`:

```js
SwaggerClient.resolve({ spec: rawSpec, allowMetaPatches: false }).then(({ spec, errors }) => {
  // do stuff
});
```

**Comment by tmkasun** [comment]
Hi @shockey ,

Thanks for the info, It worked after adding the `allowMetaPatches` property.

**Comment by shockey** [comment]
Great to hear, @tmkasun!

Closing as resolved.
