### ISSUE TITLE
How to enable CORS with npm in browser

### ISSUE THREAD

**Issue by chriswalz** [swagger-api/swagger-js#1483]
### Q&A (please complete the following information)
 - OS: macOS
 - Environment: Chrome 78, Node.js v12.12.0]
 - Method of installation: npm
 - Swagger-Client version: 3.9.5
 - Swagger/OpenAPI version: 2

### Content & configuration

Swagger-Client usage:
```js
      import Swagger from 'swagger-client'
      Swagger.http.withCredentials = true; // this activates CORS, if necessary
      Swagger({
        url: specUrl
      }).then((client: any) => {
        console.log(client.spec);
        resolve(report);
      })
```

### Screenshots

Error from chrome
<img width="1349" alt="Screen Shot 2019-11-04 at 11 53 09 PM" src="https://user-images.githubusercontent.com/6971318/68179561-5cc60200-ff5e-11e9-9db4-e798945e8c00.png">

### How can we help?
I have it working when CORS isn't necessary. 

What's the appropriate way to allow CORS using swagger-client? I've been fiddling with this for a while :(

**Comment by char0n** [comment]
Hi @chriswalz,

Your example contains exactly the the code fragments that enables CORE support on `swagger-client. You can find more about CORS in [swagger-client documentation](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md#cors).

```js
Swagger.http.withCredentials = true;
```
After executing this code `swagger-client` is requesting resources using CORS. The problem that you're having is that your server doesn't support CORS. Remember both client and server need to support CORS. You can find more information about CORS on server side in this [MDN article](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).
