### ISSUE TITLE
How can I send request again in response interceptor?

### ISSUE THREAD

**Issue by nuykon** [swagger-api/swagger-js#1486]
```js
const responseInterceptor = (res) => {
  if (res.status === 401) {
    if (res.body.message.includes('jwt invalid')) {
      updateToken().then(() => {
        // send current request again
      });
    } else {
      window.location.href = '/auth';
    }
  }
  return res;
};
```

**Comment by char0n** [comment]
@nuykon,

I would recommend doing things like that in `responseInterceptor`. Logic like that (repeating) should be handled in higher levels of your code. That being said.....

Yes it is possible to access original request via `responseInterceptor`. You can find more information about it in this [documentation](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md#accessing-request-in-response-interceptor).

In your particular case the resulting code will look like this:

```js
import SwaggerClient from 'swagger-client';

const request = {
  url: 'https://httpbin.org/',
  method: 'GET',
  responseInterceptor: async function(res) {
    if (res.status === 401) {
      if (res.body.message.includes('jwt invalid')) {
        return updateToken().then(() => SwaggerClient.http(this));
      } else {
        window.location.href = '/auth';
        return res;
      }
    }
    
    return res;
  },
};

SwaggerClient.http(request); 
```

Hope it helps.
