### ISSUE TITLE
Uncaught (in promise) SyntaxError: The requested module '/node_modules/swagger-client/dist/index.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by sdcaulley** [swagger-api/swagger-js#1496]
### Q&A (please complete the following information)
 - OS: Ubuntu 18.04.3 LTS
 - Environment: Chrome 79.0.3945.130(Official Build)(64-bit); Node.js v12.13.1
 - Method of installation: npm
 - Swagger-Client version: 3.10.0
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
import { LitElement, html } from 'lit-element';
import Swagger from 'swagger-client';

function callApi() {
  const specUrl = 'http://www.omdbapi.com/swagger.json';

  Swagger(specUrl)
    .then((res) => {
      console.log('res: ', res);
    })
    .catch((err) => {
      console.log('err: ', err);
    })
}

export class KnovaHubViewToyApi extends /* connect(store)( */LitElement /* ) */ {
  connectedCallback() {
    callApi();
  }

  render() {
    return html`<div>Hello Stephanie</div>`;
  }
}
Swagger/OpenAPI definition:
I am trying to use the definition at http://www.omdbapi.com/swagger.json

Swagger-Client usage:
```js
SwaggerClient({
  // your config options here
})
```

### How can we help?
I am getting the console error: ```Uncaught (in promise) SyntaxError: The requested module '../../../../node_modules/swagger-client/dist/index.js' does not provide an export named 'default'
Promise.catch (async)
render @ router.js:517
__onNavigationEvent @ router.js:902
setRoutes @ router.js:419
(anonymous) @ kh-root.js:24```

It seems to be coming from my import statement.  Am I not setting up swagger-client correctly?

**Comment by shockey** [comment]
@sdcaulley this can happen when your build system natively uses ESM, and doesn't support CommonJS modules (which Swagger-Client is).

What are you using in your dev toolchain to resolve `import` statements?

**Comment by sdcaulley** [comment]
Thank you for your response @shockey.  We are using Webpack.
