### ISSUE TITLE
cdnjs pull request review

### ISSUE THREAD

**Issue by Aigeruth** [swagger-api/swagger-js#150]
Hi,

I've added Swagger-UI to cdnjs (cdnjs/cdnjs#3937) and I try to add Swagger-JS too. Could you review my pull request (cdnjs/cdnjs#3939)?

Would it be possible to release minified version from this library? Should I open a pull request for this (e.g. creating a `release` task in the `Cakefile` that is using UglifyJS)?

Thanks your for your help!

**Comment by Aigeruth** [comment]
@fehguy The first one was merged (Swagger-UI), but the second one hasn't been merged yet (Swagger-JS - cdnjs/cdnjs#3939). Could you check it? Thanks!

**Comment by fehguy** [comment]
Hi @Aigeruth, a couple thoughts.

1) The repositories in the package.json are now under the swagger-api github account, not wordnik
2) We probably would want to push a minified version, including the dependencies in a single bundle
3) I'm redoing the tests right now, and suggest you hold until 2.0.48 is released

Make sense?  Also when we release 2.1.0, the two libraries (swagger.js and swagger-client.js) will be merged into one.  Currently they are separate to allow for independent development of the different versions of the swagger spec.

**Comment by fehguy** [comment]
hi @Aigeruth 2.0.48 has been released.  I'd suggest redoing the PR with that library.
