### ISSUE TITLE
How do you add an API key to the url parameters

### ISSUE THREAD

**Issue by sdcaulley** [swagger-api/swagger-js#1503]
### Q&A (please complete the following information)
 - OS: Ubuntu 18.04
 - Environment: Chrome 80, Node 12 (lts)
 - Method of installation: unpkg (using in browser)
 - Swagger-Client version: 3.10
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
http://www.omdbapi.com/swagger.yaml
```

Swagger-Client usage:
(currently working in the console)
```js
var sc = document.querySelector('kh-view-api-call').swaggerClient
sc.client.apis["Search Parameter"].titleSearch({s: "potter" }).then( res => { console.log(res) })
```

### Screenshots
N/A

### How can we help?
This api requires the apiKey as part of the query string.  I see in the spec 
```
security: Array(1)
0: {APIKeyQueryParam: Array(0)}
```
which I am assuming is what I need to access in order to pass the apiKey, but I am unclear on how to do that, or build a url that contains the apiKey with the search parameters I want. 

I have been able to build the url with the search params.

Thank you for your assistance.

**Comment by char0n** [comment]
To make a standard request via [tags interface](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/tags-interface.md) in **node.js**, here is a code how to achieve that:

```js
const SwaggerClient = require('swagger-client');

SwaggerClient({
  url: 'http://www.omdbapi.com/swagger.yaml',
  authorizations: { APIKeyQueryParam: { value: '234934239' } },
})
  .then(client => client.apis['Search Parameter'].titleSearch({ s: 'potter' }))
  .then(console.log)
```

**Browser usage**

```html
<html>
  <head>
    <script src="//unpkg.com/swagger-client"></script>
    <script>
      SwaggerClient({
        url: 'https://www.omdbapi.com/swagger.json',
        authorizations: { APIKeyQueryParam: { value: '234934239' } },
      })
        .then(client => client.apis['Search Parameter'].titleSearch({ s: 'potter' }))
        .then(console.log)
    </script>
  </head>
  <body>
  check console in browser's dev. tools
  </body>
</html>
```

I'm not entirely sure what is your goal or what you're trying to achieve but hopefully my answers shed some light into it.
