### ISSUE TITLE
JSON content type not automatically parsed

### ISSUE THREAD

**Issue by mauron85** [swagger-api/swagger-js#153]
I think that there is a problem within ShredHttpClient.prototype.execute function. It tries to find header content-type === 'application/json', but it searches in response._headers instead of response._headers.normalized returned by ShredHttpClient. 

The problem is on the line 1480:

```
var contentType = (response._headers["content-type"] || response._headers["Content-Type"] || null)
```

Need to be changed for:

``` javascript
var headers = response._headers.normalized || response._headers;
var contentType = (headers["content-type"] || headers["Content-Type"] || null)
```

**Comment by extempl** [comment]
Was it regressed again? 
```
if (contentType === 'application/json') {
    return JSON.parse(body)
  }
  return jsYaml.safeLoad(body)
```
