### ISSUE TITLE
test: index-authorization, UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-js#1530]
### Q&A (please complete the following information)
- OS: macOS 10.15.3
- Environment: Node.js v10.19.0, Node.js v13.9.0
- Method of installation: npm
- Swagger-Client version: 3.10.0
- Swagger/OpenAPI version: n/a

### Content & configuration

existing unit tests

### Describe the bug you're encountering

Although the following test passes, it should be fixed.
```
 PASS  test/index-authorizations.js
(node:43095) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ok' of undefined
(node:43095) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:43095) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### To reproduce...

1. `npm run test:unit`

### Expected behavior

Test should pass without warnings

**Comment by char0n** [comment]
I've isolated the rogue test and fixed it. The test itself was failing and the reject promise got lost in "limbo". The problem was rectified by chaining the promise returned from `execute` function into and providing a proper `Response` mock by `userFetch` override.
