### ISSUE TITLE
Automatic dependencies update

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-js#1541]
Let's utilize [dependabot](https://dependabot.com/) to do automatic dependencies updates for us. Dependabot is now part of github, and it's not an external dependency. Ideally dependabot would merge his own PRs when all CI check pass.

Before we enable the dependabot, we need to update `package.json` manually, becase the libraries we currently use are years old and would probably require changes in tests of configs.

**Comment by char0n** [comment]
Related issues: #1491

**Comment by tim-lai** [comment]
I ok giving Dependabot a try

**Comment by char0n** [comment]
I'll utilize github actions to verify that repo works on node >=10
