### ISSUE TITLE
Building artifacts / distribution

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-js#1542]
### Status Quo

 When we create a [npm distribution](https://www.npmjs.com/package/swagger-client) there are two  main files that are part of the distribution package.

**browser/index.js**

This is a minified code build as a browser bundle with all dependencies inlined. 

**dist/index.js**

This is a non minified versions for node and all other requirements. It's using commonJS under the hood so further tree-shaking by consumer is not possible.

> This setup doesn't give consumers of the library much flexibility and it's not aligned with the way how modern libraries are being distributed. 

### Future proposal

I propose to have `npm run build` process producing following artifacts. `npm run build` will execute implicitly `build:es`, `build:commonjs` and `build:umd` scripts.

#### Builds

```sh
 $ npm run build:es
```

Creates `es/` directory that mirrors structure of the codebase in `src/` directory. Contains ES5 compatible code with ES6 imports. This artifact is ideal for a bundler use supporting tree shaking and ES2015 imports.

```sh
 $ npm run build:commonjs
```
Creates `lib/` directory that mirrors structure of the codebase in `src/`. Contains ES5 compatible code with `commonJS` imports. Ideal for node.js and similar environments.

```sh
 $ npm run build:umd
```

The command will create two types of bundles in Universal Module Definition format.

`dist/swagger-client.node.js` - ES5 compliant bundle, running on all node versions. All dependencies are inlined
`dist/swagger-client.node.min.js` - ES5 compliant minified bundle, running on all node versions. All dependencies are inlined

`dist/swagger-client.web.js` - ES5 compliant bundle, running in modern browsers. All dependencies are inlined
`dist/swagger-client.web.min.js` - ES5 compliant bundle, running in browsers. All dependencies are inlined

### package.json mapping

```js
  "main": "./lib/index.js",
  "module": "./es/index.js",
  "jsnext:main": "./es/index.js",
  "browser": "./dist/swagger-client.web.min.js"
```

Behavior of the mapping can be configured on consumer side. For example in webpack, use [resolve.mainFields](https://webpack.js.org/configuration/resolve/#resolvemainfields) to determine the order of resolution.

## Tree shaking support

Tree shaking is a term commonly used in a JavaScript context for dead-code elimination. It relies on the static structure of ES2015's module syntax, i.e. `import` and `export`.  `swagger-client` should natively supports tree shaking thanks to the way the code is organized and its use of ES2015 imports.

**Comment by tim-lai** [comment]
Sounds good to me!
