### ISSUE TITLE
breaking change released in minor version

### ISSUE THREAD

**Issue by regevbr** [swagger-api/swagger-js#1546]
Hi,

You have published 3.10.3 a few days ago and it dropped support for node <10 which is a breaking change, but you released it as a minor version update, which caused all my code to stop working (I'm not directly dependent on it).
Is there a way to revert the release and publish a major version instead?

Thanks,

**Comment by char0n** [comment]
@regevbr thanks for reporting it. We're working on a solution. Will let you know when we have one.

**Comment by char0n** [comment]
Problem has been fixed on master.

**Comment by regevbr** [comment]
Thanks @char0n!

**Comment by char0n** [comment]
Released in https://www.npmjs.com/package/swagger-client/v/3.10.4
