### ISSUE TITLE
Schema $ref of $ref not working

### ISSUE THREAD

**Issue by mpoiriert** [swagger-api/swagger-js#160]
This is seem to be a valid schema but it's not loaded properly:

```JSON
{
  "definitions": {
    "Response": {
      "$ref": "User"
    },
    "User": {
      "properties": {
        "username": {
          "type": "string"
        }
      }
    }
}
```

I would expect the Reponse definition to "import" the User definition but it doesn't. This can easily be seen with the getMockSignature of a model since it does get the reference from properties but not from himself.

**Comment by whitlockjc** [comment]
If all you need is the reference dereferencing, you could use [json-refs](https://github.com/whitlockjc/json-refs).  If you want to construct an object model from a Swagger document, I don't think #152 will help.

**Comment by whitlockjc** [comment]
This has been resolved.
