### ISSUE TITLE
Pollutes the global namespace with `fetch`

### ISSUE THREAD

**Issue by vvanpo** [swagger-api/swagger-js#1634]
`swagger-client` does a good job of using `@babel/runtime-corejs2` to use pure ponyfills without polluting the global namespace. But `@babel/plugin-transform-runtime` only manages `core-js` ponyfills, which does not include `fetch`. `cross-fetch` provides the option to use either a pure **pony**fill via `import { fetch } from 'cross-fetch'` which does not pollute the global namespace, or a global **poly**fill via `import 'cross-fetch/polyfill'`. Normally you would choose one or the other, but `swagger-client` uses both:
  - https://github.com/swagger-api/swagger-js/blob/v3.10.11/src/http.js#L1
  - https://github.com/swagger-api/swagger-js/blob/v3.10.11/src/specmap/lib/refs.js#L1

This imports two different bundles in `cross-fetch`: https://github.com/lquixada/cross-fetch/tree/v3.0.5/dist (`browser-polyfill.js` and `browser-ponyfill.js`), and I assume it bloats the browser bundle unnecessarily.

Is there a reason I'm not seeing preventing us from just using the ponyfill in both places?

### To reproduce...

In Internet Explorer or another browser that does not have native `fetch`:
```html
<script>
  console.log(fetch);
    // => undefined
</script>
<script src="https://unpkg.com/swagger-client"></script> <!-- Or a bundle that imports `swagger-client`. -->
<script>
  console.log(fetch);
    // => function fetch(input, init) {
    //        return new Promise(function(resolve, reject) {
    //        ...
</script>
```

**Comment by char0n** [comment]
Hi @vvanpo,

Nice catch! I think this would be the an exception of not polluting global namespace rule (as discussed in https://github.com/swagger-api/swagger-js/issues/1633).

**Reasoning**

I can see one usecase where being able to access `fetch` on global namespace is required - implementing [custom fetch](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md#custom-fetch). There are cases where you want to slightly modify behavior of the `fetch` function. Without having global reference to `fetch` (in no fetch env) you'd have to use polyfill or ponyfill different with the one shipped with swagger-client. We could assign `fetch` to `SwaggerClient` object (default export of the library) and not assign it to global one, but that would render it backward incompatible change. For now I'd focus on using only `browser-polyfill.js` and amend our imports to reflect that. What is your opinion on that?

Feel free to issue a PR with a fix.
