### ISSUE TITLE
SwaggerClient with *.yml spec inside a Create-React-App

### ISSUE THREAD

**Issue by JavaJamie** [swagger-api/swagger-js#1693]
Hi all.

We are completely new to using Swagger and we are having issues trying to load a local *.yml file inside our application using SwaggerClient. It is a Create-React-App which hasn't been ejected so our guess would be there's no yml loader inside the Webpack configuration. It doesn't even see the file at all, but if we change it to *.json it does then.

I'm just wondering the best way to solve this as we can't get it working right now. We want to create the SwaggerClient with the spec and return this inside a custom hook to avoid repetition.

I've seen examples of using fs and js-yaml but it was causing an issue with readFileSync being an unknown function.

This is what we currently have:

```
import SPEC from './api.yml'; // Doesn't even see/notice this file. How can we load this?
const SWAGGER_CLIENT = new SwaggerClient({ spec: SPEC });

export function useSwaggerApi() {
    return SWAGGER_CLIENT.apis;
}
```

Thanks all. I really appreciate your help :)

**Comment by char0n** [comment]
@JavaJamie this is more a general JavaScript programming issue than a SwaggerClient related one. If you're using ES6 imports I assume you have some bundler like [webpack](https://webpack.js.org/) or [rollup](https://webpack.js.org/) to bundle the code into backward compatible JavaScript. 

For example with webpack you have to have YAML loader installed and configured. More info [here](https://github.com/eemeli/yaml-loader).

**Comment by char0n** [comment]
I missed the Create-React-App (CRA) in title. Not ejected CRA will use file-loader to load yaml. 


@JavaJamie you closed the issue, have you managed to solve it successfuly?
