### ISSUE TITLE
Specifying which server url to use in API call via SwaggerClient

### ISSUE THREAD

**Issue by JavaJamie** [swagger-api/swagger-js#1700]
I don't know whether or not it's missing in the documentation, but I don't see a way to specify which server URL to use when making a call via SwaggerClient if you have several specified. It seems to default to the first URL in the array which is wrong.

E.g.,

`let response = await swaggerClient.client.apis.cars.getCars({ userId: "1" });`

We have a few URLs in our *.yaml but it always defaults to the URL at [0] but we need to use the one at [1]. Is there a way to select this (other than changing the array order).

Thanks all.

**Comment by char0n** [comment]
Hi @JavaJamie,

Please have a look at [Tags Interface documentation](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/tags-interface.md#openapi-v3x). You'll find an answer for you question there.

**Comment by JavaJamie** [comment]
Hi @char0n, you're right! We didn't inspect the documentation close enough. We've added it in now.

```
    let response = await swaggerClient.client.apis.getCars(
        { id: "1" },
        { server: client.client.spec.servers[1].url }
    );
```

Thank you for your help! We are new to using Swagger.

**Comment by char0n** [comment]
Np, glad to be of help.
