### ISSUE TITLE
reusing examples with $ref

### ISSUE THREAD

**Issue by matanse** [swagger-api/swagger-js#1709]
### Q&A (please complete the following information)
 - OS: macOS     
 - Environment: Chrome 
 - Swagger-Client version: editor.swagger.io
 - Swagger/OpenAPI version: openapi: 3.0.1 

### Content & configuration

Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  title: test
  version: 2.2.2
paths:
    /me:
        get:
          summary: "Returns a user"
          responses:
            200:
              description: Success
              content:
                  application/json:
                    examples:
                        default:
                          $ref: "#/components/examples/User"
            404:
              description: The user could not be found
    /users:
        get:
          summary: Returns list of users.
          responses:
            200:
              description: Success
              content:
                  application/json:
                    examples:
                        default:
                          $ref: "#/components/examples/Users"
            404:
              description: Not Found
components:
    examples:
        User:
            value:
                username: some.user
                kind: user
        Users:
            value:
                collection:
                - $ref: "#/components/examples/User/value"
                total_users: 10000
```

Swagger-Client usage:
```js
SwaggerClient({
  // your config options here
})
```

### Screenshots
![Screenshot 2020-09-10 at 18 25 50](https://user-images.githubusercontent.com/46820871/92762938-5c26a500-f393-11ea-8859-ec44b9045410.png)
<img width="492" alt="Screenshot 2020-09-10 at 18 31 18" src="https://user-images.githubusercontent.com/46820871/92763490-e5d67280-f393-11ea-951e-b4303b718100.png">

### How can we help?
The screen shot is from swagger and is showing an example for a response that is a collection of users.
As you see In the screenshot marked in red is the reference field that is being used to reference to User. 
After the render the field is visible on the example response in swagger.
In the response it does not have that field, and I don't want it to be visible in the example as well.
I'm searching a solution for that.
maybe to hide that field from swagger or something.
Do you have a solution for that? 
Also why is it showing double dollar sign?

**Comment by matanse** [comment]
found the solution.
collection:
- allof:
  - $ref: "#/components/examples/User/value"


works perfectly.

**Comment by char0n** [comment]
Hi @matanse,

Cool that you found a solution. Regarding one of your questions that remains unanswered:

> Also why is it showing double dollar sign?

Please visit this [documentation](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/openapi-definition-resolver.md#options) to find an answer to your question.  When in documentation, search for `$$ref`
