### ISSUE TITLE
Update core-js to version 3

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-js#1715]
### Content & configuration

It's high time to update core-js to version 3. Let's do some research what effect it might have for swagger-client users, or libraries using swagger-client. I'll post my research notes here.

#### Research notes

This repo uses `@babel/preset-env` for compiling ES6 and higher JavaScript code into multiple build fragments. We explicitly use `useBuiltIns` set to `false` (so that no polyfills are applied) and `corejs` option set to `{ version: 3 }`. This combination of `useBuiltins=false` and `corejs={ version: 3 }` has no effect on polyfilling and is there only for reference or if `@babel/plugin-transform-runtime` is dropped in future. For polyfilling we exclusively utilize [@babel/plugin-transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime) to create sandboxed poly-filled environment for our code. This solution is making sure that we don't pollute global namespace with polyfills. By using sandboxed env + no polutting global scope the changes from core-js@2 to core-js@3 should be completely transparent for swagger-client consumers.

#### Implementation notes

New dependency needs to be introduces and build system ammended.

##### Resources

 - https://babeljs.io/docs/en/babel-plugin-transform-runtime
 - https://github.com/vercel/next.js/issues/8103
 - https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md
 - https://alexbogovich.com/blog/core-js/

**Comment by tim-lai** [comment]
@char0n fyi, swagger-ui and swagger-editor had their polyfills removed in recent releases. I've already tried them with core-js3 (ok), but I haven't tried removing core-js entirely.

**Comment by char0n** [comment]
@tim-lai yep I've [noticed](https://github.com/swagger-api/swagger-ui/commit/0d63e70c8e0105b02a070ae9edb7610c38676814), as we use `@babel/preset-env` it doesn't make sense to keep the file.

>  I've already tried them with core-js3 (ok), but I haven't tried removing core-js entirely.

I'm not sure what you mean this. Are you planning to remove core-js from swagger-ui entirely? If yes, is there a ticket I can look into to understand why ?

Anyway merging of attached PR needs to be synchronized with releases of swagger-js and swagger-editor. We use `@babel/runtime-corejs3` as a runtime dependency and  swagger-ui is currently using `@babel/runtime-corejs2`. This would increase bundle size significantly if not synchronized. swagger-ui [config builder](https://github.com/swagger-api/swagger-ui/blob/master/webpack/_config-builder.js#L121) has to be amended to resolve to `@babel/runtime-corejs3`.

**Comment by tim-lai** [comment]
@char0n 
> > I've already tried them with core-js3 (ok), but I haven't tried removing core-js entirely.
> 
> I'm not sure what you mean this. Are you planning to remove core-js from swagger-ui entirely? If yes, is there a ticket I can look into to understand why ?

I intended to ask this as a question if it was still needed without polyfills. e.g. still a babel/wepack requirement.

> merging of attached PR needs to be synchronized

Yup, I will do so once attached PR is merged.

**Comment by char0n** [comment]
The change is on master now.
