### ISSUE TITLE
update subtree resolver test to be more inclusive

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-js#1724]
### Content & configuration

### Is your feature request related to a problem?

The test file `test/subtree-resolver.js` currently only runs a single test due to existence of a `test.only()`. There appears to be two breaking tests that are currently skipped.

I would like to incorporate new tests into this file.

### Describe the solution you'd like

The test file `test/subtree-resolver.js` should be re-evaluated for correctness. The broken tests should be fixed or skipped.

### Additional context

Discussion from PR #1720

**Comment by Aashu23** [comment]
Hi, I would like to work on this. Can you please assign this issue to me?

**Comment by char0n** [comment]
@Aashu23 you've been assigned. Thanks for helping us!
