### ISSUE TITLE
Amend Installation documentation

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-js#1740]
Affected file: https://github.com/swagger-api/swagger-js/blob/master/docs/usage/installation.md

This documentation claims that: 
>Once swagger-ui has successfully generated the `/dist` and `/browser` directory

This is not the case anymore. `/browser` directory is no longer being generated. This have to be reflected in documentation and removed from it.

**Comment by jpacsai** [comment]
Hi, I have updated the documentation and opened a pull request :)
