### ISSUE TITLE
Is there a way to get this to load a local resource, instead of from a server? ie datauri or something?

### ISSUE THREAD

**Issue by ericblade** [swagger-api/swagger-js#1793]
The situation is this:   I want to produce a library that consumes an API, but I need it to be dependent upon a specific version of the sources, not based on whatever the official files documents, which are not under my control.  Rather than standing up my own server to serve a specific version of the swagger data files, I'd rather just include them into the library, somehow. 

I attempted to do this with a datauri, but it just complains that the uri must be http or https protocol.  I'd be willing to fork or produce a patch to support this use case, but I'm curious if it might already be possible via some way that I'm not seeing?

What I'd hope to end up with is a browser and node compatible lib that doesn't have to go to the network to pick up the API definition, and is just ready to roll with what is supplied.  

Just to test the possibility of my idea working (in node), i have created a temporary solution that starts it's own http server, points SwaggerClient at that, then closes the http server.  That works, but clearly is not an available option outside of node, and is a bit on the ugly side to begin with.  

Thanks!

**Comment by char0n** [comment]
Hi @ericblade,

`swagger-client` can consume specification as a JavaScript object as demonstrated [here](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/try-it-out-executor.md#alternate-api). This allows you to bundle the specification file in JSON format using Webpack with your library and swagger-client.

**Comment by ericblade** [comment]
So, if I were to import the .json file, then doing new SwaggerClient({ spec: jsonObj }) results in the same as new SwaggerClient('http://localhost:9000') if I'm serving it from localhost:9000 ?

This seems like it would be good to put in the main docs, instead of hiding in a supplement :-)

I'll go try it out, right away.  Thank you!

**Comment by char0n** [comment]
> So, if I were to import the .json file, then doing new SwaggerClient({ spec: jsonObj }) results in the same as new SwaggerClient('http://localhost:9000') if I'm serving it from localhost:9000 ?

Yes it's completely equivalent.

> This seems like it would be good to put in the main docs, instead of hiding in a supplement :-)

[All our documentation documents](https://github.com/swagger-api/swagger-js/tree/master/docs/usage) contains examples how to use plain JavaScript object as specification and pass it to library. It's almost everywhere. Do you have any suggestions how make it better?

> I'll go try it out, right away. Thank you!

Glad to be of help.

**Comment by ericblade** [comment]
Clearly, I don't know this very well, having just poked at it, and managed to implement a very quick usage, based on the examples.  But, my gut feel, is that there's a lot of options (most of them under the "Try It Out Executor" page) that it's not obvious are part of how you use the main API -- i totally glossed over that page, presuming it was a demonstration rather than a documentation, and the "API" page is basically void of useful information.  

I just glanced over all the pages, and although I do see spec used in a couple of examples, I don't see anything explicitly explaining it as an option to the SwaggerClient constructor, except buried in the Executor page.

There's probably a lot of room for improvement here, at the very least, an API page that actually describes all of the possible options to the constructor and the interface of the class instance, I'm not seeing anything like that here.

**Comment by ericblade** [comment]
I just checked this out, and it works great.  I just have to figure out how to get typescript to import the json in a way that browser and node find palatable :-)

Thank you very much!
