### ISSUE TITLE
Schema with model $ref not working

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#183]
See https://github.com/swagger-api/swagger-ui/issues/773#issuecomment-68212636

Also we want to support external refs.

**Comment by johnwiesel** [comment]
any workaround currently for the support of external refs? without the external file support refs are kind of limited to smaller objects and makes code reuse impossible..

**Comment by fehguy** [comment]
Please be patient, this will have formal support shortly

**Comment by johnwiesel** [comment]
Looking forward to it. Thank you fehguy, your work is greatly appreciated!

**Comment by fehguy** [comment]
addressed in https://github.com/swagger-api/swagger-js/commit/be447c4c54c5afec024113042390bd8a0e28ba25
