### ISSUE TITLE
does this provide validation for incoming data?

### ISSUE THREAD

**Issue by ericblade** [swagger-api/swagger-js#1856]
sorry for the possibly silly question, but i haven't figured out a way to test it, and the code is mostly illegible to me, but...

does this library provide validation for incoming data? i know it does for outgoing parameters, but i can't figure out if there's a mismatch in server provided data from the API spec, if it would just happily pass it along, or if it would throw, or return an error or something.

**Comment by char0n** [comment]
@ericblade,

> sorry for the possibly silly question, but i haven't figured out a way to test it, and the code is mostly illegible to me, but...

No worries, we're here to answer any question.

> does this library provide validation for incoming data? i know it does for outgoing parameters, but i can't figure out if there's a mismatch in server provided data from the API spec, if it would just happily pass it along, or if it would throw, or return an error or something.

This library does not do validation of data. It assumes that the data passed to library are already valid. It only does what it says it does: **Swagger Client** is a JavaScript module that allows you to fetch, resolve, and interact with Swagger/OpenAPI documents.

**Comment by ericblade** [comment]
I figured I should ask, because I know that if I supply an incorrect outgoing parameter, it throws :-)  While in the real world, it would be great if we could be 100% sure that the API description is what is *actually* being served, when I'm dealing with Amazon as the sender, I'm not going to have confidence that they won't send me at least additional fields beyond what is expected, if not totally different data potentially.

In any case, I'm eventually feeding this back out to a TypeScript system, so I'm trying to work out how to get some type safety out of this library.  I'm leaning towards, right now, writing a wrapper for each of the swagger-client functions that figures out if it got an API return or an error, and then returns the correct typecast for the data.

Thanks for the quick answer!

**Comment by char0n** [comment]
Yes, what you describing is possible, but type safety it out of the door in moment when code already runs in production.

It sounds more like you're looking for an end-to-end functional tests for your API that should run as part of your CI/CD pipeline. We have a [webpage](https://swagger.io/solutions/api-testing/) where you can start.

Another alternative can be using some of the opensource library like [dredd](https://github.com/apiaryio/dredd), but support for OpenApi is limited there.

**Comment by ericblade** [comment]
type safety isn't completely out, but needs an additional validation layer.  'ajv' apparently can be massaged to handle validation based on swagger data, but i haven't exactly figured out the right way to Get There From Here.

I don't have control over the endpoints of the API, and from previous experience, I don't trust that their definitions will be updated 100% when their internals change.  so, the way to absolute type safety involves -- validation that the endpoint does exactly what it claims it will do, as well as breaking if the endpoint doesn't.  It's a bit of a catch-22, in that the API should always return any additional fields, even if they aren't known, as that may be a new spec... but i don't trust amazon to not make changes that violate that contract.

*if* swagger-client validated that all expected fields were received, as well as passed on any fields that are not expected, then i could just simply typecast the return values into the typescript types, and be good.  But with at least 100 typescript types as possible returns, it's something i'd like to automate. :-D
