### ISSUE TITLE
Entities DTO and enum types

### ISSUE THREAD

**Issue by storageddd** [swagger-api/swagger-js#1869]
Hello! I try to use swagger-js API client. It good solution, but I have one question:

How I can get entities DTO and their enum types from this package? Maybe need to add new feature for it?
DTO need for props convert and validate, enum need for DRY principle.

Example of usage entity DTO and enum:
```
// Create new order
const orderDTO = new Order(params);
client.apis.order.createOrder(orderDTO);

// Update order
client.apis.order.updateOrder({ status: status: Order.statusEnum.done });
```

**Comment by char0n** [comment]
Hi @storageddd,

This library doesn't generate DTOs, it just accepts data in form of POJOs (Plain old Java object). It's up to library consumer to provide his own DTOs. 

We will probably not be adding DTO generation layer as it introduces additional layer of complexity.

**Comment by storageddd** [comment]
Thanks for fast answer!
Well, we can close issue.
