### ISSUE TITLE
usage with react client 

### ISSUE THREAD

**Issue by HebaAhmadSaleh** [swagger-api/swagger-js#1885]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Environment: [e.g. Chrome 59, Node.js v10.0.0]
 - Method of installation: [e.g. npm, unpkg]
 - Swagger-Client version: [e.g. 3.8.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-Client usage:
```js
SwaggerClient({
  // your config options here
})
```

### How can we help?

I made all steps and it is working but I have a question I shall make node server to make it work ? because when I remove the server it is not working ? I just don't understand why shall I have server to fetch a request, isnt it client library

**Comment by char0n** [comment]
Hi @HebaAhmadSaleh,

I'd need more information about what you're trying to achieve to in order to help you. 

> I made all steps 

When you refer to steps, what do you actually mean? Can you share a complete code fragment?

> shall make node server to make it work ? because when I remove the server it is not working ? I just don't understand why shall I have server to fetch a request, isnt it client library

Yes, swagger-client is client library and can fetch an OAS definition if located on any URL accessible on internet. Or it can consume a `spec` object loaded by `fs` module when in `node.js` environment.

I could help you more, but I need to understand what you're trying to do and ideally see some code fragment along with it.

**Comment by HebaAhmadSaleh** [comment]
What I need, I have the open api contract for the backend and it refers to url where it is not developed yet, I mean url inside the yaml file.
I need to start developing in frontend and fetching apis and I do so now by swaggerclient sending my operationId which is in the contract. Can I use the swagger Client in order to fetch api not developed yet but its specs ready in yaml/json swagger file ?

**Comment by char0n** [comment]
> Can I use the swagger Client in order to fetch api not developed yet but its specs ready in yaml/json swagger file ? I mean like SwaggerClient("getUsers"). then (response => // use response )

Yes you can. But the actual calls to non existing API server will fail and SwaggerClient will return rejected promises. 

What you need here is a mock of backend API generated from yaml/json swagger file. You can generate a mock version of your backend API by using your yaml/json spec swagger file pasting it to https://editor.swagger.io/. In menu use `Generate Server` -> `nodejs-server`. Download the generated nodejs server, and run it locally. Then modify your yaml/json swagger file to point to this mock server.

**Comment by HebaAhmadSaleh** [comment]
Thank you so much, Yes this is actually what I have been done according to the link and thought I did wrong
