### ISSUE TITLE
[develop 2.0] support inline schemas

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#189]
It's legal to support schemas directly in-line, which is not currently supported in the js client.

**Comment by hamx0r** [comment]
FYI this is visible in the petstore example:
http://petstore.swagger.io/#!/user/loginUser

Per the respective JSON, we should be seeing a "200" response defined in addition to the (visible) "400" response:
```
"responses":{  
               "200":{  
                  "description":"successful operation",
                  "schema":{  
                     "type":"string"
                  },
                  "headers":{  
                     "X-Rate-Limit":{  
                        "type":"integer",
                        "format":"int32",
                        "description":"calls per hour allowed by the user"
                     },
                     "X-Expires-After":{  
                        "type":"string",
                        "format":"date-time",
                        "description":"date in UTC when toekn expires"
                     }
                  }
               },
               "400":{  
                  "description":"Invalid username/password supplied"
               }
```
![image](https://cloud.githubusercontent.com/assets/423974/6630741/89a285b6-c8d9-11e4-9193-fc68da5de3be.png)

**Comment by webron** [comment]
@hamx0r - that's actually something different. You can see the 200 response at top, just below the path of the operation.

**Comment by hamx0r** [comment]
@webron - I see that.  I assumed the Response Messages section contained an exhaustive list of response types per the "responses" section of the swagger spec for the operation.  Is it expected behavior to split up the location where response types are presented on Swagger UI?  I'd expect the "200" "description" (successful operation) to show up somewhere.  

Also, the Response Content Type dropdown isn't clear to me - it appears to be an input for selecting how the server responds, but there's nothing in the swagger spec I see to control response content type.  Perhaps these issues will be addressed in 2.1-M2.

**Comment by webron** [comment]
Regarding the display - https://github.com/swagger-api/swagger-ui/issues/674.

Regarding the response content type drop down, that's what the `produces` is for.

**Comment by whitlockjc** [comment]
This has been fixed in recent commits.

**Comment by hamx0r** [comment]
Question: If i'm using Swagger UI (master) and would like to update it's
underlying swagger-js with a swagger-js develop_2.0 branch, what files
ought I to replace?  I assumed just replace the UI's
dist/lib/swagger-client.js (or swagger-client.min.js) with files from from:
https://github.com/swagger-api/swagger-js/tree/develop_2.0/browser.

Doing so throws a JS error, so i'm likely doing something wrong.  It looks
like most fixes in Swagger UI are from Swagger JS fixes, so I'd like to
know how to stay on the bleeding edge most effectively.

**Comment by whitlockjc** [comment]
The build process for swagger-ui has changed recently.  It use to be as simple as replacing a JavaScript library but now I will need to defer to @mohsen1 for this one.

**Comment by mohsen1** [comment]
if you use the develop_2.0 branch it's using npm to fetch directly from current SwaggerJS#develop_2.0.

**Comment by hamx0r** [comment]
Thanks  - i'd checked the timestamps of recent checkins, and swagger-ui looked about 10 hrs behind swagger-js, so i wouldn't have guessed.  

All the same, i'm seeing the same JS error when using what's pulled from swagger-ui develop_2.0:
swagger-ui.js:1670 Uncaught TypeError: Cannot read property 'replace' of undefined

![image](https://cloud.githubusercontent.com/assets/423974/6853010/8842544a-d3a5-11e4-8686-db4344673f04.png)

I'll open a bug report after looking for a related bug
