### ISSUE TITLE
if I have many server url in openApi3 yaml/json file 

### ISSUE THREAD

**Issue by HebaAhmadSaleh** [swagger-api/swagger-js#1901]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Environment: [e.g. Chrome 59, Node.js v10.0.0]
 - Method of installation: [e.g. npm, unpkg]
 - Swagger-Client version: [e.g. 3.8.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```
	"servers": [
		{
			"url": "production url",
			"description": "production"
		},
		{
			"url": "staging url",
			"description": "staging"
		},
		{
			"url": "http://localhost:7000",
			"description": "development"
		}
	],
Swagger-Client usage:
```js
SwaggerClient({
  // your config options here
})
```

### How can we help?

I have the openApi file contains inside servers an array and I want SwaggerClient to use only development in development Environment how to make it without setting it myself inside options of SwaggerClient like SwaggerClient({server: 'localhost' }) ?

**Comment by char0n** [comment]
Unfortunately it's not that simple. As Server can be defined via Server Object and associated Server Variables and can be placed in different places (like OpenApi.servers, Operation.servers, PathItem.servers) you always have to provide it when doing an actual request with swagger-client.

Here is an example how to achieve that in a request call: https://github.com/swagger-api/swagger-js/blob/master/docs/usage/tags-interface.md#openapi-v3x

**Comment by HebaAhmadSaleh** [comment]
yes, I actually did that and it is working nnow for example: 
const serverConfig = { server: process.env.API_URL };
export const getCountries = () => {
	return createSwaggerClient().then((client) => {
		return client.apis.countries.findAllCountries({}, serverConfig);
	});
};

**Comment by char0n** [comment]
I understand that this API doesn't really fit your simple usecase. You could probably use [requestInterceptor](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md#request-interceptor) to [override URL](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/tags-interface.md#options-override) that's being requested.

```js
const requestInterceptor = (request) => {
   if (!request.loadSpec) {
      // modify request.url here to change it to server: process.env.API_URL
   }
   return request;
};

new SwaggerClient({ 
  url: 'http://petstore.swagger.io/v2/swagger.json',
  requestInterceptor,
});

**Comment by HebaAhmadSaleh** [comment]
Okay, great Thank you so much.

**Comment by HebaAhmadSaleh** [comment]
I made it, but it replace whole request url, is there a way to make it not ignore function name for example 
baselink localhost:3000/ and operation which is for example getUsers on link /users. what is happening now it overides request url with origin only ( localhost:3000/ ) 

`const requestInterceptor = (request) => {
   if (!request.loadSpec) {
      // modify request.url here to change it to server: process.env.API_URL
      request.url = process.env.API_URL;
   }
   return request;
};

new SwaggerClient({ 
  url: 'myschema.json',
  requestInterceptor,
}); 
export const getUsers = () => {
return createSwaggerClient().then((client) => {
// this fails now cause request is localhost:port/ not localhost:port/users
return client.apis.countries.findAllUsers();
});
};
`

**Comment by char0n** [comment]
Well you have to parse the `request.url` and replace protocol, host and port with information contained in process.env.API_URL.

Refer to the documentation of URL parser how to achieve that: https://developer.mozilla.org/en-US/docs/Web/API/URL
