### ISSUE TITLE
Bundle size issue

### ISSUE THREAD

**Issue by Ragnar-Oock** [swagger-api/swagger-js#1903]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Environment: FireFox/Chrome
 - Method of installation: npm
 - Swagger-Client version: ^3.12.2
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger-Client usage:
```js
// get the spec, parse it, return and cache the result for future calls
function getClient() {
	return new Promise((resolve, reject) => {
		if (getClient.cachedClient) {
			resolve(getClient.cachedClient);
		}
		else {
			new SwaggerClient(process.env.VUE_APP_SWAGGER_PATH)
				.then(client => {
					getClient.cachedClient = client;
					resolve(client);
				})
				.catch(e => reject(e));
		}
	});
}
```

### Screenshots
> `vue-cli-service build --report` result :
> 
> ![image](https://user-images.githubusercontent.com/38219333/106935474-b007a100-671b-11eb-8a15-662a4233dd4a.png)

### How can we help?
Even though I'm not using YAML at any point (the Spec is a JSON file, all API responses are JSON). At build time `js-yaml` and `esprima` are part of my build artifact, making up to 30KB of Gziped code that will never be of any use.

Is there a way to tell swagger-client not to import those libraries?

related issues: #960 and #1165

**Comment by char0n** [comment]
Hi @Ragnar-Oock,

Yes there is a way. I assume you're building Vue application and using webpack to bundle it. swagger-client/swagger-js comes with a [specialized ES6 build fragments](https://unpkg.com/browse/swagger-client@3.12.2/es/). When you use webpack to bundle swagger-client in these ES6 build fragments are used. In order not to bundle esprima + js-yaml you have to configure you [webpack externals](https://webpack.js.org/configuration/externals/) not to include these two externals into your build fragment.

```js
module.exports = {
  //...
  externals: {
    esprima: 'esprima',
    'js-yaml': 'jsyaml',
  }
};
```

**Comment by Ragnar-Oock** [comment]
I'm getting the package from `npm`, from what I'm reading on webpack documentation I'll need to get the package from another source (i.e. unpkg), is that correct? Additionally, I added the lines you've shared to my webpack config but when I run a report both `esprima` and `jsyaml` are still in the bundle, I would assume it's a problem with my webpack config though.

**Comment by char0n** [comment]
> I'm getting the package from npm, from what I'm reading on webpack documentation I'll need to get the package from another source (i.e. unpkg), is that correct?

Nope, the fragments I described are part of npm package distribution. I've just used unpkg to demonstrate their presence.

> Additionally, I added the lines you've shared to my webpack config but when I run a report both esprima and jsyaml are still in the bundle, I would assume it's a problem with my webpack config though.

Yes I would say the problem is in the config as the webpack is the primary bundling mechanism for you. Unless you really use YAML file, the build should work without problem (and should not contain js-yaml and esprima)

**Comment by Ragnar-Oock** [comment]
thank you for your help, I'll try and make my config work.
