### ISSUE TITLE
Proper enum parsing for arrays

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-js#198]
The proper way to limit the allowed values of an array, should be defined within the `items` property.

```js
{
	"type": "array",
	"items": {
		"type": "string",
		"enum": [ "value1", "value2", "value3", "value4"]
	}
}
```

The current behavior ignores the enum definition, and reads it if it is defined at the same level as the `"type": "array`". Such a definition should be ignored.

**Comment by webron** [comment]
To clarify, the following use case should not be read as an enum, and the `enum` should be ignored:

```js
{
	"type": "array",
	"items": {
		"type": "string"
	},
	"enum": [ "value1", "value2", "value3", "value4"]
}
```

**Comment by fehguy** [comment]
moving to m2

**Comment by whitlockjc** [comment]
With array display currently broken in a few places, I think it's a good idea to punt on this one for now.  `getMockSignature` currently shows `array {}` and since arrays aren't displayed properly, fixing them in some places but not all doesn't make sense.

**Comment by whitlockjc** [comment]
This should be fixed.

**Comment by kevinconaway** [comment]
@whitlockjc I don't see this fixed in current master.

It looks like [this check](https://github.com/swagger-api/swagger-js/blob/master/lib/types/model.js#L278) is incorrect:

```javascript
if (cProperty.enum) {
    html += ' = <span class="propVals">[\'' + cProperty.enum.join('\', \'') + '\']</span>';
}
```

In the case of an array, _enum_ will be null.  The _enum_ value is actually in _cProperty.items.enum_

**Comment by kevinconaway** [comment]
Actually, it looks like [the test](https://github.com/swagger-api/swagger-js/blob/master/test/models.js#L415) is setup incorrectly:

```javascript

    cPetStore.definitions.Statuses = {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'available',
          'pending',
          'sold'
        ]
      }
    };
```

Shouldn't that be something like:

```javascript
    cPetStore.definitions.Statuses = {
      properties: {
        status: {
          type: 'array',
          items: {
            type: 'string',
            enum: [
              'available',
              'pending',
              'sold'
            ]
          }
        }
      }
    };
```

**Comment by ponelat** [comment]
@kevinconaway would you mind showing a partial of the spec and the expected results? I don't beleive the *check* mentioned above is meant for type:array's at all.

Also the test seems valid (at least from a glance).
It's injecting the partial as a type:array(with enum)
It doesn't need to inject it as type:object(statuses: type:array(with enum)) 
If that makes sense :smile:

**Comment by kevinconaway** [comment]
>It doesn't need to inject it as type:object(statuses: type:array(with enum)) 

I'm relatively new to Swagger but its my understanding that definitions needed to contain a _properties_ element to contain the properties.

> would you mind showing a partial of the spec and the expected results?

Below is the full spec I am testing with.  I expect to see the the allowable values for _types_ be _ONE_ and _TWO_

You can drop this in to the swagger editor or swagger UI to see how it renders.

```javascript
{
  "swagger": "2.0",
  "info": {
    "description": "Api Documentation",
    "version": "1.0",
    "title": "Api Documentation",
    "termsOfService": "urn:tos",
    "contact": {
      "name": "Contact Email"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "host": "localhost:__PORT__",
  "basePath": "/",
  "tags": [
    {
      "name": "enum-service",
      "description": "Service that return enums"
    }
  ],
  "produces": [
    "application/xml",
    "application/json"
  ],
  "paths": {
    "/enums/collection": {
      "get": {
        "tags": [
          "enum-service"
        ],
        "summary": "Example with enum collection",
        "operationId": "getCollectionValueUsingGET",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "*/*",
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/EnumCollection"
            }
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "petstore_auth": {
      "type": "oauth2",
      "authorizationUrl": "http://petstore.swagger.io/api/oauth/dialog",
      "flow": "implicit",
      "scopes": {
        "write:pets": "modify pets in your account",
        "read:pets": "read your pets"
      }
    },
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  },
  "definitions": {
    "EnumCollection": {
      "properties": {
        "types": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "ONE",
              "TWO"
            ]
          }
        }
      }
    }
  }
}
```

**Comment by webron** [comment]
@kevinconaway - if you're referring to it displaying just `ONE` and not both values, that has nothing to do with this issue. You can open a separate ticket for that.

`definitions` don't have to contain object types, so in terms of what's being tested, there's no problem.

**Comment by kevinconaway** [comment]
> if you're referring to it displaying just ONE and not both values, that has nothing to do with this issue.

@webron  If you take the swagger def that I posted above and move the _enum_ element out of _items_ and in to the same level as `"type": "array"`, you'll see that it ref is correctly modeled.  That was my read of this ticket.

I'll create a new issue though if you wish

**Comment by webron** [comment]
Thanks for the clarification. It looks like some cases are working and some don't. I don't know if this is because it wasn't fully fixed initially or because of a regression, but I'll reopen it.

The original two posts in the thread pretty much cover the cases, and it doesn't matter if the array is inside a model or as a 'primitive' array definition (for any parameter type). It's evident the in the case in the second post is not being followed (i.e., the `enum` is not ignored).

**Comment by kevinconaway** [comment]
Thanks @webron! Please let me know if I can provide any more details or clarification
