### ISSUE TITLE
[develop 2.0] `package.json` expects `dist/swagger.js` to exist

### ISSUE THREAD

**Issue by bebraw** [swagger-api/swagger-js#199]
I'm currently trying to use the development version of your client. I noticed there are a couple of gotchas with this. You might be aware of these but just listing these below:

* The 2.0 compatible version has to be installed through `npm install swagger-api/swagger-js#develop_2.0`. Ideally you would have a beta version available (maybe later?)
* `package.json` main field is set to point at `dist/swagger.js`. I figured out `gulp build` generates a dist but then it's named `dist/swagger-client.js`. Fortunately I can use that as a standalone for now.

**Comment by fehguy** [comment]
Thanks, you'll see a version in npmjs.org shortly.
