### ISSUE TITLE
Swagger doesn't handle case classes with same name but different package in request and response types

### ISSUE THREAD

**Issue by vbeffa** [swagger-api/swagger-js#200]
If I have an `ApiImplicitParam` with `dataType = "com.foo.in.Something"` and an `ApiResponse` with `response = classOf[com.foo.out.Something]` the generated docs will use `out.Something` for both the parameter's data type as well as the response's data type. Renaming `out.Something` to `out.OutSomething` causes the docs to generate the expected types.

**Comment by webron** [comment]
@vbeffa - did you intend to open this on [swagger-core](https://github.com/swagger-api/swagger-core)?

**Comment by vbeffa** [comment]
Maybe - I just did a web search on the problem I was having and found another issue for this project. Should this be in swagger-core?

**Comment by webron** [comment]
If the problem is with the output of @ApiImilicitParam, then yes. Assuming you use swagger-core and not swagger-springmvc or grape-swagger, or any other library that depends on swagger-core.

**Comment by vbeffa** [comment]
OK, I'll open it there instead. Thanks.
