### ISSUE TITLE
how to send query param when I use tags interface 

### ISSUE THREAD

**Issue by HebaAhmadSaleh** [swagger-api/swagger-js#2009]
### Q&A (please complete the following information)
 - OS: [e.g. linux]
 - Environment: [e.g. Chrome 59, Node.js v10.0.0]
 - Method of installation: [e.g. npm, unpkg]
 - Swagger-Client version: [e.g. 3.8.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-Client usage:
```js
const createSwaggerClient = spec =>
    SwaggerClient({
        spec,
        responseContentType: 'application/json',
    });

const serverConfig = {
    server: process.env.API_URL,
};

// in this api I want to send for example ====> ?q=test
const getStepsByCountryCode = countryCode =>
    createSwaggerClient(contract).then(client =>
        client.apis.steps.findStepsByCountry(countryCode, serverConfig)
    );
```

**Comment by HebaAhmadSaleh** [comment]
fixed by doing so: 
const getStepsByCountryCodeClientSwagger = (countryCode, area) =>
    createSwaggerClient(OnboardingAPIContract).then(client =>
        client.apis.steps.findStepsByCountry(
            {},
            { parameters: { area, countryCode } },
            serverConfig
        )
    );

**Comment by char0n** [comment]
Hi @HebaAhmadSaleh,

Parameters as passed in the following way:

```js
const getStepsByCountryCodeClientSwagger = (countryCode, area) =>
  createSwaggerClient(OnboardingAPIContract).then(client =>
    client.apis.steps.findStepsByCountry(
      { area, countryCode },
      {},
      serverConfig
    )
);
```

The syntax that you describe can be considered alternative way of doing the same thing. More info here: https://github.com/swagger-api/swagger-js/blob/master/docs/usage/tags-interface.md
