### ISSUE TITLE
Error callback is not called when opt not specified in call

### ISSUE THREAD

**Issue by brodyd** [swagger-api/swagger-js#203]
When calling a method resource with the signature { opt, callback, error } the error is not passed through into the lower calls because of the rebadging as arg1, arg2, arg3 and arg4 in the code.

Because the signatire is actually { args, opts, callback, error } arg4 should be set to callback if opts is not supplied because error will be null (and callback will contain the error callback).

```
if(typeof opts === 'function') {
        arg2 = {};
        arg3 = opts;
        arg4 = error;
      }
``` 
Should be
```
if(typeof opts === 'function') {
        arg2 = {};
        arg3 = opts;
        arg4 = callback;
      }
```
Otherwise the shift is ineffective and the error callback is lost.  This was introduced by the change for default callback but it appears to be a waiting issue because previously the arguments were passed through directly and not re-packaged as arg1 to 4.

**Comment by brodyd** [comment]
I've added a Pull Request to fix this issue.  A workaround can be done by adding an empty opts object to all resource requests.

**Comment by fehguy** [comment]
thanks added tests as well for both cases.
