### ISSUE TITLE
Provide fully configured swagger-js client for consumers

### ISSUE THREAD

**Issue by DinisCruz** [swagger-api/swagger-js#206]
Is it possible to set-up swagger-js on the server side in a such a way that its JS can be downloaded from a client (web or node) in a fully configured way?

Kinda like the asmx -> asmx.cs C# generation from a WSDL where the client *.cs files are already configured to connect to the host server?

**Comment by SLonoed** [comment]
+1
Dont want load configs in production.

**Comment by fehguy** [comment]
Yes, when you configure swagger-js you can pass the spec directly to it, which means it can be bundled up in a single file with the entire swagger definition in it.  Is that what you mean?

**Comment by DinisCruz** [comment]
@fehguy  Sounds like it, can you point me to an example?

**Comment by SLonoed** [comment]
@DinisCruz, I found this https://github.com/signalfx/swagger-client-generator/
Use it in my project.

**Comment by fehguy** [comment]
Yes, you can simply set your swagger spec to a variable:

```js
var spec = { swagger: "2.0", host: "http://blah.com"... }
```

and pass it when initializing the client:

```js
var client = new SwaggerClient({spec: spec, ...})
```

**Comment by DinisCruz** [comment]
Great, thanks

**Comment by fehguy** [comment]
supported in M1
