### ISSUE TITLE
How to use swagger client with typescript ?

### ISSUE THREAD

**Issue by mrsolarius** [swagger-api/swagger-js#2117]
### Q&A (please complete the following information)
 - OS: Windows 7
 - Environment: NodeJs V14.15.1
 - Method of installation: npm
 - Swagger-Client version: 3.13.5
 - Swagger/OpenAPI version: Swagger 2.0

Swagger/OpenAPI definition:
I make my try on this public swagger API : https://lldev.thespacedevs.com/2.2.0/swagger?format=openapi

Swagger-Client usage:
this is my test code
```typescript
import SwaggerClient from 'swagger-client';

async function testOpenAPI() : Promise<void> {
    const client : SwaggerClient = await new SwaggerClient('https://lldev.thespacedevs.com/2.2.0/swagger?format=openapi')
    console.log(client)
}

testOpenAPI()
```

### How can we help?
I wanna use swagger client with my full typescript code but when I run the test code I have this typescript error : 
```
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
test/testSwagger.ts:1:27 - error TS7016: Could not find a declaration file for module 'swagger-client'. 'C:/Users/LVO/WebstormProjects/StarsBot/node_modules/swagger-client/lib/commonjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/swagger-client` if it exists or add a new declaration (.d.ts) file containing `declare module 'swagger-client';`

1 import SwaggerClient from 'swagger-client';
                            ~~~~~~~~~~~~~~~~

    at createTSError (C:\Users\LVO\WebstormProjects\StarsBot\node_modules\ts-node\src\index.ts:587:12)
    at reportTSError (C:\Users\LVO\WebstormProjects\StarsBot\node_modules\ts-node\src\index.ts:591:19)
    at getOutput (C:\Users\LVO\WebstormProjects\StarsBot\node_modules\ts-node\src\index.ts:921:36)
    at Object.compile (C:\Users\LVO\WebstormProjects\StarsBot\node_modules\ts-node\src\index.ts:1189:32)
    at Module.m._compile (C:\Users\LVO\WebstormProjects\StarsBot\node_modules\ts-node\src\index.ts:1295:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\LVO\WebstormProjects\StarsBot\node_modules\ts-node\src\index.ts:1298:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```

So I have tried to install the swagger type like that: `npm i --save-dev @types/swagger-client` but I have get a 404 error like this : 
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fswagger-client - Not found
npm ERR! 404
npm ERR! 404  '@types/swagger-client@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git URL.
```
So what I'm doing wrong with my typescript try?

**Comment by char0n** [comment]
Hi @mrsolarius,

swagger-client doesn't officially come with typescript support. There has been multiple attempts to create TypeScript typings for this library; latest of these attempts can be tracked here: https://github.com/swagger-api/swagger-js/issues/1969

In order to make swagger-client work within TypeScript codebase have a look at this article: https://medium.com/@steveruiz/using-a-javascript-library-without-type-declarations-in-a-typescript-project-3643490015f3 (Plan C). Basically you have to create your own declaration file.

**Comment by mrsolarius** [comment]
Thanks for your comments and suggestions I will try it 😁.

**Comment by char0n** [comment]
Np
