### ISSUE TITLE
Does Swagger Client supports pagination?

### ISSUE THREAD

**Issue by tarfahalrashed** [swagger-api/swagger-js#2146]
- OS: macOS
 - Environment: Node.js v14.15.5
 - Method of installation: npm
 - Swagger-Client version: 3.13.7
 - OpenAPI version: OpenAPI 3.0.2

### Content & configuration

OpenAPI Specification:
```json
https://api.apis.guru/v2/specs/vimeo.com/3.4/openapi.json
```

Swagger-Client usage:
```js
SwaggerClient({ 
  url: 'https://api.apis.guru/v2/specs/vimeo.com/3.4/openapi.json',
  authorizations: { oauth2: { token: { access_token: '<MY-TOKEN>' } } }
}).then(client => client.execute({
  operationId: "search_videos",
  parameters: { query:"Adele"},
})).then(result => {
  console.log("result: ", result.body.data)
})
```

Does Swagger Client supports pagination? 
With Vimeo search video API I know that it uses index pagination with the two parameters "page" which starts at 1 and "per_page" which can be set to 100 max. Is there an easy way to specify the pagination using the Swagger Client library.

Thanks,

**Comment by char0n** [comment]
Hi @tarfahalrashed,

Yes it does, it should just a matter of providing the actual params:

```js
SwaggerClient({ 
  url: 'https://api.apis.guru/v2/specs/vimeo.com/3.4/openapi.json',
  authorizations: { oauth2: { token: { access_token: '<MY-TOKEN>' } } }
}).then(client => client.execute({
  operationId: "search_videos",
  parameters: { query:"Adele", page: 1, per_page: 20},
})).then(result => {
  console.log("result: ", result.body.data)
})
```

**Comment by tarfahalrashed** [comment]
Thanks for your reply.
I know that this is how you get the result for each page.
But my question was let's say I want to get 300 videos from Vimeo, can I specify that using the Swagger Client library, and Swagger Client will "automatically" go over multiple pages (send multiple requests to Vimeo and fetch the results for me)?

**Comment by char0n** [comment]
Unfortunately no, that's something you'll have to do yourself. As there are different types of pagination (page + items per page or offset + limit, and others...) mechanisms, swagger-client provides basic way to achieve it via parameters but leaves higher-order use-cases like yours for implementors.
