### ISSUE TITLE
Rendered Array missing closing square bracket

### ISSUE THREAD

**Issue by retrospectacus** [swagger-api/swagger-js#215]
I have the following JSON which describes the schema of a 200-code response.

>        "Array Of Trades": {
>            "required": [ "Trades" ],
>            "properties": {
>                "Trades": {
>                    "description": "Search results",
>                    "type": "array",
>                    "$ref": "Trade"
>                }
>            }
>        }

It is rendered as: `Trades (Array[undefined): Search results` - the closing square bracket is missing. (I think "undefined" should be "Trade" but that is another issue)

**Comment by retrospectacus** [comment]
This was my fix,

> @@ -1288,10 +1288,11 @@
>  getStringSignature = function(obj) {
>    var str = '';
>    if(obj.type === 'array') {
> -    obj = (obj.items || obj['$ref'] || {});
>      str += 'Array[';
> +    str += getStringSignature((obj.items || obj['$ref'] || {}))
> +    str += ']';
>    }
> -  if(obj.type === 'integer' && obj.format === 'int32')
> +  else if(obj.type === 'integer' && obj.format === 'int32')
>      str += 'integer';
>    else if(obj.type === 'integer' && obj.format === 'int64')
>      str += 'long';
> @@ -1313,8 +1314,6 @@
>      str += simpleRef(obj['$ref']);
>    else
>      str += obj.type;
> -  if(obj.type === 'array')
> -    str += ']';
>    return str;
>  }

**Comment by retrospectacus** [comment]
I fixed my other issue ("undefined" should be "Trade") like so

```javascript
@@ -1312,7 +1313,7 @@
   else if(obj['$ref'])
     str += simpleRef(obj['$ref']);
   else
-    str += obj.type;
+    str += obj;
   return str;
```
But I don't know if that is ideal

**Comment by retrospectacus** [comment]
Here is my patch which also fixes the other issue ("undefined" should be "Trade"):
```javascript
@@ -1287,11 +1287,14 @@
 
 getStringSignature = function(obj) {
   var str = '';
-  if(obj.type === 'array') {
-    obj = (obj.items || obj['$ref'] || {});
+  if(typeof obj.type === 'undefined')
+    str += obj;
+  else if(obj.type === 'array') {
     str += 'Array[';
+    str += getStringSignature((obj.items || obj['$ref'] || {}))
+    str += ']';
   }
-  if(obj.type === 'integer' && obj.format === 'int32')
+  else if(obj.type === 'integer' && obj.format === 'int32')
     str += 'integer';
   else if(obj.type === 'integer' && obj.format === 'int64')
     str += 'long';
@@ -1301,6 +1304,8 @@
     str += 'date-time';
   else if(obj.type === 'string' && obj.format === 'date')
     str += 'date';
+  else if(obj.type === 'string' && typeof obj.format === 'undefined')
+    str += 'string';
   else if(obj.type === 'number' && obj.format === 'float')
     str += 'float';
   else if(obj.type === 'number' && obj.format === 'double')
@@ -1313,8 +1318,6 @@
     str += simpleRef(obj['$ref']);
   else
     str += obj.type;
-  if(obj.type === 'array')
-    str += ']';
   return str;
 }
 
```
Now it renders as: `Trades (Array[Trade]): Search results`

**Comment by retrospectacus** [comment]
Those patches are to `lib/swagger-client.js`, I forgot to mention.

**Comment by fehguy** [comment]
ok thank you.  The output, lib/swagger-client.js, is generated by running gulp build.  It's built by all the files under src/js so your patch needs to be made on those files.  Can you please update the PR for that?

**Comment by fehguy** [comment]
BTW this is in develop_2.0 branch, which is where swagger-client lives:

https://github.com/swagger-api/swagger-js/tree/develop_2.0/src/js

**Comment by fehguy** [comment]
this is fixed
