### ISSUE TITLE
Endpoint missing in URL when building request

### ISSUE THREAD

**Issue by pferioli** [swagger-api/swagger-js#2169]
### Q&A (please complete the following information)
 - OS: macOS
 - Environment: [loopback4, node.js v14.15.4]
 - Method of installation: "npm loopback-connector-openapi"
 - Swagger-Client version: "swagger-client": "^3.11.1"
 - Swagger/OpenAPI version: [swagger 2.0]

### Content & configuration
i'm interacting with an API provided by a BMC product using the loopback-connector-openapi, the datasource has a URL parameter with and endpoint "https://192.168.100.68:8443/automation-api"

### How can we help?
the connector requires an URL which in my case it's the base url followed by an endpoint (/automation-api). When creating the request for any operation this function "swagger2BaseUrl" (./lib/execute/index.js line #397) in the swagger-client is called and the request URL returned has no endpoint, so the final url joins the "baseUrl" + "operation" missing a part and then fails.

swagger2baseUrl receives the following parameters...

```
contextUrl:'https://192.168.100.68:8443/automation-api'
pathName:'/run/job/{jobId}/status'

```
and returns 'https://192.168.100.68:8443'

when it's time to build the request uses (line #206 within buildRequest function)  

```
 req.url += baseUrl({
    spec,
    scheme,
    contextUrl,
    server,
    serverVariables,
    pathName,
    method
  }); // Mostly for testing
...
req.url += pathName; 
```
and in this step the "automation-api" endpoint is missing and the request fails

So for testing purposes i modified the req.url manually and worked but i think this is a wrong behavior in the swagger-client

`req.url += "/automation-api" + pathName;
`

![image](https://user-images.githubusercontent.com/19712247/128092462-e77bb328-c588-4df9-97a6-a53196fb3e34.png)

thanks for your help !

**Comment by char0n** [comment]
Hi @pferioli,

Could I ask you to come up with a test case I can actually test on to verify this? I need a OAS fixture and the minimal actual code that I need to run and see the actual result (and compare with  expected). If I have those two things I would probably be able to fully understand your problem and help you. 

Cheers

**Comment by char0n** [comment]
Closing this as we couldn't actually reproduce without minimal code + fixture.
