### ISSUE TITLE
add extended formats

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#219]
It'd be nice to support more extended formats:
- [ ] password
- [ ] uuid, uuid3, uuid4, uuid5
- [ ] email
- [ ] uri (absolute)
- [ ] hostname
- [ ] ipv4
- [ ] ipv6
- [ ] credit card
- [ ] isbn, isbn10, isbn13
- [ ] social security number
- [ ] hexcolor
- [ ] rgbcolor
- [ ] date
- [ ] date-time
- [ ] duration

**Comment by webron** [comment]
Closing as an old ticket.
