### ISSUE TITLE
model samples can get in infinite loop

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#222]
The ArrayModel can get in an infinite loop

**Comment by domaindrivendev** [comment]
Component: {
  type: "object",
  properties: {
    name: {
      type: "string"
    },
    subComponents: {
    type: "array",
    items: {
     $ref: "Component"
    }
  }
  },
  x-schema: "bar"
}

**Comment by domaindrivendev** [comment]
ListOfSelf: {
type: "array",
items: {
$ref: ListOfSelf"
}

DictionaryOfSelf: {
  type: "object",
  additionalProperties: {
  $ref: "DictionaryOfSelf"
  }
}

**Comment by fehguy** [comment]
fixed in master, will be in 2.1.1-M1
