### ISSUE TITLE
switch isBuffer to ArrayBuffer.isView

### ISSUE THREAD

**Issue by jimmywarting** [swagger-api/swagger-js#2243]
...just a suggestion for not depending on node:buffer as much

https://github.com/swagger-api/swagger-js/blob/af2b86cf9c7552b3e9d00659522bd4ca91dd489e/src/http/index.js#L354-L363

node buffer is a bloated nodeJS specific thing, something more cross friendly for Deno/Browser is using plain uint8array...

**Comment by char0n** [comment]
Yeah great idea, now that we are on Node.js min version of 12.4 this should be possible and the code will be isomorphic (working in browser and node respectively).
 
 The only requirement is that the library needs to work as before: it needs to support consuming Buffer instances and process them correctly. We have a lot of tests demonstrating how we consume buffer instances.
 
 As you already suggested we can replaced `Buffer.isBuffer` with `ArrayBuffer.isView`.
 
 We can use `TextEncoder` to create TypedArray instances of `Uint8Array`; `TextDecoder` to do the opposite.


Feel free to issue a PR.
