### ISSUE TITLE
Provide type definition file for TypeScript

### ISSUE THREAD

**Issue by pvcresin** [swagger-api/swagger-js#2248]
I want you to provide a type definition file for TypeScript.

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Write index.d.ts file and add to package.json

**Comment by char0n** [comment]
Swagger-js officially doesn't support TypeScript and doesn't come with the typings definition. There has been multiple attempts to provide one by the community, but none of these attempts were successful:

- https://github.com/swagger-api/swagger-js/issues/2117
- https://github.com/swagger-api/swagger-js/issues/1969

**Comment by pvcresin** [comment]
@char0n I understand. Thanks.
