### ISSUE TITLE
option to disable ssl cert check

### ISSUE THREAD

**Issue by rahulreddy** [swagger-api/swagger-js#229]
Currently there is no way to disable ssl certificate check, so I am using this monkey patch in my code
```
var src = fs.readFileSync(module_file, 'utf8')
    .replace(
        'this.shred = new this.Shred(options)',
        'this.shred = new this.Shred({defaults: {sslStrict:false}})' 
    )
```
It would be helpful if we can pass this as an option when instantiating the client.

**Comment by webron** [comment]
That looks like one step before submitting a PR ;)

**Comment by fehguy** [comment]
you can now pass opts to the client when making the calls:

```
new SwaggerHttp().execute(obj, opts);
```

These opts will flow to which either client specified as in obj.useJQuery.

**Comment by nrshrivatsan** [comment]
Should the options be passed like

```
var opts = {};
      opts.spec = {
          swagger: '2.0',
          defaults: {
        	  sslStrict:false
          }      
      };
      new SwaggerHttp().execute(obj,opts);

```
