### ISSUE TITLE
replace node:url with native url?

### ISSUE THREAD

**Issue by jimmywarting** [swagger-api/swagger-js#2291]
https://github.com/swagger-api/swagger-js/blob/ba0db610cfbd6b716206e2eefe8b46760606b30c/src/index.js#L86-L102

**Comment by char0n** [comment]
Yeah, don't see a reason why not.

**Comment by char0n** [comment]
I was triaging this issue a bit and came into conclusion that replacing the `url` Node.js module with WHATWG API will not be that easy. 

`url.resolve` can be replaced with following function, that's no brainer.

```js
// WHATWG URL API replacement for url.resolve function
export function urlResolve(from, to) {
  const resolvedUrl = new URL(to, new URL(from, 'resolve://'));
  if (resolvedUrl.protocol === 'resolve:') {
    // `from` is a relative URL.
    const { pathname, search, hash } = resolvedUrl;
    return pathname + search + hash;
  }
  return resolvedUrl.toString();
}
```

But  `url.parse(str)` cannot be easily replaced with `new URL(str)` as the URL constructor expects valid URL as the first parameter and throws error when provided argument is not valid URL.

**Comment by char0n** [comment]
Found an inconsistency in WHATWG URL parsing. Before this inconsistency is addressed, let's put this issue on hold.

Inconsistency described here: https://github.com/whatwg/url/issues/677
