### ISSUE TITLE
use extension in relative imports

### ISSUE THREAD

**Issue by jimmywarting** [swagger-api/swagger-js#2292]
https://github.com/swagger-api/swagger-js/blob/ba0db610cfbd6b716206e2eefe8b46760606b30c/src/index.js#L3-L8

extension less is a bit non-esm ish way of doing things

**Comment by jimmywarting** [comment]
I'm guess the only reason why this still work without extension is b/c you transpile it to cjs for compability?

**Comment by char0n** [comment]
@jimmywarting exactly, CJS is just one of the transpiled form. Mapping of build fragments is explicitly defined in package.json:

https://github.com/swagger-api/swagger-js/blob/master/package.json#L10
