### ISSUE TITLE
enable map support

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#230]
for the 2.0 spec support, need to add map support for model samples, data types, etc.

**Comment by fehguy** [comment]
the `createJSONSample` needs to support maps:


```json
{
  "string": ...
}
```

as does the `getMockSignature` function

**Comment by whitlockjc** [comment]
Just to make sure I'm understanding this properly, you want complex properties to be supported where the type of the property is `object` or a reference to an model.  Is this correct?

**Comment by fehguy** [comment]
Yes that sounds correct

**Comment by whitlockjc** [comment]
This is the test I have passing right now for `createJSONSample`: http://pastie.org/private/fxtzghfhz3wtn1um86rfw  I now need to do the same for `getMockSignature`.

**Comment by fehguy** [comment]
Will this work with "flat" model definitions?  Meaning, you have an in-line definition for `social` which should also behave correctly if it's a `$ref`

**Comment by whitlockjc** [comment]
No, references need to be updated to work this way but there is already an open issue(s) for that.  So it would work the same as it did before.  We can fix that soon.

**Comment by whitlockjc** [comment]
Pull request #261 was created against `master` instead of `develop_2.0` so it was closed.  Sorry about that, didn't realize.

**Comment by whitlockjc** [comment]
Any movement on this?  Tests pass but I need you to make sure this is what you wanted.

**Comment by whitlockjc** [comment]
There are a number of _related_ issues that will help make this better but _map support_ should be fixed by #262.
