### ISSUE TITLE
File upload with Node

### ISSUE THREAD

**Issue by kimgust** [swagger-api/swagger-js#231]
I'm having a hard time figuring out how to create a file upload example using our swagger docs. It works fine with our [Swagger UI](http://swagger.eyefi.com/#!/files/uploadFile).

The API declaration basically looks like:

``` json
{
    "apiVersion": "3",
    "swaggerVersion": "1.2",
    "basePath": "/3",
    "resourcePath": "/files.{format}",
    "apis": [
        {
            "path": "/files.{format}",
            "operations": [
                {
                    "method": "POST",
                    "summary": "Upload a JPG file (up to 100MB)",
                    "nickname": "uploadFile",
                    "parameters": [
                        {
                            "name": "File",
                            "description": "The file",
                            "paramType": "body",
                            "required": true,
                            "type": "file"
                        }
                    ],
                    "type": "File",
                    "responseMessages": [
                        {
                            "code": 201,
                            "message": "Request succeeded"
                        }
                    ]
                },
```

In the swagger js client the method ends up being as shown [here](https://github.com/eyefi/eyefi-js#objects-and-methods):

``` js
swagger.apis.files.uploadFile(...)
```

It's just unclear to me what to pass in as the arguments. I imagine is some combination of a the output of fs.readFileSync() and setting a requestContentType header to multipart/form-data, but so far I haven't been able to get the data sent to the server.

Any ideas? I haven't seen any examples of this yet through extensive searching.

Thanks! It's the missing link in our recently publishes Swagger docs.

**Comment by fehguy** [comment]
Hi, currently file upload strictly with swagger-js is not supported.  There is a [branch](https://github.com/swagger-api/swagger-js/tree/feature/file-upload) to move the file upload INTO swagger-js for browsers, but this does not support node.

I do think, though, that file upload from node is the easy part.  I want to get it into the library, where jquery is required for the browser-based upload, and node can do it natively inside the lib.

Let's use this ticket to track progress, my goal was to move the file upload support out of swagger-ui and into swagger-js in the 2.1.0-M2 release.

**Comment by kimgust** [comment]
Got it, thanks! I could help take a look at this for node, especially if you already have some hints as to where to start in the library.

**Comment by fehguy** [comment]
That'd be great.  Let me post back here once I get the fileUpload logic merged into develop_2.0..  Thaks for offering!

**Comment by fehguy** [comment]
The file upload logic has been merged into 2.1.8-M1 for swagger 2.0 specs only.  It's triggered here:

https://github.com/swagger-api/swagger-js/blob/develop_2.0/src/js/swagger-a.js#L677

I think the right thing to do is to add logic for node here, where if useJQuery is not set, it'll fire the node logic for preparing the body param object.  Then in the underlying ShredHttpClient:

https://github.com/swagger-api/swagger-js/blob/develop_2.0/src/js/swaggerHttp.js#L138

We can determine that the file is going to be read from node.  Make sense?

**Comment by ozruiz** [comment]
just spent a fair amount of time trying to get this to work. would love to get it in.

**Comment by let4be** [comment]
Any update?

**Comment by fehguy** [comment]
added in 2.1.19 and greater

**Comment by glebmachine** [comment]
So, how i do upload file with swagger-client?
Can you provide code example please (there is no example in readme file)

**Comment by fehguy** [comment]
Please look in the tests, there are tests for both browser and node-based file uploads

**Comment by glebmachine** [comment]
Thanks!

**Comment by mauricesvay** [comment]
I haven't found the test containing a node-based file upload. Could you indicate a filename to look for?

**Comment by fehguy** [comment]
Well!  I thought the tests were tighter.  Please see here for browser based upload:

https://github.com/swagger-api/swagger-js/blob/master/test/browser/petstore.js#L17

And I'll get some tests implemented for node uploads as well.

**Comment by mauricesvay** [comment]
I was confused at first because there's no `attach()` method like in Superagent, but I found out that I could just pass a `ReadStream` of my file with `fs.createReadStream` to upload it.
Thanks!

**Comment by thiagobustamante** [comment]
I'm having problems to implement file uploads in node js.

I have the following swagger 2.0:
```yaml
  /middleware/authentication/strategies:
    post:
      operationId: MiddlewareRestAddAuthStrategy
      responses:
        '204':
          description: No content
      description: ''
      tags:
        - Middleware
      security:
        - Bearer: []
      consumes:
        - multipart/form-data
      parameters:
        - description: 'Middleware file'
          in: formData
          name: file
          required: true
          type: file
        - description: 'Middleware name'
          in: formData
          name: name
          required: true
          type: string
```
And I am trying to call this using the following code:

```javascript
function addAuthStrategy(name, fileName) {
        return new Promise((resolve, reject) => {
            const stream = fs.createReadStream(fileName);
            this.swaggerClient.apis.Middleware.MiddlewareRestAddAuthStrategy({name, file: stream})
                .then(response => {
                    if (response.status === 204) {
                        return resolve();
                    }
                    reject(response.text);
                })
                .catch(reject);
        });
}
```
The request is created to target operation, but the expected parameters (name and file) are both being received as undefined. Not is being sent to the server.

I also tried to change the ```createReadStream```call to ```fs.readFileSync(fileName)```, but the problem remains. 

I am missing something? It is the correct way to call this? I could not found any documentation nether a test case. The links to test cases above are broken.

Thanks in advance.

**Comment by dcarrot2** [comment]
@thiagobustamante Were you able to fix your issue? I'm experiencing the same problem, and from reading the source code, it's not possible to pass a buffer for a formdata file upload if you're targeting a swagger 2.0 spec? https://github.com/swagger-api/swagger-js/blob/ba6c94912bb13e7fb2cdc6bc88b348c353a789c8/src/execute/oas3/build-request.js#L71
