### ISSUE TITLE
This API is using a deprecated version of Swagger! 

### ISSUE THREAD

**Issue by alycda** [swagger-api/swagger-js#234]
Hi,

Before your most recent commits ( b33ba3edc8e206100c715609e4e28e638b4aae06 - 968f56e02b2ac3c3a54a73ed1707d0b15246827f ) I was able to use swagger-js (v2.1.1-M1) in the browser, following your example in the [README](https://github.com/swagger-api/swagger-js#calling-an-api-with-swagger--the-browser) and setting `useJQuery: true` (Issue #96). However, I now get the following error:

`XMLHttpRequest cannot load http://petstore.swagger.wordnik.com/api/api-docs?_=1423595984814. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://swagger-js.dev' is therefore not allowed access.` **(index):1**
`swagger-client.js:541 Uncaught Can't read from server.  It may not have the appropriate access-control-origin settings.` **swagger-client.js:541**

I changed the `url` to **http://petstore.swagger.io/v2/swagger.json** but now I'm getting a new error:

`This API is using a deprecated version of Swagger!  Please see http://github.com/wordnik/swagger-core/wiki for more info` **swagger-client.js:197**
`swagger-client.js:1595 Uncaught TypeError: Cannot read property 'length' of undefined` **swagger-client.js:1595**

I discovered this issue yesterday, when a project I'm developing (utilizing requireJS) stopped working. After changing the url as noted above, I did not get the second error mentioned, but `swagger.ready` was no longer set, so the apis object remains empty. I encountered the second error above by cloning this repo (v2.1.2-M1), the other project I'm referring to is using version v2.1.1-M1

**Comment by fehguy** [comment]
OK but in general are you using swagger 2.0 specs or 1.2?  There is a fix coming for the 1.2 specs to avoid the swagger.ready check.

**Comment by alycda** [comment]
We are using 2.0 specs, which your json [file](http://petstore.swagger.io/v2/swagger.json) is defined as, correct? I have created a json file to describe my API, and it works with a standalone version of swagger-ui (2.1.0-M1), but I haven't gotten it to work within an AMD environment, possibly due to authorization issues:

    define([
      'bower_components/swagger-ui/lib/swagger-client'  // returns SwaggerClient
    ], function(
      Client                        // useless namespace
    ){
        'use strict';

        var API = {

            swagger: {},
            url: 'http://petstore.swagger.io/v2/swagger.json', // swagger.ready never fires
            // url: 'http://swagger.dev/swagger.json', // local env, since a relative path will not work

            initialize: function() {
                authorizations.add("apiKey", new ApiKeyAuthorization("key", "ApI_KeY", "query"));
                // initialize swagger, point to a resource listing
                this.swagger = new SwaggerClient({
                    debug: true, // remains 'false' when SwaggerClient is console.logged
                    url: this.url,
                    // authorizations: {}, // unsure how to set here
                    useJQuery: true, // Issue #96 
                    progress: function(data) {
                      console.log(data); // fetching resource list:...
                    },
                    success: function(data) {
                      console.log(this); // SwaggerClient: {}
                    },
                    failure: function(data) {
                      console.log('fail');
                    }
                });
            }
        }

        API.initialize();
        return API;
    });

**Comment by alycda** [comment]
I just noticed, it may have something to do with the `useJQuery: true` flag, as if I add that to my standalone swagger-ui project, I get the deprecation warning above.

**Comment by fehguy** [comment]
ok there was a bug in loading the client with useJQuery: true.  I can't speak to your script but you can update the client to 2.1.4-M1 and report back.

**Comment by alycda** [comment]
This issue appears fixed, however, swagger.ready is still not set and the apis object is empty (trying to run swagger from the browser). I'll open a separate issue for that.
