### ISSUE TITLE
Feature Request: Ability to abort tagged operations

### ISSUE THREAD

**Issue by SeanLMcCullough** [swagger-api/swagger-js#2349]
Unsure if this is a closer fit for a bug or feature, as the direct `SwaggerClient.http.http()` method [is documented to support](https://github.com/swagger-api/swagger-js/blob/22da4ad9bbe9ea742ad8a20b15f7c10160bb3043/docs/usage/http-client.md#browser) [AbortController ](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) signals.

 ### Content & configuration

 Swagger/OpenAPI definition:
https://petstore3.swagger.io/api/v3/openapi.json

 Swagger-Client usage:
 ```html
<html>
  <head>
    <script src="https://unpkg.com/swagger-client"></script>
    <script>
        const controller = new AbortController();
        const { signal } = controller;
        const timeout = setTimeout(() => {
          controller.abort();
        }, 1);

        (async () => {
          try {
            const client = await SwaggerClient({ url: 'https://petstore3.swagger.io/api/v3/openapi.json' })
            await client.apis.pet.getPetById({ petId: 1 }, { signal });
          } catch (error) {
            if (error.name === 'AbortError') {
              console.info('request was aborted');
              return;
            }
          } finally {
            clearTimeout(timeout);
          }
          console.error('request was NOT aborted');
        })();
    </script>
  </head>
  <body>
    check console in browser's dev. tools
  </body>
</html>
 ```

### Is your feature request related to a problem?

I would like the ability to cancel requests made by the `client.apis.{tag}.{operationId}` API. This feature is present with `SwaggerClient.http()` but does not work with tagged operations. This would allow me as a to ensure that race conditions do not occur, by using a native browser feature.

### Describe the solution you'd like

I would like to be able to supply an `AbortController` signal (and ideally any other init parameters to [fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters)) such that I can cancel requests.

### Describe alternatives you've considered

A workaround for this problem could be achieved by using request/response interceptors or more complex flow control around the usage of the client - but I have not explored these in depth.

### Additional context

AbortController[ is documented to be usable](https://github.com/swagger-api/swagger-js/blob/22da4ad9bbe9ea742ad8a20b15f7c10160bb3043/docs/usage/http-client.md#browser) with `SwaggerClient.http()` and works as documented. This same parameter does not work with tagged API operations, possibly because buildRequest [discards aditional init params](https://github.com/swagger-api/swagger-js/blob/b978355cceacae72fdc3c6fc27365f1589a1cef9/src/execute/oas3/build-request.js#L8).

**Comment by char0n** [comment]
Hi @SeanLMcCullough,

I've issued a PR https://github.com/swagger-api/swagger-js/pull/2380 which adds support for abort signals in [HTTP Client for OAS operations](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client-for-oas-operations.md) as well as to [Tags Interface](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/tags-interface.md). The feature will be release in couple of minutes as swagger-client@3.18.0.

For older versions of swagger-client, there is workaround in using `requestInterceptor` to intercept the `Request` before it's made and inject he abort signal into the request.

```js
