### ISSUE TITLE
make SwaggerHttp pluggable

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#239]
It'd be easy to register different transports for executing http requests, as we do for swagger authorizations.  Then proxies, websockets, etc., can be added

**Comment by whitlockjc** [comment]
We moved from shred to superagent as a part of https://github.com/swagger-api/swagger-js/pull/279, which should resolve https://github.com/swagger-api/swagger-js/issues/267.  When we work on this pluggable feature, I'd like to remove jquery as superagent should make it no longer necessary.  Superagent works on the browser and in Node.js, while jquery does not, and it supports all of the features that require using jquery (form data, cors, ...).

**Comment by hekike** [comment]
+1

**Comment by aurelian** [comment]
:+1:

**Comment by andrewdavidmackenzie** [comment]
Any indication of where this lies on your priority stack Tony?
It's a must have for one of the features our customers appreciate when using our Swagger based (1.2) ActiveDocs.
Thanks

**Comment by fehguy** [comment]
Yes, I'd like to get this in the next release, @andrewdavidmackenzie It's needed also to address a regression in IE.

**Comment by fehguy** [comment]
added by https://github.com/swagger-api/swagger-js/pull/428

**Comment by aurelian** [comment]
Unfortunately it means you have to write your own HTTP/s js client instead of re-using (extending) existing ones. Nice progress thou.
