### ISSUE TITLE
`URLSearchParams` not available in React Native

### ISSUE THREAD

**Issue by davidyuk** [swagger-api/swagger-js#2457]
They are not going to implement it due to saving bundle size: https://github.com/facebook/react-native/issues/23922

`URLSearchParams` was introduced in the recent PR: https://github.com/swagger-api/swagger-js/commit/e96702ff4a6d30ccecb2f6f07774110baaa3bb36#diff-649819c985ad609b5b71b21fc77464a381e6e202379c30f480dab171a19b250fR435-R445

Possible resolutions:
- enable polyfill for `URLSearchParams`
- switch to a third-party npm package that implements this (revert `querystring-browser`?)
- document this React Native quirk
- to do nothing 🙃

**Comment by char0n** [comment]
Hi @davidyuk,

We will be progressively migrating to native APIs as we go. I understand thing might introduce problems. I'd like to avoid those problems or have mitigating mechanism for various cases (like React Native).

Isn't there an option for React native similar to webpacks [ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/)?

**Comment by char0n** [comment]
Closing this as I wan't able to establish further conversation on this topic. Reopen if more info surface.

**Comment by davidyuk** [comment]
React Native supports "eject" command that copies build configuration to your project, so you can adjust it, but then you have to maintain it by yourself. There is no way to alter RN configuration without ejecting. Compatibility with RN without ejecting would improve developer experience.
