### ISSUE TITLE
broken example in README: apis object is empty, throws error

### ISSUE THREAD

**Issue by alycda** [swagger-api/swagger-js#247]
I believe this is related to #238, using the following markup in an index.html

    <!DOCTYPE html>
    <html>
    <head>
    <script src='lib/shred.bundle.js' type='text/javascript'></script>
    <script src='lib/swagger-client.js' type='text/javascript'></script>
    <script type="text/javascript">
      // initialize swagger, point to a resource listing
      window.swagger = new SwaggerClient({
        url: "http://petstore.swagger.io/v2/swagger.json",
        success: function() {
          if(swagger.ready === true) {
            // upon connect, fetch a pet and set contents to element "mydata"
            swagger.apis.pet.getPetById({petId:1}, function(data) {
              document.getElementById("mydata").innerHTML = data.content.data;
            });
          }
        }
      });

    </script>
    </head>
    <body>
      <div id="mydata"> </div>
    </body>
    </html>

Getting the following error:

    (index):13 Uncaught TypeError: Cannot read property 'getPetById' of undefined
    (index):13 window.swagger.SwaggerClient.success
    swagger-client.js:547 SwaggerClient.buildFromSpec
    swagger-client.js:393 SwaggerClient.build.obj.on.response
    swagger-client.js:2990 ShredHttpClient.execute.res.response
    shred.bundle.js:1391 EventEmitter.emit
    shred.bundle.js:1191 request._raw.http.request.emit
    shred.bundle.js:1211 (anonymous function)
    shred.bundle.js:1815 raw.on.setBodyAndFinish
    shred.bundle.js:1832 (anonymous function)
    shred.bundle.js:1388 EventEmitter.emit
    shred.bundle.js:2715 Response.handle
    shred.bundle.js:2584 module.exports.xhr.onreadystatechange

error when `useJQuery:true` is set:

    Uncaught TypeError: Cannot read property 'getPetById' of undefined
    (index):17 window.swagger.SwaggerClient.success
    swagger-client.js:547 SwaggerClient.buildFromSpec
    swagger-client.js:393 SwaggerClient.build.obj.on.response
    swagger-client.js:2871 JQueryHttpClient.execute.obj.complete
    jquery-1.8.0.min.js:2 p.Callbacks.k
    jquery-1.8.0.min.js:2 p.Callbacks.l.fireWith
    jquery-1.8.0.min.js:2 y
    jquery-1.8.0.min.js:2 p.support.ajax.p.ajaxTransport.send.d

**Comment by fehguy** [comment]
Hi, this is because I just deployed a new version of the petstore, which uses the `tags` object and names the resource `pets` (plural).  I will revert that name change, since it will cause some headaches.

**Comment by fehguy** [comment]
Ok this has been redepoyed and the js client fixed.  And tests to make sure it doesn't break again!  Grab 2.1.6-M1.
