### ISSUE TITLE
$ref not working on paths

### ISSUE THREAD

**Issue by wodka** [swagger-api/swagger-js#255]
I'm trying to split my API documentation into several files - but somehow nothing is showing up :(

Even if I try https://github.com/swagger-api/swagger-spec/blob/master/fixtures/v2.0/json/resources/resourceWithLinkedDefinitions.json it just does now show anything. (no error in development console of chrome)

(using v2.1.7-M1 https://github.com/swagger-api/swagger-ui/issues/953)

**Comment by wodka** [comment]
Just now realized that the obj scope in used the parameter opt -> which in return is always the last one.

-> I'll try to fix this in the same pull request because the $ref loading would otherwise only work with one entry.

**Comment by fehguy** [comment]
Thanks, see the test structure and let's get some in for this

**Comment by wodka** [comment]
should be done now

**Comment by whitlockjc** [comment]
To fix this, we will need to get the `Resolver` to work with this is two fold:

* Update `Resolver` to process paths _(Better yet would be to get `Resolver` to process all `$ref` regardless of where they are in the document)_
* Update `Resolver` to handle `$ref` encoded values.  For example, if I wanted my `/testing` path to basically be a clone _(a reference)_ to `/pets`, I'd need a reference like this: `#/paths/~1pets`.  _(The way I solve this in json-refs is handled here: https://github.com/whitlockjc/json-refs/blob/master/index.js#L196)_

**Comment by fehguy** [comment]
added support to process path references when escaped
