### ISSUE TITLE
Global Parameters not supported

### ISSUE THREAD

**Issue by hamx0r** [swagger-api/swagger-js#258]
Per  [swagger-ui bug 929](https://github.com/swagger-api/swagger-ui/issues/929), `parameters` set at the `paths` level are not being displayed at the `operation` level.  The expected behavior on swagger-ui is to see fields to input values for a given `operation` even though those fields were defined as `parameters` in the `paths` section of the swagger spec JSON.

**Comment by fehguy** [comment]
see https://github.com/swagger-api/swagger-js/issues/255

**Comment by fehguy** [comment]
closing as this is covered in #255
