### ISSUE TITLE
drop 1.0, 1.1, 1.2 code, build a 2.0 transformer

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#259]
The swagger-compat library keeps the code separate, but we should really remove it all, and add a simple converter from the 1.x specs to 2.0.  Then the same 2.0 codepath can be used.

**Comment by mohsen1** [comment]
We build a convertor from 1.2 to 2.0 here
https://github.com/apigee-127/swagger-converter

**Comment by whitlockjc** [comment]
In all honesty, 1.2 and 2.0 aren't all that different.  In swagger-tools, we have one code base that works with both types without a lot of effort.  It's not perfect but it felt a lot better than separating implementations only to have a bunch of copy/paste/duplication.  What if we were to have a version-specific object model but a single source base that handled both intelligently?  Just a thought.

**Comment by fehguy** [comment]
There are similarities when done right, once you fetch the apiDeclaration files. My thought was that the transformer would be rein single for fetching the additional files (with authentication as needed) by using the same underlying swaggerHttp object. We then have different transformers for each spec version. Make sense?

**Comment by whitlockjc** [comment]
I don't know the API well enough yet to answer but when I do, I'll let you know.

**Comment by fehguy** [comment]
My view on the API to invoke the transformer is something along these lines:

```js
var spec = ....;
var version = parseFloat(spec.version);
if(version === 1.2) {
  new Swagger12Transformer().resolve(spec, // spec passed in by swagger-ui
    self.buildFromSpec, // callback to build the client from a 2.0 spec
    self);              // scope for the callback
}
else if(version === 1.1) {
  // ...
}
```

**Comment by fehguy** [comment]
this would allow us to remove the entire `swagger-compat.js` class.

**Comment by fehguy** [comment]
see here: https://github.com/swagger-api/swagger-js/pull/309

Remaining tasks:

- [ ] migrate api descriptions to tags
- [ ] add security definitions
