### ISSUE TITLE
switch from shred to super agent?

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#267]
Seems like the shred version we're on is broken for some important use cases, and their API has changed considerably.  Can we move to super agent instead?  @whitlockjc might be able to assess.

I would simply add it to the `swaggerHttp.js` class and should be 100% transparent

**Comment by mohsen1** [comment]
This bug(https://github.com/swagger-api/swagger-ui/issues/956) is a result of bugs in shred library. 

the [`parseUri`](https://github.com/swagger-api/swagger-js/blob/7414ad062ba9b6d9cc397c72e7561ec775b35a9f/lib/shred/parseUri.js#L6) function has a bug that can't parse a URI with `@` in it.

**Comment by aurelian** [comment]
:+1: also jquery http-client (even dependency) can be ditched in the process.

**Comment by aurelian** [comment]
There was also this use case with file uploads not exactly working with shred explained more recently in #231

**Comment by whitlockjc** [comment]
I'm going to do this after I get the current browserify/cleanup done, which should be today.

**Comment by fehguy** [comment]
@aurelian does super agent encode support uploading files via FormData?

**Comment by aurelian** [comment]
@fehguy -- [it should](https://github.com/visionmedia/superagent/blob/master/lib/client.js#L721), but haven't used it myself.

**Comment by whitlockjc** [comment]
This should be done as of https://github.com/swagger-api/swagger-js/pull/279.  It's not fully tested but swagger-js and swagger-ui tests pass with this implementation.  I am sure swagger-ui will help us find anomalies as will our adding of new tests.

**Comment by whitlockjc** [comment]
#279 has been merged so superagent is now being used instead of shred.
