### ISSUE TITLE
Issue with nested $ref in arrays

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-js#270]
According to this [comment](https://github.com/swagger-api/swagger-ui/issues/915#issuecomment-77062246), SwaggerJS is not generating correct HTML for arrays with nested $refs.

**Comment by Smolations** [comment]
:+1: for this. This issue is one of the few blockers keeping me from implementing swagger in my team's current project. Can't wait for it to be fixed!  :smile:

**Comment by whitlockjc** [comment]
This should be fixed.

**Comment by wangning0** [comment]
I also have encountered this problem on swaghub today, maybe we should reopen this issue?

**Comment by shockey** [comment]
@xialu4820723 @wangning0 please reach out to SwaggerHub support with your issue 😄
