### ISSUE TITLE
Add response headers to response model 

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-js#277]
Swagger UI needs response headers in response object model under `headers` property. 

Related: https://github.com/swagger-api/swagger-ui/pull/1000

**Comment by fehguy** [comment]
you can get sample response headers from the petstore api now:

http://petstore.swagger.io/v2/swagger.json

**Comment by whitlockjc** [comment]
I think he means the response object from `SwaggerHttp`.

**Comment by whitlockjc** [comment]
@mohsen1 Can you tell me which fields you use in the response object?  I see some duplication in what is there now and would like to know what you're using.

**Comment by fehguy** [comment]
I thought i replied to this.  There is a response header definition in the spec, which should be part of the "model" returned by each operation.  That's different from what response headers actually come back from the server.

**Comment by whitlockjc** [comment]
I was wrong.  I misunderstood.

**Comment by whitlockjc** [comment]
After being in the `SwaggerHttp` code recently and seeing now official response model structure, I thought that was the response he was referring to.  But after looking at the code he pointed me to, I had just figured this out when you commented.

**Comment by whitlockjc** [comment]
I just tested this locally and if you have a response with the `headers` property, which is optional, it is provided already.  Are you sure you didn't just process a response object that didn't have a `headers` property?  I'm in the process of writing more tests to ensure it's working but for the simple test without references to a globally-defined response, it works.  Any example that can reproduce this would be useful.

**Comment by whitlockjc** [comment]
This should be fixed.

**Comment by whitlockjc** [comment]
The fix for this does not support references.  References are broken in most of swagger-js and will be addressed together.
