### ISSUE TITLE
Authorizations are always applied

### ISSUE THREAD

**Issue by xhh** [swagger-api/swagger-js#283]
For example I have two authorizations defined in my app:

```javascript
client.authorizations.add("HTTP Basic Auth", new client.PasswordAuthorization("HTTP Basic Auth", "my-name", "my-pass"));
client.authorizations.add("API Key (Header)", new client.ApiKeyAuthorization("X-API-KEY", "my-api-key", "header"));
```

Then calling all endpoints will send these two headers:

```
Authorization: Basic bXktbmFtZTpteS1wYXNz
X-API-KEY: my-api-key
```

Even for endpoints that do not need to be authorized. So it seems all authorizations are applied to all endpoints. (I'm using version 2.1.10-M1 of swagger-client installed via npm with swagger 2.0 spec)

**Comment by fehguy** [comment]
You need to define what is required in each of the operations.  If there are no security requirements defined on an operation, all headers will be sent.  Other wise, it will send only the ones defined, or "none" if that key exists but is empty.  Take a look here:

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#security-requirement-object

**Comment by xhh** [comment]
I made the definition as described in the spec: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#operation-object

For "endpoints that do not need to be authorized", I meant operations whose `security` is empty array. For these operations, no authorization headers should be applied, right? But in my case, both of the 2 authorizations headers are sent.

**Comment by fehguy** [comment]
Hi, this path is fairly well tested.  Please anonymize and share a spec and we can sort it out.

**Comment by xhh** [comment]
Hi @fehguy, please have a look at this line:
https://github.com/swagger-api/swagger-js/blob/master/src/js/auth.js#L23

For empty array, `Object.keys([])` returns `[]` (empty array) whose length is 0.
I guess it's the problem, i.e. for an operation whose "security" is an empty array ("To remove a top-level security declaration, an empty array can be used"), all authorizations defined for the client will be applied to the operation.
When I tried changing that line to the following
```javascript
  if (typeof authorizations === 'undefined' || (!Array.isArray(authorizations) && Object.keys(authorizations).length === 0)) {
```
then it works (no auth parameters are sent for operations that do not require auth).

**Comment by fehguy** [comment]
@xhh that makes sense to me.  @whitlockjc can this get into the queue?

**Comment by whitlockjc** [comment]
Based on the spec, if you want to turn off authorization for an operation when there are authorizations at a higher level (global for example), you set `authorizations` to be an empty array.  So we need to do that.  The current code could be "tricked" to do the wrong thing but it would require an invalid Swagger document.  We can make it better.  Thanks @xhh for tracking this down.  I can fix this in the M2 milestone to get it done quicker but that is a decision for @fehguy.

**Comment by whitlockjc** [comment]
Can we verify if this is still happening in the latest swagger-js release?

/cc @xhh

**Comment by xhh** [comment]
@whitlockjc I don't think so as I can see the same line causing the issue [is still there](https://github.com/swagger-api/swagger-js/blob/master/lib/auth.js#L28). Please refer to [my comment above](#issuecomment-82237463).

To describe the issue again:
the `security` key is set to empty array for an operation, but all securities are applied for that operation.

**Comment by whitlockjc** [comment]
I read your comment, I was just asking if you could still reproduce...not if you think it should still reproduce.  I'll talk to @fehguy about how security should work and go from there.  I *think* this is for global authorizations but I'm not sure.

**Comment by whitlockjc** [comment]
I've got a fix incoming.

**Comment by whitlockjc** [comment]
I think the way this _should_ work is if authorizations is `undefined`, add all authorizations.  Otherwise, use the provided authorizations.  If you supply an empty array/object, of course you'll end up with no authorizations being applied like you want.  Does that seem reasonable?

**Comment by whitlockjc** [comment]
This is fixed.

**Comment by xhh** [comment]
It works now. Thanks!
