### ISSUE TITLE
swagger-js model renderer does not parse/display model description

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-js#294]
https://github.com/swagger-api/swagger-ui/issues/406

**Comment by fehguy** [comment]
I believe this used to work, must be a regression.

**Comment by whitlockjc** [comment]
I just went back through the code, the last master merge from develop_2.0 before I got involved.  The model description was never displayed prior so this is a new feature, not a regression.

**Comment by fehguy** [comment]
I propose we move this to a future swagger-ui release, where the rendering will live in the UI code, not JS.

https://github.com/swagger-api/swagger-ui/issues/1248

**Comment by HolgerVogelsang** [comment]
I'ts not rocket science:
1. Open swagger-ui.js
2. Search for function processModel(schema, name)
3. Change the first lines of this function to something like this (or whatever you want to display):

```
  function processModel(schema, name) {
    var type = schema.type || 'object';
    var isArray = schema.type === 'array';
    
    var html = schema.description !== undefined ? '<div style=\'margin-left: 0px; font-size: 14px;\'>' + strongOpen + '// ' + schema.description + strongClose + '</div>' : '';
    html += (strongOpen + name + ' ' + (isArray ? '[' : '{') + strongClose);
```
