### ISSUE TITLE
attributes of type "object" (Map) do not show additionalProperties

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-js#298]
From https://github.com/swagger-api/swagger-ui/issues/913

**Comment by todd-richmond** [comment]
this seemed to close the original bug with all the details instead of the dup

**Comment by whitlockjc** [comment]
There is a reference to the original so I know what to look for, don't worry.  :)

**Comment by whitlockjc** [comment]
While I know how this should work, and some ideas on how it could, how would you (those involved) want this to be displayed?

**Comment by webron** [comment]
In the UI? I can think of a way, not sure how easy it would be to implement it.

**Comment by whitlockjc** [comment]
Yeah.  I'm wondering how the UI will look.  I've implemented some stuff recently that should make the implementation possible but the generated HTML for the UI hasn't been suggested anywhere.

**Comment by webron** [comment]
Was this a rage-issue-closing?

**Comment by whitlockjc** [comment]
It was a mistake, thanks for catching it.

**Comment by webron** [comment]
This is my job. To point out people's mistakes.

And I know I'm going to regret asking, but does the HTML representation of the UI come here in the js project?

**Comment by whitlockjc** [comment]
Believe it or not but swagger-ui uses swagger-js to generate HTML for certain parts of swagger-ui.  I'm not joking.

**Comment by webron** [comment]
Yeah, that's what I was thinking. Let me jot down what I was thinking, though it may require some fine tuning.

**Comment by todd-richmond** [comment]
On the "Model" tab, I'd like to see fields like this:
map_field (map<string, Clazz>, optional): description
and include the Clazz object section as well

The "Model Schema" tab could show JavaScript like
"map_field": { "string": clazz }

**Comment by whitlockjc** [comment]
That is already working then.  The thing is that `additionalProperties` is for the schema that is used to validate all properties not mentioned in the `properties` part of the object definition.  So this would end up with something like an addendum/asterisk/... at the bottom of the Model properties display with the pertinent information.

**Comment by webron** [comment]
Wait, are we talking about how the input is going to work or how the model definition is going to look like?

**Comment by whitlockjc** [comment]
We are talking about the display of Model objects that have the `additionalProperties` attribute set.

**Comment by todd-richmond** [comment]
what is working? I'm using the latest core 1.5.3 and UI 2.1.8.M1 and just see this for a model that has a map field. No reference to what the object is either

map_field (object, optional): description

    {
    type: "object",
    description: "system prerequisites",
    additionalProperties: {
        $ref: "#/definitions/Prereq"
        }
    },

**Comment by webron** [comment]
Oh, I was thinking about the input. 
For the Model display, it should be `Map[string, <type>]`, for model schema just `{ "key": <type> }`.

**Comment by whitlockjc** [comment]
The display of Model objects is working.  `additionalProperties` support is not done which is why this issue is still open.  Why you're using `additionalProperties` by itself doesn't make much sense to me as its only intention is to specify the schema for all properties not defined in the `properties` attribute.  Just to humor me, mind telling me what `Prereq` looks like?

**Comment by whitlockjc** [comment]
@webron I'm not sure I like using `Map` as a container as it's not a container type, or even a keyword/type, in many languages.  Basically, we need a way to render this: `All other properties provided will be of type {type} and have the following constraints`.  So you could display it like a regular model property but instead of the property name, you'd need an asterisk or something else to denote `All other properties that are not the ones above`.

**Comment by whitlockjc** [comment]
Here is an example:

**Typical Property Display in a Model**

`{propertyName} ({propertyType}, {optionality}){: description}`

**Suggested Display for Additional Properties in a Model**

`* ({additionalPropertyType}, optional){: description}`

Here is an example schema and it's proposed display:

```js
{
  type: 'object',
  properties: {
    age: {
      type: 'integer'
    },
    name: {
      type: 'string'
    }
  },
  additionalProperties: {
    type: 'string'
  }
}
```

```
MyModel {
  age (integer, optional),
  name (string, optional),
  * (string, optional)
}
```

**Comment by whitlockjc** [comment]
With recent commits to support inline models, you could even support that.  Here is a brief example:

```js
  // ...
  additionalProperties: {
    type: 'object',
    properties: {
      email: {
        type: 'string'
      }
    }
  }
  // ...
```

```
MyModel {
  age (integer, optional),
  name (string, optional),
  * (Inline Model 1, optional)
}

Inline Model 1 {
  email: (string, optional)
}
```

**Comment by todd-richmond** [comment]
Here is a simplified version. However, it also shows "object" for dataType = "Map[string,string]"

    public class Host {
        public static class Prereq implements Serializable {
            @ApiModelProperty("current value")
            private String value;
            @ApiModelProperty("correction help message")
            private String message;
            @ApiModelProperty("minimum required value")
            private String required;
        }
        @ApiModelProperty(value = "system prerequisites", dataType =
            "Map[string,com.foo.model.Host$Prereq]")
        private Map<String, Prereq> prereqs;
    }

**Comment by whitlockjc** [comment]
Well, we support displaying Maps of all types now in swagger-js _(swagger-ui uses this to render parts of the UI)_ so all we need now is to support `additionalProperties` as mentioned above.

**Comment by fehguy** [comment]
Yes, you should not have that `dataType` in your annotations.  Please open an issue in swagger-core so we can define the map correctly.

**Comment by todd-richmond** [comment]
What should the ApiModelProperty syntax look like? I'm actually using a direct subclass of Map<String, Prereq> purely to allow storing the hibernate column data as JSON instead of serialized java (no extra methods other than an AttributeConverter)

If I don't supply the dataType, the field doesn't show up in the UI at all

**Comment by fehguy** [comment]
@todd-richmond it should appear--have you tried with the 1.5.3-M1 release?  This test:

https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-core/src/test/scala/ModelConverterTest.scala#L17

Based on this model:

```java
public class Person {
  private Long id;
  private String firstName;
  private Address address;
  private Map<String, String> properties;
  private Date birthDate;
  private Float floatValue;
  private Double doubleValue;

// ...
}
```

shows the expected output.

**Comment by todd-richmond** [comment]
I'm using 1.5.3.M1 and private Map<String, String> foo; still displays as "object" in the UI (2.1.8-M1 npm package). I don't see a newer UI release

**Comment by fehguy** [comment]
for debugging purposes can you either:

a) add a test case with an anonymized model in swagger-core/develop_2.0
b) change your map value model to be a public class rather than a static inner class?

**Comment by ikitommi** [comment]
hi. this spec doesn't render any additional properties with `v2.1.1-M2`:
https://gist.githubusercontent.com/ikitommi/006240a06500634caeaa/raw/44730d096578ce086a734c84887767a41f1b9ff4/swagger.json

**Comment by ponelat** [comment]
@ikitommir, support for rendered additionalProperties in the UI is still pending. As per @whitlockjc comment above. I'm sure this issue will be resolved when it we have it in swagger-ui(via swagger-js)

**Comment by ikitommi** [comment]
Ok, and thanks for the info.

**Comment by fehguy** [comment]
this is actually addressed in swagger-js and will appear in swagger-ui after the next release.

**Comment by maver1ck** [comment]
Is there any ETA of next release ?
Or maybe a branch of code I can use ?

What about editor.swagger.io ?

**Comment by ponelat** [comment]
@fehguy is this done? Can we see representation of additionalProperties in swagger-js#sampleJSON ? I don't see linked commit.

**Comment by webron** [comment]
This is https://github.com/swagger-api/swagger-ui/issues/558.
