### ISSUE TITLE
Handle expected error responses from swaggerized api

### ISSUE THREAD

**Issue by netzwerch** [swagger-api/swagger-js#299]
I seem to have a problem with the swagger-js behaviour.

When I use the generated swagger client object and pass for example an id that exists, there will be a 200 response and the **callback** will be called with **data**. Everything ok in the following example.
```php
swagger.apis.pet.getPetById({petId:1}, function(response) {
        // response.status === 200
        document.getElementById("mydata").innerHTML = JSON.stringify(response.obj);
      });
```
When I fill in an Id that does not exist a 404 will be retourned. Unfortunately the callback will not be called, instead I only see the response printed on the console.
```php
swagger.apis.pet.getPetById({petId:"<<somenotexistingid>>"}, function(response) {
        // This code will not be called
        document.getElementById("mydata").innerHTML = JSON.stringify(response.obj);
      });
```

So my question is here, how do I handle an expected error (404) when I call my API via swagger?

**Comment by fehguy** [comment]
pass an error handler:

```
swagger.apis.getPetById({petId:1}, function(success){...}, function(error){...});
```

**Comment by netzwerch** [comment]
Works, thanks!
