### ISSUE TITLE
Error resolving open api spec after upgrading to v3.19.5

### ISSUE THREAD

**Issue by hdoan741** [swagger-api/swagger-js#2991]
### Q&A (please complete the following information)
 - OS: macOS
 - Environment: Chrome 112
 - Method of installation: npm
 - Swagger-Client version: 3.19.5
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-Client usage:
```js
SwaggerClient({
  // your config options here
})
```

### Describe the bug you're encountering

After upgrading to v3.19.5, we're seeing error with using `Swagger.resolve`
```
TypeError: Cannot add property __originalOperationId, object is not extensible
    at normalize (normalize.js:55:37)
```

In the logs, there are a lot of errors like this logged as well.
<img width="1138" alt="Screen Shot 2023-06-06 at 9 42 01 AM" src="https://github.com/swagger-api/swagger-js/assets/687617/c5f5ff2b-f12d-4fb0-adfe-94a4bb53fd23">
(spec)`. 

### To reproduce...

1. Call `Swagger.resolve` on the spec file.
2. I'm unable to share the spec file at this moment.

### Expected behavior

The spec file can be resolved without error.

### Screenshots

Seeing errors mentioned above

**Comment by char0n** [comment]
Hi @hdoan741,

Thanks for the report, would you be able to provide minimal OpenAPI 3.0.x definition on which the bug can be reproduced?

**Comment by char0n** [comment]
@hdoan741 any update on this? Could you provide the definition?

**Comment by char0n** [comment]
Closing this for now as no actionable information was prodided.
