### ISSUE TITLE
[develop_2.0] Console Error Typos

### ISSUE THREAD

**Issue by Smolations** [swagger-api/swagger-js#301]
This one will be easy to close.  :smile: 

![screen shot 2015-03-19 at 11 20 49 am](https://cloud.githubusercontent.com/assets/952681/6736396/1f70a460-ce2a-11e4-8361-9d8154befe95.png)

1. I believe the word you're looking for here is "deprecated"
2. 'S' or 's'?  `waggerUi.api.clientAuthorizations.add()`
3. Keep error messages consistent. If you are going with capitalization and full sentences, always do so: 
        
        Using window.ApiKeyAuthorization is deprecated. Please use SwaggerClient.ApiKeyAuthorization.
        Using window.authorizations is deprecated. Please use (S|s)waggerUi.api.clientAuthorizations.add().

_**note:** you can probably ignore the fact that these errors showed up twice in the screenshot. i have not thoroughly checked the initialization code I am using so I don't know if it's happening twice due to a bug in your code or my own._

**Comment by mohsen1** [comment]
Damn English! This is an issue in Swagger UI. Let's move it there

**Comment by whitlockjc** [comment]
Yes, swagger-js is not creating these errors.

**Comment by Smolations** [comment]
Oops! I meant to post it in that project, but I clicked a link in that project to go to issue 270, and I didn't realize that issue was in _this_ project. Sorry guys!
