### ISSUE TITLE
re-enable model signature check

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#306]
from feature/spec-converter

**Comment by whitlockjc** [comment]
Can you explain this a little more?  I did a lot of work recently on the model signature stuff and I want to add tests for things based on known issues.

**Comment by fehguy** [comment]
@whitlockjc yes--if you look here:

https://github.com/swagger-api/swagger-js/pull/309

`test/compat/modelSignatures.js` has a disabled test which should be re-enabled

**Comment by fehguy** [comment]
@whitlockjc it looks like the json sample for this:

```json
{
  "Animals": {
      "id": "Animals",
      "properties": {
        "cat": {
          "type": "Pet"
        },
        "dog": {
          "type": "Pet"
        },
        "mouse": {
          "type": "Pet"
        }
      }
    }
}
```

is writing like this:

```json
{
  "cat": {},
  "dog": {},
  "mouse": {}
}
```

I'm expecting it to have the `Pet` model for each of the attributes.

**Comment by whitlockjc** [comment]
The 2.0 tests work fine so this seems to be related to the converter.  I'll look into it.

**Comment by fehguy** [comment]
if it's a converter issue, please reassign to me.

**Comment by whitlockjc** [comment]
Nah, I can handle it.  ;)  We do have sample/signature tests for 2.0 that are current passing and handle references.  Since that is a 1.2 model reference, the short `Pet` vs. `#/definitions/Pet`, I'd assume it's a converter issue but to avoid being an idiot, let me look into it first.

**Comment by whitlockjc** [comment]
Scratch that, you can't take the idiot out of me.  But I do want to look into it.

**Comment by whitlockjc** [comment]
This has been fixed.
