### ISSUE TITLE
Error resolving open api spec with circular dependency

### ISSUE THREAD

**Issue by mikewang333** [swagger-api/swagger-js#3063]
### Q&A (please complete the following information)
 - OS: macOS
 - Environment: Chrome 114
 - Method of installation: npm
 - Swagger-Client version: 3.19.8
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```
https://raw.githubusercontent.com/mikewang333/throwaway/main/circularDependencyError.json

Swagger-Client usage:
```js
SwaggerClient({
  // your config options here
})
```

### Describe the bug you're encountering

We were running into 100% error rate resolving this spec on version 3.19.5 and noticed there were circular reference fixes so we upgraded to 3.19.8. Now we'll sometimes see errors and sometimes it resolves fine. 

### To reproduce...

1. ...Call Swagger.resolve on the spec file.

### Expected behavior

The spec file can be resolved without error.

### Screenshots

<img width="1195" alt="image" src="https://github.com/swagger-api/swagger-js/assets/16713706/12e56184-15f0-4417-8951-3763ac6ded15">

### Additional context or thoughts

- The circular dependency is with SegmentCombinator

**Comment by char0n** [comment]
Hi @mikewang333,

On [v3.20.0](https://github.com/swagger-api/swagger-js/releases/tag/v3.20.0) I couldn't reproduce the issue running `resolve` 100 times in a sequence:


```js
const range100 = Array.from({ length: 100 }, (value, index) => index);

range100.forEach(async () => {
  await SwaggerClient.resolve({
    url: 'https://raw.githubusercontent.com/mikewang333/throwaway/main/circularDependencyError.json',
  }).then(({ errors }) => console.dir(errors));
});
```

The result was:

```
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
```

**Comment by char0n** [comment]
The issue that I'm seeing is, that the resolution failed to eliminate all the cycles, thus the resolved (dereferenced) definition cannot be serialized  back to JSON/YAML.

**Comment by char0n** [comment]
@mikewang333 would you be able to produce minimal definition that we can start fixing this on?

This can be achieved by pasting you definition to https://editor-next.swagger.io/ and see if `File -> Download Resolved JSON` works or returns error.

**Comment by mikewang333** [comment]
It looks like I misinterpreted the error we were getting. Closing this for now--sorry about that!
