### ISSUE TITLE
Provide an API for getting model schema

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-js#311]

**Comment by fehguy** [comment]
seems like there's really only one way forward, which is to expose the JSON schema from the client and let the front-end render it in whatever format it needs

**Comment by mohsen1** [comment]
That would work better since I can use third party libraries for converting JSON Schema to XSD and render it.

**Comment by fehguy** [comment]
required for https://github.com/swagger-api/swagger-ui/issues/1248

**Comment by fehguy** [comment]
Schema is now available.
