### ISSUE TITLE
Check Node.js 18 and 20 on CI

### ISSUE THREAD

**Issue by pvcresin** [swagger-api/swagger-js#3114]
Support for Node.js 16 will end on 2023-09-11.
- https://github.com/nodejs/release#release-schedule

So I thought it would be better to support 18 and 20 as well.

Currently Node.js 14 and 16 are being tested by CI,

https://github.com/swagger-api/swagger-js/blob/master/.github/workflows/nodejs.yml#L18C9-L18C35

```yaml
node-version: [14.x, 16.x].
````

So I think it would be better to change it as follows.

```yaml
node-version: [14.x, 16.x, 18.x, 20.x]
```

With `fetch` being supported by default since Node 18, is it perhaps difficult to support?

**Comment by char0n** [comment]
Good idea.

> With fetch being supported by default since Node 18, is it perhaps difficult to support?

No it's not. It's used automatically if present as `globalThis.fetch` symbol.

**Comment by char0n** [comment]
Closed by https://github.com/swagger-api/swagger-js/commit/108e732c91a0abe3244fb45f3d3037c549c30abb

**Comment by pvcresin** [comment]
@char0n Thank you so much for your quick reply and changes!
