### ISSUE TITLE
@swagger-api/apidom-core@0.76.0 requires node 15 or greater, breaks Node-14 CI

### ISSUE THREAD

**Issue by shazron** [swagger-api/swagger-js#3127]
However this lib's version range will include it:
https://github.com/swagger-api/swagger-js/blob/1c5396acfcae216957d9fd42f7efe6e441f1ffd2/package.json#L117

It [fails Node-14 CI](https://github.com/swagger-api/swagger-js/pull/3118) because `@swagger-api/apidom-core@0.76.0` uses `AggregateError` which only occurs in Node-15.

A "fix" would be to either:

1. polyfill this module it with https://www.npmjs.com/package/es-aggregate-error
2. limit `@swagger-api/apidom-core` version range to 0.75.0 or lesser in this module's package.json
3. fix the issue in `@swagger-api/apidom-core@0.76.0` so it is compatible with Node-14 (use the shim specified above, if not available in the current node runtime)

**Comment by char0n** [comment]
Hi @shazron,

Thanks for the report. You're absolutely right, Node.js >12.20.0 is our supported runtime for swagger-client. 

Created tracking issue with ApiDOM and working on the fix: https://github.com/swagger-api/apidom/issues/3128

**Comment by char0n** [comment]
Backward compatibility in ApiDOM addressed in https://github.com/swagger-api/apidom/pull/3129/files

**Comment by char0n** [comment]
Addressed in this repo by https://github.com/swagger-api/swagger-js/pull/3129

**Comment by char0n** [comment]
Released as https://github.com/swagger-api/swagger-js/releases
