### ISSUE TITLE
Is there something missing in supporting OAS3 servers?

### ISSUE THREAD

**Issue by fulviodenza** [swagger-api/swagger-js#3143]
From this line we deduce that is still something missing in the OAS3 servers support:
https://github.com/swagger-api/swagger-js/blob/9463136b21782374e7c8042b52db2fcc71d65977/src/index.js#L134

Although it looks it already has been added support to it:
https://github.com/swagger-api/swagger-js/tree/96d261987700297a472db5587c0a8c769095d73e/src/execute

I found it a bit confusing, is it to delete?

**Comment by char0n** [comment]
Hi @fulviodenza,

Good question. Investigating. Maybe slightly related: https://github.com/swagger-api/swagger-js/issues/2967

**Comment by fulviodenza** [comment]
> Hi @fulviodenza,
> 
> Good question. Investigating....
> 
> Maybe slightly related: #2967

We are already using the feature with no issues, opening a PR to remove the stale comment.

**Comment by char0n** [comment]
@fulviodenza yes I can confirm as well. Probably the intention was to make server URLs absolute using the spec url when they are represented as relative URI Reference, but that is already handled in `baseUrl` function.

**Comment by char0n** [comment]
On the hand following code is fully OpenAPI 2.0 specific:

```js
  if (specUrl && specUrl.startsWith('http')) {
    const parsed = new URL(specUrl);
    if (!spec.host) {
      spec.host = parsed.host;
    }
    if (!spec.schemes) {
      spec.schemes = [parsed.protocol.replace(':', '')];
    }
    if (!spec.basePath) {
      spec.basePath = '/';
    }
  }
```

I think what the `// TODO: OAS3: support servers here` comment is trying to relay to us that we should do the same for OpenAPI 3.x.y Server Object. Interpolating here probable intention for OpenAPI 3.x.y:

```js
if (specUrl && specUrl.startsWith('http') && spec is OpenAPI 3.x.y) {
  if (!spec.servers) {
    spec.servers = [{ url: specUrl }];
  }
}
```

@fulviodenza what do you think?

**Comment by char0n** [comment]
I've issued https://github.com/swagger-api/swagger-js/pull/3219 to align the code with https://github.com/swagger-api/swagger-js/issues/3143#issuecomment-1790360887

**Comment by char0n** [comment]
Closed by https://github.com/swagger-api/swagger-js/pull/3219. @fulviodenza thanks for pointing this `TODO` comment out. It lead to adding missing piece of functionality!

**Comment by char0n** [comment]
OpenAPI 3.x.y spec actually tells us what to do when, the `OpenAPI.servers` field is missing or is defined as empty array:

![image](https://github.com/swagger-api/swagger-js/assets/193286/3df0349a-8710-48c2-8371-4ececfa1a2b8)

I'll have amend the implementation to reflect this.

**Comment by char0n** [comment]
Closed by https://github.com/swagger-api/swagger-js/pull/3220 which introduces spec compliant default for `OpenAPI.servers` field in OpenAPI 3.x.y definitions.

**Comment by fulviodenza** [comment]
Sorry for not answering before didn't read, I'm happy this led to a fix!
