### ISSUE TITLE
Introduce backward compatible URI Reference resolution

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-js#3147]
In https://github.com/swagger-api/swagger-js/releases/tag/v3.21.0 we've drop legacy [url](https://www.npmjs.com/package/url) depedency and replaced it with new [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) API. New URL API is not capable of resolving Relative URI References against Relative URI Reference. We've made sure that latest SwaggerUI version always sends absolute `baseURL`, but earlier EOL versions of SwaggerUI (v3 and v4) and legacy SwaggerEditor@4 are affected by this change. 

The goal of this issue is to provide backward compatible behavior while resolving Relative URI References.

Refs https://github.com/swagger-api/swagger-ui/issues/9215

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-js/pull/3148 and released in v3.22.2

**Comment by AlvaroRausell** [comment]
Hi @char0n, this PR has broken our repos on Windows, as the `cwd` value has backslashes and [line 82](https://github.com/swagger-api/swagger-js/blob/cd84a30db43c14f4e2f1876465ce0ed2a4d0d9c8/src/specmap/helpers.js#L82) fails with `[ERR_INVALID_URL]: Invalid URL`. 
Could you please correct this behaviour by normalising the paths before resolving?

**Comment by AlvaroRausell** [comment]
Opened #3149
