### ISSUE TITLE
Path param encoding ignores forward slashes

### ISSUE THREAD

**Issue by Jazzatola** [swagger-api/swagger-js#315]
I'm working on an application using [Digital Object Identifiers](http://www.doi.org) in path parameters. These identifiers contain slashes (`/`). Unfortunately the current implementation of `encodePathParam` in `swagger-client.js` ignores the slashes when encoding the path parameters. The comment indicates there is some uncertainty about this implementation. Any plans to change it?

Thanks.

**Comment by fehguy** [comment]
@whitlockjc can you comment on this?

**Comment by whitlockjc** [comment]
Can you tell me if this is still happening with the latest release?

**Comment by fehguy** [comment]
see https://github.com/swagger-api/swagger-js/pull/280

Need feedback from @webron

**Comment by webron** [comment]
Gave the feedback in #280.

**Comment by webron** [comment]
Based on #280, I'll assume this is done. Please reopen if needed.
