### ISSUE TITLE
Cookie Auth not working while sending req through different port then server.

### ISSUE THREAD

**Issue by VijayRathod20** [swagger-api/swagger-js#3167]
I am using deferent port for swagger api then my backend api , while sending cookie from swagger api its getting undefined, and while i use same port for swagger api as backend then its work fine.

**Comment by char0n** [comment]
Hi @VijayRathod20,

I'm sorry but this is insufficient info to act upon. Please reopen this issue after you provide more information, code example, steps to reproduce or other.
