### ISSUE TITLE
operation description is undefined after converting

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-js#317]
SwaggerUI v1 example has undefined description after conversion

**Comment by fehguy** [comment]
can you please share more?  There are many places where descriptions live:

https://github.com/swagger-api/swagger-js/blob/develop_2.0/test/compat/converter.js#L51

**Comment by mohsen1** [comment]
operation description. I think it's `summary` in v1. for exaple `Everything about your Pets` is missing

**Comment by fehguy** [comment]
Added tests to confirm working.  If you see an issue, please reopen with some specifics.
