### ISSUE TITLE
When i update to 2.23.0 ,build failed 

### ISSUE THREAD

**Issue by KingDracula** [swagger-api/swagger-js#3176]
I was used in nestjs ,when i build ,it is failed
but ,before i was used  2.18.0  is working fine.
so how to fix this error ?
thanks
![image](https://github.com/swagger-api/swagger-js/assets/13584613/17292c38-c857-4da8-8314-b1b5a5ae8018)

**Comment by char0n** [comment]
Looks like related to this: https://github.com/ramda/ramda/issues/3415#issuecomment-1757260119

**Comment by char0n** [comment]
Created new discussion on https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/67032. Let's wait a bit for authors to fix it.

**Comment by char0n** [comment]
To sum it up:

> This error is because you are on typescript < 5
@types/ramda, which is backed by types-ramda is labeled that [min support is typescript 5.0](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/index.d.ts#L8)
Specifically, the [const Type Parameter](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters) syntax is being used [here](https://github.com/ramda/types/blob/develop/types/pick.d.ts#L3)

So if you're using TypeScript >5, you're just fine. If you use TypeScript >= 4 < 5, you have to use the [overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides):

```json
"overrides": {
   "swagger-client": {
     "types-ramda": "0.29.4"
   }   
}
```

[Yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) is the mechanism of overrides specific to `yarn`.

More info in: https://github.com/ramda/types/issues/64

**Comment by char0n** [comment]
Related to https://github.com/swagger-api/apidom/issues/3279

**Comment by char0n** [comment]
Issue explicitly addressed in https://github.com/swagger-api/apidom/pull/3281
