### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by hamx0r** [swagger-api/swagger-js#322]
Swagger-ui develop_2.0 branch pulls from swagger-js develop_2.0 branch hangs with a message like:

`fetching resource list: https://...../swagger.json`

Looking at chrome's developer console, we see this JS error:
`swagger-ui.js:1670 Uncaught TypeError: Cannot read property 'replace' of undefined`

**Comment by fehguy** [comment]
Please retest with the latest in develop_2.0 and reopen if you're still having an issue.
