### ISSUE TITLE
confirm response for operation is clear

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#325]
Need to make sure the response code/schema is clear for non-200 responses.

**Comment by whitlockjc** [comment]
Here is the code that takes responses and handles them:

https://github.com/swagger-api/swagger-js/blob/develop_2.0/lib/types/operation.js#L117

It will only create a `Model` object, the thing that lets you call `getMockSignature` and `createSampleJSON` and other APIs that swagger-js uses, for the default success response and the others do not result in a `Model` object instance.  We also will need to create an API for operations to allow you to iterate over all response models and to retrieve a response model by code/name.

**Comment by fehguy** [comment]
@whitlockjc this logic looks good to me.  Do we need to change any code?

**Comment by whitlockjc** [comment]
Code would change since we'd need to create a `Model` for all responses, not just the one we deem to be the default success response, and we'd need APIs added to the `Operation` object to give access to these response `Model` objects.

**Comment by whitlockjc** [comment]
This is not a regression.  The feature/bug that led to this was that swagger-ui wants to render rich representations for the non-default response.  To be able to do this, we would need to make `Model` objects for all responses, not just the default, and provide an API to get access to the responses models, not just the default.

This is a new feature, not a regression.

**Comment by fehguy** [comment]
@whitlockjc my bad for taking a while to get back to this.  I believe we actually used to return rendering operations for all models inside response codes.

**Comment by whitlockjc** [comment]
I looked into this and the release prior to my involvement didn't have this.  I'll have to look back further to see how it was done and we'll get it knocked out.

**Comment by fehguy** [comment]
This has been implemented
