### ISSUE TITLE
pass empty json {} on post

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#326]
from https://github.com/swagger-api/swagger-ui/pull/873 we must pass either nothing or an empty JSON when posting to an operation and specifying content-type `application/json`

**Comment by saadmufti** [comment]
The original issue was actually about surrounding an enum with quotes when used as a POST body parameter and the content-type is application/json

**Comment by fehguy** [comment]
OK digging into this more, here's some feedback.

Currently the content-type is NOT set if there is no body passed in the request.  This is good and bad--namely it will not set `Content-Type` to `application/json` if you don't pass an object.  The bad is that because the content type isn't set, the server has to guess.  And depending on the server implementation, this is potentially a problem.

First we need to pass Content-Type regardless of presence of a body.  Then we can detect that it's application/json and set it to an empty object.

**Comment by fehguy** [comment]
see https://github.com/swagger-api/swagger-js/commit/a6b21420bdf2d3440e3d52eb17736813a8f9bba9
