### ISSUE TITLE
Refereced primitives are misrepresented

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-js#339]
While the title may be a bit wrong, here's the gist of it: according to https://github.com/swagger-api/swagger-ui/issues/1100, when using:

```js
"ApplicationConfigPatch" : {
  "type" : "object",
  "properties" : {
    "variantManagement" : {
      "$ref" : "#/definitions/OperationalState"
    }
  }
},
"OperationalState" : {
  "type" : "string",
  "enum" : [
    "Enabled",
    "Disabled"
  ]
}
```

over

```js
"ApplicationConfigPatch" : {
  "type" : "object",
  "properties" : {
    "variantManagement" : {
      "type" : "string",
      "enum" : [
        "Enabled",
        "Disabled"
      ]
    }
  }
}
```

the display in the ui gets mangled (see original issue for images). Since we know referenced objects are parsed properly, I suspect this is an issue with referenced primitives and their validation constraints and not only an `enum` constraint specifically as mentioned in the original issue.

**Comment by fehguy** [comment]
This belongs in the [resolver.js](https://github.com/swagger-api/swagger-js/blob/master/lib/resolver.js)

**Comment by whitlockjc** [comment]
This isn't a resolver thing.  Basically, `lib/types/models.js` assumes that all `definition` schemas are complex types and in this case that isn't true.  So what we need to do is when we render a model, we need to make sure for non-complex type references we just render the value as if it were a property.  I'm working on this now.

**Comment by whitlockjc** [comment]
This has been fixed.
