### ISSUE TITLE
Need better documentation

### ISSUE THREAD

**Issue by ethanjcohen** [swagger-api/swagger-js#340]
I really want to use this library, but I see very little documentation and examples.

I need the following questions answered, at least:
1. What are the available options for the SwaggerClient({}) class?
2. Can I pass my swagger spec in as a variable, or file reference, instead of fetching from a URL? How?
3. I see that each api function returns data through a callback. What happens in the case of an error? Invalid params? Network error?
4. Examples, for clarity.

**Comment by TrentBrown** [comment]
I'm searching for answers to questions #2 and #3 above, too.

**Comment by whitlockjc** [comment]
You can use the `spec` option value.  If you look at the tests at the bottom of `test/models.js` it should give you an example.

**Comment by fehguy** [comment]
OK we will update the documentation on this but...

@TrentBrown @ethanjcohen as @whitlockjc said, you can pass your spec as a variable by using the `spec` property when initializing swagger-js:

```js
var opts = {};
opts.spec = {
    swagger: '2.0',
    //....
};

sample = new SwaggerClient(opts);
```

For #3, you can pass a error callback as well:

```js
client.getPetById({petId: 3}, function(success) {
  /* success */
}, function(error) {
  /* error */
});
```

**Comment by indolering** [comment]
> OK we will update the documentation on this but...

Where is the documentation?  Perhaps you could start a Github wiki?

**Comment by fehguy** [comment]
We will keep this in the README.  the wikis tend to rot quickly...

**Comment by zub2** [comment]
Same here, I would like to use the library, but to do that I had to dig quite deep into the guts to see what methods are generated and what arguments they accept.

Perhaps it's obvious to you, but I found it difficult - how to go from a method in the swagger spec I want to call to a statement in JS that calls it, passing the parameters correctly etc.

I'd like to see a clear description of how the api spec turns into the client instance. How to access the methods (client.apis.something? or client.something.else?). What arguments to pass to the generated function ({all api call args}, {opts}, ...)). I found out there is "opts" argument that can have some extra opts. What opts are supported? What do they do.

**Comment by sl2** [comment]
+1

**Comment by indolering** [comment]
@zub2 I guess just pile it all onto the README.md?

**Comment by fehguy** [comment]
I do think this stuff belongs in the README.  The best reference is the unit tests but we all know that human documentation is best.  @indolering if you have cycles to help with a PR, I'll send you chocolates.

**Comment by indolering** [comment]
@fehguy I'll add a BasicAuth example, me and a coworker spent a lot of time trying to track that down.

FWIW, if it won't fit in the README StackOverflow is a good place for random info. I spent a lot of time trying to figure out how to pass in auths to the constructor and [documented it on SO](http://stackoverflow.com/questions/32149573/pass-in-auth-credentials-when-initializing-js-swagger-client).

**Comment by fehguy** [comment]
I would really appreciate that.

**Comment by indolering** [comment]
If the README is going to serve as the sole source of official documentation, it needs better structure.  I propose that we maintain the "Calling an API with swagger + node.js!" as a quickstart at the beginning of the README followed by more formal sections:

* Initialization
* Authentication
* Calling 

Since the wiki is enabled, can we just use that as a scratchpad?  We can delete it later, but I don't have a cookie authentication to test against and it would be easier to write and edit everything there before submitting a PR.

**Comment by fehguy** [comment]
I believe that all documentation can always be better.  If not by content, then with nice fonts.  We've added a lot of documentation since this was opened, so...
![image](https://cloud.githubusercontent.com/assets/249413/21871572/d9ce2532-d817-11e6-809d-0608955f9933.png)
