### ISSUE TITLE
swagger-js/ui does not show number data type

### ISSUE THREAD

**Issue by oblonski** [swagger-api/swagger-js#341]
I specify my api with the swagger-editor, download it as json and put it as static content on my webserver. Everything works well. However, when I want to display the generated api.json with swagger-ui (the latest from the master branch), it happens that it cannot render data of type "number" and format "double" in the model schema. It just omit these data types. Every other types are rendered correctly. Once I change the type to "integer" it works perfectly. 

[Here](https://groups.google.com/forum/#!topic/swagger-swaggersocket/FG3GqFuuRxo) you can find my swagger.yml and .json file as well as two screenshots showing what swagger-ui renders (and not renders)

**Comment by oblonski** [comment]
Interestingly, it works with swagger-ui-2.1.8-M1, i.e. numbers are rendered correctly.

**Comment by fehguy** [comment]
should be fixed in https://github.com/swagger-api/swagger-js/issues/353
