### ISSUE TITLE
Parameter display does not display arrays of models properly

### ISSUE THREAD

**Issue by whitlockjc** [swagger-api/swagger-js#343]
Whenever you have an array of models and the schemas items are a reference, instead of `Array[ReferencedType]` you get `Array[Reference]` in the parameter display.  So for example, the following parameter schema:

```js
// ...
{
  name: 'testing',
  in: 'body',
  schema: {
    type: 'array',
    items: {
      $ref: '#/definitions/Person'
    }
  }
}
// ...
```

results in a display of `Array[#/definitions/Person]` instead of `Array[Person]`.

This was original reported from [domaindrivendev/Swashbuckle/issues/200](https://github.com/domaindrivendev/Swashbuckle/issues/200).

**Comment by beryozad** [comment]
As noted elsewhere this behavior can also be observed in http://petstore.swagger.io/#!/user/createUsersWithArrayInput - parameter "body" is shown as "Array[#/definitions/User]"

Once it is fixed, will it only be shown as "Array[User]", or will there be a way to expand it to see the definition of User? 

Thanks!

**Comment by whitlockjc** [comment]
@ponelat So is this fixed after merging #381?

**Comment by ponelat** [comment]
Yes it works in the latest develop_2.0 now.
@beryozad Arrays of models will render the JSON as expandable, something like....

```javascript
[
  {
     "your": "model here",
      "...": "..."
  }
]

**Comment by whitlockjc** [comment]
What about parameters?  When you see a parameter that is an array of models, inline or referenced, does it show `Array[SomeDefinition]` or `Array[#/definitions/SomeDefinition]`?

**Comment by ponelat** [comment]
It wouldn't show a string signature but an expandable widget(lack of a better word?)
Like so.... (Note on the right)


![screenshot from 2015-04-23 17 58 43](https://cloud.githubusercontent.com/assets/8438485/7301356/8619b67e-e9e2-11e4-9a97-7405dd4a55d9.png)

**Comment by whitlockjc** [comment]
That's correct.  I think it showed the string version because it wasn't typed right but it seems you've fixed this.  Thanks a lot.
