### ISSUE TITLE
/browser/swagger-client.js does not seem to set a global SwaggerClient?

### ISSUE THREAD

**Issue by tlbdk** [swagger-api/swagger-js#350]
Hi,

I'm trying to use swagger-client from the browser but the current code does not seem to work, also it would be nice if /browser/index.html would show how to use the client from code.

Regards Troels

**Comment by whitlockjc** [comment]
I just tested this and `SwaggerClient` is exposed as expected.  I do see that the usage in the README is wrong.  I will update that here shortly.

**Comment by whitlockjc** [comment]
This should be fixed.  I'm not sure why the README on `master` is so different than the one on `develop_2.0` but the one on [develop_2.0](https://github.com/swagger-api/swagger-js/tree/develop_2.0) works.  Until @fehguy gets the README on `master` to work, please use the aforementioned link.
