### ISSUE TITLE
Escape regular expressions with values passed by the user

### ISSUE THREAD

**Issue by glowcloud** [swagger-api/swagger-js#3505]
We need to escape regular expressions which are built with values passed by the user:

https://github.com/swagger-api/swagger-js/blob/43e55ec1d20c52b4b2410625c2db470082100c98/src/execute/index.js#L356

For this, we can use `escapeRegExp` function from the [ramda-adjunct](https://github.com/char0n/ramda-adjunct) library.

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-js/pull/3506
