### ISSUE TITLE
Data type number doesn't show on model schema view

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#353]
from https://github.com/swagger-api/swagger-ui/issues/1115

After last update to latest swagger version, models with parameter type number, doesn't show on model schema view, but they can be seen on model view

**Comment by ebrukaya** [comment]
I had the same issue and after a day of debugging, found a solution by adding the following statements to schemaToJSON method in swagger-ui.js

else if (type === 'number') {
      output = 0.0;
    }

**Comment by lifeBCE** [comment]
So correct me if I am wrong but the fix put in place for swagger-js does not fix the issue in swagger-ui. Or does it? I am not using swagger-js and am experiencing this issue as well exclusively in swagger-ui. Are there plans to implement @ebrukaya fix?

Furthermore, the code seems to suggest that float, long, double, etc are valid type values when the swagger spec (https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types) suggests they are not.

**Comment by lifeBCE** [comment]
It seems the swagger editor honors the latest spec format but the swagger-ui code has not kept up. If setting a parameter to type float, the editor gives an error saying that float is not supported and wants "type: number and format: float" but the swagger-ui code does not understand this.
