### ISSUE TITLE
Allow passing baseURL to Swagger.exeute  method.

### ISSUE THREAD

**Issue by sauravazad** [swagger-api/swagger-js#3537]
### Content & configuration

 Swagger-Client usage:
 ```js
 SwaggerClient.execute({
  baseURL: 'someURL'
 })
 ```

### Is your feature request related to a problem?

**baseURL** is computed every time when an execute is invoked . 
https://github.com/swagger-api/swagger-js/blob/ee7fdd67a1369cdb90056ad96751ac97c9c31131/src/execute/index.js#L313

Please have a look at below flame chart . 
Building the URL consumes almost 75% of execution time  for the **executeClient** method .
<img width="2041" alt="image" src="https://github.com/swagger-api/swagger-js/assets/3856934/845a9dcb-baf5-4754-a3aa-27475d30ebf9">

### Describe the solution you'd like

If  SwaggerClient.execute() were to accept a **baseURL**  , and use it if provided instead of building it , It would help in improving the performance and execution time .

Please let me know if  this added support is acceptable . If so, I will raise a PR to add the support.

**Comment by sauravazad** [comment]
@char0n

Any comments or thought on the above proposal ?

**Comment by char0n** [comment]
Hi @sauravazad,

The proposal is reasonable. We're gonna go for it. I'll tend the the PR ASAP. 

Thank you!

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-js/pull/3538

**Comment by char0n** [comment]
Released as https://github.com/swagger-api/swagger-js/releases/tag/v3.31.0
