### ISSUE TITLE
swagger_output.json() file can't making endpoint of form type is fileupload .swagger_output.json() can generate simple form not multer type in node with express

### ISSUE THREAD

**Issue by Ritik558** [swagger-api/swagger-js#3599]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Environment: [e.g. Chrome 59, Node.js v10.0.0]
 - Method of installation: [e.g. npm, unpkg]
 - Swagger-Client version: [e.g. 3.8.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-Client usage:
```js
SwaggerClient({
  // your config options here
})
```

### To reproduce...

1. ...

**Comment by char0n** [comment]
I'm sorry but I don't understand this issue. Please reopen with more actionable information.
