### ISSUE TITLE
global parameters may not be properly expanded

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#360]
from https://github.com/swagger-api/swagger-ui/issues/1137#issuecomment-91294012

**Comment by fehguy** [comment]
fixed in 8030793c248229a52ee6ad8344a986c3be027f78

**Comment by xelwarto** [comment]
Is there a PR for this fix or any plan to merge? or should we just test with the develop_2.0 branch?

**Comment by webron** [comment]
You can test the develop_2.0 branch.

**Comment by fehguy** [comment]
It will be released in the next dot version, which I expect in the next 2 days.  In the meantime, feedback/testing would be great.
