### ISSUE TITLE
The SwaggerClient "spec" property does not support version < 2.0 (easy fix in comments)

### ISSUE THREAD

**Issue by ethanjcohen** [swagger-api/swagger-js#365]
A check is done when the spec is loaded via http, to see if the spec contains "swagger" or not, to see if it's version 2.0. That check should also be done when the spec is passed in via a variable.

**Comment by ethanjcohen** [comment]
Just replace the code inside of the setTimeout(..., 10) with this code and it will work:

```JavaScript
//This is the check you need to do
if (self.spec.swagger && parseInt(self.spec.swagger) === 2)
		{
			new Resolver().resolve(self.spec, self.buildFromSpec, self);
		}
		else
		{
                //Convert the spec, just like in the section above this
			self.swaggerVersion = self.spec.swaggerVersion;
			
			var converter = new SwaggerSpecConverter();
			  converter.setDocumentationLocation(self.url);
			  converter.convert(self.spec, function(spec) {
					new Resolver().resolve(spec, self.buildFromSpec, self);
					self.isValid = true;
			  });
		}
```

**Comment by fehguy** [comment]
Hi, i'm looking into this but if it was not working the 1.2 tests would fail.  Can you please share more details with the issue?

**Comment by ethanjcohen** [comment]
Sure, here's my code to convert a swagger spec/schema into a client:
```JavaScript
function getGeneratedAPIs(cb)
{
	var schema = require(schemaLocation);
	
	var SwaggerClient = require("swagger-client");
	
	var swagger = new SwaggerClient({
		url: 'http://localhost:4000/api-docs',
		spec: schema,
		success: function()
		{
			cb(swagger.apis);
		}
	});
}
```

schema is a swagger 1.2 spec object (built using swagger-node-express)

If you look in /lib/client.js, under this function:
```JavaScript
SwaggerClient.prototype.build = function (mock) {
```

You'll see that it checks for a spec, but doesn't bother checking the version:
```JavaScript
  if (this.spec) {
    setTimeout(function () {
      new Resolver().resolve(self.spec, self.buildFromSpec, self);
   }, 10);
  } else {
```

The code directly above that handles the old version, but that only gets called if an http request is done, I believe:
```JavaScript
response: function (resp) {
        var responseObj = resp.obj || JSON.parse(resp.data);
        self.swaggerVersion = responseObj.swaggerVersion;

        if (responseObj.swagger && parseInt(responseObj.swagger) === 2) {
          self.swaggerVersion = responseObj.swagger;

          new Resolver().resolve(responseObj, self.buildFromSpec, self);

          self.isValid = true;
        } else {
//RIGHT HERE - This is the important missing part from the other section of code
          var converter = new SwaggerSpecConverter();
          converter.setDocumentationLocation(self.url);
          converter.convert(responseObj, function(spec) {
            new Resolver().resolve(spec, self.buildFromSpec, self);
            self.isValid = true;
          });
        }
      }
```

**Comment by ethanjcohen** [comment]
It's a lot of code, so I may be missing something - but it looks like someone added the conversion in one place but not the other.

**Comment by ethanjcohen** [comment]
Doesn't look like the tests cover this case. From tests/client.js:

```JavaScript
//Only version 2 is tested
var petstoreRaw = require('./spec/v2/petstore.json');
```

**Comment by fehguy** [comment]
1.2 tests are covered here:

https://github.com/swagger-api/swagger-js/tree/master/test/compat

**Comment by ethanjcohen** [comment]
I saw that, but couldn't find where the client was being tested

**Comment by fehguy** [comment]
any of the tests under that folder are testing 1.2 compatibility.

Just run `mocha test/compat/request.js` for example.

**Comment by ethanjcohen** [comment]
I see that now. But they still don't test the "spec" property.

Just building from URLs, for example:
```JavaScript
 it('allows override of headers when fetching the swagger specification', function () {
    var opts = {
      swaggerRequestHeaders: 'foo/bar'
    };
    var sample = new SwaggerClient('http://localhost:8000/api-docs.json', opts);
    var req = sample.build(true);

    expect(req.headers.accept).toBe('foo/bar');
  });
```

**Comment by fehguy** [comment]
Please look into the tests more--there are many tests, i'm guessing you're going to want to inspect https://github.com/swagger-api/swagger-js/blob/master/test/compat/converter.js

**Comment by ethanjcohen** [comment]
Already looked at that file. I'll take a look at all of them more later so see if there's something like the code I'm using.

**Comment by webron** [comment]
@ethanjcohen - did you get a chance to look further?

**Comment by fehguy** [comment]
OK the cause of this issue is that the spec being passed in is not being passed by URL--it's being passed by object.  In this case, it's technically not possible to use a swagger 1.x specification, since they are, by definition, multiple files.  That makes it weird to pass as an object.

Thus there is no check for version when loading the `spec` property when passed in options.  It may be an issue for a newer version of swagger spec, but for now, it's not an issue.

**Comment by ethanjcohen** [comment]
Ok I see what you're saying. I've been passing in a using a single file to that variable, which is how my modification has gotten it to work. I'm using the specification built from the fetch library, which concatenates everything into one file.

**Comment by fehguy** [comment]
What is the fetch library?

**Comment by ethanjcohen** [comment]
From my dependencies: "fetch-swagger-schema": "0.1.2"
https://github.com/signalfx/fetch-swagger-schema

If you look at the swagger-client-generator page, it mentions this library, which is working pretty good for me.
https://www.npmjs.com/package/swagger-client-generator

**Comment by fehguy** [comment]
Got it. I'll look at getting this working

**Comment by ethanjcohen** [comment]
Awesome, thanks.

**Comment by ethanjcohen** [comment]
Was the code ever modified to accommodate this (i.e. loading the 1.2 spec from an object rather than a URL)?

**Comment by fehguy** [comment]
It was not.  Given that the 1.2 specs are multi-file and the spec is quite old, it doesn't make sense to implement it in this library.
