### ISSUE TITLE
No way to prevent encoding in serverVariables injection

### ISSUE THREAD

**Issue by paztis** [swagger-api/swagger-js#3656]
Since this PR: https://github.com/swagger-api/swagger-js/pull/3557/files all the serverVariables are automatically encoded.
We use serverVariable to manage the protocol://host:port, but :// are encoded

https://github.com/swagger-api/swagger-js/blame/b52871ebcc396c873c5616724cd191547c730e4e/src/execute/index.js#L362

openapi-server-url-templating is allowing to provide customEncoder. Is it possible to add a topLevel optional  serverVariablesEncoder to be able to cover our case ? Or to disable the encoding by default ?

the Saas and On-Premise specification provide this example of serverVariables  https://swagger.io/docs/specification/api-host-and-base-path/
![image](https://github.com/user-attachments/assets/3065a8b0-498a-443b-8da2-b570c0818dd0)

and it no more works

**Comment by ponelat** [comment]
Thank you @paztis, and good catch. We don't have the resources to look into this right now, but would welcome a PR :)

**Comment by ponelat** [comment]
@char0n are you able to take a look though?

**Comment by char0n** [comment]
Hi @paztis,

Thanks for the issue.

If we want to support “SaaS on On-Premise” usecase, which we do - then we have to turn off the default encoding. 
We can also introduce a config option to SwaggerJS to turn the encoding on/off, with the default behavior turned off.

I'm on it.

**Comment by char0n** [comment]
Addressed in https://github.com/swagger-api/swagger-js/pull/3660
