### ISSUE TITLE
IE9 and below API calling issues

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-js#366]
Moved from https://github.com/swagger-api/swagger-ui/issues/1129

**Comment by whitlockjc** [comment]
Gotta love IE8/IE9: https://github.com/visionmedia/superagent/issues/409

**Comment by fehguy** [comment]
This can only really be handled by enabling jquery.

**Comment by fehguy** [comment]
Depends on #239

**Comment by ponelat** [comment]
This looks like an unclosed issue (my powers of observation are strong), which should be closed as @fehguy  merged in pluggable clients for Ajax... 

Issue that indicates this is resolved.... https://github.com/swagger-api/swagger-js/issues/239
The PR referenced by that issue... https://github.com/swagger-api/swagger-js/pull/428
@webron close?

**Comment by webron** [comment]
Sure, let's close.
