### ISSUE TITLE
Upgrade all @swagger-api dependencies in latest release

### ISSUE THREAD

**Issue by paztis** [swagger-api/swagger-js#3721]
Because of this issue 
https://github.com/swagger-api/apidom/issues/4539#issuecomment-2493279621

It is impossible to use swagger client last version without forcing resolution
Can you upgrade the d'EPS to support the beta ?

**Comment by char0n** [comment]
Hi @paztis

Released as https://github.com/swagger-api/swagger-js/releases/tag/v3.32.0.

**Comment by paztis** [comment]
Thanks a lot
