### ISSUE TITLE
Missing parameters not handled correctly

### ISSUE THREAD

**Issue by ethanjcohen** [swagger-api/swagger-js#375]
In the case of missing parameters, only a log is shown. The callback isn't even called. 

This is unacceptable, since my code will just hang at that point and I won't be able to properly handle the error.

In operation.js:
```JavaScript
if (missingParams.length > 0) {
    var message = 'missing required params: ' + missingParams;

    helpers.fail(message); //logs the error

    return; //needs to call the error callback!
  }
```

**Comment by ethanjcohen** [comment]
I just tested this fix in my code and it works great:

```JavaScript
if (missingParams.length > 0) {
    var message = 'missing required params: ' + missingParams;

//remove this, because error is helper.log by default
    //helpers.fail(message); 

//this is the new code, call the error callback or log
    return error(new Error(message), parent); 
  }
```

**Comment by webron** [comment]
Sounds like a step before a PR ;)

**Comment by ethanjcohen** [comment]
What do you mean? PR? o_O

**Comment by webron** [comment]
A Pull Request? An official fix that can be merged into this repository.

**Comment by ethanjcohen** [comment]
Ah. Right lol

I'm building up a pretty good list of bugs I've fixed now, so I'll submit one at some point. But for now, I don't have enough time to fully examine the code and test my changes. I'm not knowledgeable enough to ensure that my changes won't break anything.

So, I'm supplying small fixes here, in the hope that someone more experienced will include them in a pull request.

**Comment by ethanjcohen** [comment]
Unless you're ok with half-tested changes in a pull request. Not sure how this project has been using pull requests.

**Comment by webron** [comment]
Well, no, we're not quite fans of changes that aren't tested.

**Comment by ethanjcohen** [comment]
I assumed not.

**Comment by ethanjcohen** [comment]
See, I just realized that returning an Error object to error(...) isn't 100% correct, because a response object is usually returned instead.

So, I'm not sure what the original designers intended to happen, in the case of invalid params. Ideally, error() should return an error object, with the response inside that, since the error can come from the library itself. Or, there needs to be another way to detect these validation errors from the library, since the error callback is supposed to get the response object.
