### ISSUE TITLE
Browser tests

### ISSUE THREAD

**Issue by mrhanlon** [swagger-api/swagger-js#383]
I am primarily using swagger-js in the browser. I noticed that there are not any browser tests currently in the test suite. I have a couple of browser tests written related to working on #382. I did not want to add the phantomjs dev dependency, though, without first gauging interest. I would be willing to contribute some browser tests if the interest is there.

**Comment by mohsen1** [comment]
Firefox is available in TravisCI. We use Chrome outside of TravisCI and Firefox inside TravisCI for SwaggerUI. PhantomJS is known to be very incompatible with actual browsers. Sooner or later you'll hit PhantomJS limitation. I think if you use actual browser it's easier to maintain and more accurate.

**Comment by mrhanlon** [comment]
Ok, I'm fine with that, too. I've already encountered such instances of incompatibility. Mostly I was just noticing the lack of browser tests.

**Comment by mrhanlon** [comment]
Following the lead of SwaggerUI's browser tests, I [started a branch](https://github.com/mrhanlon/swagger-js/tree/feature/browser-tests) that adds browser tests. I have only implemented one test related to #382.

I see in the `paths.tests` config in the gulpfile that browser tests are explicitly ignored. I presume this is for speed, which is fine. So I added a new task to the gulpfile for just running the browser tests. Also, the way I have the tests configured right now it uses the built swagger-client.js, which is less than ideal. I would rather require the appropriate modules as needed, but I didn't want to put in that effort if there isn't much interest in this.

Since using PhantomJS has been ruled out I'm going to change the issue title to simply "browser tests".

**Comment by webron** [comment]
@mrhanlon - just make sure you work off of develop_2.0 and not master.

**Comment by mrhanlon** [comment]
@webron yep, that branch is based off develop_2.0, thanks.

**Comment by webron** [comment]
@mrhanlon - any update on this? No rush, of course, just trying to plan the next release.

**Comment by mrhanlon** [comment]
@webron I got caught up with some other things. I have one browser test written related to #382 and I setup a gulp task and npm script for running the browser tests. Right now the browser tests are configured separately from the other tests as I was unsure how you guys would want to wire them into the CI or other processes.

Let me review what I have and then submit a PR so you guys can take a look.

**Comment by webron** [comment]
@mrhanlon - great, thanks for the update.

**Comment by mrhanlon** [comment]
Sorry about the delay on getting this pull together. Let me know if there are issues/questions.

**Comment by webron** [comment]
Never apologize for delays in contributions. Since @fehguy merged the PR, is there anything else you'd like to add here or shall we close the issue?

**Comment by mrhanlon** [comment]
Nope, I think we can close it. Thanks!

**Comment by webron** [comment]
Thanks for the contribution!
