### ISSUE TITLE
Normalize instances of String#trim

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-js#386]
I noticed a comment on using String#trim and IE8 Support (talking about you @mohsen1 ).
I made the mistake, and it looks like this code has a few instances...
https://github.com/swagger-api/swagger-js/blob/master/lib/http.js#L101-L117

The only reason that I'm creating an issue and not a direct PR, is because I see two solutions...
Make sure we use jQuery.trim (enforce it with a comment somewhere in contributions?)
Or better yet, pollyfill it with something like this...

Taken from CSSTricks...https://css-tricks.com/snippets/javascript/strip-whitespace-from-string/
```javascript
if (!String.prototype.trim) {
  String.prototype.trim = function () {
    return this.replace(/^\s+|\s+$/g, '');
  };
}
```

**Comment by mohsen1** [comment]
SwaggerJS is not having a dependency to jQuery. The polyfill looks like a better option since it's not being used in any other browser other than IE8

**Comment by webron** [comment]
Fixed in develop_2.0.
