### ISSUE TITLE
A $ref needs to be wrapped inside a schema which is not according to spec.

### ISSUE THREAD

**Issue by ralphvanetten** [swagger-api/swagger-js#402]
This is a followup to https://github.com/swagger-api/swagger-ui/issues/1228

I have

```
 "Person" : {
         "type" : "object",
         "title" : "Information about a person",
         "properties" : {
            "externalId1" : {
               "title" : "first",
               "type" : "object",
               "$ref" : "#/definitions/map1"
            }
```

which does not work. The answer was to wrap it inside a "schema" and then it works:

```
"externalId1" : {
               "title" : "first",
               "type" : "object",
               "schema": {  // < -------------- This will make it work like you expect
                    "$ref" : "#/definitions/map1"
                } // ------------------- :)
            },
```

However, after looking into the spec of both swagger and JSON schema, there is no reference anywhere the "schema" wrapper is required. 

As far as I can tell, my version without the "schema" wrapper is correct.

The example here https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#simple-model does not use the "schema" wrapper.

Am I missing something?

**Comment by ralphvanetten** [comment]
Also, when using https://github.com/apigee-127/swagger-tools to validate the swagger file, the validator also does not like having the "schema" wrapper present.

**Comment by ponelat** [comment]
I think you're right... @webron knows the spec better than I (better than anyone?) but there seems to be an inconsistency of what works and what's in the spec.

**Comment by webron** [comment]
@ralphvanetten - that's not the way to define it, but without seeing what `#/definitions/map1`, it would be difficult to suggest the proper solution.

**Comment by ralphvanetten** [comment]
It is the example from https://github.com/swagger-api/swagger-ui/issues/1228 :

```
{
   "paths" : {
      "/person" : {
         "post" : {
            "parameters" : [
               {
                  "in" : "body",
                  "name" : "body",
                  "schema" : {
                     "$ref" : "Person"
                  }
               }
            ],
            "tags" : [
               "person"
            ],
            "summary" : "Create new person",
            "responses" : {
               "200" : {
                  "schema" : {
                     "$ref" : "Person"
                  },
                  "description" : "Success"
               }
            }
         }
      }
   },
   "swagger" : "2.0",
   "basePath" : "/person",
   "info" : {
      "title" : "Person API",
      "version" : "1",
      "description" : ""
   },
   "tags" : [
      {
         "name" : "person",
         "description" : "Persons"
      }
   ],
   "definitions" : {
      "map1" : {
         "type" : "object",
         "properties" : {
            "anId1" : {
               "title" : "Id",
               "type" : "string"
            }
         },
         "title" : "map1"
      },
      "map2" : {
         "type" : "object",
         "properties" : {
            "anId2" : {
               "title" : "Id",
               "type" : "string"
            }
         },
         "title" : "map2"
      },
       "Person" : {
         "type" : "object",
         "title" : "Information about a person",
         "properties" : {
            "externalId1" : {
               "title" : "first",
               "type" : "object",
               "$ref" : "#/definitions/map1"
            },
            "externalId2" : {
               "title" : "second",
                "type" : "array",
                "items": {
                    "$ref" : "#/definitions/map2"
                }
            }
         }
      }       
   }
}
```

The suggestion given in that issue is to wrap the `$ref` inside a `schema` but I can not found any reference in the swagger spec or the JSON schema spec this extra `schema` is needed.

**Comment by webron** [comment]
Are you trying to define maps with `map1` and `map2`? Because that's not the way to do it.

**Comment by ralphvanetten** [comment]
No, perhaps its a poor choice for those names, but `map1` and `map2` are supposed to be normal JSON objects with a couple of fields.

**Comment by webron** [comment]
Okay, just wanted to make sure. 

This how `"Person"` should be defined:

```js
{
  "type": "object",
  "title": "Information about a person",
  "properties": {
    "externalId1": {
      "$ref": "#/definitions/map1"
    },
    "externalId2": {
      "title": "second",
      "type": "array",
      "items": {
        "$ref": "#/definitions/map2"
      }
    }
  }
}
```

**Comment by ralphvanetten** [comment]
So `title` and `type` are not allowed?

**Comment by ralphvanetten** [comment]
Ah, yes, I tried it and as soon as you add `title` it does not work anymore.

**Comment by webron** [comment]
You add *anything* when there's `$ref`. This is a restriction of [JSON Reference](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-3).

**Comment by ralphvanetten** [comment]
Ok, thanks for the reference.
However, I tried putting a `description` there and this works :

```
         "properties" : {
            "externalId1" : {
                "$ref" : "#/definitions/map1",
                "description": "hello"
            },
```
![selection_109](https://cloud.githubusercontent.com/assets/1533323/7455530/76bb7bce-f27d-11e4-9d5f-eef3d22d466a.png)

If this is not allowed, how can you add a description which shows up in swagger-ui?

**Comment by webron** [comment]
The parser may read it somehow, but most parsers would ignore it. The way to add the description would be in the referenced object.

**Comment by ralphvanetten** [comment]
Ok, I thought the `description` is used to describe the field (`externalId1` and `externalId2` in this case). 
If the `description` must be on the referenced object, then you can not have a different description if you have multple references to the same object?

So something like:

```
"properties" : {
            "externalId1" : {
                "$ref" : "#/definitions/map1",
                "description": "This is the ID for the first thing."
            },
            "externalId3" : {
                "$ref" : "#/definitions/map1",
                "description": "This is the ID for the third thing."
            },
```
is not correct and not otherwise possible?

**Comment by webron** [comment]
If you use `$ref`, that is not possible. As explained, this is a limitation of JSON Reference.

**Comment by ralphvanetten** [comment]
Isn't this a bit of a flaw in the (swagger) spec?

I have a fairly large object used by many other objects. Using `$ref` would be a nice solution to keep the swagger file small but if you do you can't have different descriptions in the object which uses the reference.

**Comment by webron** [comment]
It's not a flaw in the Swagger spec. It's a limitation of JSON Reference which is used by JSON Schema which is used by Swagger. Not much we can do about it besides contest the JSON Reference spec, I wouldn't get my hopes up actually affecting it.

**Comment by ralphvanetten** [comment]
I looked at the JSON reference spec. again and according to the spec it is fine to have other properties besides `$ref` :

> If a JSON value does not have these characteristics, then it SHOULD
>  NOT be interpreted as a JSON Reference.
> ...
> Any members other than "$ref" in a JSON Reference object SHALL be
> ignored.

https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-3 

So it seems the spec leaves room for adding a `title` and `description` property which are then shown by swagger-ui.

**Comment by webron** [comment]
Nope. `SHALL be ignored.` I don't know of any JSON Schema/Reference parser that does not ignore those. It's not going to change.

**Comment by fehguy** [comment]
OK while it would be very convenient that `$ref` and other fields could merge together, json schema simply doesn't support this.  I'm closing this issue, and we can put other requests in the swagger-spec project.

**Comment by mutkur** [comment]
Going by the above discussion is it legal to have a $ref along with other fields 'type' and 'description' etc? I have

**Comment by webron** [comment]
It's legal in terms of whether it's valid to write it that way or not. In terms of meaning - the `"type": "object"` is just going to be ignored.
