### ISSUE TITLE
can not read property 'definition' of undefined in types/model.js

### ISSUE THREAD

**Issue by ralphvanetten** [swagger-api/swagger-js#404]
This seems incorrect and gives me a "Cannot read property 'definition' of undefined" :

https://github.com/swagger-api/swagger-js/blob/develop_2.0/lib/types/model.js#L258

The model variable is checked for undefined but it is still used inside the if.

**Comment by ponelat** [comment]
When are you getting this? It does look faulty, but some context would be helpful :D

**Comment by ralphvanetten** [comment]
I'll see if I can find a minimal sample

**Comment by ralphvanetten** [comment]
It is caused by a non existing $ref:

```
{
   "swagger" : "2.0",
   "info" : {
       "description" : "...",
      "title" : "API",
      "version" : "1"
   },
   "basePath" : "/x",
   "paths" : {
      "/test" : {
         "post" : {
            "responses" : {
               "200" : {
                  "description" : "Success",
                  "schema" : {
                     "$ref" : "#/definitions/Object"
                  }
               }
            }
         }
      }
   },
   "definitions" : {
      "Object" : {
         "properties" : {
            "link" : {
                "title" : "Links",
                "schema": {
                    "$ref" : "TODO"
                },
               "type" : "object"
            }
         },
         "type" : "object"
      }
   }
}
```

**Comment by ponelat** [comment]
Thanks, I'm going to take a look at this a little later.

**Comment by ponelat** [comment]
The line you've shown isn't as erroneous as it first appeared, although where this error is coming from is a bit of a mystery to me - as all references seem to be guarded.
isUndefined should catch before looking beyond that with the || operator.

As the error only occurs in a faulty spec, I'll revisit this at a later stage. 
There are some issues with the $ref property, so some refactoring may occur, which may incidentally solve this.

**Comment by webron** [comment]
@ralphvanetten - that's not really a valid definition. The whole `links` property is a bit odd, and I'm not sure what you were trying to do there. If you can describe it, I may be able to suggest a proper definition.

**Comment by ralphvanetten** [comment]
Is there something else wrong besides the non existing reference?

Anyway, `link` is supposed to be a JSON object which is described somewhere else. Hence the $ref.

But in this case I made a mistake in the swagger file and got the $ref wrong and it then gives the "can not read property" error.
I created this issue because swagger does not seem to handle this error in the swagger file cleanly and it was very difficult to find out what exactly was wrong with my swagger file.

**Comment by webron** [comment]
There's no `schema` property at all in the `Schema Object` so it's just not a valid definition.

**Comment by ralphvanetten** [comment]
The `schema` property was suggested as a solution in another issue. But yes, the schema is not valid. Only it would be nice if there was a more friendly error message.

**Comment by fehguy** [comment]
correct definition or not, the client shouldn't explode.  Should be fixed now.
