### ISSUE TITLE
API containing operation /apis fails to parse

### ISSUE THREAD

**Issue by olensmar** [swagger-api/swagger-js#405]
When attempting to parse the swagger 2.0 definition I first get a warning in the log:

The 'apis' tag conflicts with a SwaggerClient operation function/property name. Use 'client.apis._apis' instead of 'client.apis.apis'.

and then an error:

spec-converter.js:90 Uncaught TypeError: Cannot set property 'apisGet' of undefined

Using the latest develop_20 branch

/Ole

**Comment by olensmar** [comment]
i've fixed this by adding "apis" to the reservedClientTags list as well - due to line 344 in client.js:

operationGroup = self[clientProperty] = self.apis[apiProperty] = {};

since the value of clientProperty is "apis", the assignment overwrites itself.

@webron / @fehguy if there is no prettier way to fix this I can submit a PR

**Comment by fehguy** [comment]
this is for @whitlockjc

**Comment by whitlockjc** [comment]
I somehow missed this when adding the fixes that caused this static list of restricted tag values.  Regardless, his has been fixed.

**Comment by olensmar** [comment]
great - thank you!
