### ISSUE TITLE
clientAuthorizations are ignored in case of multipart/form-data + file

### ISSUE THREAD

**Issue by z0mt3c** [swagger-api/swagger-js#407]
clientAuthorizations are working fine for multipart/form-data as long as no file is included. With a file field clientAuthorizations (header + query) are being ignored.

Tested: swagger-ui@2.1.1-M2 (swagger-js@2.1.2-M2?!)

**Comment by fehguy** [comment]
I hate to bounce this back to swagger-ui, but that's where this logic lives:

https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/view/OperationView.js#L327
