### ISSUE TITLE
Pass spec via options.spec

### ISSUE THREAD

**Issue by adborden** [swagger-api/swagger-js#408]
Is creating a swagger client directly from spec supported? We'd like to avoid having to request the schema over the network just to instantiate our swagger client. We found this approach to mostly work.

```javascript
var schema = parseSchema();

client = new SwaggerClient();
client.initialize({spec: schema});
client.build();
client.apis.pets.getById();
```

The only catch we found with this is there's a `setTimeout` call making the build call async. We'd like to make this approach first class. Would you be open to a PR?

**Comment by fehguy** [comment]
Yes, it is supported.  You should follow something more like this, to properly handle the async nature of the building:

```js
client.initialize({spec: schema}, function() { 
  client.pets.getById({petId: 3}, function(response) {
    // do something with your pet
  }
}
```

**Comment by adborden** [comment]
That example just hangs. Looks like I still need to specify a ["success" callback](https://github.com/swagger-api/swagger-js/blob/f0cb7a76d2531876dff9be9fd0a963889b85e7b3/lib/client.js#L144) in order to kick off the build method. Is this the preferred method then?

```javascript
client.initialize({
  spec: schema,
  success: function() { 
    client.pets.getById({petId: 3}, function(response) {
      // do something with your pet
    });
   }
});
```
