### ISSUE TITLE
Top level example does not end up in model

### ISSUE THREAD

**Issue by Hes-Siemelink** [swagger-api/swagger-js#409]
In Swagger 2.0 spec you can set an example on a definition. For example:

    {
        "definitions": {
            "Release": {
                "description": "The release type.",
                "example": "{ Handcrafted JSON example for RELEASE type }",

This is not being picked up in the model (`swagger-client.js`), so swagger-ui won't display it.

**Comment by fehguy** [comment]
fixed in #410
