### ISSUE TITLE
Supporting HMAC calculation via callback(s)

### ISSUE THREAD

**Issue by joegluntz** [swagger-api/swagger-js#41]
How would Swagger be best enhanced to support the calculation of certain headers or request parameters upon each call, on behalf of HMAC-based authentication and authorization?

I've noticed the pull request https://github.com/wordnik/swagger-ui/pull/77 (which didn't ultimately get submitted to swagger-js) which would allow you to calculate a single header via a callback.  But I'm wondering if the solution should be more flexible. addressing:
- That in HMAC auth solutions, there are often multiple headers, calculated in concert (the HMAC signature with associated nonce, timestamp, or other values, etc.)
- That some APIs put these values in the headers, whereas others put them in the request parameters (e.g. Amazon)
- That the callback will likely need the entire SwaggerOperation object, so that it can factor-in things like the httpMethod into the signature

I am thinking of enhancing SwaggerOperation.getMatchingParams to support this kind of dynamic header calculation on each call, but wondering what the official team thinks of the best direction:
- it could support single-header callbacks, as in the pull request above
- or it could be a single callback to calculate arbitrary additional params (either header or query)
- or it could be a single callback which fires sometime later (just before the call is made) to decorate the call in arbitrary ways

I'm leaning towards the middle option but wanted to get feedback before I submit a Pull Request.  Thanks in advance.

**Comment by srl295** [comment]
The docs (`README.md`) is missing this critical line from [this comment](https://github.com/swagger-api/swagger-js/issues/41#issuecomment-33376206):

```
window.authorizations.add("my_authorization", new CustomAuthorization("my_authorization");
```

**Comment by webron** [comment]
@srl295 - that seems like just one step before a PR.

**Comment by srl295** [comment]
@webron just so. The step before that is getting it to work, though. Is there a way to get at the 'string body' as in that snippet?
