### ISSUE TITLE
Bad expression in lib/types/model.js

### ISSUE THREAD

**Issue by pip25** [swagger-api/swagger-js#421]
This part:
```javascript
if (_.isUndefined(model) || _.indexOf([undefined, 'array', 'object'], model.definition.type) === -1) {
                // Use referenced schema
                cProperty = helpers.resolveSchema(model.definition);
}
```
is obviously incorrect, since if `model` is undefined, then `model.definition` cannot be evaluated. 
Simply negating the expression causes some sort of infinite loop, however, freezing the browser, so the issue is probably more complicated than that. 
This issue currently breaks Swagger-UI for me.

**Comment by webron** [comment]
Not saying that doesn't need to be fixed, but is your Swagger definition correct? Can you share it?

**Comment by pip25** [comment]
I'm not in the position to share it, but my Swagger definition is working just fine with earlier versions of Swagger-UI. By the way, the infinite loop disappears if I comment out the whole 

```javascript
	if (!_.isUndefined(cProperty.$ref)) {
              model = models[helpers.simpleRef(cProperty.$ref)];

              if (!(_.isUndefined(model) || _.indexOf([undefined, 'array', 'object'], model.definition.type) === -1)) {
                // Use referenced schema
                cProperty = helpers.resolveSchema(model.definition);
              }
      }
``` 
part. Then the UI renders fine.

**Comment by webron** [comment]
By the way, this is tested with which version?

**Comment by pip25** [comment]
Latest of the develop_2.0 branch of Swagger UI, which depends on Swagger Client 2.1.4-M2. I was trying the test the fix for another issue (https://github.com/swagger-api/swagger-ui/issues/1139) when I ran into this one.

**Comment by fehguy** [comment]
This is because you have a missing model reference in your spec, which is an issue.  The client crashing is a different matter, but it should be fixed here:  https://github.com/swagger-api/swagger-js/commit/75ac5598e1db96c2eb6baea0aaa784a5d2b41e4b

You can test this change by pulling swagger-js develop_2.0 branch, running `npm link` in that project, then `npm link swagger-client` in swagger-ui, develop_2.0 branch.  Then run `gulp` and you'll have the latest swagger-js and swagger-ui.

**Comment by whitlockjc** [comment]
Should probably be: `if (!_.isUndefined(model) && _.indexOf([undefined, 'array', 'object'], model.definition.type) === -1) {`  We only want to use the referenced model when it exists and its type is what we call a model.

**Comment by pip25** [comment]
Yes, I can confirm that the issue is no longer present in the current swagger-js develop_2.0 branch HEAD. Thank you. :)
