### ISSUE TITLE
Possible improvements converting response messages in spec-converter

### ISSUE THREAD

**Issue by mikewatt** [swagger-api/swagger-js#423]
I'm pretty unfamiliar with the swagger code, but we've come across a couple of issues in the way swagger-ui displays response models, which seems to be rooted in SwaggerSpecConverter.responseMessages().

Specifically, SwaggerSpecConverter.responseMessages():

* Creates a 200 response entry if no such response was explicitly declared.  This seems unnecessary, as you end up with a documented 200 response even if the api operation may never return such a response.

* Looks for a documented 200 response, creating an additional 'default' response if one exists. This should at least be expanded to look for 200-299 responses. However, it also seems unnecessary to create a default response entry in this case, which according to the spec is used to document undeclared responses. Rather, it seems more useful to associate the default response schema with the documented 2xx response, if found.

See https://github.com/mikewatt/swagger-js/commit/5b250b4a5cc93e0e2ed5cf74a3c29af6837081d0 for a patch which addresses these issues locally for us. Are these changes reasonable?

**Comment by webron** [comment]
Mind reading the discussion in https://github.com/swagger-api/swagger-ui/issues/1266 before we continue? :)

**Comment by mikewatt** [comment]
Ok, I can appreciate the subtleties of 1.2 to 2.0 conversion now.

Instead of assuming the default response is a 200, why not always write the default response as the swagger 2.0 'default' response object?

FWIW, we are sticking with swagger-ui 2.0.24 for now. There's a non trivial amount of work for us to update from a 1.2 to 2.0 definition as the definition is dynamically aggregated from a bunch of micro-services. We were hoping to update the UI first, then work on the backend update. I'm happy for this issue to be closed unless there's any realistic chance of changing the conversion behaviour.

**Comment by webron** [comment]
Well, the `default` is an interesting option, but we don't treat the `default` as a successful response and that also changes the behavior of the UI. I appreciate there's work to be done when moving from 1.2 to 2.0 and perhaps we can suggest some ideas on how to migrate those, but that's probably out of scope to this issue and more suitable for the google group.

**Comment by webron** [comment]
I'd keep it open for now as @fehguy may have other ideas as well.
