### ISSUE TITLE
parameter enums not working in 1.2 specs

### ISSUE THREAD

**Issue by cancan101** [swagger-api/swagger-js#424]
The enum for parameters is no properly handled when loading 1.2 spec files
See: https://gist.github.com/cancan101/e5e60a1fefd70d276102

reposted from: https://groups.google.com/d/topic/swagger-swaggersocket/17n4k2dzTH0/discussion

Should look like:
![image](https://cloud.githubusercontent.com/assets/51059/7594020/fba3f7ba-f8ab-11e4-8506-d2e3514723ca.png)
instead:
![image](https://cloud.githubusercontent.com/assets/51059/7594036/09daa25c-f8ac-11e4-8dde-fcc02db4f2a4.png)

**Comment by fehguy** [comment]
I have a feeling you're either on an old build, or there are fixes pending for develop_2.0 that need to be pushed.  I just tested this scenario out and get what you'd expect:

![image](https://cloud.githubusercontent.com/assets/249413/7609357/2c1c0074-f940-11e4-86db-f0b84c0ec767.png)

Let's re-test this upon next point release?

**Comment by fehguy** [comment]
Fixed in 2.1.5-M2
