### ISSUE TITLE
Question around PUT & POST Operations

### ISSUE THREAD

**Issue by sberryman** [swagger-api/swagger-js#435]
I just tried upgrading to 2.1.6-M2 and also upgrading my swagger spec to 2.0. I noticed when making a POST or PUT that the payload now needs to have a property matching the model name.

Old way:
```js
var payload = {
  body: {
    returnDeleted: true
  }
};
```

The way it works now:
```js
var payload = {
  body: {
    ModelName: {
      returnDeleted: true
    }
  }
};
```

Parameters:
```json
{
  "parameters":[
    {
      "required":false,
      "in":"body",
      "name":"ModelName",
      "schema":{
        "$ref":"#/definitions/ModelName"
      }
    }
  ]
}
```

This is a pretty major change which is fine but I'm wondering if this was desired or if it is a bug. It certainly isn't documented.

**Comment by fehguy** [comment]
Hi, not a bug, it's actually how the swagger 1.2 spec was written.  You were required to have the parameter name of `body`.  In 2.0, you can name the body parameter whatever you like.  I suggest updating your spec and client access to use the `name` field of the body parameter.  If you can't change the client, just name it `"name": "body"`.

**Comment by webron** [comment]
Please reopen if needed.
