### ISSUE TITLE
Supporting IE8 more thoroughly or drop it

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-js#438]
There are a few little ecma 5 methods that are not supported by IE8 which we are using...
So far I've seen Array.isArray and Object.keys.

They can be fixed, but perhaps we need to use real browsers (perhaps *just* IE8) to test against.

1. I'm not a fan of testing in real browsers as it is slow and prone to mistakes, timeouts and errors.
What we can do is use the existing unit tests + browserify transform + karma + moch + selenium( they have packages for OSS).

2. On the other hand it would be nice if there were an IE8 linter, that scans for these non-supported methods and warns. I can look around for one, which would save us the hassle of real browser testing.

I'd like to support the latter option, the first being too much IMHO.

@mrhanlon, I know you've done some work integrating browser tests. Do you have any thoughts?
@webron your thoughts?

**Comment by webron** [comment]
@fehguy?

**Comment by whitlockjc** [comment]
Maybe now is the time to make IE9 the standard.  IE9 support ES5 and so do all other browsers.  If we do support IE8, we could/should lean on lodash like I started doing for the code I touched prior the the 2.1 release.  I do think we need to make a decision but I wanted to bring this up because I've been talking with @fehguy about the idea and he didn't turn it down yet.  ;)

**Comment by webron** [comment]
@whitlockjc, @ponelat and I discussed it over on IRC. We're definitely looking into dropping support for IE8, but need to check that first. If we find it's possible, we'll be more than happy to do that.

**Comment by Smolations** [comment]
+1 for dropping IE8 support.  :+1:

**Comment by fehguy** [comment]
Next minor version we will drop IE8 support.  I know, seems silly but it has been a requirement.

**Comment by fehguy** [comment]
Dropping it.
