### ISSUE TITLE
Default to application/json if it exists in produces

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-js#444]
We have inheritance regarding Accept header, but I would like to be more friendlier by default to `application/json` if possible.

##### The current resolution of Accept header..
- set as option in operation#execute 
- 1st item in operation.produces 
- 1st item in global.produces

Instead of defaulting to the 1st item in the produces array, we first try to default to `application/json` if it exists in the relative `produces`... like so...

##### The proposed resolution of Accept header..
- set as option in operation#execute
- application/json if in operation.produces 
- 1st item in operation.produces
- application/json if in global.produces 
- 1st item in global.produces)

Which would help make things less unpredictable, and easier to use if you're not concerned about the contentType. While still adhering to the spec and inheritance structure.

NOTE the ugly inclusion of requestContentType in this simple example... https://github.com/ponelat/swagger-js/commit/7423ec5cefd4a4058aa24b86f4ed30119313adf9

**Comment by webron** [comment]
Available in develop_2.0.
