### ISSUE TITLE
Authorization for the inital fetching of swagger spec file.

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-js#445]
Short of recreating a rough implementation of SwaggerAuthorization (yuck), there isn't much one can do to include authorization headers/tokens for the fetching the spec file.

> Authorizations only get applied after we fetch the spec file. Is it required that spec files are public?

I think the correct functionality should be so....
- The [authorization](https://github.com/swagger-api/swagger-js/blob/develop_2.0/lib/client.js#L131) option in SwaggerUi/SwaggerJS can contain a hash of `{ authName: authFunc(){} }`, 
- which will get appended to a fresh `SwaggerAuthorization` instance on initializing.

This happens before any HTTP executes are done, and so will apply to all. 

The only question is whether we should have a special authName for fetching the spec file (so that spec specific headers/tokens don't get sent with other requests). Or we rely on the security arrays inside the spec file to _NOT_ include our arbitrarily named auth (for fetching the spec file).

**Comment by fehguy** [comment]
@ponelat I don't think that's true--we should be able to set the authorization headers when initializing swagger-client.  I think that's a requirement for it to work correctly.

If it is the case, that's a regression in the client.

**Comment by ponelat** [comment]
@fehguy the only possible way to do so is via the `authorization` field. But we require it to be an instance of SwaggerAuthorization. Which the user has no way of creating, as it isn't exposed. Much simpler would be to create the instance from a hash, no?
ApiAuthorizationKey and such _are_ exposed by-the-way.

**Comment by fehguy** [comment]
I believe @whitlockjc changed it so you can call the constructor then the `initialize(args)` function, which allows you to add the authorizations at that point, which is _before_ calling to get the spec.

**Comment by ponelat** [comment]
You can, so long as you don't provide a `url` which would trigger `initialize` from within the constructor.
However the crux is still within `initialize` which is where SwaggerAuthorization is instantiated, _unless_ we define it as an option.... but we _must_ define it as an instance of SwaggerAuthorization which is the original argument.

**Comment by fehguy** [comment]
OK got it.  So the proper flow should be something like  this:

```
var client = new SwaggerClient(); // initializes swagger authorizations
client.authorizations.add(...);
client.initialize({url: url, opts: opts});
```

Or something like that...

**Comment by ponelat** [comment]
That would be much better than ....
```javascript
var client = new SwaggerClient({
   authorization: new window.SwaggerAuthorization(), // assuming we expose it
   url: false
});
client.clientAuthorization.add(...);
client.initialize({url: ... });
```

Perhaps better still? 
```javascript
var client = new SwaggerClient({
   authorizations: {  // will become a SwaggerAuthorization object
     api_key: new ApiKeyAuthorization(...),
   }.
   url: '...'
   success: ....
});
```

**Comment by whitlockjc** [comment]
I think this is already supported.  If you provided `options.authorizations`, those become the authorizations to always use.  (https://github.com/swagger-api/swagger-js/blob/develop_2.0/lib/client.js#L130)  So if you initialize with a `options.authorizations` and `options.url`, it **should** use those authorizations when retrieving the initial Swagger document identified in the URL.  Are you not seeing this?

**Comment by ponelat** [comment]
this is true... the original argument is about have to create an instance of SwaggerAuthorization... which isn't even exposed. It would be much easier to create a hash, that becomes a SwaggerAuthorization instance.

**Comment by whitlockjc** [comment]
Yes it is exposed.  :)  `SwaggerClient.SwaggerAuthorization`.  If you inspect the globally provided `SwaggerClient`, you'll see that it's there along with the `*Authorization` constructors themselves.

**Comment by whitlockjc** [comment]
I just validated this.  Here is my test:

```js
console.log(Object.keys(SwaggerClient)); // => ["ApiKeyAuthorization", "PasswordAuthorization", "CookieAuthorization", "SwaggerApi", "SwaggerClient"]
```

**Comment by ponelat** [comment]
So where is SwaggerAuthorization :D

**Comment by whitlockjc** [comment]
Ah, I do see that one isn't exposed.  Maybe it wasn't because it's really just a simple object or an oversight.  (https://github.com/swagger-api/swagger-js/blob/develop_2.0/lib/auth.js#L9)  We could easily expose it I guess.

**Comment by ponelat** [comment]
Yes indeed... But that would required more knowledge of the system.
Take a look again at this flow (the second one), and see if it isn't simpler ... https://github.com/swagger-api/swagger-js/issues/445#issuecomment-107972056

**Comment by whitlockjc** [comment]
Basically you're suggesting getting rid of the `SwaggerAuthorization` _container_ and allowing you, the caller of `SwaggerClient`, to provide _container_ yourself.  I like this idea a lot as `SwaggerAuthorization` really doesn't do much but setup a _container_ to have named authorizations.  One less moving part and a very simple interface to adhere to.

Of course, if you had to do this now, you could do it like this:

```js
var client = new SwaggerClient({
  authorizations: {
    authz: {  
      api_key: new ApiKeyAuthorization(...)
    }
  }.
  url: '...'
  success: ...
});
```

**Comment by ponelat** [comment]
Bingo! We can have a helper function that runs through the hash, making sure each one gets its chance to manipulate the request.
