### ISSUE TITLE
More robust handling of content types in SwaggerHTTP

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-js#449]
As per IRC chat, use a more robust approach to handling content types in SwaggerHTTP.

Currently we check the mime type before deciding to parse responses.
Refactor [isParseable](https://github.com/swagger-api/swagger-js/blob/develop_2.0/lib/http.js#L85) to check for leading '{' or ':' to indicate json/yaml. Which allows the inevitable issue of a lying server.

**Comment by fehguy** [comment]
done in #468
