### ISSUE TITLE
Creating unit tests in browser

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-js#450]
We've been using a selenium driver to test code in the browser, but this comes at the cost of complexity and unreliability.

Use a test runner and mocha to put tests in the browser and pull out the results. This is for unit testing only, as we cannot manipulate the browser itself, only the code therein. 

This is a library, so no end-to-end testing is actually needed as no user input actually takes place. Hence the move towards unit testing.

**Comment by mrhanlon** [comment]
@ponelat Thanks, I should have done this to begin with. I set up selenium because that's what swagger-ui was using, but you are correct, that is better for e2e testing.

**Comment by ponelat** [comment]
@mrhanlon We really appreciate the efforts that drove us here. I managed to port over the test your wrote, just let me know if I'm hitting the right spots :D

**Comment by webron** [comment]
This is done in develop_2.0.
