### ISSUE TITLE
Annoying console.log when produces is */*

### ISSUE THREAD

**Issue by joeheyming** [swagger-api/swagger-js#452]
See https://github.com/swagger-api/swagger-js/blob/3e498a5d0b0d7fc493f01eed2371c4fed8019813/lib/types/operation.js#L764

If this.produces is "&ast;/&ast;" this.produces.indexOf('application/json') fails...  Please fix this since I see this warning all the time:

server can't produce application/json
server can't produce application/json
server can't produce application/json
...
server can't produce application/json

**Comment by joeheyming** [comment]
Naive pull request: https://github.com/swagger-api/swagger-js/pull/454

**Comment by fehguy** [comment]
merged
