### ISSUE TITLE
Unexpected client generated for https://api.taxamo.com/swagger with 2.1.6-M2

### ISSUE THREAD

**Issue by zub2** [swagger-api/swagger-js#466]
Using swagger-client 2.1.6-M2 with https://api.taxamo.com/swagger results in a client instance that has keys like:
* `api/v1/transactions`
* `api/v1/transactions/{key}/invoice`
* `api/v1/verification`

This is strange and different from swagger-client 2.0.49. For example the method https://api.taxamo.com/swagger/ui/index.html#!/payments/capturePayment could be invoked like this in 2.0.49:
```javascript
   client.apis.payments.capturePayment(...)
```
but in 2.1.6-M2 I have to use:
```javascript
   client['api/v1/transactions/{key}/payments'].capturePayment(...)
```

Here is a testcase:
```javascript
var SwaggerClient = require('swagger-client');

function runTest(taxamo) {
	console.log('Generated swagger instance keys:');
	var keys = Object.keys(taxamo).sort();
	for (var i = 0; i < keys.length; i++)
		console.log("\t" + keys[i]);

	// this his how https://api.taxamo.com/swagger/ui/index.html#!/payments/capturePayment could be invoked
	// with swagger-client 2.0.49; this does not work with 2.1.6-M2
	console.log('typeof taxamo.apis.payments.capturePayment:');
	try {
		console.log(typeof taxamo.apis.payments.capturePayment);
	}
	catch (e) {
		console.log("\t" + e); // 2.1.6-M2 ends up here because taxamo.apis.payments is undefined
	}

	// but with 2.1.6-M2, capturePayment has moved here:
	console.log("typeof taxamo['api/v1/transactions/{key}/payments'].capturePayment:");
	console.log("\t" + typeof taxamo['api/v1/transactions/{key}/payments'].capturePayment);
}

var taxamo = new SwaggerClient({
	url: 'https://api.taxamo.com/swagger',
	success: function() {
		if (taxamo.ready === true)
			runTest(taxamo);
	}
});
```

On my box I get the following output:
```
Generated swagger instance keys:
	api/v1/dictionaries
	api/v1/geoip
	api/v1/settlement
	api/v1/stats
	api/v1/tax
	api/v1/transactions
	api/v1/transactions/{key}/invoice
	api/v1/transactions/{key}/payments
	api/v1/transactions/{key}/refunds
	api/v1/verification
	apis
	apisArray
	authSchemes
	authorizationScheme
	authorizations
	basePath
	clientAuthorizations
	consumes
	debug
	defaultErrorCallback
	defaultSuccessCallback
	definitions
	failure
	host
	info
	isBuilt
	isValid
	modelPropertyMacro
	models
	modelsArray
	options
	parameterMacro
	produces
	progress
	ready
	resourceCount
	sampleModels
	scheme
	schemes
	securityDefinitions
	spec
	success
	supportedSubmitMethods
	swaggerRequestHeaders
	swaggerVersion
	title
	url
	useJQuery
typeof taxamo.apis.payments.capturePayment:
	TypeError: Cannot read property 'capturePayment' of undefined
typeof taxamo['api/v1/transactions/{key}/payments'].capturePayment:
	function
```

**Comment by fehguy** [comment]
Hi,
First off, it'd be awesome if you can update your server/swagger specs to 2.0 :)  You'll have much more control over this.

Next, it looks like the way the `/resourcePath` is what's causing the problem.  In swagger 1.2, the notion of `resourcePath` is actually a path for the documentation, not necessarily the API.  So you could have your documentation at `/foo` but the actual api is called from `/bar/{userId}/baz`.  So the two are actually unrelated.

The swagger javascript client actually converts the spec from 1.2 to 2.0, and your former resource path, `api/v1/transactions/{key}/payments` is actually being converted into what is known as a `tag` in the 2.0 world.

This is confusing, and part of why we migrated to the new 2.0 structure.  Please reopen with any questions, but I suggest either updating your spec to 2.0, changing your resourcePath, or continuing with the current swagger-client that you're using.

**Comment by zub2** [comment]
Thanks for feedback. Too bad it's not my API.
When I use 2.0.49, I see a different issue. Should I report the bug, or is 2.0.x dead?

**Comment by webron** [comment]
"dead" is a bit extreme, but it is no longer under development.
