### ISSUE TITLE
auth broken from UI

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#472]
Somehow, this commit: https://github.com/ponelat/swagger-js/commit/d49c6130c39428389863933266f5f57baa198d79

is causing trouble for the swagger-ui.  It appears that an object is being added to the `auth` object which is failing the `_.apply()` function here:

https://github.com/swagger-api/swagger-js/blob/master/lib/auth.js#L62

@ponelat can you please look?

**Comment by whitlockjc** [comment]
This was not a problem with swagger-js but with swagger-ui.  Here was the fix:

https://github.com/swagger-api/swagger-ui/commit/a4124fba7cff89f05143f1f493175544ade909c9

**Comment by whitlockjc** [comment]
Let me clarify: swagger-js' recent change did cause the problem but the fix was in swagger-ui.
