### ISSUE TITLE
Support for JQuery style done/fail/always callbacks?

### ISSUE THREAD

**Issue by indolering** [swagger-api/swagger-js#479]
Checking error codes is a real pain, any chance we could get support for registering callbacks for success vs fails?

**Comment by ponelat** [comment]
Could you elaborate? 
Where are you looking for success/fail callbacks?

**Comment by indolering** [comment]
Whenever you call a function, like `client.user.getUserInfo({user:"indolering"})`.  There are a few ways to do it, but since you probably want to support promise/Fetch/.then syntax in the future, you could just drop in a second response object:

    client.user.getUserInfo(
      {user:"indolering"},
      {
        success: function(data, response){
          console.log("it worked, here is your data:", data)
        },
        failure: function(error, response){
          console.log("it failed!")
        },
        complete: function(){
          console.log("Time to clean up!")
        }
      }
    );

**Comment by ponelat** [comment]
I think Promise-like functionality is necessary. Especially for error checking. 
It's on the cards, and we'd welcome any PRs to that affect.

**Comment by indolering** [comment]
This is unrelated to Promises and should be closed if there is no interest in working on it.
