### ISSUE TITLE
CookieAuthorization is outdated

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-js#483]
The auth method CookieAuthorizations is outdated (ie: it don't work).
Also we need to (or would like to) document the CORs restrictions around cookies.

To sum up cookies in browsers...

> A cookie is key/value pair that gets sent with requests and is found in responses.

Thats all good and well for normal HTTP requests..

For AJAX (ie XHR) requests.
- Cookies will _NOT_ be sent unless the `xhr.withCredentials = true` is set
- Cookies will _NOT_ be sent unless the server has the `Access-Control-Allow-Credentials: true' header and value in the **preflight** request.
- For Internet Explorer < IE10, which uses the XDomainRequest (not XHR) _NO_ cookies will be sent.
- Internet Explorer >= 10 Deprecates XDomainRequest in favour of XHR which allows cookies.

If any information here is incorrect, please advise! I'm no CORs expert.

Sources: 
http://blogs.msdn.com/b/ieinternals/archive/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds.aspx
http://www.w3.org/TR/cors/#access-control-allow-credentials-response-header

**Comment by fehguy** [comment]
OK since cookies are not supported officially in the spec, I'm going to close this out.

**Comment by blop** [comment]
Why closed?

**Comment by fehguy** [comment]
blop: https://github.com/swagger-api/swagger-js/issues/483#issuecomment-138004492

**Comment by blop** [comment]
"not supported officially in the spec", which "spec" are you referring to ?

**Comment by webron** [comment]
The Swagger/OpenAPI specification.
