### ISSUE TITLE
The 'label' tag conflicts with a SwaggerClient operation function/property name.  Use 'client.apis._label' instead of 'client.apis.label'.

### ISSUE THREAD

**Issue by martinhbramwell** [swagger-api/swagger-js#484]
My swagger input file is generated from a third-party REST API, and "label" is one of the principal entities of their API.  I am powerless to influence their already widely used API specification, but I am trying to create 100% compatible client and server interfaces.  Now this issue makes that goal impossible or forces me to use something other than Swagger.

If this is an easily repairable problem I can do it myself, but I have no way of knowing whether it is easy, hard or impossible.

If it is impossible to alter it, then it would seem that SwaggerClient suffers from a fundamental namespace defect.

If it is not impossible to do it, then it is really a very heavy-handed design decision to prohibit REST API developers from using a normal English language word in their interface design.

Why cannot SwaggerClient prefix all **its own** "operation function/property names" with underscore, and leave API developers the freedom to not worry about prohibitions on legitimate terminology?

**Comment by fehguy** [comment]
OK this is a fairly old issue but the solution is still the same.

You can use swagger's shortcuts--via function prototypes--or alternative methods which behave consistently.  For example:

this:
```
api.pet
```

is the same thing as this:
```
api.apis["pet"]
```

and this:
```
api.pet.findPetsByStatus(...)
```

is the same as this:
```
api.apis["pet"].operations["findPetsByStatus"]
```

In short, you can use the human-friendly shortcut bindings (which have some obvious naming constraints) or the consistent hash lookup functions.  We chose to support both for human friendly interaction in a repl with tab-complete.
