### ISSUE TITLE
Regression for SwaggerAuthorizations

### ISSUE THREAD

**Issue by Smolations** [swagger-api/swagger-js#487]
I was noticing weirdness when applying headers to requests, so I dug in. What I found was that, 8 days ago, a commit was added to master in `auth.js` that results in only a single header being set if 1 or more are added:

[The regression is here, in this block:](https://github.com/swagger-api/swagger-js/commit/d49c6130c39428389863933266f5f57baa198d79#diff-f82db47d45e5a0dba4628b19ccb5eb30R111)
```
_.each(this.authz, function (auth, authName) {
  if(applyAll || _.includes(flattenedSecurities, authName)) {
    status = status || !!auth.apply(obj); // logical ORs regarding status
  }
});
```

The result of this shorter code block (when compared to the code it replaced) is that, if `status == true` for  any headers, any additional headers won;t get set because the logical OR operation takes that truth value and skips calling `auth.apply(obj)`, which results in the lack of those additional headers being sent.

**Comment by ponelat** [comment]
Thanks for spotting this...
Looks like the ordering is wrong, should be..
```javascript
status = !!auth.apply(obj) || status; // ensures auth.apply gets applied each time.
```

**Comment by agskill** [comment]
Hello,
I use swashbuckle (last version) and i have the same problem. Do these changes have been added please ?
when I look at the source code file "swagger-ui-js". I do not see the change.
Thanks

**Comment by webron** [comment]
Not entirely sure which version of the ui Swashbuckle uses. Can you check the version at the top of the swagger-ui.js file?

**Comment by agskill** [comment]
Hello @webron 
Thanks for your response. I use the version v2.1.0. Is it good ?

**Comment by webron** [comment]
The fix is included in 2.1.2. I'd suggest trying to use the version from this repo, point it at your definition, and see if you still experience the problem.

**Comment by agskill** [comment]
@webron can you tell me how to do this , please ? Is like that ?
```html
<script src='https://github.com/swagger-api/swagger-ui/blob/master/dist/swagger-ui.js' type='text/javascript'></script>
```

**Comment by webron** [comment]
Just clone this repository, go to the `/dist` directory and open the `index.html. At the top bar input the URL based on the structure as defined at https://github.com/domaindrivendev/Swashbuckle#getting-started and click explore.

**Comment by agskill** [comment]
@webron 
Sorry but I have not managed to do this. In fact , I use "sawshbuckle.core"  in my web api (hosted with owin) with a custom "index.html". Is it necessary that I generates a new version of sawshbuckle.core contains the correction ?
Thanks

**Comment by webron** [comment]
I don't know. Regardless of what you get from swashbuckle, you can use swagger-ui externally and independently, so just try it.

**Comment by agskill** [comment]
OK thanks for your help ... i will see
