### ISSUE TITLE
Oauth authetnications doesn't work if there is one one scope in spec

### ISSUE THREAD

**Issue by machowski** [swagger-api/swagger-js#490]
spec-converter.js SwaggerSpecConverter.prototype.securityDefinitions
there is code

``` javascript
     else if(definition.type === 'oauth2') {
        var existingScopes = definition.scopes || [];
        var scopes = {};
        var i;
        for(i in existingScopes) {
          var scope = existingScopes[i];
          scopes[scope.scope] = scope.description;
        }
        securityDefinition.type = 'oauth2';
        if(i > 0) {
          securityDefinition.scopes = scopes;
        }
```

so If there is only one scope 'i' has value 0 ("0" to be precise as for some reasons it's iterated by 'in' loop) and  securityDefinition.scopes is never set.
As result there are no scopes when clicking authorise button.

**Comment by shockey** [comment]
Closing; this issue only applies to 2.x, which is no longer under development.

Thanks for the report, @machowski!
