### ISSUE TITLE
Extract 1.2 to 2.0 converter into separate library.

### ISSUE THREAD

**Issue by IvanGoncharov** [swagger-api/swagger-js#492]
Your [converter](https://github.com/swagger-api/swagger-js/blob/master/lib/spec-converter.js) is stand alone file without any dependencies on rest of the library.
Also there are very similar library [swagger-converter](https://github.com/apigee-127/swagger-converter) with only minor differences in API and functionality.

Reliable `1.2` to `2.0`  converter is crucial piece that should allow library owners switch to `2.0` and still have backward-compatible with `1.2`.
Your `spec-converter` is used in `Swagger-UI` that mean it really well tested and covering all corner cases.

Ideal solution will be extract `spec-converter` into separate library and try unify effort with `swagger-converter` library.
I also simular issue  apigee-127/swagger-converter/issues/26

P.S. I really interested in reliable converter and can do all required work as series of PR.

**Comment by fehguy** [comment]
Going to leave this alone
