### ISSUE TITLE
Set BOTH formData and path parameters in client for PUT request

### ISSUE THREAD

**Issue by gconst02** [swagger-api/swagger-js#495]
The example below requires 3 parameters:
* `ResetPassword` is a **path** parameter
* `password` is a **formData** parameter
* `repeat_password` is a **formData** parameter
```
swagger_client.apis.users.resetPassword(<DATA>, 
{responseContentType: 'application/json'},
function(response) {
    // success
}, function(err) {
    // failure
}); 
```
How can I set the **<DATA>** to make this work?
I was not able to set the data properly or there is a bug.

**Comment by ponelat** [comment]
@gconst02 you can put both types as parameter data, swagger-js will pluck out the 'path' params and make sure the URL is correct.

so it should work, and if it isn't you can always see what _would_ be sent, by mocking it.
```javascript
swagger_client.apis.users.resetPassword({
  ResetPassword: 'something',
  password: 'something',
  repeat_password: 'same something'
//....
```

to mock just add the option, `mock: true`
```javascript
var mockRequest = swagger_client.apis.users.resetPassword({ 
  { /* data */} , {
  responseContentType: 'application/json',
  mock: true
});
console.log('mockRequest', mockRequest); // to have a look

**Comment by gconst02** [comment]
Problem solved. Thanks!
