### ISSUE TITLE
The `asCurl` method doesn't allow to set content type for response and request

### ISSUE THREAD

**Issue by iushankin** [swagger-api/swagger-js#504]
This method doesn't allow to set custom content type:
```
Operation.prototype.asCurl = function (args) {
  var obj = this.execute(args, {mock: true});
```

https://github.com/swagger-api/swagger-js/blob/develop_2.0/lib/types/operation.js#L810-L811

**Comment by fehguy** [comment]
this was handled in https://github.com/swagger-api/swagger-js/pull/505
