### ISSUE TITLE
Enum with null entry triggers "too much recursion" error

### ISSUE THREAD

**Issue by wking** [swagger-api/swagger-js#507]
If I point swagger-ui v2.1.0 at the following spec:

    {
      "swagger": "2.0",
      "definitions": {
        "pet": {
          "type": "object",
          "properties": {
            "species": {
              "type": "string",
              "enum": [
                null,
                "cat",
                "dog"
              ]
            }
          }
        }
      }
    }

I get a `too much recursion` error pointing at `resolveAllOf`.  The JSON Schema spec [says for enums][1]:

> Elements in the array MAY be of any type, including null. 

[1]: http://json-schema.org/latest/json-schema-validation.html#anchor77

**Comment by webron** [comment]
`null` is not a valid value in Swagger. We don't support full JSON Schema. Please follow https://github.com/swagger-api/swagger-spec/issues/229.

**Comment by wking** [comment]
On Thu, Jun 25, 2015 at 09:56:07AM -0700, Ron wrote:
> `null` is not a valid value in Swagger. We don't support full JSON
> Schema. Please follow
> https://github.com/swagger-api/swagger-spec/issues/229.

I'm clear on this for Swagger 2.0 now, and I just submitted #508 here
to make it easier for other folks to find this information.  Between
swagger-api/swagger-spec#229 and #508, I think this is closable.
