### ISSUE TITLE
Support node standard callbacks

### ISSUE THREAD

**Issue by tommymessbauer** [swagger-api/swagger-js#524]
Please consider support for node's standard callback signature.  It would make it easier to integrate with async (my current need) or a promise library like q, bluebird, or ES6 promises.

This syntax is a bit dated and means that using this client requires wrapper code.
```
client.getSomething({ id: '123' }, function(thing), {
// do something
}, 
function(err) {
// do something
});
```

Would prefer b/c it just works with async and promisify() operations in the promises libs.
```
client.getSomething({ id: '123' }, function(err, thing), {
// do something
});
```

**Comment by fehguy** [comment]
we now support promises, which is better (IMHO) than the conventions for the standard callback signature.  The reason we didn't support it previously was because of variable args.

**Comment by tommymessbauer** [comment]
Promises are fine too.
