### ISSUE TITLE
Doesn't support loading YAML from URL source.

### ISSUE THREAD

**Issue by NicholasRBowers** [swagger-api/swagger-js#525]
When a request and subsequent response are created (line 29,710), we assume that the response is coming is formatted in JSON, even though we're now supporting YAML.

`err = new Error('Parser is unable to parse the response');` is triggered when creating the Response object.

If the URL parameter points to a YAML file, it's contents are likely to be transferred with the header `application/json`, because YAML MIME types are not very common.

```
request.parse = {
  'application/x-www-form-urlencoded': parseString,
  'application/json': JSON.parse
};
```

Here, we only allow for processing of two MIME types, so we're kind of stuck.  I would add cases for YAML MIME types and use the already implemented `js-yaml` plugin to process these contents.

This is important because currently our `url` parameter can only consume JSON, while the `spec` contents can ONLY be sent in JSON.  Without this change, I'm unsure of how SwaggerUI can support loading and parsing YAML files?

**Comment by ponelat** [comment]
@NicholasRBowers 
Thanks for looking into the mime types.
What we ended up doing is to try and parse the contents of the response, regardless of mime type (as @fehguy says... servers lie).
While this is fine for client side, there might be implications when requesting the file (if we ask for a yaml file, but have Accept: json). Haven't bumped into it yet, but prevention is better than the cure :wink:

**Comment by mohsen1** [comment]
@ponelat Since JSON is YAML you don't need to do any detection for YAML vs. JSON. Always use YAML for parsing, it will work with JSON content also.

**Comment by ponelat** [comment]
@mohsen1 thanks, that's what we do (use js-yaml for everything that is)
I believe that @NicholasRBowers is referring to the Accept header sent? While this won't affect the client (we parse whatever, see what sticks) I'm not sure if there are any implications for the server.
For example, if I send `Accept: application/json` to the server, but I want a yaml file ... the server has the right to send me json, no? Probably won't happen (custom mime types on a swagger spec? too much effort ;) )

**Comment by mohsen1** [comment]
I think you should provide a better Accept header. For example Chrome send  this Accept header:

```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
```

It prefers `text/html` but if server can't do that it can also work with `application/xhtml`.

So for Swagger UI `application/yaml,application/json` would be a fair Accept header. Although [nobody knows](http://stackoverflow.com/questions/332129/yaml-mime-type) what is the correct mime type for YAML!

**Comment by ponelat** [comment]
Hmm, is this for a swagger.json file? It should have `Accept: application/json` when requesting the spec... the header (I believe) is the default header for Chrome requesting a page.

We have default Accept header for requesting specs (swagger.json)...
https://github.com/swagger-api/swagger-js/blob/master/lib/client.js#L118

I can't believe know-one has settled on a mime for yaml... feels like the dark ages :wink: Thanks for the link

**Comment by mohsen1** [comment]
If you add YAML first in list of accepted headers and **if** server is honoring headers right, it will send you YAML if it's available otherwise it will send JSON.

I would say change that line to :+1: 

``js
  this.swaggerRequestHeaders = options.swaggerRequestHeaders || 'application/x-yaml,application/json;charset=utf-8,*/*';
```

**Comment by NicholasRBowers** [comment]
Hey, no, sorry @ponelat I was not referring to MIME types sent to or from any server. The `request.parse` object is used by the request object to decide which parser to use for the incoming content.

As you can see, if a server sends something to your server with an `application/json` header (many frameworks do, and YAML MIME types aren't solidified yet), it will use JSON.parse engine to parse the contents.

My suggestion is to change this to `js-yaml` to parse `application/json`, `application/x-yaml`, and `text/yaml` MIME types.

**Comment by ponelat** [comment]
@NicholasRBowers so, it would seem I mis-understood.
I had a look around for the code you wanted to change, and realized it's not ours... its a 3rd party lib called superagent (http lib)

It has it's own parsing strategy, but it's based on the incoming mime (Content-Type: some/mime)
However, we are by passing that - for the reasons you suggest ( by using req.buffer(false) or something)


Can you validate your yaml ? Try using [swagger-tools](https://www.npmjs.com/package/swagger-tools)

**Comment by NicholasRBowers** [comment]
@ponelat 

Hmm, it definitely didn't bypass it in my situation.  And my YAML was validated and built using the Swagger editor (downloaded the JSON and YAML afterwards as well).

I think the issue is this line here:

```
Response.prototype.parseBody = function(str){
  var parse = request.parse[this.type];
  return parse && str && (str.length || str instanceof Object)
    ? parse(str)
    : null;
};
```

`request.parse` returns `JSON.parse`.  So `parse(str)` uses `JSON.parse` - meaning that when we use the `parseBody` method in the `Response` constructor we are NOT using `js-yaml`.

Perhaps I'm mistaken?

**Comment by NicholasRBowers** [comment]
Perhaps this is still part of the `superagent` lib, but this code is definitely being executed, and therefore not bypassed. :/

**Comment by ponelat** [comment]
If it's not getting bypassed, it could be that the server is sending `Content-Type: application/json` . Could you confirm that? You can do so by using the network tab in your browser's debugging tools.

If it isn't working for you then something is wrong :smile:

Could you send some some more details? Like a minimal failing example if possible (as I can load a yaml file from swagger-ui, in the URL bar on top)

**Comment by fehguy** [comment]
Hi guys, this is an old issue and I'd like to figure it out or close it.

The issue says, loading YAML doesn't work, but we test it and know it does.  Is the real issue that the client can't parse YAML when the server says it's JSON but it's really YAML?  Please clarify @NicholasRBowers !  Thank you

**Comment by fehguy** [comment]
Please reopen if still an issue.
