### ISSUE TITLE
"collectionFormat": "multi" does not work with post parameter in formData

### ISSUE THREAD

**Issue by birbird** [swagger-api/swagger-js#529]
I have tried master and develop_2.0 branch, just use the dist directly.
It works well with query parameter, but not with post formData

This is my swagger
```
                    {
                        "name": "circle[member_profile_itmes]",
                        "in": "formData",
                        "type": "array",
                        "items": {
                            "type": "string",
                        },
                        "collectionFormat": "multi"
                    }
```
And I input multi lines in the textarea, they are just joined with a comma.

**Comment by glen-84** [comment]
I have the same issue, using PATCH.

**Comment by birbird** [comment]
I made a pull request #537 to fix this

**Comment by jeevanrd** [comment]
I have the same issue. Any idea on push date?
