### ISSUE TITLE
Please document how to handle http error responses

### ISSUE THREAD

**Issue by defcronyke** [swagger-api/swagger-js#531]
If the API server returns some error code instead of 200 OK, the default behaviour is to print a large Javascript Object of the response to the console. Most times I would like to handle the error condition instead, but couldn't find info on how to do so.

The way to handle the error condition is to pass in a callback as the fourth parameter to an API method call, like this:

swagger.someResource.someMethod({}, {}, successCallback, errorCallback);

Could you please document this error handling somewhere obvious, because it stumped me for a while and I had to ask on IRC about it.

**Comment by sl2** [comment]
+1

**Comment by fehguy** [comment]
updated the readme
