### ISSUE TITLE
allow override of `host` and `basePath`

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#532]
Once swagger-client is loaded, you cannot easily override the `host` or `basePath` values as they are copied to each operation.  While you can currently iterate over each api + host, it's a pain.

**Comment by jifka** [comment]
Bump - could someone explain how to use this feature to change the URL/basePath on the fly?

I've tried creating a SwaggerClient and called setHost and setBasePath and the UI still uses the url/path defined in the swagger.json.

**Comment by fehguy** [comment]
OK @jifka it sounds like you're trying to override those in the context of the UI.  If that's true, you'll need to get the `swagger-js` instance that the UI is using, and call it from there.  For example, I open http://petstore.swagger.io and enter this in the console:

```js
window.swaggerUi.api.setBasePath('/v3');
```

The calls will now reflect that `basePath`.

**Comment by jifka** [comment]
I'm actually more interested in setting the URL to execute calls against a different server, instead of the URL defined in the yaml/json definition of the API.  This is supposed to be thru the 'host' but doesn't seem to work.

**Comment by fehguy** [comment]
Hi, I'm confused.  by setting the basePath like I suggested, you can load the swagger file from one location and execute methods against a different one, just as if you had set the `host` parameter.  It does work, so if you can share more info we can help troubleshoot it.

**Comment by jifka** [comment]
Like the OP stated, I'm also looking for a way to dynamically set the host URL without reloading the API definition yaml/jason.

I now see that there's a function on swaggerUi.api.setHost() that will change the endpoint on the fly so I'll need to update the UI to allow users to select their own host.

**Comment by fehguy** [comment]
So my suggestion from https://github.com/swagger-api/swagger-js/issues/532#issuecomment-245409602 should do just that.  You can let the user choose which host and trigger logic like what I mentioned.  Then you can dynamically target different hosts as needed

**Comment by pcontezini** [comment]
Hi.
I'm trying to create a select box so my user can choose between production and test environment.
My code looks like this:

function addBaseUrl() {
              var url = $('#input_baseUrl').val();
              if (url && url.trim() != "") {
                      window.swaggerUi.api.setHost(url);
                      log("host: " + url);
              }

      }

$('#input_baseUrl').change(addBaseUrl);

But it is simply not working, when I inspect the swaggerUi object, they are all with my new host, but when I try to do the call, it always calls the original host. I've trying calling swaggerUi.api.build() and the returned object also seems fine.

I'm thinking this is a bug, so i'm reporting it here.

I'm attaching the full index.html file, maybe it helps.

[index.txt](https://github.com/swagger-api/swagger-js/files/677076/index.txt)

**Comment by dnascimento** [comment]
@pcontezini  can you share the link to your branch of Swagger UI?

**Comment by pcontezini** [comment]
@dnascimento Just imported, here it is: [https://github.com/asaasdev/swagger-ui](https://github.com/asaasdev/swagger-ui)

**Comment by AlwaysAbhl001** [comment]
```
const ui = SwaggerUIBundle({
                    url: `url1` ,
                    dom_id: '#swagger-ui-1',
                    presets: [
                  SwaggerUIBundle.presets.apis,
                  // yay ES6 modules ↘
                  Array.isArray(SwaggerUIStandalonePreset) ? SwaggerUIStandalonePreset : SwaggerUIStandalonePreset.default
                    ],
                    plugins: [
                      SwaggerUIBundle.plugins.DownloadUrl
                    ],

                    layout: "StandaloneLayout"

                })
```

how could i achieve this setBasePath/setHost functionality here..

**Comment by webron** [comment]
It's not supported in the new client. Please file a new ticket.

**Comment by char0n** [comment]
Addressing this issue should now be possible purely from `swagger-ui` by [UrlMutatorPlugin](https://github.com/swagger-api/swagger-ui/issues/5981).

**Comment by Padmahas** [comment]
> OK @jifka it sounds like you're trying to override those in the context of the UI. If that's true, you'll need to get the `swagger-js` instance that the UI is using, and call it from there. For example, I open http://petstore.swagger.io and enter this in the console:
> 
> ```js
> window.swaggerUi.api.setBasePath('/v3');
> ```
> 
> The calls will now reflect that `basePath`.

Hi @fehguy , which console do you mean? Browser console? Which will show up when F12 key is pressed?
I opened the URL you gave and executed the command you showed, to change the basePath, but I'm getting the below error "Uncaught TypeError: Cannot read property 'api' of undefined
    at <anonymous>:1:18
(anonymous) @ VM51:1"

I think I'm executing this in wrong console. which console do you mean?
