### ISSUE TITLE
Nested schemas do not show description in swagger-ui

### ISSUE THREAD

**Issue by nickg415** [swagger-api/swagger-js#533]
When working with swagger-ui, I've found that nested schemas do not show the description. While I found the issue in swagger ui, I believe the actual fix is in swagger-js. I was able to track this down in swagger-ui.js to the resolveSchema helper function.

This function is called within the processModel function (which is within the schemaToHTML function in swagger-client.js). The problem occurs at line 2432 in swagger-client.js:

```javascript
// Resolve the schema (Handle nested schemas)
cProperty = helpers.resolveSchema(cProperty);
```

I temporarily put in a couple of console.log statements to print the before and after values of cProperty:

```javascript

console.log("Property Before: ", cProperty);

// Resolve the schema (Handle nested schemas)
cProperty = helpers.resolveSchema(cProperty);

console.log("Property After: ", cProperty);

```

The first console.log gives the following:

```
description: "Some description here"
schema: Object
  $ref: "#/definitions/ModelB"
  __proto__: Object
__proto__: Object
```

where the second log after the resolveSchema gives this:

```
Object {$ref: "#/definitions/ModelB"}
```

Later on in processModel, the following is what shows the description:

```javascript
if (!_.isUndefined(cProperty.description)) {
  html += ': ' + '<span class="propDesc">' + cProperty.description + '</span>';
}
```

Since the description property is stripped off, it sees undefined, and as a result does not show the description. Not sure if there was a reason to strip all properties off here or not, or if only schema needed to be stripped off, but I managed to fix this by making resolveSchema reappend any properties in the old object that isn't named 'schema':

```javascript
var resolveSchema = module.exports.resolveSchema = function (schema) {
  var resolvedSchema = schema;

  if (_.isPlainObject(schema.schema)) {
    resolvedSchema = resolveSchema(schema.schema);

    for(var key in schema) {
      if(key != "schema") {
        resolvedSchema[key] = schema[key];
      }
    }
  }

  return resolvedSchema;
};
```

I did notice that resolveSchema is used in a few other places, so not sure if this is the proper fix, but if it is, or close to anyway, I would be happy to contribute a pull request.

I should also mention that the project is using the 1.2 swagger spec. An example json being returned by the api is as follows (only including what I believe is relavent for brevity):

```
{
	"swaggerVersion": "1.2",
	"models" : {
	  "ModelA" : {
	    "description" : "",
	    "id" : "ModelA",
	    "properties" : {
	      "modelB" : {
		"description" : "Some description here...",
		"required" : true,
		"type" : "ModelB"
	      }
	    }
	  },
	  "ModelB" : {
	    //omitted for brevity...
	  }
	}
}
```

I am new to swagger, so if I am misunderstanding something or missing anything in my post, please let me know.

**Comment by Lattyware** [comment]
I am also seeing this bug, and it's a pretty big deal as it strips descriptions off half the properties in the models.

See [this simple example](https://gist.github.com/Lattyware/91bb2c2dbc877ce541ca), where Test.test doesn't show the description because it's type is Test2:

![image](https://cloud.githubusercontent.com/assets/1239492/10642487/d1bb4874-7815-11e5-817b-349cb6445f2f.png)

Both properties should have the description 'test'.

**Comment by fehguy** [comment]
Thanks @nickg415 and @Lattyware for the input on this.  @whitlockjc can you please look, as you wrote this helper?

**Comment by whitlockjc** [comment]
All that `helpers.resolveSchema` does is recurse until it finds the *final* schema.  The reason for this is for Swagger 2.0, you can have properties/responses whose `schema` property is the **real** schema to be used, not the property/response definition itself.  The only way something could be stripped is if the compatibility layer for 1.2->2.0 is doing something weird.

I'll look into it but I don't see how the code mentioned is involved.

**Comment by whitlockjc** [comment]
I've figured this out.  Basically, the compatibility layer is taking 1.2 models and creating weird 2.0 representations for them.  Take the given example for `ModelA`:

```js
{
  id: 'ModelA',
  description: 'ModelA',
  properties: {
    modelB: {
      description: 'modelB',
      required: true,
      type: 'ModelB'
    }
  }
}
```

I would expect the following compatibility model definition to be created:

```js
{
  description: 'ModelA',
  properties: {
    modelB: {
      $ref: '#/definitions/ModelB'
    }
  },
  required: ['modelB']
}
```

But instead we get this:

```js
{
  "schema": {
    "$ref": "#/definitions/ModelB"
  },
  "description": "ModelB"
}
```

*(This isn't even a valid model definition.  Is this suppose to be some meta-model?)*

So what happens is we see the `schema` property and get the *real* schema and use it.  I can fix this but this was caused by the compatibility code creating a model schema that is not a valid 2.0 model schema.  The code is working as expected but we need to update it to work around this case.

**Comment by whitlockjc** [comment]
I have fixed this in #597.  It has unit tests showing that the mock signature code now will render property descriptions for Swagger 1.2 model properties that are *references*.

**Comment by satyamallya** [comment]
Do you have a petstore example where the description of each variable shows up in swagger UI. I am having the problem where swagger is not showing the description that I have entered in the json file for each request parameter.

Thanks

**Comment by fehguy** [comment]
@satyamallya see here:

![image](https://cloud.githubusercontent.com/assets/249413/12838031/7c5efb3a-cb7d-11e5-9866-848374489d2a.png)

which comes from here:

http://petstore.swagger.io/v2/swagger.json

**Comment by vlad2** [comment]
I think this is still open, as I don't see any description for a nested object. (In Swagger UI 3.10.0)

It may be related to this: https://stackoverflow.com/questions/43003348/swagger-add-description-with-ref

My object looks like this:

{
  "swagger": "2.0",
...
    "properties": {
        "customerTimezone": {
          "description": "Customer timezone; we use this for squirrels",
          "allowEmptyValue": false,
          "$ref": "#/definitions/ZoneId"
        },
...

**Comment by ericraymond** [comment]
+1

**Comment by bwross** [comment]
I'm on 2.0.8 and this is still happening. Found a temporary workaround by removing the `@Schema` from the nested class, but that's not ideal.

**Comment by suhasbhatta** [comment]
> ~@Kadams64, we're no longer working on or supporting the 2.x series of the UI - you'll need to upgrade to v3 in order to get support in the issue tracker.~
> 
> Oops, that is v3. Please open a new issue 😄

Anyone created issue in v3 (Swagger 3.0) ?
