### ISSUE TITLE
Better error description when schema mentioned $ref doesn't exist

### ISSUE THREAD

**Issue by KrzysztofMadejski** [swagger-api/swagger-js#540]
I'm getting an exception running swagger-ui, but it originates from this project.

I'm getting `swagger-ui.js:2950 Uncaught TypeError: Cannot read property 'definition' of undefined` thrown on https://github.com/swagger-api/swagger-js/blob/master/lib/schema-markup.js#L221

It would be a lot better if an exception was thrown just after https://github.com/swagger-api/swagger-js/blob/master/lib/schema-markup.js#L213 if no schema definition was found
```javascript
if(typeof schema.$ref === 'string') {
    name = Helpers.simpleRef(schema.$ref);
    if (typeof models[name] === 'undefined') {
      throw 'Couldn\'t find model ' + schema.$ref;
    }
    schema = models[name];
  }
```

Suprisingly in https://github.com/swagger-api/swagger-ui/releases/tag/v2.1.0-M2 
it was working ok (almost - it would be nice if specyfing title wouldn't kill displaying referenced schema) 
giving me 
![mpapi-bug1](https://cloud.githubusercontent.com/assets/849975/8938354/7417a234-355e-11e5-839e-6c45cac0b09b.png)

when I had:
```
"Dataobject": {
          "type": "array",
          "items": {
            "$ref": "https://api-v3.mojepanstwo.pl/schemas/dane/dataobject.json"
          }
        },
```

and 
![mpapi-bug2](https://cloud.githubusercontent.com/assets/849975/8938357/7b555ae6-355e-11e5-92e8-450fc2419914.png)

when I had:
```
"Dataobject": {
          "type": "array",
          "items": {
            "title": "Dataobject-title",
            "$ref": "https://api-v3.mojepanstwo.pl/schemas/dane/dataobject.json"
          }
        },
```

**Comment by fehguy** [comment]
OK so I actually don't agree that we should throw an exception when a model can't be found.  It will stop processing and make a bad user experience.  I will open an issue in the UI to show something more helpful, perhaps a mouse-over with details.
