### ISSUE TITLE
A model with an attribute of "nodeName" will fail in the example JSON generation step

### ISSUE THREAD

**Issue by lmprice** [swagger-api/swagger-js#546]
We are currently using v2.1.1 with Swagger-UI and Swagger-Core. We have a few models that contain attributes with the name "nodeName". Unfortunately, these models cannot be changed.

When using Swagger-UI, it's been necessary to remove a particular block from the anonymous function: Operation.prototype.getModelSampleJSON in swagger-api/swagger-js/master/browser/swagger-client.js for the UI to load.
```
if (t.nodeName) {
        var xmlString = new XMLSerializer().serializeToString(t);

        return this.formatXml(xmlString);
}
```

Is there a clean workaround for this, or a way to keep the generation from breaking?

**Comment by fehguy** [comment]
I think that's a bug.  We'll have to escape the name, just like we do for api and client tags.

**Comment by akaravashkin** [comment]
I have the same issue. I have to remove this block too. @fehguy, do you have any plans to fix it in nearest future?

**Comment by fehguy** [comment]
Hi, I'm unable to reproduce this, but it could be because you're on 2.1.1 where swagger-js is now on 2.1.5.  Please see https://github.com/swagger-api/swagger-js/commit/19bada362f16df911277cc7836e3491b182908ae for a test, and reopen this if you still have an issue.

**Comment by akaravashkin** [comment]
I have tried v2.1.5 and still have the issue. It fails on 

```javascript
if (t.nodeName) {
   var xmlString = new XMLSerializer().serializeToString(t);
   ...
```

`Uncaught TypeError: Failed to execute 'serializeToString' on 'XMLSerializer': parameter 1 is not of type 'Node'.`

My json piece is:

```
definitions: {
  Call: {
    properties: {
      nodeName: {
        type: "string"
      }
    }
  }
}
```

I guess your test [19bada3](https://github.com/swagger-api/swagger-js/commit/19bada362f16df911277cc7836e3491b182908ae) does not correspond to issue. createJSONSample() passes good, but problem is XMLSerializer applying to json.

P.S. Sorry, I don't know how to reopen this issue.
