### ISSUE TITLE
Non-200 errors should be handled by the normal Model system.

### ISSUE THREAD

**Issue by AmandaCameron** [swagger-api/swagger-js#549]
I've got some code that spits out a 404 for invalid users, or their objects, with additional details in the API for if the user is invalid, or the object you're trying to get from that user is.

The result is that `result.obj` in the error callback of swagger-js is not a parsed version of the specified error object in the spec.

I can work around this by using `JSON.parse(result.data)` instead, however this feels like a non-start for me for production use.

**Comment by dustinsmith1024** [comment]
I was wondering this too.  Are error descriptions ignored by the client and only used for the documentation right now?

**Comment by fehguy** [comment]
It may be good if we attempt to put the `obj` as a parsed object in the error payload, yes.
