### ISSUE TITLE
swagger does not support referencing main schema object

### ISSUE THREAD

**Issue by bjne** [swagger-api/swagger-js#570]
I am unable to reference just a document in its full, seems I need to reference a
spesific deinition or property. It should support just referencing schema.json, and
also eventually with id's

**Comment by fehguy** [comment]
for example: `/foo/bar#myModel` works, but `/foo/bar` does not

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-js/commit/4eb41cc54be90f38b19dfd9be8f32397929db768
