### ISSUE TITLE
Swagger does not resolve $ref's from external schema

### ISSUE THREAD

**Issue by bjne** [swagger-api/swagger-js#573]
If I point to a external schema definition, and the schema references a #/definitions/some_var
that in included in the schema, swagger-ui shows the definition as blank {}

**Comment by bjne** [comment]
Some details:

if I do schema, $ref: "http://some.external.json#/definitions/myobject"  from main.yaml .... and myobject has say "foo":{"$ref":"#/definitions/my_foo"}
then foo will show as {} in ui.. even tho my_foo is completely resolvable in external schema

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-js/commit/f934ceb4f38ea340679f0bf8a3c38406c492de94
