### ISSUE TITLE
Promise Wrapper Package

### ISSUE THREAD

**Issue by toddtreece** [swagger-api/swagger-js#576]
I wrote a `swagger-client` ES6 promise wrapper for a project a few months ago, and just moved it into it's own package for use in another project now that node v4.0.0 is out. I see that there also a new pull req (#554) that adds promise support directly to this package, but I thought I would link to my package just in case it helps anyone that is looking for API operations to return ES6 promises.

https://www.npmjs.com/package/swagger-client-promises

**Comment by fehguy** [comment]
hi, as of https://github.com/swagger-api/swagger-js/commit/572dd92898a792df00f02b539b98509b4a139bca promises are supported natively in the library.
