### ISSUE TITLE
Please don't pass an error to a callback and then throw it too

### ISSUE THREAD

**Issue by achingbrain** [swagger-api/swagger-js#582]
Right now the swagger client accepts a `failure` option which is a callback that accepts a message when something goes wrong, [defaulting to a noop](https://github.com/swagger-api/swagger-js/blob/1d01f484c896f9f648cc08ac598b1ce75910ee52/lib/client.js#L138).  The method [looks like this](https://github.com/swagger-api/swagger-js/blob/1d01f484c896f9f648cc08ac598b1ce75910ee52/lib/client.js#L513-L517) :

```javascript
SwaggerClient.prototype.fail = function (message) {
  this.failure(message);

  throw message;
};
```

I've observed the error being thrown if a network request is interrupted - ie. if a users' network goes down, a proxy resets the connection or if they navigate away from the page.

Obviously we want to know about these errors but is there any chance that the error could not be thrown if a failure callback was passed?  It's quite hard to catch it otherwise.

**Comment by fehguy** [comment]
@achingbrain right you are, the current behavior doesn't make any sense.  Working on a fix--the only risk is that by not throwing the error, we run the risk of no longer halting execution.  The throw clause ensured that the client execution stops, but I guess that's up to the author of the `failure` function.
