### ISSUE TITLE
Bump gulp-less to Version 3+ for nodejs 4

### ISSUE THREAD

**Issue by xFragger** [swagger-api/swagger-js#586]
For v2.1.8-M1 (and some earlier tags too) you can't "gulp" on nodejs 4, because there's a problem with gulp-less < v3. 

```
/swagger-ui/node_modules/gulp-less/index.js:42
      .then(function(result, opts){
       ^

TypeError: less.render(...).then is not a function
```

A bump to gulp-less 3 or higher fixes this and makes, as i saw locally, no problems.
(https://github.com/plus3network/gulp-less/issues/140)

**Comment by fehguy** [comment]
Fixed
