### ISSUE TITLE
Why are jQuery and superagent bundled in the browser version?

### ISSUE THREAD

**Issue by RainerAtSpirit** [swagger-api/swagger-js#589]
Looks like they are required here https://github.com/swagger-api/swagger-js/blob/90f55b7c4f6589c7f5ebd037ee529db79df48827/lib/http.js#L4

and therefore ends up in https://github.com/swagger-api/swagger-js/blob/master/browser/swagger-client.js

Is that the indented behavior?

**Comment by fehguy** [comment]
It's gone as of https://github.com/swagger-api/swagger-js/commit/4ff3c50bcc6f46dc3113f2ec4adc1626142570b3
