### ISSUE TITLE
detection and prevention of duplicate `operationId` attributes

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#595]
The swagger-js client should, if possible, detect and prevent issues if the `operationId` is duplicated in a single definition.

**Comment by ponelat** [comment]
should it warn or throw in such cases? Perhaps we can have that as a setting in initial params, for example... `{strict: true}`

**Comment by fehguy** [comment]
I'd like it to warn and generate unique operation ids like `body`, `body_1`, `body_2`, etc.

**Comment by ponelat** [comment]
ok, shouldn't be difficult. We have a global map of  `operationId -> count`. 
But this would be a mutation of the spec, right? Can we avoid that if possible.... it'll depend out what the use case for unique `operationId`s are.

Is this specific to swagger-js... or is it about rendering in swagger-ui

**Comment by fehguy** [comment]
Yes, that's right--it would modify the spec slightly.  Same as we do with `tag` values that collide with reserved words too.

This affects the UI and actually all operations with swagger-js.  If you execute some operation by operationId and it is a duplicate, it will execute the last defined operation, which is usually not good.

**Comment by ponelat** [comment]
ok. would users interact with the mutated `operationId` it... or is it just internal? I just want to make sure there isn't a friendlier approach. For instance combining path + operationId in transactions.
If there isn't, we can just add a note of this mutation... we could keep a list somewhere.

**Comment by fehguy** [comment]
You'd interact with it.  If for example you name an operationId `tags`, it'll rename it `_tags` and give a warning.

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-js/commit/b0cb893531a99e2f2e46bd3fabd1fc0ac9c36fe2
