### ISSUE TITLE
Can't build with local built swagger-js and swagger-ui

### ISSUE THREAD

**Issue by TheAxeMan301** [swagger-api/swagger-js#602]
Forked swagger-ui and swagger-js with no additional changes. When I switch swagger-ui's package.json to use my fork everything builds but it doesn't work. Seems there is a bad or incompatible package somewhere. It does work with the official 2.1.6 build. Error message is:
Uncaught TypeError: Cannot set property length of [object Object] which has only a getter

I have tried many combinations but stuck with npm 0.10.40 since the .travis file specifies 0.10. I found that updating to most recent npm helped. What node / npm versions are used for the official builds and what is recommended?

The problem could be anywhere since the error happens in Buffer. stream-browserify looked suspicious but didn't make a difference.

**Comment by fehguy** [comment]
Hi, if you want to make a local build of swagger-ui with changes in swagger-js, please follow these steps.

* Clone swagger-js and update the version number
* Run `npm link` in the project root, then build with `gulp`
* Clone swagger-ui and update the package.json to the version number you created in the swagger-js project
* Run `npm link swagger-client` in the project root then build with `gulp`

The output files should reflect your changes.  Always check your configuration by searching for the version number in the dist/swagger-ui.js

Please close this if it covers your question

**Comment by TheAxeMan301** [comment]
Thank you for the help! Unfortunately this did not fix my problem. dist/swagger-ui does show my updated version but that wasn't a problem before. I still get that Buffer error.

**Comment by TheAxeMan301** [comment]
Looks like the real problem was that I was using node 0.10 instead of 0.12. Works fine with that. I was lead astray by the .travis.yml file showing 0.10 here and swagger-ui's .travis.yml that shows 0.10 and 0.12.
