### ISSUE TITLE
Form parameter not being sent

### ISSUE THREAD

**Issue by bigblind** [swagger-api/swagger-js#604]
I have an operation which is defined with `"in": "formData"`, but it doesn't get sent. Looking through the client's source, it looks like it's not being added because the condition on [lib/types/operation.js:534](https://github.com/swagger-api/swagger-js/blob/master/lib/types/operation.js#L534) always evaluates to false. It checks that `param.in === "formData"`, but we're outise the params loop, so this always refers to the last parameter. Am I missing something, or should this check be removed from the if statement entirely, so we just check for the `Content-Type` header?

**Comment by fehguy** [comment]
Hmm you may be right.  If you don't mind, it'd be great getting a test case in a PR.  I think the proper fix would be to check the length of the `formParams` object, and if it's > 0 it fires.

**Comment by bigblind** [comment]
Done: #607

**Comment by fehguy** [comment]
fixed with https://github.com/swagger-api/swagger-js/commit/28073c491d2d8e5d47b94bf6726fa0c8aa55422d
