### ISSUE TITLE
add support for message pack?

### ISSUE THREAD

**Issue by hankya** [swagger-api/swagger-js#605]

**Comment by fehguy** [comment]
Please provide more details

**Comment by Apophis3000** [comment]
It would be great to have support for different kinds of en/de-coding of requests / responses like MessagePack. 
I propose to extend the swagger-api to allow custom MediaTypeFormatters like ASP.Net WebAPI does. So somewhere during the initialization of swagger you would insert your own .NET MediaTypeFormatter which is then used as default. 

This is what we do currently in Startup.cs of the WebAPI:

`_httpConfiguration.Formatters.Insert(0, new MessagePackMediaTypeFormatter());`

The function(s) for encoding requests from the browser could be injected in a separate js-file (like you can already do in SwaggerUiConfig)

Note: I don´t know the source code of the swagger-api so I´m not sure if / how this is achievable. But I think it would be a great enhancement given that its not limited to MessagePack-format only (One could even inject custom json-formatters)

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-JS 2.x is no longer under development. We'd be happy to consider any reports about Swagger-JS 3, though.

Closing as 2.x wontfix.
