### ISSUE TITLE
About 'throw message' in fail function

### ISSUE THREAD

**Issue by skyhit** [swagger-api/swagger-js#609]
for https://github.com/swagger-api/swagger-js/blob/master/lib/client.js#L532

any reason to do throw, it is inside the callback so it is hard to catch.

and we meet a problem to use this package in our meteor application, so I'd like to check why to throw.

Thanks, 

Guiqiang

**Comment by fehguy** [comment]
This was just fixed in https://github.com/swagger-api/swagger-js/commit/daf4a909c7e02e00719ffb4e9d92facdd8966183
