### ISSUE TITLE
Proxy enhancement for client side in node app

### ISSUE THREAD

**Issue by v-sullivan** [swagger-api/swagger-js#62]
Hi,
I am new in this area, so apologizes for potential mistakes ...
first of all, it's not an issue but I don't know where to post my queries !
I am playing with Swagger js lib client inside a Node.js App and I can't figure how to set a proxy to reach a Swagger API service outside my company network.  
Thanks for your help.
Regards,
Vernon

**Comment by abhagupta** [comment]
I am looking for similar thing. How can I make a HTTP request go through a HTTP proxy?

**Comment by fehguy** [comment]
Easy.  just override the host / basepath / scheme using `setHost`, etc.  Or write a request interceptor to rewrite the URL

**Comment by abhagupta** [comment]
Thanks.. that worked.  For others looking for example, 
```
var client = new Swagger({
    url: 'http://petstore.swagger.io/v2/swagger.json',
    requestInterceptor: function(temp){
        this.proxy = 'http://127.0.0.1:8442';
    },
    success: function(){
        client.pet.getPetById({petId:2}, {responseContentType: 'application/json'}, function(pet){
            console.log('pet', pet)
        });
    }
});
```

should make every request go through proxy running at http://127.0.0.1:8442

**Comment by estermer** [comment]
I noticed that swagger-js v2.X is struggling to connect to the Host of a proxy in IE10. 

We have a couple different api's for different levels of deployment such as development and production. So currently I have set the `url: /accountservice/swagger.json` and I am setting the `basePath('/accountService')` and `setSchemes([window.location.protocol.slice(0, -1)])`.

here is my current setup: 

```js
export const buildAccountServiceClient = () => {
  const swagger = new Swagger({
    url: '/accountservice/swagger.json',
    usePromise: true,
  });

  // Reconfigure swagger client to override service path if we're using a reverse proxy:
  // /accountservice/swagger.json -> /accountservice
  // Originally tried setting basePath to null, undefined, and '', but that didn't work
  let basePath;
  if (API_URI.startsWith('/')) {
    basePath = API_URI.substring(0, API_URI.lastIndexOf('/'));
    console.log(window.location);
    swagger.then((client) => {
      client.setBasePath(basePath);
      if (typeof(window) !== 'undefined') {
        // use current protocol, so either http or https
        client.setSchemes([window.location.protocol.slice(0, -1)]);
      }
    });
  }
  return swagger;
};
```

^^^This works fine in all browsers and IE11+.

But in IE10 I have to specify the url to the full address of the api such as `url: 'http://accountservice-test.app.net/swagger.json'`. This will work but the other way will not. The above will give me a state of `rejected` and an error `failed to parse JSON/YAML response` with a `catch()` on the promise.

Is there any experience with setting up the url to a proxy in IE10?
