### ISSUE TITLE
`asCurl` method applies clientAuthorizations twice

### ISSUE THREAD

**Issue by prydonius** [swagger-api/swagger-js#624]
I've added an ApiKeyAuthorization as part of the query, and it seems the `asCurl` method for the operation adds the API key twice. E.g.

`http://myapi.com/operation?api_key=1234&api_key=1234`

Tracing back, it seems the clientAuthorizations are being applied on the object in `execute` (https://github.com/swagger-api/swagger-js/blob/master/lib/types/operation.js#L729) and in `asCurl` (https://github.com/swagger-api/swagger-js/blob/master/lib/types/operation.js#L852).

Is this intended for any reason/am I doing something wrong here? Thanks!

**Comment by fehguy** [comment]
right you are.  It does look like executing the operation mutates the original object which is then used in the asCurl.  This is causing duplicate query params for api-key but not for headers.

**Comment by fehguy** [comment]
fixed & tested by https://github.com/swagger-api/swagger-js/commit/954e5ac0bce07be94842a2b82c2c49b5ec7ef9af
