### ISSUE TITLE
npm latest version is incorrect ? 

### ISSUE THREAD

**Issue by justjico** [swagger-api/swagger-js#625]
I installed the latest version 2.1.6 from npm, but it appears to be an old version ? 

For instance I could not find/use the usePromise option for client.

**Comment by fehguy** [comment]
2.1.7 will have this support and it has not been released yet.  Should be soon

**Comment by justjico** [comment]
ok, thanks for the quick reply!

**Comment by indolering** [comment]
2.1.8 is now on NPM, please close.
