### ISSUE TITLE
DELETE requests don't send with formData

### ISSUE THREAD

**Issue by STRML** [swagger-api/swagger-js#642]
https://github.com/swagger-api/swagger-js/blob/57fdc0d7f02ef631f420afaaf10ee6ba51d85777/lib/types/operation.js#L795 checks for a non-null `body`, but it also must check for `definedFormParams.length > 0`. Otherwise, `DELETE` methods with a form body fail to send.

**Comment by fehguy** [comment]
Confirmed this is fixed from #936
