### ISSUE TITLE
Relative spec URL results in error

### ISSUE THREAD

**Issue by artema** [swagger-api/swagger-js#645]
```javascript
var client = require('swagger-client');

var swagger = new client({
  url: './swagger.json'
});
```

``Uncaught TypeError: Cannot read property 'replace' of undefined``

**Comment by fehguy** [comment]
Thank you @artema.  What is the expected behavior of using a relative spec for a browser-based client like swagger-ui?

**Comment by artema** [comment]
@fehguy Swagger UI supports relative spec URLs. Swagger itself requires that you specify a hostname and base path, so it doesn't affect it.
