### ISSUE TITLE
confused with cors message

### ISSUE THREAD

**Issue by jmls** [swagger-api/swagger-js#651]
if I can do this from curl

```bash
curl -k https://myapp.io/pathfinder/resources
```
and get
```
{"swaggerVersion":"1.2","apiVersion":"0.0.0","apis":[{"path":"/Users"},{ yadayadayada
```

why does swagger-client code like this
```javascript
var Swagger = require('swagger-client');

var swagger = new Swagger({
  url: 'https://myapp.io/pathfinder/resources',
  success: function() {
[snip]
```
give me this error ?
```
  this.failure = options.failure || function (err) { throw err; };
                                                     ^
Can't read from server.  It may not have the appropriate access-control-origin settings.
```
surely if curl can read without any cors errors, then swagger-client should be fine ?

thanks

**Comment by webron** [comment]
When running from the browser? No. That's a browser limitation - https://github.com/swagger-api/swagger-ui#cors-support.

**Comment by jmls** [comment]
No, this is running in node, no browser was involved

**Comment by webron** [comment]
Right. So that could be a different fault, unfortunately. You'll get that error message also where there's a problem parsing the spec that's read. I believe we have an open ticket somewhere to improve on that. Apologies for the misunderstanding.

**Comment by jmls** [comment]
Oh, OK. I'll check the returned data.. It's v1.2, anything that I should be looking for

**Comment by webron** [comment]
Lots of room there, can't point into something specific. It's easy to write a malformed 1.2 spec. If you can share what you have, I may be able to help.

**Comment by felixSchl** [comment]
Has there been any progress on this? I am having the same issue and it's hard to track down.

**Comment by fehguy** [comment]
CORS handling isn't part of this library.  It should be handled by users of it.
