### ISSUE TITLE
Dashes cause non-idiomatic use of JavaScript

### ISSUE THREAD

**Issue by mach-kernel** [swagger-api/swagger-js#653]
Route tags in the schema may contain dashes, which is fine, but this will require the user to use "array style" resolution of the tag, as follows:

```js
client.then(function(client) {
    client['with-dashes'].help();
});
```

Would you accept a pull request where the tag name would be modified and camel-cased in the name of code style and readability over having the exact same tag name as is in the schema?

**Comment by fehguy** [comment]
There is already a way to reference "non-mappable" tags by using the apis and operations arrays.  I think that may be better than mutating their tags.

**Comment by mach-kernel** [comment]
@fehguy are you suggesting they look it up by index?

**Comment by fehguy** [comment]
yes, rather than modifying their existing tags

**Comment by mach-kernel** [comment]
What if the order of the schema changes, e.g, the API team for some company adds new endpoints and decides to move things around. Can you guarantee that the index will be the same?

**Comment by fehguy** [comment]
It doesn't affect anything.  Works like this:

```js
// shortcut
api.pet.addPet.help()

// by hash
api.pet.operations['addPet'].help()
```

So in cases when you can't use the shortcut (like with dashes), you can look it up in the hash.

**Comment by fehguy** [comment]
Please reopen if you'd like discuss further.
