### ISSUE TITLE
Swagger trying to parse xml file as JSON

### ISSUE THREAD

**Issue by MichCest** [swagger-api/swagger-js#661]
I am using swagger version 2.0.30 and swagger-ui version 2.0.17

Swagger is correctly treating my xml file as an xml file in the responseContentType.

Once it gets to:
`var contentType = (response._headers["content-type"]||response._headers["Content-Type"]||null)`

the response is:
`contentType = "application/json;charset=utf-8"`

This is causing an error in the console since swagger is trying to parse xml as json:
`Uncaught SyntaxError: Unexpected token <` (within the xml file)

The error is being thrown from:
<pre>
if(contentType != null) {
      if(contentType.indexOf("application/json") == 0 || contentType.indexOf("+json") > 0) {
        if(response.content.data && response.content.data !== "")
          <b>out.obj = JSON.parse(response.content.data); </b>
        else
          out.obj = {}
      }
    }
</pre>

I have been looking for a while and haven't been able to come up with a solution. Any help would be greatly appreciated.

**Comment by fehguy** [comment]
well if your server is claiming to return JSON but it really has XML, isn't that a bad thing?

**Comment by MichCest** [comment]
I am basically trying to nail down where the issue is originating, my xml file has the correct headers and the server does see it as an xml file, but swagger is trying to parse it as a JSON file. Are you trying to say this is not an issue with swagger? Just some background, I am very new to swagger and was asked to try and fix this bug.

**Comment by fehguy** [comment]
Sure--well it appears that your server is lying about the content type.

Are you working inside a browser or inside node?  If inside the browser, you can look at the network tab to see the response payload.

Also your version of swagger-js is fairly old.  Can you update to a newer one, like 2.1.9 as released yesterday?

**Comment by MichCest** [comment]
Thank you for that tip, the response header for that file is content-type: application/json. I will update my swagger implementation too but does this confirm that it is a problem on our end and not with swagger?

**Comment by fehguy** [comment]
I'm pretty sure.  It would be nice, though, if the swagger client gives a helpful error.  I do think it will with newer versions of the library which is why I was asking if you could upgrade.  Are you using a browser or headless with node.js?

**Comment by MichCest** [comment]
I am using a browser, and actually get a different error in firefox vs chrome.

Chrome:
`Uncaught SyntaxError: Unexpected token <` (within the xml file)

Firefox:
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` (within swagger.js line:1395)

I thought upgrading would just be a matter of upgrading the swagger.js file but it looks like a lot more than that. I will need someone to help me do that since I don't know how it was originally implemented.

I will check in and let you know if I am able to fix the issue without touching swagger or if I upgrade and get a new error.

Thank you for you time and you very quick responses.

**Comment by fehguy** [comment]
Click the network tab in Chrome and look at the response tab like below:

![image](https://cloud.githubusercontent.com/assets/249413/11750081/5025749e-9fe6-11e5-802d-11131f21ad3a.png)

**Comment by MichCest** [comment]
It looks like this, not formatted correctly like your.

![screen shot 2015-12-11 at 12 09 47 pm](https://cloud.githubusercontent.com/assets/3931469/11750220/376fe05a-a000-11e5-9c06-d2f6d584f1ce.png)

**Comment by fehguy** [comment]
ok getting closer.  Can you please click the headers tab?  You should see something like this:

![image](https://cloud.githubusercontent.com/assets/249413/11750282/652c44de-9fe7-11e5-86ea-608d661dce03.png)

Your response is certainly XML so if the server is declaring it to be JSON, that's the issue.

**Comment by MichCest** [comment]
![screen shot 2015-12-11 at 12 24 13 pm](https://cloud.githubusercontent.com/assets/3931469/11750592/260eebf6-a002-11e5-9ef0-0e178ca802e1.png)

**Comment by MichCest** [comment]
Also, just so you know, this is what we have within the java file for this GET request:

```@GET
	@Produces({MediaType.APPLICATION_XML})
	@Path("hidden")
	@ApiOperation(value = "hidden", response = String.class)
	public String getParsed(
			@ApiParam(value = hidden, required = true, allowMultiple = false) @PathParam(hidden) String hidden,
			@ApiParam(value = hidden, required = true, allowMultiple = false) @PathParam(hidden) String hidden,
			@ApiParam(value = hidden, required = true, allowMultiple = false) @PathParam(hidden) String hidden)
					throws ServiceException;```

(anything labelled hidden was done by me for this post FYI)

**Comment by fehguy** [comment]
can you please try updating the swagger ui?  Or just point this one:

http://petstore.swagger.io

To your server?

**Comment by MichCest** [comment]
I actually believe we have found the issue, our backend is returning the "xml" file as a string rather than a valid xml file. They are working on fixing this and then our problem should be fixed. Your help guided us to this finding.

Thank you for all of your help and for being so attentive with my issue.

**Comment by fehguy** [comment]
great news!  I'll close this then.
