### ISSUE TITLE
resolveInline / resolveTo property is null when evaluating property.$ref

### ISSUE THREAD

**Issue by kaoh** [swagger-api/swagger-js#662]
The result of this bug is that the processing stops and the complete UI is not rendered.

Attached is a diff for the patch together with another bug fix for correct base path handling: [swagger.txt](https://github.com/swagger-api/swagger-ui/files/60804/swagger.txt)

Fix at line 2461 @version v2.1.4:
```
Resolver.prototype.resolveInline = function (root, spec, property, resolutionTable, unresolvedRefs, location) {
  if (property == null) {
    return;
  }
  var key = property.$ref, ref = property.$ref, i, p, p2, rs;
```

Fix at line 2536 @version v2.1.4:
```
Resolver.prototype.resolveTo = function (root, property, resolutionTable, location) {
  var sp, i;
  if (property == null) {
    return;
  }
```

Attached is a stripped down version of an JSON input which is incorrectly handled:  [test.json.txt](https://github.com/swagger-api/swagger-js/files/60818/test.json.txt)

Thr JSOn was produced by the Java class: `io.swagger.jaxrs.listing.ApiListingResource`. If the produced JSON is invalid, forward it to this project.

It is quite hard to debug swagger due to the usage of RequireJS. This seems to destroy at least the debugger of Chrome.

**Comment by fehguy** [comment]
This should be supported and tested.  Please reopen if you find otherwise.
