### ISSUE TITLE
Invalid basePath parsing when trying out REST request

### ISSUE THREAD

**Issue by kaoh** [swagger-api/swagger-js#663]
When trying out a REST call the produced URL is incorrect. It is producing something  like `http://localhost:8080/http://localhost:8080/service/api/v1/FooBar`. The `basePath` is not correctly constructed.

Attached a diff for the patch against version 2.1.4: [swagger.txt](https://github.com/swagger-api/swagger-js/files/60819/swagger.txt)

At line 4411:

```
 var basePath = this.basePath;

  // correct base path
  if (basePath.indexOf("/") === 0) {
    basePath = basePath.substring(1);
    var baseUrlPattern = /^https?:\/\/[a-z\:0-9.]+/;
    var result = "";

    var match = baseUrlPattern.exec(basePath);
    if (match != null) {
      result = match[0];
    }
    if (result.length > 0) {
      basePath = basePath.replace(result, "");
    }
  }

  if (basePath !== '/') {
    url += basePath;
  }
```

**Comment by fabian-rump** [comment]
I also encountered this issue, but later found out that swagger-js is behaving correctly. Citing the [Swagger specification](http://swagger.io/specification/):

> basePath: [...] **The value MUST start with a leading slash (/)**

For specification of the hostname/IP there is the **host** field.

**Comment by koh-osug** [comment]
I do not see these properties. I start swagger by passing a url:

```
  window.swaggerUi = new SwaggerUi({
        url: serviceUrl+"services/api/v1/swagger.json",

 window.swaggerUi.load();
```

When starting swagger with this its internals do not construct a proper basePath. Based on the given URL Swagger must be able to handle this automatically.

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-JS 2.x is no longer under development. We'd be happy to consider any reports about Swagger-JS 3, though.

Closing as 2.x wontfix.
