### ISSUE TITLE
File formdata not working anymore

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-js#664]
This is https://github.com/swagger-api/swagger-ui/issues/1815 follow-up

Using [this swagger definition](http://yabb.herokuapp.com/v2/api-docs), the image formData is not correctly sent in the request POST /banner.

It seems to be a regression as it is working with the current http://petstore.swagger.io.

**Comment by fehguy** [comment]
Yes, this broke.  Please try the `dist` from master, as it has this fix applied:

https://github.com/swagger-api/swagger-js/issues/668
