### ISSUE TITLE
Port from `url: "http://...` not included in `.host`

### ISSUE THREAD

**Issue by jad-b** [swagger-api/swagger-js#670]
`new SwaggerClient` drops the port from the host after parsing the URL.
Found using [swagger-client.min.js @ v2.1.9](https://github.com/swagger-api/swagger-js/blob/647c7713b6c9cfbb05a08021b718879d0ca5170b/browser/swagger-client.min.js) 

```javascript
var swagger = new SwaggerClient({
    url: "http://localhost:18001/spec/swagger.yaml",
    success: function() {
        console.debug("LOADED");
    }
});
console.log("Swagger host: " + swagger.host); // Prints "localhost"
```

Discovered this when a POST request back to my API server caused a CORS error. 
Setting the correct host with `swagger.setHost("localhost:18001")` fixed the issue.

**Comment by fehguy** [comment]
I don't think this is possible, since all the unit tests are using non-standard ports.  Please provide a test case for this?
