### ISSUE TITLE
PR #593 caused a regression in Swagger-UI; tooltips no longer function properly

### ISSUE THREAD

**Issue by xiehan** [swagger-api/swagger-js#674]
This is the root cause of swagger-api/swagger-ui#1836

I don't have a grasp of what the exact issue is -- it seems like a `<div>` tag is not being closed properly, but I'm not sure -- but I was able to verify that reverting the code to its state from before pull request #593 was merged in caused tooltips to function properly again.

**Comment by dolmen** [comment]
Is is fixed by #690?

**Comment by webron** [comment]
Yup, looks like.
