### ISSUE TITLE
Nested, linked, relative references don't resolve properly

### ISSUE THREAD

**Issue by pwfff** [swagger-api/swagger-js#677]
I'm making a pull request with a broken test that I'll link here.

A simple test case is swagger.json that has a path with "$ref": "paths.json#/my_path" which includes a schema that has "$ref": "definitions.json#/MyModel".

**Comment by pwfff** [comment]
See PR #678

**Comment by fehguy** [comment]
Got it, thanks.  Will try to get this supported shortly.  Glancing at your test case, I believe that is valid and should be supported.
