### ISSUE TITLE
access-control-origin settings

### ISSUE THREAD

**Issue by delenius** [swagger-api/swagger-js#679]
When I try to initialize swagger-client with my own swagger.json, I get this error:

> Can't read from server.  It may not have the appropriate access-control-origin settings.

When I use the same code and substitute the URL

> http://petstore.swagger.io/v2/swagger.json

it works.

The server (on my localhost) has CORS set up. I am using the swagger jersey servlet to produce and serve the swagger.json file.

If I curl to my swagger.json URL, I get:

>HTTP/1.1 200 OK
>Date: Fri, 08 Jan 2016 20:58:44 GMT
>Content-Type: application/json
>Access-Control-Allow-Origin: *
>Access-Control-Allow-Methods: GET, POST, DELETE, PUT, OPTIONS
>Access-Control-Allow-Headers: Content-Type, api_key, Authorization
>Content-Length: 0
>Server: Jetty(9.3.5.v20151012)

This looks very similar to what I get from the "pet store" swagger URL:

>HTTP/1.1 200 OK
>Access-Control-Allow-Origin: *
>Access-Control-Allow-Methods: GET, POST, DELETE, PUT
>Access-Control-Allow-Headers: Content-Type, api_key, Authorization
>Content-Type: application/json
>Content-Length: 0
>Connection: close
>Server: Jetty(9.2.7.v20150116)

curl also returns the entire swagger.json document in both cases.

One additional clue. If I do 

> require('request')('http://localhost:8080/some/url/to/swagger.json');

then I get an error:

> Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at TCP.onread (net.js:544:26)
> Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at TCP.onread (net.js:544:26)

Could this have something to do with the "Connection: close" in my response headers?

**Comment by fehguy** [comment]
Looks to me like your server isn't working correctly. Can you see the swagger json in your browser?  Can you give the url to that, plus the entire code snippet where you are initializing swagger client?

**Comment by delenius** [comment]
Yes, I can see my swagger.json in the browser at the same URL that I am trying to connect to from the client.

My client looks like:

```javascript
var Swagger = require('swagger-client');
var docurl = ...
var client = new Swagger({
  url: docurl,
  usePromise: true
}).then(function(client){
    console.log('Swagger client created from ' + docurl);
}).catch(function(error){
    console.log(error);
    process.exit(1);
});
```

**Comment by fehguy** [comment]
That looks correct.  Ensure that your docurl is not a redirect (it should work even if so) with this:

curl -i http://path/to/your/url

and post the response here?

**Comment by delenius** [comment]
I posted the curl output (just the headers) above. The body (swagger.json file content) is also printed by curl.

**Comment by fehguy** [comment]
ok well, it is definitely not a cors issue as it's localhost, and if you're running inside of node, it won't care anyway.  I have to guess that there is some problem with the spec.  If you want to share it privately, you can send it to me to scan

**Comment by delenius** [comment]
Don't think I can share the spec, but note that it was generated automatically by the swagger jersey servlet.

Also, what about those ECONNRESET errors?

I tried initializing Swagger with a local copy of swagger.json, but it doesn't like 'file:swagger.json'...

**Comment by fehguy** [comment]
that error means that your server is rejecting the request.  It's simply not even being read by the swagger-client.

You can initialize swagger with the swagger.json directly--simply create a variable with the spec object in it, and set `spec: yourSpecObject` when initializing the client.

**Comment by delenius** [comment]
Yeah, it works with the "spec:  yourSpecObject" method!

**Comment by fehguy** [comment]
OK there is definitely a problem loading your spec.  Let me know if you want to troubleshoot this more.

**Comment by delenius** [comment]
I don't know why you closed the issue since the problem is not solved.

I tried the following: Copy swagger.json to the root of my web server, so that it's served as a plain file by jetty. Presto, that also works!

So it appears that the problem is with the Swagger Jersey servlet. However, the Swagger-UI web client *does* work with the swagger.json that is served by the Swagger Jersey servlet.

I tried the method here for adding CORS support
https://github.com/swagger-api/swagger-core/wiki/CORS-Support

but that made no difference.

**Comment by fehguy** [comment]
I believe we've isolated it to how you're serving up your swagger definition. So let's move this to the swagger Java province ice (swagger-core) and I'm happy to trot sort it out there

**Comment by gaah666** [comment]
I need access-control-origin settings to be able to use this client with swagger on a different server. 
I've configured the backend server to support cors, but the frontend (this client lib) isn't setting the required headers by looking at the request. 
Or am I missing something?

**Comment by fehguy** [comment]
Need more info.  What is the problem?  Is it from node or the browser?

I suggest opening a new issue, as this is a quite different task.

**Comment by delenius** [comment]
Sounds like the same problem to me. It seems like the client works from the browser but not from node (because the browser handles the CORS stuff automatically?).

**Comment by gaah666** [comment]
Alright thanks! See here:
https://github.com/swagger-api/swagger-js/issues/722

**Comment by dleute** [comment]
We are getting a similar error but we are fairly sure it is due to our target system using a self signed SSL certificate. (it's working when we move the swagger.json elsewhere). Is there any way around that?

**Comment by dleute** [comment]
Also, we could store the swagger locally, but then it tries to talk to the api locally which doesn't make sense. Is there any way to split where the swagger json is stored and the target host?

**Comment by fehguy** [comment]
You can pass the swagger object to the client when constructing it.  Perhaps you can open a new issue to discuss this

**Comment by dleute** [comment]
I was able to set schemes, basepath and host in the spec. now the right url is created, but in my case, the target server still is not happy because of self signed ssl.
I'm not sure what is actually making the rest calls based on this swagger spec. Still looking into that.

**Comment by A-J-Bauer** [comment]
In my case asp.core app with custom swagger UI I had to add this in `Configure();`
`var provider = new FileExtensionContentTypeProvider();`
`provider.Mappings[".json"] = "application/octet-stream";`
basically configuring the server to allow serving ".json"
