### ISSUE TITLE
allOf property fails to resolve inline

### ISSUE THREAD

**Issue by gnidan** [swagger-api/swagger-js#688]
This might be related to #681 which was recently closed.

I have a few constructs in my API:

```
definitions:
  Field:
    type: object
    required:
      - type
    properties:
      type:
        type: string
      required:
        type: boolean

  EchoField:
    allOf:
    - $ref: "#/definitions/Field"
    - type: object
      required:
        - value
      properties:
        type:
          type: string
          enum:
          - echo
        value:
          type: string
```

When I use extend from `EchoField` inline, à la:

```
...
                    field_not_required:
                      allOf:
                      - $ref: "#/definitions/EchoField"
                      - type: object
                        properties:
                          required:
                            type: boolean
                            enum:
                            - false
...
```

Then the schema output is as follows:

```
    "field_not_required": {
      "type": "echo",
      "required": true,
      "value": "string"
    }
```

The `required` property of the `field_not_required` object resolves as having value `true`, even though the inline override of `required` provides the singular enum value `false`. The behavior works properly if I make the entire `field_not_required` property simply use a `$ref`, defining, say, `NotRequiredEchoField`. Types don't matter (doesn't matter if I'm using a boolean and specifying an enum, or a string... notice that the `type` property correctly resolves to include the value `"echo"`, overridden by the non-inline model `EchoField`)

**Comment by fehguy** [comment]
Have you tested this against 2.1.11?

**Comment by gnidan** [comment]
Yep, updated as soon as I saw you merged the #681 fix :)

**Comment by gnidan** [comment]
(That did fix the inline response issues, BTW; it's just these inline properties now aren't being resolved the way I would expect)

**Comment by fehguy** [comment]
ok thanks.  Will get that tested.

**Comment by gnidan** [comment]
thank you! let me know if more information is needed

**Comment by hsingh23** [comment]
Was this fixed?

**Comment by fehguy** [comment]
Yes should be fully working.
