### ISSUE TITLE
deprecation warnings when using sample code in README in v2.1.11

### ISSUE THREAD

**Issue by srl295** [swagger-api/swagger-js#689]
I'm not calling these functions, not sure where the message is coming from. Didn't show up in v2.1.10, but in v2.1.11.

> Method getMockSignature is deprecated

> Methods createJSONSample and getSampleValue are deprecated

I put in a 'throw' to try to find where they are coming. Will try to make a small example.

```
      at Model.createJSONSample.Model.getSampleValue (node_modules/swagger-client/lib/types/model.js:25:7)
      at Operation.getModelSampleJSON (node_modules/swagger-client/lib/types/operation.js:604:36)
      at new module.exports (node_modules/swagger-client/lib/types/operation.js:152:29)
      at node_modules/swagger-client/lib/client.js:345:29
      at arrayEach (node_modules/lodash-compat/internal/arrayEach.js:15:9)
      at Object.forEach (node_modules/lodash-compat/internal/createForEach.js:15:9)
      at node_modules/swagger-client/lib/client.js:324:7
      at node_modules/lodash-compat/internal/createBaseFor.js:19:11
      at baseForOwn (node_modules/lodash-compat/internal/baseForOwn.js:14:10)
      at node_modules/lodash-compat/internal/createBaseEach.js:17:14
      at Object.forEach (node_modules/lodash-compat/internal/createForEach.js:16:9)
      at SwaggerClient.buildFromSpec (node_modules/swagger-client/lib/client.js:318:5)
      at Resolver.finish (node_modules/swagger-client/lib/resolver.js:409:14)
      at Resolver.resolve (node_modules/swagger-client/lib/resolver.js:318:10)
      at obj.on.response (node_modules/swagger-client/lib/client.js:202:26)
      at responseInterceptor (node_modules/swagger-client/lib/http.js:68:12)
      at obj.on.response (node_modules/swagger-client/lib/http.js:72:5)
      at node_modules/swagger-client/lib/http.js:284:7
      at Request.callback (node_modules/superagent/lib/node/index.js:788:12)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:997:12)
      at endReadableNT (_stream_readable.js:905:12)
```

**Comment by srl295** [comment]
actually the sample in the README generates the warnings.

```javascript
var Swagger = require('swagger-client');

var client = new Swagger({
  url: 'http://petstore.swagger.io/v2/swagger.json',
  success: function() {
    client.pet.getPetById({petId:7},{responseContentType: 'application/json'},function(pet){
      console.log('pet', pet);
    });
  }
});
```

**Comment by fehguy** [comment]
The swagger-ui is calling functions which are going away soon.  The next swagger-ui release will not call the swagger-js client for rendering anymore.

**Comment by srl295** [comment]
@fehguy thanks- I'm not sure what the above code has to do with swagger-ui? It seems like it's the dynamic builder that is calling the functions.

**Comment by fehguy** [comment]
I will take a look at that

**Comment by srl295** [comment]
06c6cb6e88d728a5ec7c7ef01b343c35c65fc4d7 by @bodnia added the warning messages.

**Comment by noirbizarre** [comment]
Same here, not using SwaggerUI, only Swagger-JS but I'm having these warning breaking my console and I'm not calling these functions.

**Comment by fehguy** [comment]
OK I'll get these updated in a release today.

**Comment by srl295** [comment]
@fehguy thanks, glad to help test

**Comment by fehguy** [comment]
@srl295 I've merged the change, if you want to test it out from master before I release 2.1.12 that'd be great.

**Comment by srl295** [comment]
@fehguy master looks good now, thx

**Comment by jmwohl** [comment]
@fehguy Any idea when 2.1.12 will be released? I'd like to get rid of these messages as well :+1:

**Comment by fehguy** [comment]
Help test https://github.com/swagger-api/swagger-js/pull/710 and I'll release it!

**Comment by wfayeBerman** [comment]
I had the same problem running the sample code in the README.md.  I only did `npm install swagger-client` and ran the code provided in the demo as seen below.  Node version is v6.3.0

    var Swagger = require('swagger-client');

    var client = new Swagger({
      url: 'http://petstore.swagger.io/v2/swagger.json',
      success: function() {
        client.pet.getPetById({petId:7},{responseContentType: 'application/json'},function(pet){
          console.log('pet', pet);
        });
      }
    });

Error message:

    { url: 'http://petstore.swagger.io/v2/pet/7',
      method: 'GET',
      headers: 
       { date: 'Thu, 28 Jul 2016 18:06:09 GMT',
         'access-control-allow-origin': '*',
         'access-control-allow-methods': 'GET, POST, DELETE, PUT',
         'access-control-allow-headers': 'Content-Type, api_key, Authorization',
         'content-type': 'application/json',
         connection: 'close',
         server: 'Jetty(9.2.9.v20150224)' },
      errObj: 
       { Error: Internal Server Error
           at Request.callback (/var/www/abc/node_modules/superagent/lib/node/index.js:698:17)
           at IncomingMessage.<anonymous> (/var/www/abc/node_modules/superagent/lib/node/index.js:922:12)
           at emitNone (events.js:91:20)
           at IncomingMessage.emit (events.js:185:7)
           at endReadableNT (_stream_readable.js:973:12)
           at _combinedTickCallback (internal/process/next_tick.js:74:11)
           at process._tickCallback (internal/process/next_tick.js:98:9)
         original: null,
         response: 
          Response {
            domain: null,
            _events: {},
            _eventsCount: 0,
            _maxListeners: undefined,
            res: [Object],
            request: [Object],
            req: [Object],
            links: {},
            text: '{"code":500,"type":"unknown","message":"something bad happened"}',
            body: [Object],
            files: {},
            buffered: true,
            headers: [Object],
            header: [Object],
            statusCode: 500,
            status: 500,
            statusType: 5,
            info: false,
            ok: false,
            redirect: false,
            clientError: false,
            serverError: true,
            error: [Object],
            accepted: false,
            noContent: false,
            badRequest: false,
            unauthorized: false,
            notAcceptable: false,
            forbidden: false,
            notFound: false,
            type: 'application/json',
            setEncoding: [Function: bound ],
            redirects: [] },
         status: 500 },
      status: 500,
      statusText: '{"code":500,"type":"unknown","message":"something bad happened"}',
      obj: { code: 500, type: 'unknown', message: 'something bad happened' },
      data: '{"code":500,"type":"unknown","message":"something bad happened"}' }

**Comment by wfayeBerman** [comment]
I think I found the problem, the README.md should be referencing `pet` items with a `petId` of 1 - 5.  the following worked for me

	var Swagger = require('swagger-client');

	var client = new Swagger({
	  url: 'http://petstore.swagger.io/v2/swagger.json',
	  success: function() {
	    client.pet.getPetById({petId:1},{responseContentType: 'application/json'},function(pet){
	      console.log('pet', pet);
	    });
	  }
	});

**Comment by fehguy** [comment]
Thanks. Could you send a pull request for that?

**Comment by wfayeBerman** [comment]
sure thing, i just issued one here: [https://github.com/swagger-api/swagger-js/pull/821](https://github.com/swagger-api/swagger-js/pull/821)
