### ISSUE TITLE
Where is the realize of curl command (http/https request) for the swagger-ui.js

### ISSUE THREAD

**Issue by LouisZou** [swagger-api/swagger-js#694]
I want to re-write the curl command and execute it to access the Restful API Host to get/post request and then analyze the response to get some information (Header and Body).
Sorry for that I don't know where is the realization code for it.

I found there is the following points in swagger-ui.js:
31919: var curlCommand = this.model.asCurl(this.map);
I know it is the point for making the curl command but I know where is executing for this command , and where is the callback for analyzing the response and then overwrite the response form in the web page.

I think the execution is in the swagger-ui.js with ajax.
is it correct?

**Comment by LouisZou** [comment]
I have a restful api server in the LAN intranet. I think maybe the proxy is not supported in the definition file so that the request is not sent to the host.
And I want to debug the trace for swagger.js.

**Comment by fehguy** [comment]
You can see the curl logic quite clearly in the code:

```
Operation.prototype.asCurl = function (args1, args2)
```
