### ISSUE TITLE
When I try to test the swagger ui to my restful api server whose protocol is https, the request is not executed.

### ISSUE THREAD

**Issue by LouisZou** [swagger-api/swagger-js#696]
I debug the swagger-ui.js, and I found the function request.end is not executed:

this.on('end', function(){
var err = null;
var res = null;

try {
     res = new Response(self);
}
...
}

how to run the test for https server?

**Comment by LouisZou** [comment]
And I receive a error from the response : 
Origin is not allowed by Access-Control-Allow-Origin

How can I set the datatype to "jsonp", in the swagger-ui.js?

**Comment by fehguy** [comment]
JSONP is not supported by the UI.  Your other question is not clear, you'll have to share more details.
