### ISSUE TITLE
How to convert the character "/" in the username , such as "/user/{user}".

### ISSUE THREAD

**Issue by LouisZou** [swagger-api/swagger-js#697]
If there is "/" in my user name ,such as "/a/b/"when I execute the get method using swagger-ui.js.
it will expand it to "https://apiserver/user/%2Fa%2Fb%2F",
this request will failed because my real usl should be "https://apiserver/user/a/b/".

how to set the converting in swagger-ui.js to get the correct path?

the path of swagger definition is like : 
"/user{user}/": {

the username is like : 
"/a/b"

the real url for restful host is like:
https://apihost/user/a/b/

**Comment by fehguy** [comment]
That's actually not right.  A parameter name of {user} cannot have a `/` in it as it will change the path locator itself.  Doing the replacement of `/` as `%2F` is actually intentional.

**Comment by LouisZou** [comment]
Thanks fehguy.
Now I have a completed restful api host using the above path to provide the API.
that's meaning I have to consider the special character "/".
is there any workaround for this?

**Comment by LouisZou** [comment]
Thanks fehguy.
I found a simple method to resolve it temporarily like the following:
Operation.prototype.encodePathParam = function (pathParam) {
  //return encodeURIComponent(pathParam);
  return pathParam.toString().split('/').map(encodeURIComponent).join('/');
};
