### ISSUE TITLE
Trouble with 1.2 API conversion to 2.0

### ISSUE THREAD

**Issue by brianfife** [swagger-api/swagger-js#699]
Hello,

I'm encountering a unique issue when creating a SwaggerClient with the following json snippet (paired down from a larger API):

```json
{
  "apiVersion": "1.0",
  "consumes": [
    "application/json"
  ],
  "apis": [
    {
      "description": "create",
      "operations": [
        {
          "method": "POST",
          "summary": "Create a user",
          "notes": "Create a user",
          "nickname": "create",
          "produces": [
            "application/json"
          ],
          "consumes": [
            "application/json"
          ],
          "parameters": [
            {
              "allowMultiple": false,
              "defaultValue": "",
              "description": "The information required to create a user",
              "name": "body",
              "paramType": "body",
              "type": "RequestUserInfo",
              "required": false
            }
          ],
          "deprecated": "false",
          "type":"UserInfo"
        }
      ],
      "path": "/api/users"
    }
  ],
  "models": {
    "RequestUserInfo": {
      "description": "",
      "id": "RequestUserInfo",
      "properties": {
        "data": {
          "required": false,
          "type": "UserInfo"
        }
      }
    },
    "UserInfo": {
      "description": "The information required to create a user",
      "id": "UserInfo",
      "properties": {
        "password": {
          "description": "The password for the user",
          "required": true,
          "type": "string"
        },
        "userName": {
          "description": "The user name",
          "required": true,
          "type": "string"
        }
      }
    }
  },
  "basePath": "/obj",
  "resourcePath": "/api/users",
  "info": {
      "contact": "",
      "description": "",
      "license": "",
      "licenseUrl": "",
      "termsOfServiceUrl": "",
      "title": ""
  },
  "swaggerVersion": "1.2"
}
```

What I am running:

```javascript
    new SwaggerClient({
      url: "http://localhost/spec.json",
      usePromise: true,
      progress: function(m) {console.log(m);}
    }).then(function(client) {
      console.log(client['api/users'].apis.create.parameters[0].sampleJSON);
    });
```

What I am trying to do is extract the sampleJSON used in the create request (post data).  

My (incorrect) output is:

```json
{
  "data": "password"
}
```

What I am expecting to see is:

```json
{
  "data": {
    "password": "string",
    "userName": "string"
  }
}
```

I spent far too much time learning what swagger-client is doing, and discovered that the reason this is occurring comes from https://github.com/swagger-api/swagger-js/blob/master/lib/spec-converter.js#L150.  When converting the 1.2 spec to 2.0, properties[enum] is created using the names found in UserInfo.properties{}.

Since there is now a UserInfo.properties.enum present, schemaToJSON will return enum[0]  https://github.com/swagger-api/swagger-js/blob/master/lib/schema-markup.js#L119 as the JSON sample for the UserInfo definition.

client.definitions.UserInfo
```json
{ properties: 
   { password: { type: 'string', description: 'The password for the user' },
     userName: { type: 'string', description: 'The user name' } },
  enum: [ 'password', 'userName' ],
  required: undefined }
```

I have no idea what the right solution is.  Should the UserInfo.properties.enum[] be created in the first place?  I used swagger-codegen to create a nodejs server (which converts the spec to 2.0), and it didn't add the enum[] to UserInfo.properties.  

Should the schema-markup code not short-circuit to setting output = properties.enum[0], which would let it iterate through all the UserInfo.properties{} to build the JSON sample ?

**Comment by brianfife** [comment]
The swagger-client used for swagger-ui doesn't seem to have trouble rendering the sampleJSON on the webpages, likely due to using buildFrom1_2Spec.

```
/**
 * swagger-client - swagger.js is a javascript client for use with swaggering APIs.
 * @version v2.1.9-M1
 * @link http://swagger.io
 * @license apache 2.0
 */
```

**Comment by webron** [comment]
Looks like you're using an old version. As a first step, try upgrading to the latest.

**Comment by brianfife** [comment]
Apologies, I didn't make it too obvious in that post - the v2.1.9-M1 is the swagger-client.js included in the automated api-docs (that is included in the project we are building).

I am experiencing this problem with swagger-client v2.1.11 from npm, and master:

git clone https://github.com/swagger-api/swagger-js.git
cd swagger-js/
npm install
cd ..
node test.js, which runs

```nodejs
var SwaggerClient = require('./swagger-js');

    new SwaggerClient({
      url: "http://localhost/spec.json",
      usePromise: true,
      progress: function(m) {console.log(m);}
    }).then(function(client) {
      console.log("UserInfo =",client.definitions.UserInfo);
      console.log('---');
      console.log("create sampleJSON is", client['api/users'].apis.create.parameters[0].sampleJSON);
      //console.log(client);
    });
```

```
$ node test.js
fetching resource list: http://localhost/spec.json; Please wait.
UserInfo = { properties:
   { password: { type: 'string', description: 'The password for the user' },
     userName: { type: 'string', description: 'The user name' } },
  enum: [ 'password', 'userName' ],
  required: undefined,
  id: 'userinfo',
  name: 'UserInfo' }
---
create sampleJSON is {
  "data": "password"
}
```

**Comment by brianfife** [comment]
Any comments/thoughts on what's going wrong (creating the enum, defaulting to enum[0])?

**Comment by IvanGoncharov** [comment]
@brianfife Is right it's mistake. `enum` serve totally different purpose in JSON Schema:
 http://json-schema.org/latest/json-schema-validation.html#anchor76
And in this case it should be `required`:
http://json-schema.org/latest/json-schema-validation.html#anchor61
Just replace `enum` with `required` at this line:
https://github.com/swagger-api/swagger-js/blob/master/lib/spec-converter.js#L156
See how it's done in `swagger-converter`:
https://github.com/apigee-127/swagger-converter/blob/master/index.js#L739-L767

**Comment by brianfife** [comment]
I can't just replace enum with required at [line 156](https://github.com/swagger-api/swagger-js/blob/master/lib/spec-converter.js#L156), since [line 159](https://github.com/swagger-api/swagger-js/blob/master/lib/spec-converter.js#L159) will immediately set it from existingModel.

I guess line 159 would have to be similar to https://github.com/apigee-127/swagger-converter/blob/master/index.js#L757, right?

```
schema.required = existingModel.required || _enum;
```

**Comment by IvanGoncharov** [comment]
@brianfife Yes you right. 
And obviously it's better to rename `_enum` into something more appropriate.

**Comment by brianfife** [comment]
Sure.  I'll submit a pull request shortly.
