### ISSUE TITLE
Add custom header when new a SwaggerClient.

### ISSUE THREAD

**Issue by wangzilong** [swagger-api/swagger-js#700]
When I want to new a SwaggerClient, I want to add a custom  header (  "k" : "v" ), but I can not found a wiki to teach me how to config it.
```
var swagger = new SwaggerClient({
                url: "http://i-digi-sign.appspot.com/rest/swagger.json",
                enableCookies: true,
                authorizations:{new SwaggerClient.ApiKeyAuthorization("k", "v","header")},
                success: function() {}
            });
```

Please help me.

**Comment by fehguy** [comment]
You can use the [authorization system](https://github.com/swagger-api/swagger-js#handling-success-and-failures) by creating a security requirement and attaching it to each operation (or the API as a whole).  Then each operation will receive the header, if it has been set.

If you need to send a header to _all_ operations and don't want to define that they're required, you can use a _requestInterceptor_, please see here for an example:

https://github.com/swagger-api/swagger-js/blob/master/test/client.js#L523
