### ISSUE TITLE
Avoid console.log

### ISSUE THREAD

**Issue by felixSchl** [swagger-api/swagger-js#702]
Is there any chance we could remove `console.log` from `lib/helpers.js`? Would anything break by removing it? Could we use a logger instance or something like [debug](https://www.npmjs.com/package/debug) instead?

**Comment by fehguy** [comment]
seems like making a logger an argument for the SwaggerClient constructor prototype would be best.  Do you have time to submit a PR?  We can fall back to console.log when not configured.
