### ISSUE TITLE
Use proper errors

### ISSUE THREAD

**Issue by felixSchl** [swagger-api/swagger-js#703]
Is there any chance we could use proper errors other than [just strings](https://github.com/swagger-api/swagger-js/blob/cf6251cffec42b600eba12bc95a42b4d3f794e96/lib/client.js#L180)? Even the HTTP status codes you are deriving the string from would be more helpful than the string itself. By "proper errors" I mean functions that extend the Error prototype and can be checked against using `instanceof`. Alternatively, some library defined application codes that are guaranteed not to change at random would do. I do not feel comfortable checking the error with a regex or `substring`-checks, it seems brittle.

EDIT: Even more important, imo, is this one: https://github.com/swagger-api/swagger-js/blob/master/lib/types/operation.js#L692-L694

**Comment by fehguy** [comment]
Definitely, the error payload can follow some structure, even the Error prototype.  Do you have time to send a PR for this?

**Comment by djMax** [comment]
+1
