### ISSUE TITLE
Nested reference in remote file not resolved

### ISSUE THREAD

**Issue by mxgr7** [swagger-api/swagger-js#716]
See this snippet:
https://gist.github.com/mxgr7/c68e3ffd520b1a877587

The reference in the remote file is not resolved apparently. I get an error in swagger-ui:
 `#/SuperErrorModel is not defined!`

Using swagger-ui version 2.1.4, swagger-js version 2.1.11
Possibly related to #677.

**Comment by fehguy** [comment]
Correct, references directly inside schemas are not yet supported.

**Comment by mxgr7** [comment]
Is this something that will be supported in the future? Are there reasons why it hasn't been implemented other than no one taking the time to do it?

**Comment by fehguy** [comment]
so much to do, so little time.  It will be implemented, feel free to submit a PR if you have cycles.  Otherwise, it is an issue and will be fixed.  It has not been reported as a common issue, which is how priorities are set.

**Comment by mxgr7** [comment]
Okay. I was thinking about a different approach towards references. Why not add a pre-processing step where all references are resolved purely inside the JSON layer. Then hand the result to the swagger parser which doesn't need to handle or even know about references anymore.

Seems logical to me especially since references are part of the JSON specification.

**Comment by fehguy** [comment]
Yes, however that is what the parser is supposed to do.  We didn't have much luck with any off-the-shelf parsers for fully resolving swagger definitions.  In this project, there is a `resolver` component to do just that.
