### ISSUE TITLE
2.1.11 is causing SCRIPT28: Out of stack  space errors in IE

### ISSUE THREAD

**Issue by tsmith-sdm** [swagger-api/swagger-js#717]
2.1.11 is causing SCRIPT28: Out of stack space errors in IE. While reverting back to 2.1.10 seems to fix the issue.

I'm loading these two specs in the order shown:

http://api.stratasysdirect.com/Rapidity/swagger/ui/index
http://api.stratasysdirect.com/PMD/swagger/ui/index

and this is how I'm using the swagger client

`
		function load() {
			var defer = $q.defer();

			new SwaggerClient(configuration.rapidityUrl, {
				usePromise: true,
				enableCookies: true,
				requestInterceptor: {
					apply: function(request) {
						request.headers[configuration.contextIdHeader] = SessionService.contextId;
						request.headers['X-XSRF-TOKEN'] = $cookies.get('XSRF-TOKEN');
						return request;
					}	
				}
			}).then(function (swagger) {
                service.baseUrl = swagger.scheme + '://' + swagger.host + swagger.basePath + '/';
				service.apis = swagger.apis;
				$timeout(function() {
					defer.resolve(swagger);
				});
			});

			return defer.promise;
		}
`

**Comment by fehguy** [comment]
Please share the swagger definition that is causing the issue

**Comment by fehguy** [comment]
I believe the fixes in 2.1.12 have addressed this.  Can you please try with that version?

**Comment by fehguy** [comment]
Please reopen if you see issues.  We now have 2.1.13 available.
