### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by cougil** [swagger-api/swagger-js#720]
Hi.
We are trying to use the latest master version from the Swagger UI but it appears that something it not working properly in the JS frontend. The UI does not get/parse all the values from the swagger API.

It appears that the response that comes from the endpoint /v2/api-docs is correct. What we can do? 

The chrome console shows an error like this:

```
index.js:24 XHR finished loading: GET "http://xxx:xxx/v2/api-docs".Request.end @ index.js:24SuperagentHttpClient.execute @ schema-markup.js:163SwaggerHttp.execute @ schema-markup.js:24SwaggerClient.build @ resolver.js:291SwaggerClient.initialize @ resolver.js:216module.exports @ resolver.js:165window.SwaggerUi.Backbone.Router.extend.load @ index.js:24window.SwaggerUi.Backbone.Router.extend.updateSwaggerUi @ index.js:24(anonymous function) @ index.js:24f @ backbone-min.js:3e.Events.trigger @ backbone-min.js:3SwaggerUi.Views.HeaderView.Backbone.View.extend.showCustom @ index.js:24r @ lodash.min.js:26p.event.dispatch @ jquery-1.8.0.min.js:2g.handle.h @ jquery-1.8.0.min.js:2
resolver.js:645 Method getMockSignature is deprecated
resolver.js:645 Methods createJSONSample and getSampleValue are deprecated
resolver.js:645 Method getMockSignature is deprecated
... (too many calls like this after...)
resolver.js:645 Methods createJSONSample and getSampleValue are deprecated
index.js:24 Uncaught TypeError: Cannot read property '0' of undefinedSwaggerUi.partials.signature.getInlineModel @ index.js:24SwaggerUi.partials.signature.createParameterJSONSample @ index.js:24SwaggerUi.Views.ParameterView.Backbone.View.extend.render @ index.js:24SwaggerUi.Views.OperationView.Backbone.View.extend.addParameter @ index.js:24SwaggerUi.Views.OperationView.Backbone.View.extend.render @ index.js:24SwaggerUi.Views.ResourceView.Backbone.View.extend.addOperation @ index.js:24SwaggerUi.Views.ResourceView.Backbone.View.extend.render @ index.js:24SwaggerUi.Views.MainView.Backbone.View.extend.addResource @ index.js:24SwaggerUi.Views.MainView.Backbone.View.extend.render @ index.js:24window.SwaggerUi.Backbone.Router.extend.render @ index.js:24options.success @ index.js:24SwaggerClient.buildFromSpec @ resolver.js:497Resolver.finish @ spec-converter.js:99Resolver.resolve @ spec-converter.js:8obj.on.response @ resolver.js:261responseInterceptor @ schema-markup.js:4obj.on.response @ schema-markup.js:8(anonymous function) @ schema-markup.js:220Request.callback @ index.js:24(anonymous function) @ index.js:24Emitter.emit @ index.js:24xhr.onreadystatechange @ index.js:24
```

Cheers,

**Comment by webron** [comment]
Can you share the spec so we can investigate it?

**Comment by cougil** [comment]
The spec? What do you mean with the spec? Do you mean the Json returned by the application?

**Comment by webron** [comment]
Yup.

**Comment by fehguy** [comment]
Please reopen with the spec that you're using.

**Comment by couds** [comment]
Im getting the same error. here my json file. I dont know how to generate the docs.. 

`
{
    "swagger": "2.0",
    "info": {
        "version": "0.0.1",
        "title": "Workflow system"
    },
    "basePath": "/api",
    "schemes": [
        "http",
        "https"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/test": {
            "get": {
                "x-swagger-router-controller": "workflow",
                "description": "Test Swagger",
                "operationId": "test",
                "responses": {
                    "200": {
                        "description": "default response",
                        "schema": {
                            "$ref": "#/definitions/Success"
                        }
                    },
                    "default": {
                        "description": "response other than",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/action/dispatch/": {
            "post": {
                "x-swagger-router-controller": "workflow",
                "description": "Fire an action",
                "operationId": "dispatch",
                "parameters": [
                    {
                        "name": "action",
                        "in": "body",
                        "description": "action to be fired",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Success"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/timeline/{timelineId}": {
            "get": {
                "x-swagger-router-controller": "timeline",
                "description": "Get a timeline",
                "operationId": "get",
                "parameters": [
                    {
                        "name": "timelineId",
                        "in": "path",
                        "description": "ID of timline to fetch",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Timeline"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/timeline/{timelineId}/activeStep": {
            "get": {
                "x-swagger-router-controller": "timeline",
                "description": "Get a timeline active step",
                "operationId": "getActiveStep",
                "parameters": [
                    {
                        "name": "timelineId",
                        "in": "path",
                        "description": "ID of timeline to fetch",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Step"
                            }
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/workflow/": {
            "post": {
                "x-swagger-router-controller": "workflow",
                "description": "Get a workflow",
                "operationId": "create",
                "parameters": [
                    {
                        "name": "workflow",
                        "in": "body",
                        "description": "The workflow label and definitions to instanciate the template",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/WorkflowDefinition"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/WorkflowCreated"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/workflow/create": {
            "post": {
                "x-swagger-router-controller": "workflow",
                "description": "Create a new a workflow using the timelines templates on the request",
                "operationId": "createCustom",
                "parameters": [
                    {
                        "name": "workflow",
                        "in": "body",
                        "description": "The workflow label and definitions to instanciate the template",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CustomWorkflowDefinition"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/WorkflowCreated"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/workflow/{workflowId}": {
            "x-swagger-router-controller": "workflow",
            "get": {
                "description": "Get a workflow",
                "operationId": "getWorkflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "workflowId",
                        "in": "path",
                        "description": "ID of workflow to fetch",
                        "required": true,
                        "type": "string",
                        "format": "ObjectID"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Workflow"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/swagger": {
            "x-swagger-pipe": "swagger_raw"
        }
    },
    "definitions": {
        "Step": {
            "properties": {
                "status": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "requires": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "Timeline": {
            "required": [
                "id",
                "name",
                "steps",
                "icon"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Step"
                    }
                }
            }
        },
        "WorkflowCreated": {
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "Workflow": {
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "timelines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Timeline"
                    }
                }
            }
        },
        "WorkflowDefinition": {
            "required": [
                "label"
            ],
            "properties": {
                "label": {
                    "type": "string"
                },
                "definitions": {
                    "type": "object"
                },
                "timelines": {
                    "type": "object"
                }
            }
        },
        "TimelineDefinition": {
            "required": [
                "id",
                "label"
            ],
            "properties": {
                "label": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "definitions": {
                    "type": "object"
                },
                "active": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                }
            }
        },
        "CustomWorkflowDefinition": {
            "required": [
                "label",
                "timelines"
            ],
            "properties": {
                "label": {
                    "type": "string"
                },
                "definitions": {
                    "type": "object"
                },
                "timelines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TimelineDefinition"
                    }
                }
            }
        },
        "Error": {
            "required": [
                "code",
                "message"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "Success": {
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}
`

on my app.js 

`
var SwaggerExpress = require('swagger-express-mw');
var SwaggerUi = require('swagger-tools/middleware/swagger-ui');
var app = require('express')();
module.exports = app; // for testing

var config = {
  appRoot: __dirname // required config
};

SwaggerExpress.create(config, function(err, swaggerExpress) {
  if (err) { throw err; }

  app.use(SwaggerUi(swaggerExpress.runner.swagger));
  // install middleware
  swaggerExpress.register(app);

  var port = process.env.PORT || 3000;
  app.listen(port);
});

`

**Comment by hmonadjem** [comment]
having the same problem ... the swagger editor tells me that everything is fine ...

**Comment by meeximum** [comment]
have the problem too

**Comment by ricardona** [comment]
Same here too!
