### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by nammoncs-11** [swagger-api/swagger-js#722]
how  to enable Access-Control-Allow-Origin ?

**Comment by gaah666** [comment]
Yes, I need this too!

My setup: 
Backend running on tomcat using spring for rest api with springfox to enable swagger.
Frontend angular driven SPA running on apache 2 web server. Here I wish to use swagger-js to help me implement one layer of the rest api on frontend. 
Backend and frontend running on different virtual servers.

Enabling CORS in backend is cake, but I see no way to do this with swagger-js? 
TBH I don't know if the server side setup I did works yet, but by just looking at the request headers in chrome the required CORS stuff isn't there.

**Comment by webron** [comment]
Enabling CORS is a back-end thing. swagger-js is a client. Not really relevant.
