### ISSUE TITLE
Readme shows camelcase operations but I can't seem to get this package to give me this format

### ISSUE THREAD

**Issue by colwem** [swagger-api/swagger-js#724]
From readme
```
  client.pet.getPetById({petId:7})
```
But I either can't find the option that will generate camelcase type operations or this is out of date or something.  When I run this I would get
```
  client.pet.pet_petId_GET({petId:7})
```

**Comment by fehguy** [comment]
You should use the `operationId` in your spec.  If that doesn't exist, you'll get ugly, auto-generated methods.

**Comment by fehguy** [comment]
Please reopen with any issues.
