### ISSUE TITLE
Forced Async

### ISSUE THREAD

**Issue by briananderson1222** [swagger-api/swagger-js#725]
Is there any reason why we are forced to use the SwaggerClient in an asynchronous way? If I have a spec that I am passing in (not from a URL), the result of instantiating a new SwaggerClient should return the client itself. It looks like if you don't pass 'usePromise' this is the case.. but for some reason the code still requires you to provide a 'success' callback in the absence of 'usePromise' in order for it to build the spec.

**I am going to add a PR to highlight the lines I am talking about.**

**Comment by fehguy** [comment]
Per the PR, I think best we close this out in an effort to keep behavior consistent between modes.
