### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by briananderson1222** [swagger-api/swagger-js#729]
This project could really benefit from some extra documentation. For example, digging around in the code I found out that I can actually implement my own HTTP Client by passing in a client option which I have done to wrap angular's $httpProvider for my angular implementation so that my service calls can be intercepted easily using a single interceptor.

**Comment by fehguy** [comment]
Thanks, and agreed that documentation can be improved.

**Comment by Ondoher** [comment]
In fact, this is such a useful feature, it should be made a first class citizen of the API. To get this to work I had to override `SwaggerHttp.prototype.execute` and modify opts.client. Not the most elegant way of handling this.

**Comment by briananderson1222** [comment]
I agree. This is a super useful feature that is not documented anywhere. I didn't want to have to define multiple interceptors throughout my angular application so I wrote a little angular wrapper like this:

```
class AngularSwaggerHttpClient {
  constructor($http) {
    this.type = 'AngularHttpClient';
    this.http = $http;
  }

  execute(obj) {
    obj.deferred = {
      promise: this.http({
        url: obj.url,
        method: obj.method,
        data: obj.body,
        params: obj.params,
        headers: obj.headers
      })
    }
  }
}
```

And then I create an angular factory with the following:

```
class HttpClient {
  static SwaggerClient($http) {
    'ngInject';
    return new SwaggerClient({
      spec: swaggerJson,
      client: new AngularSwaggerHttpClient($http)
    });
  }
}
```

One little caveat is that the above code relies on https://github.com/swagger-api/swagger-js/pull/728 because as you can see it is creating the SwaggerClient synchronously based on the provided spec.

**Comment by mbana** [comment]
Thanks, my vote is for this library: https://github.com/github/fetch.

**Comment by nucleardreamer** [comment]
@briananderson1222 do you have any current examples of this on github?

**Comment by briananderson1222** [comment]
@nucleardreamer not publicly :) but I have implemented it on an Ionic application and an Angular web app with no issues.

**Comment by shamas** [comment]
How do parameters on the execute function work?
Is execute with parameters the exact same as using the tag interface execute?
What happens if we pass multiple objects to the tag interface execute function?
How are we meant to override headers using the execute interface?

**Comment by xunxky** [comment]
actually WHERE is the documentation? it lacks documentation completely!

**Comment by char0n** [comment]
Created first [PR](https://github.com/swagger-api/swagger-js/pull/1506) that should increase the documentation coverage and quality of our documentation. I've started with a `Swagger specification resolver`.

**Comment by char0n** [comment]
@briananderson1222 thanks for angular example. At this point there is an example in our documentation how to implement custom fetch mechanism: https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md#custom-fetch

Replacing entire HTTP Client is also possible, by supplying `fetch` or `http` option as documented here: https://github.com/swagger-api/swagger-js/blob/master/docs/usage/openapi-definition-resolver.md#options

Feel free to submit your Angular example as into our [examples](https://github.com/swagger-api/swagger-js/tree/master/examples) directory as a PR.

**Comment by char0n** [comment]
Hi @shamas let me provide answers to your questions.

> How do parameters on the execute function work?
> Is execute with parameters the exact same as using the tag interface execute?
> What happens if we pass multiple objects to the tag interface execute function?
> How are we meant to override headers using the execute interface?
