### ISSUE TITLE
Per Request Authorization

### ISSUE THREAD

**Issue by markmarkoh** [swagger-api/swagger-js#744]
The resolution of https://github.com/swagger-api/swagger-js/issues/146 seems to show how to do per client authorization, but doesn't mention per request authorizations.

I have userA with a token "abc", and userB with a token "def", and a single Swagger client instance behind an Express API. Tokens are stored for users in a cookie and included with a request to the Express API. The Express API wants to pass the request & token through to the Swagger client.

I can't add a `clientAuthorizations` for userA or userB, since the entire client is affected with doing `clientAuthorizations.add`. I can't create a new client for every request since that takes too much time.

I've tried to handle it with `requestInterceptors` like this:

```js
api.user.operations.getAuthenticatedUser.requestInterceptor = function(obj) {
    this.headers['Authorization'] = obj.token;
    return this;
}
```

And calling the function like:

`api.user.getAuthenticatedUser()`, or `...getAuthenticatedUser({token: 'abc'})`, or `...getAuthenticatedUser(null, {token: 'abc'})`, but `requestInterceptor` doesn't get access to that object with `token` in it.

I've tried using a custom request signer, but I get the same issue:

```js
CustomHeaderSigner.prototype.apply = function(obj, authorizations) {
  obj.headers['Authorization'] = obj.options.token
}
```

None of the arguments sent to the custom signers (or `requestInterceptor`s) account for per-request level values.

Locally, I edited [`/lib/http.js`](https://github.com/swagger-api/swagger-js/blob/master/lib/http.js#L91) to add `opts` as a parameter to `requestInterceptor` (and a few lines above it at line ~54). and that works great. I can call `...getAuthenticatedUser(null, {token: 'abc'})`

Is there a cleaner solution that doesn't involve making this code change? (and doesn't involve using the swagger client in the browser, which isn't an option for us).

**Comment by DanielBodnar** [comment]
This has been to be a very frustrating limitation, especially in a node environment where one client != one session.

**Comment by fehguy** [comment]
The solution seems to be the ability to add authorization values or headers on each request.
