### ISSUE TITLE
Uses 'localhost' when no host specified in swagger file.

### ISSUE THREAD

**Issue by gerardabello** [swagger-api/swagger-js#748]
If the swagger-js client is running on a host (for example 5.5.5.5:44) and the swagger file is in the same host, I use:
```
var client = new Swagger({
    url:  "./swagger.yaml",
    ...
```
swagger.yaml does not contain a host definition. So when I try to do a request (In my case to '/oauth/token'), I expected the request url to be '5.5.5.5:44/oauth/token' but instead it is 'localhost/oauth/token'.

**Comment by fehguy** [comment]
so that's not really possible, because swagger.js doesn't have access to the `window.location` variable (it may be running in a node environment).
