### ISSUE TITLE
Question: Using swaggerjs synchronously 

### ISSUE THREAD

**Issue by hswolff** [swagger-api/swagger-js#751]
Howdy!

I'm looking to use the swagger-js client synchronously. However even when loading the spec from the initial `options` object (`new Swagger({spec: {}})`) the client is not instantiated until 10 seconds later due to a setTimeout defined here: https://github.com/swagger-api/swagger-js/blob/master/lib/client.js#L225  (I also did some [history digging to see when it was initially added and found what I think was the initial change](https://github.com/swagger-api/swagger-js/commit/958f4f97c31c28c01a8f0cc9463510e1023b5e8d)).

Is there a reason for the setTimeout of 10? Can we remove that to allow for truly synchronous instantiation of the client?

**Comment by fehguy** [comment]
Hi, first off, setTimeout is in milliseconds, not seconds.  Next, the setTimeout was introduced to have the same behavior as the async loading from the network.  This makes it transparent between the object-based and network-based calls.

So i suggest using promises or getting used to async on the client.  It's really hard to have a good interface without callbacks.

**Comment by hswolff** [comment]
Sorry about the seconds/milliseconds typo.

I'm fine using promises and async interfaces however most libraries support a sync mode as well. I'd fully understand if there was a restriction due to architecture, but in this case it seems like an artificial constraint put into the library.

The API that you would interact with remains the same, except it would be called without the artificial 10 millisecond delay.

Would you be open to removing the setTimeout of 10 and/or be open to adding a new method like `Swagger.sync({options})` which doesn't allow for a url property? If so I'd be happy to collaborate to make that happen!

**Comment by fehguy** [comment]
I really want to keep the behavior the same between network and objects.  The 10ms delay is probably more than it needs to be, it could be 1.  If we introduce another configuration, it's another path to break.

**Comment by hswolff** [comment]
Not to beat this to death, but if you are instantiating an Swagger client from a url or from an object, then isn't that behavior already different? Why would different input produce different the same output?

**Comment by fehguy** [comment]
it's behavioral.  The client can pass an object or a URL and expect exactly the same behavior.

**Comment by hswolff** [comment]
Alrighty.

Anyway we can introduce some sync behavior? Otherwise I'll [stick to my fork](https://github.com/TodayTix/swagger-js/commit/6b93c2f34e2315dfc400c2f7e789049dce14f533) but would love to see this upstream.

**Comment by briananderson1222** [comment]
The functionality I introduced in my pull request allows the library to continue working in the exact same way that it did previously via a success callback and promise if wanted. It simply provides an additional synchronous spec creation. 

If there is a way to make this behavior synchronous wouldn't that be preferred? I understand the want for having consistent behavior, but I agree with @hswolff that this is completely unnecessary. Think about the scenario like in an angular application where I now have to purposefully introduce an asynchronous delay just to bootstrap my application just because of an artificial constraint by this library. 

At the very least can this be a future consideration rather than just dismissing it as behavioral?

**Comment by fehguy** [comment]
OK I'll need to ensure that this doesn't break anything.  I guess we can get it in, but the lack of a callback was an issue for swagger-ui and other clients.  I'm not sure that it's in the tests though, so even with the successful test exectution here, it may still break some clients.

**Comment by briananderson1222** [comment]
I definitely understand the necessity of wanting to be completely backwards compatible. I don't want to rush this either, just wanted to start the conversation and give a little insight into how I solved the issue for my project. At this current moment all the unit tests are passing in my PR but if you can think of some other scenarios that I should test I am willing to add more test cases. I definitely didn't spend as much time in that area

**Comment by fehguy** [comment]
I'm going to close this out.  When we refactor the library for the next version we will consider this.

**Comment by viliam-jobko** [comment]
@hswolff, @briananderson1222: If you are still looking for way to create swagger-client synchronously, I created this package for it: https://www.npmjs.com/package/swagger-client-sync

**Comment by DannyDelott** [comment]
@fehguy Happy 2020! This is a great library, and it's been a few years now.. any update or changes of opinion on the ability to create the SwaggerClient synchronously from the spec object? This is a common pattern for api client libraries (eg: Apache Thrift) and from this discussion the only blocker seems to be:

> I really want to keep the behavior the same between network and objects. 

As others have mentioned, we also pass the full spec to the constructor, so it's not clear why we would receive a promise back-- plus, it forces the rest of our bootstrapping process to be async in an unintuitive way. 

What does the consistency in output buy us given the cost to developer expectations and general ergonomics? Passing the promise of the SwaggerClient around introduces misdirection for questionable benefit. Are there use cases that wouldn't support @briananderson1222's additive approach for a synchronous constructor?
