### ISSUE TITLE
Only create deferredClient if usePromise is true?

### ISSUE THREAD

**Issue by jchip** [swagger-api/swagger-js#752]
Would it make sense to move this https://github.com/jchip/swagger-js/blob/master/lib/client.js#L102

to here

https://github.com/jchip/swagger-js/blob/master/lib/client.js#L132?

AND change it to:

```js
  if (this.usePromise) {
    this.deferredClient = Q.defer();
  }
```

**Comment by fehguy** [comment]
Yea, i think you're right.
