### ISSUE TITLE
Pass promise library to Swagger constructor

### ISSUE THREAD

**Issue by artemjackson** [swagger-api/swagger-js#758]
Hello!

I'd like to do something like this
```
var promise = require('bluebird');
var Swagger = require('swagger-client')(promise);
```
Actually, it's needed for integration of Swagger with Angularjs lifecycle, where all is dependent on `$digest` cycle that angular `$q` promise library handles.

**Comment by artemjackson** [comment]
Or even better, can I pass custom http to Swagger constructor? E.g. angular's `$http`

**Comment by fehguy** [comment]
That's your best bet, take a look at the tests, you can create a custom http client.

**Comment by artemjackson** [comment]
Awesome! Thanks! I missed this option.
