### ISSUE TITLE
DEL http method used instead of DELETE

### ISSUE THREAD

**Issue by jessedobbelaere** [swagger-api/swagger-js#764]
Noticed that my swagger api explorer was using DEL http methods in the requests (which return a 405 method not allowed) instead of actual DELETE http methods. Removing these lines in swagger fixed the issue. Can we remove these 3 lines? Is it still needed for SuperAgent? Or what was the reason?

https://github.com/swagger-api/swagger-js/blob/master/lib/http.js#L199-L201

**Comment by fehguy** [comment]
Both should work, but it seems you're experiencing otherwise:

https://github.com/visionmedia/superagent/issues/605
