### ISSUE TITLE
allow user to pick a promise lib

### ISSUE THREAD

**Issue by jchip** [swagger-api/swagger-js#766]
Having this module explicitly depend on Q is an inconvenience when user doesn't want to use Q.  The browser version also packs a copy of Q, even if we don't want to use Promise or want to use another Promise polyfill.

Would you consider removing explicit dependence on any specific Promise implementation, and allow user to supply a polyfill?  

Some ideas:
- expose a `swaggerClient.Promise` that user can set but assign global Promise to it by default.
- If Promise is not defined, then throw error if usePromise is true.

Q.defer can be implemented using the ES6 Promise:

``` js
function defer() {
  var deferred = {};
  deferred.promise = new Promise(function (resolve, reject) {
    deferred.resolve = resolve;
    deferred.reject = reject;
  });

  return deferred;
};
```

This change would require a major version bump.

**Comment by fehguy** [comment]
We're working on this for the next version.

**Comment by mbana** [comment]
Thanks. Would be nice to use this https://github.com/stefanpenner/es6-promise.

**Comment by sebinsua** [comment]
The best way of doing this is with: [`any-promise`](https://github.com/kevinbeaty/any-promise)

**Comment by fehguy** [comment]
This has been done in the 3.x version.
