### ISSUE TITLE
Maybe we should add errorInterceptor?

### ISSUE THREAD

**Issue by yoihito** [swagger-api/swagger-js#767]
Hey, guys! 
I found out that there are reponseInterceptor and requestInterceptor. It is possible to handle on.error in requestInterceptor [here](https://github.com/swagger-api/swagger-js/blob/1bc83e2a870ca010e0f7222ef069e32a7096340c/test/client.js#L595) , but it's impossible to handle errors with responseInterceptor. I think it would be helpful to add errorInterceptor. 

What do you think?

**Comment by fehguy** [comment]
doesn't `responseInterceptor` trigger during any response, including errors?  Please elaborate on what it's not doing correctly, because the intent is for that to handle errors as well.

**Comment by yoihito** [comment]
@fehguy `on.reponse` callback is overwritten [here](https://github.com/swagger-api/swagger-js/blob/ef1ad2ae16925c45a235da7e4b6b7914c2e8f9e7/lib/http.js#L59-L77) in swagger-js. It would be nice to add a similar thing for `on.error`. 
I'm using `requestInterceptor` right now. These are properties for `SwaggerClient`:
```es6
    const swaggerClientProps = {
      url: this.props.swaggerApiUrl,
      usePromise: true,
      requestInterceptor: {
        apply: (request) => {
          const errorHandler = request.on.error;
          request.on.error = (res) => {
            const modifiedRes = this.onSwaggerApiError(res);
            errorHandler(modifiedRes);
          };
          return request;
        }
      }
    };
```

**Comment by fehguy** [comment]
Yes but to catch error conditions you want a response handler. And the responseHandler is called for 'on.response' so I would think it's covered, no?
