### ISSUE TITLE
URL-Based Queues

### ISSUE THREAD

**Issue by indolering** [swagger-api/swagger-js#768]
I would like to prevent race conditions with Ajax requests and some googling indicates that queuing edits (so that each is sent only after the others have completed) is the standard solution.  Since most REST APIs have a single URL for each resource, I was thinking of automatically adding a queue based on each URL.

There appears to be a few jQuery plugins that do this, but nothing for superagent.  However, I think it would probably be more efficient to place this into the standard library.

Would a PR for this functionality be welcomed?    Obviously, any such enhancements would be optional.

Edited for clarity.

**Comment by fehguy** [comment]
Hi, interesting.  But I think that sort of layer belongs on top of swagger-js, meaning the library is thread safe, and having concurrent operations run inside it shouldn't be any issue.  Is your primary use case around swagger-ui or some other client-side app?

**Comment by indolering** [comment]
A client side app.  I'm no longer interested in working on this.
