### ISSUE TITLE
tsv arrays seem broken but easy to fix

### ISSUE THREAD

**Issue by dkottow** [swagger-api/swagger-js#769]
Hi,

I have an API where I use a TSV string to hold a query parameter that represents an array of values. I believe, the swagger client does not generate a proper URL when trying to call the endpoint.

I am attaching my swagger.json as well as a fix. 
[tsv.zip](https://github.com/swagger-api/swagger-js/files/253651/tsv.zip)
It seems just a matter of replacing the \t by its urlencoded value, %09 when defined in the source code. Let me know if you need the fix done differently.

Greetings
Daniel

**Comment by fehguy** [comment]
@dkottow i believe you're right, the `\t` is not allowed in a query param.  Can you please send a PR?

**Comment by dkottow** [comment]
sure, done [here](https://github.com/swagger-api/swagger-js/pull/770).

**Comment by fehguy** [comment]
Fixed in https://github.com/swagger-api/swagger-js/pull/770
