### ISSUE TITLE
Maximum call stack exceeded between 2.1.10 and 2.1.11

### ISSUE THREAD

**Issue by djMax** [swagger-api/swagger-js#773]
Same swagger docs in both cases. It has something to do with definitions, as I can fix it by removing them all, but even a single one, seemingly no matter how simple, will fail.

```
/myproject/node_modules/swagger-client/lib/resolver.js:523
      var o = this.getRefs(item);
                   ^

RangeError: Maximum call stack size exceeded
    at Resolver.getRefs (/myproject/node_modules/swagger-client/lib/resolver.js:523:20)
    at Resolver.getRefs (/myproject/node_modules/swagger-client/lib/resolver.js:523:20)
    at Resolver.getRefs (/myproject/node_modules/swagger-client/lib/resolver.js:523:20)
    at Resolver.getRefs (/myproject/node_modules/swagger-client/lib/resolver.js:523:20)
    at Resolver.getRefs (/myproject/node_modules/swagger-client/lib/resolver.js:523:20)
    at Resolver.getRefs (/myproject/node_modules/swagger-client/lib/resolver.js:523:20)
    at Resolver.getRefs (/myproject/node_modules/swagger-client/lib/resolver.js:523:20)
```

**Comment by fehguy** [comment]
Hi, can you please share a spec?  We have a lot of tests around this but would like to see what's triggering this issue.  FYI we're on 2.1.14 now.

**Comment by djMax** [comment]
Yeah, that's what's confusing the hell out of us - this was working a week ago, and 2.1.10 is much older. Working on isolating such that we could post some reasonable spec.

**Comment by fehguy** [comment]
OK happy to help if you can share a definition, even privately.  I'm currently working on a release of swagger-js right now, so it could be fast.

**Comment by djMax** [comment]
```
{
  "swagger": "2.0",
  "info": {
    "version": "0.0.1"
  },
  "paths": {
    "/token": {
      "post": {
        "description": "Create a token for sensitive payment information"
      }
    }
  },
  "definitions": {
    "Foobar": {
      "type": "object",
      "required": [
        "token"
      ],
      "properties": {
        "token": {
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by djMax** [comment]
Here's the other trick - you have to load two swagger docs, of which this should be one.

**Comment by fehguy** [comment]
Then I don't really understand.  Can you explain that more?  Perhaps with a test?

**Comment by djMax** [comment]
@jasisk says it's this line https://github.com/swagger-api/swagger-js/blob/edf58820cca52149a76acf296783439c513a51b6/lib/types/operation.js#L150

**Comment by jasisk** [comment]
I'm actively diagnosing but will try to provide more info and a test case as soon as I can.

**Comment by djMax** [comment]
Here's the (abridged) way it's loaded:

```
function loadService(services, name) {
      const client = new Client({
        url,
        spec: require(name),
        usePromise: true,
      });
      services[name] = (await client).apis.default;
}
```

**Comment by djMax** [comment]
It has something to do with usePromise

**Comment by fehguy** [comment]
Can you just update to 2.1.14 or better yet, master?  I'm afraid I just don't have enough info to even reproduce this.

**Comment by djMax** [comment]
It happens there too. We're digging. It seems that the constructor returns a promise in usePromise case? A bit odd... My guess is that's messing with scopes somehow.

**Comment by djMax** [comment]
Now seems babel-related...

**Comment by djMax** [comment]
And in the end, it appears to be pg-promise. If I require that, this happens. If not, it doesn't. Yeesh.

**Comment by vitaly-t** [comment]
Sorry about the trouble, the issue has been fixed in `pg-promise` ;)

**Comment by fehguy** [comment]
Great, thanks for the follow up
