### ISSUE TITLE
Handle 401 HTTP code with meaningful error message

### ISSUE THREAD

**Issue by ojauch** [swagger-api/swagger-js#776]
I'm using Swagger UI with a api key that the user inputs. If he inputs a wrong client id the server where the swagger file is stored responds with a 401 response. Currently swagger-js just returns the http code and the json error message that comes from the server. But I think it would be nicer if it handles this error like a 404 code with an error message like: "Access to swagger json denied".

**Comment by fehguy** [comment]
I don't really know how we would make this behavior consistent across different API implementations.  I'm going go close this out, we can reopen with more info and a proposal on how to make this general across other implementations.
