### ISSUE TITLE
initially login the forward acquired (jwt) token

### ISSUE THREAD

**Issue by mbana** [swagger-api/swagger-js#777]
Hi, I've been playing with the browser-based library and it is pretty cool:

* Is it possible to do an initial login using a username and password on the same server that the JWT token is retrieved from then forward this to the ``SwaggerClient``? My current flow is something like; a. do request to get a jwt token inside of the ``then`` callback of ``SwaggerClient`` then set up the client using it like:

    client.clientAuthorizations.add('apiKey', new SwaggerClient.ApiKeyAuthorization(..., ..., ...));

It is sorta weird that I have to do the calls separately since the spec file also contains the authentication routes as well.

* Any future plans on supporting JWT?
* Would be doubly-nice if ES6-Promises were used as well ;)
* I am having a very strange debugging experience; I think two of the files might be minified as the debugger is confused in the non-compressed version.

Thanks a lot,

**Comment by fehguy** [comment]
You have three choices--
1.  Set up the client with authorization information.  You'll need that when initializing it, of course
2.  Add authorization after the client is created by adding them to an existing client.  Note, that of course means if authorizations are needed when reading the swagger definition, it will fail
3.  Add authorizations on a per-request basis.  Then you can reuse the same client for multiple auth schemes, users, etc.

**Comment by fehguy** [comment]
Unless you have any other questions on this, I'll close it out.
