### ISSUE TITLE
rendering schemas to human readable

### ISSUE THREAD

**Issue by lucidtech** [swagger-api/swagger-js#779]
Hi - this is a question - not an issue... I don't see a place for questions.

I have written an interactive UI for a swagger defined API.  And it works great - JS loads the model - iterates through and builds the UI etc... the only thing I am stumped with is rendering the response schema.  In my front end I iterate and explore the schema definitions - but never quite get it right.  I find functions like schemaToHtml in the lib - but I am not smart enough to figure out if they do what I want or how to call them and with the right params.

The commits and discussions seem to indicate that this functionality is there in the client - can anyone point me to some docs or examples that can help me figure out how to use it?

Thanks so much

**Comment by fehguy** [comment]
Yes but it is being removed so please don't rely upon it

**Comment by fehguy** [comment]
Right now, the swagger-js client is turning models into two internal types, one being a JSON Schema object.  You can grab those easily:

```
var models = swaggerClient.models['Order'].definition;
```

And when done in the petstore, you get a nice JSON schema, which you can render with lots of different renderers:

`JSON.stringify(api.models.Order.definition, null, 2)`

gives:

```json
{
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "petId": {
      "type": "integer",
      "format": "int64"
    },
    "quantity": {
      "type": "integer",
      "format": "int32"
    },
    "shipDate": {
      "type": "string",
      "format": "date-time"
    },
    "status": {
      "type": "string",
      "description": "Order Status",
      "enum": [
        "placed",
        "approved",
        "delivered"
      ]
    },
    "complete": {
      "type": "boolean",
      "default": false
    }
  },
  "xml": {
    "name": "Order"
  },
  "id": "order",
  "name": "Order"
}
```
