### ISSUE TITLE
Allow override of scheme (for example 'http' or 'https')

### ISSUE THREAD

**Issue by wapolinar** [swagger-api/swagger-js#782]
Similar to #532, it would be nice if you could not only override the 'host' or the 'basePath', but also the scheme (usually 'http' or 'https'). This makes it easier to have a scenario where you use the same (production) swagger file also for debugging (localhost->http instead of server_name->https).

**Comment by fehguy** [comment]
You can use `SwaggerClient.prototype.setSchemes`:

```
var client = new SwaggerClient()...
client.setSchemes(['http']);
```

**Comment by wapolinar** [comment]
Ok, I tried that, but it is ignored (following the example):
````
       var Swagger = require('swagger-client');
        var client = new Swagger({
            url: swaggerUrl,
            success: function() {
                client.prototype.setSchemes([window.location.protocol]); //This does not work
                client.setHost(window.location.host);... //This works
````
The swaggerUrl contains a swagger.json with:
````
  "host" : "localhost:8081",
  "basePath" : "/myBasePath/api",
(...)
  "schemes" : [ "http" ],
````
The host can be changed successfully, but the call still uses http instead of (in this case) https.

**Comment by fehguy** [comment]
I can guarantee you that it works.  What version of swagger-client are you using?

**Comment by wapolinar** [comment]
Yes, it works, sorry that I bothered you again.

I tested it on the wrong method, realized that today and planned to do a new test today and extend/correct my reply.

So I did a new test just now, everything is working fine.

**Comment by fehguy** [comment]
no problem, thanks for the follow-up

**Comment by kavanat** [comment]
Can you please tell what should be the parameter that should be passed to this method var client = new SwaggerClient(). I have made same changes but still it is taking reques url as http
