### ISSUE TITLE
Cannot properly rendering responses -> schema -> allOf

### ISSUE THREAD

**Issue by dgofman** [swagger-api/swagger-js#783]
I have to handle pagination across all GET API's
The common signature is
```
{
    offset: number,
    limit: number,
    total: number,
   result: [
   ]
}
```
However "result" contains for each GET different inner object(s) (User, UserProfile, Application, Group, etc.)
So, here is sample of two definitions:
```
definitions:
  PaginationHeader:
    type: object
    properties:
      offset:
        type: number
      limit:
        type: number
      total:
        type: number
  User:
    type: object
    properties:
      id:
        type: number
      name:
        type: string
      active:
        type: boolean

Now in each response I am trying combine PaginationHeader + result Object
      responses:
        "200":
          description: Success
          schema:
            allOf:
              - $ref: '#/definitions/PaginationHeader'
              - properties:
                  result:
                    type: array
                    items:
                      $ref: '#/definitions/User'
```
No Errors.
But in editor I can see undefined, and I can expand result but not RaginationHeader

![image](https://cloud.githubusercontent.com/assets/147298/15695691/a45d9a96-275e-11e6-9fae-c7141ed68332.png)

And UI just empty object
![image](https://cloud.githubusercontent.com/assets/147298/15695658/419d964a-275e-11e6-912a-debd26fd93ec.png)

Whats wrong and how can I fix it?

**Comment by fehguy** [comment]
What version of the UI are you using?  This scenario should be supported already.

**Comment by fehguy** [comment]
Please take a look at this test, which should reproduce what you're trying to do:

https://github.com/swagger-api/swagger-js/blob/issue-783/test/composition.js#L401

The properties exist as expected, so perhaps you're not using master of swagger-ui?

**Comment by dgofman** [comment]
I don't see syntax is wrong I copied pasted your code, but error on UI and in Editor

```
{
  "swagger": "2.0",
  "info": {
    "version": "0.0.1",
    "title": "Test"
  },
  "paths": {
    "/foo": {
      "get": {
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/PaginationHeader"
                },
                {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "array",
                      "items": {
                        "$ref": "#/definitions/User"
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        "security": []
      }
    }
  },
  "definitions": {
    "PaginationHeader": {
      "properties": {
        "offset": {
          "type": "integer",
          "format": "int32"
        },
        "limit": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "User": {
      "properties": {
        "name": {
          "type": "string"
        }
      }
    }
  }
}
```

![image](https://cloud.githubusercontent.com/assets/147298/15797394/67211a12-29cb-11e6-9f95-b3692b8a5413.png)

**Comment by fehguy** [comment]
OK that's swagger-editor, which does not use this library.  I suggest you open an issue in that project.  For swagger-ui, we get what is expected:

![image](https://cloud.githubusercontent.com/assets/249413/15805705/0368c246-2ae7-11e6-9bb9-a066b8a15b78.png)

**Comment by Maxooo** [comment]
Hi,
Is there anything new on this behavior (a reference to a new ticket for example) ?
This problem seems to be still relevant.

Thank you.
