### ISSUE TITLE
Undocumented default tag for operations

### ISSUE THREAD

**Issue by deckar01** [swagger-api/swagger-js#788]
> I think https://github.com/swagger-api/swagger-ui/issues/605 incorrectly fixed a UI bug by patching `swagger-js`.
> 
> ... the spec doesn't require [operations](http://swagger.io/specification/#operationObject) to have tags and doesn't document a default value ...

https://github.com/swagger-api/swagger-ui/issues/1311#issuecomment-224439277

`swagger-js` should probably match the spec and not provide an undocumented default value for operation tags.

**Comment by fehguy** [comment]
Unfortunately there are features in swagger-js which require a tag or the client won't work correctly.  So we have to add the `default` tag.

**Comment by deckar01** [comment]
Thanks for looking at this.

I thought `swagger-js` was a "library to connect to swagger-enabled APIs". Injecting extra data into the response does not seem to be within the scope of this project.

The implicit "default" tag could collide with a project's existing tags causing untagged operations to get mixed in with operations explicitly tagged "default".

The spec allows for empty tag lists, but `swagger-js` does not.

> Note! We will not merge pull requests for features not supported in the OAI Specification! Add an issue there instead!

**Comment by fehguy** [comment]
Sorry!  since all operations require a tag associated with them, I think it would be far worse to remove this behavior than to document it as a known issue.  Feel free to help with a work-around, fix, via PR.

**Comment by deckar01** [comment]
Adding a configuration value (`defaultTag`?) for the default tag name would help avoid collisions. Maybe setting it to `false` could disable the behavior.

I can see why making tags required would enforce good organizational habits. Maybe `defaultTag` should be requested as part of the spec.
