### ISSUE TITLE
Add an option to avoid cache effect

### ISSUE THREAD

**Issue by boly38** [swagger-api/swagger-js#792]
As discussed here: 
https://github.com/swagger-api/swagger-ui/issues/2203#issuecomment-225065423

I would like to avoid cache effect with Internet Explorer 
By default, IE will cache json answer and If I do this sequence on a CRUD ReST API I've not the expected result
- get items => res A
- post new item => res B
- get items => res C

In my case, res A == res C but a new item is expected as res B is a success (I don't reproduce on another browser than IE).

@fehguy suggest:

Create a request interceptor and set the headers before the request is sent:

```
var interceptor = {
  requestInterceptor: {
    apply: function (requestObj) {
      var headers = request.Obj.headers || {};
      headers['If-Modified-Since'] = 'Mon, 26 Jul 1997 05:00:00 GMT';
      headers['Cache-Control'] = 'no-cache';
      headers['Pragma'] = 'no-cache';
      return requestObj;
    }
  }
};

// assign the request interceptor in the UI
new SwaggerClient({
      url: 'http://localhost:8000/v2/petstore.json',
      requestInterceptor: interceptor.requestInterceptor,
```

I have not tested this solution but I like it.
As it is a common issue, I would like this as an option.

**Comment by wsaxton** [comment]
I also seem to having this problem in Chrome.  

When I call the web service directly via CURL, I verify that it hits the database and responds.

When I call the web service via swagger-ui "Try it out!", I get stale data.

**Comment by RehanSaeed** [comment]
@boly38 I think disabling cached responses should be the default option. Perhaps you should raise a PR with your small fix in it. Also, any idea where to add that code?

**Comment by boly38** [comment]
Hello @RehanSaeed 
here is  the way I've added cache control to the header. I'm using authorization config.
I'm maybe on an old version of swagger and I think my way is maybe not the good way to do that (little bit confusing to use Authorization config in order to set cache control header). That's why I would like to keep this improvment to swagger commiters: let them deciding the good way on how to do that integration.


```
var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("Authorization", "Bearer " + key, "header");
var apiKeyCacheA = new SwaggerClient.ApiKeyAuthorization("If-Modified-Since", "Mon, 26 Jul 1997 05:00:00 GMT", "header");
var apiKeyCacheB = new SwaggerClient.ApiKeyAuthorization("Cache-Control",     "no-cache", "header");
var apiKeyCacheC = new SwaggerClient.ApiKeyAuthorization("Pragma",            "no-cache", "header");

window.swaggerUi = new SwaggerUi({
	authorizations: {
		key:keyAuth,
		cacheA:apiKeyCacheA,
		cacheB:apiKeyCacheB,
		cacheC:apiKeyCacheC
	},
	url: url,
	(...)

```

**Comment by ahashem** [comment]
In 2.x can we use the `middleware.swaggerMetadata()` to intercept and add the no-cache headers?

**Comment by javaworkinggirl** [comment]
Any updates on this?  Swagger is an excellent tool and to have testers use it, we need this fixed.  Thanks.

**Comment by achuth-amplify** [comment]
Can we please look into this ? We are having the same issue.

**Comment by webron** [comment]
We're not actively working on the 2.x version. If someone submits a PR we'll try to review it.

**Comment by achuth-amplify** [comment]
@webron does upgrading to 3.x fix this issue ?

**Comment by webron** [comment]
I couldn't say.

**Comment by shockey** [comment]
I just gave this a quick test, and it doesn't seem to be an issue in 3.x. Here's how I did it:

1. open http://editor.swagger.io/ (Swagger-Editor uses Swagger-Client behind-the-scenes)
2. load the definition below
3. execute try-it-out twice, and observe that the current time is returned both times (no cached response)


```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: HTTPBin Current Time
  description: |
    Fetches the current time from HTTPBin - good for cache testing in tooling.
    
    You'll need to disable CORS since HTTPBin doesn't support it - these Chrome command-line flags will do it\: `--disable-web-security --user-data-dir`
  termsOfService: terms
host: now.httpbin.org
schemes: [https]
paths:
  /:
    get:
      summary: Get the current time
      responses:
        '200':
          description: the time
```

---

I'm going to close this - if anyone using 3.x encounters a caching issue, please open a new ticket and reference this one.

Thanks, everyone!

**Comment by schof** [comment]
I'm actually still seeing this problem in swagger-ui v3.20.2. In my case changes to an schema definition that uses `$ref`.

**Comment by shockey** [comment]
@schof please open an issue in Swagger UI, I'd love to hear more about this case!

**Comment by mazh-jarvis** [comment]
For me I had to manually delete `SwaggerConfig.class` and rebuild

**Comment by kritibharadwaj** [comment]
I am using @ref tag to embed the yaml schema file. It loads it for the first time , but doesn't reflect any subsequent updates to that remote reference.

**Comment by DenisKnoepfle** [comment]
> I am using $ref tag to embed the yaml schema file. It loads it for the first time , but doesn't reflect any subsequent updates to that remote reference.

I can confirm this. I am experiencing exactly the same issues. Even force-refreshing the browser (CTRL+F5 under Chrome) does not refresh the stale referenced file. The only way to get it refreshed is to wipe out whole browser data cache.

**Comment by cleliofs** [comment]
In Chrome, there is an option to "disable" browser cache: 
![image](https://user-images.githubusercontent.com/1814628/122564827-b6991400-d03d-11eb-8a8e-4e24f25cc37a.png)

**Comment by m0x61h0x64i** [comment]
@cleliofs It only works if you open dev tools
