### ISSUE TITLE
Trouble Uploading File via Post

### ISSUE THREAD

**Issue by cwbuecheler** [swagger-api/swagger-js#793]
Greets,

I'm working with swagger-js in a React environment to connect to our swagger 2.0 API (of which I'm not the author). I've been able to get swagger-js working with no problems for things like authentication, but I'm having trouble with file uploading (I get a "400 - Bad Request" error), and I can't seem to tell what I'm doing wrong. I know the spec is right, because it works fine with swagger-ui. Here's my (slightly abbreviated) client code:

```javascript
const swaggerApi = new Swagger({
  url: `${API_URI}/swagger.json`,
  usePromise: true,
});
```
[and then later, in a function for posting files we're calling "layouts"]
```javascript
export function createLayout(layoutData, token) {
  return (dispatch) => {
    return swaggerApi
    .then((client) => {
      client.datasets.uploadLayout({
        Authorization: `bearer ${token}`,
        dataset_id: layoutData.datasetId,
        file: layoutData.file,
      })
      .then((response) => {
        if (response.status >= 200 && response.status < 300) {
          const layoutInfo = response.obj;
          dispatch(layoutCreateSuccess(layoutInfo));
          reportSuccess(dispatch, 'New Layout Uploaded', null);
        }
      })
      .catch((err) => {
        const statusText = JSON.parse(err.statusText);
        const error = new Error(statusText.message);
        reportError(dispatch, error);
      });
    });
  };
}
```
the file referenced in `layoutData.file` is created elsewhere using `new formData()` -- I had this working using [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) instead of swagger-js, but we're hoping to switch to the latter. Here's the working fetch snippet, for reference:
```javascript
return fetch(Routes.createLayout(layoutData.datasetId), {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        Authorization: `bearer ${token}`,
      },
      body: layoutData.file,
    })
```

I'm wondering if there's something blatantly obvious that I'm doing wrong in the code? I've tried `body: { file: layoutData.file }`, `body: layoutData.file`, and various other possibilities, but nothing seems to actually send a body with the request.

Thanks!

**Comment by fehguy** [comment]
Hi, i've been working on this just recently.  To upload files with swagger-js, _only_ browser environments are currently supported (you should be OK with that) and they require that jQuery is enabled (you might not like that).  I'm almost done making this work via superagent which would remove that requirement.

For file uploads, you should be passing the File object to the javascript client, which it looks like you are.  What is the file "type"?  And have you specified that you're uploading using `multipart/form-data`?

**Comment by cwbuecheler** [comment]
Awesome, thanks for the info. I don't have jQuery enabled so that's probably the issue. Superagent would be preferable but I think I can work around it for now (this won't be a production app for a couple months anyway).

The headers I'm sending seem to indicate that, yes, it's multipart/form-data. This is what the dev tools are showing:

```javascript
Accept:application/json
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,fr;q=0.6
Authorization: (bearer token)
Connection:keep-alive
Content-Length:0
Content-Type:multipart/form-data
```

I'll enable jQuery and see if I can get it working. Thanka again.

**Comment by fehguy** [comment]
OK just pushed a fix to allow the Form elements to be sent w/o jquery, tested in a simple react app.

**Comment by cwbuecheler** [comment]
Fantastic, thank you!
