### ISSUE TITLE
Missing separator between prefix and path

### ISSUE THREAD

**Issue by ramiel** [swagger-api/swagger-js#800]
With the latest version this url is generated
`http://localhost:8888/v1carts/`
and a `/` is missing between `v1` and `carts`. I was able to identify that the problem has been introduced on commit #cbc384bc6b36e224093f6f93bb671988b9424280 but I'm not able to identify which part.
Which information do you need to solve this?

**Comment by fehguy** [comment]
Please share the relevant part of your spec. I believe this is well tested but it would be helpful to see what is causing it for tou

**Comment by fehguy** [comment]
Closing as no further info provided
