### ISSUE TITLE
External reference to examples object

### ISSUE THREAD

**Issue by mdigirolami** [swagger-api/swagger-js#801]
In 
https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#examplesObject
I've seen that with release 3.0 of specifications will be possible to resolve external references for the "examples" object.

My question is this: is it possible to do this also with version 2.0 of specs/tools? I've tried with swagger-ui 2.1.4 but it seems to me that it doesn't work, the $ref is not resolved (see the attachments, in questionnaireAPI.json you can see the not-working $ref at line 48). Can you confirm/contradict me if/how it is possible to use this reference with current version of swagger tools.

Thanks in advance,
Marco

[questionnaireAPI_json.txt](https://github.com/swagger-api/swagger-js/files/326558/questionnaireAPI_json.txt)

![swaggerui-screenshot](https://cloud.githubusercontent.com/assets/12843872/16245672/3f5ddd86-3802-11e6-814b-460d039f0260.png)

**Comment by webron** [comment]
It's not possible to do that, and I don't think it'd stay that way in 3.0 as well. There's a technical difficulty there.

Looking at your own example:

```json
"application/json": {
                "$ref": "./questionnaire_example.json"
              }
```

Tell me, is the example what's referenced or is it the object containing the reference itself (that alone can be the example response)? There's no easy way to distinguish between the two.

**Comment by mdigirolami** [comment]
You are right!

What do you think if we provide a specific wrapper type to address the wanted case? I mean: change the type for any single "example"
**now:** the type for any example entry is "Any";
**future:** we provide a new type (named f.i. "SingleExample") that has two **alternatively** properties:
- "example-ref": of type "Reference Object";
- "example-content": of type Any (the old one).
?


Example:
1) example without a reference:
`examples: {
    "application/json" {
        "example-content": {
            "name": "Marco",
            "surname": "Digi"
        }
    }
}`

2) example with a reference:
`examples: {
    "application/json" {
        "example-ref": {
            "$ref": "./questionnaire_example.json"
        }
    }
}`
with questionnaire_example.json defined separately as now:
`{
    "name": "Marco",
    "surname": "Digi"
}`

What do you think? In my opinion allow to manage external examples is very very convenience in many cases...

**Comment by fehguy** [comment]
I believe that until it's part of the spec, it shouldn't be supported in this lib :(
