### ISSUE TITLE
Supply Swagger Definition Directly instead of through URL

### ISSUE THREAD

**Issue by fny** [swagger-api/swagger-js#803]
It would be nice if there was a way to supply a swagger definition directly instead of requiring the data to be provided from a URL.

**Comment by fehguy** [comment]
You can pass the `spec` object, see examples in tests:

https://github.com/swagger-api/swagger-js/blob/master/test/client.js#L1235

**Comment by fny** [comment]
Can a section detailing the full initialization options be added to the README? I had actually dug through the source, and wasn't sure what was what.

Here's what I have so far. 

### Initialization Options

You can initialize a `SwaggerClient` via `new SwaggerClient(options)` with the following options:

```js
{
  // URL to the Swagger specification to use for the client (String)
  url: null,
  // Authorizations to supply (Object - See "API Keys")
  authorizations: null,
  // Callback executed on success of reading the spec at the `url` (Function)
  success: function() {},
  // Function - Callback executed on failure of reading the spec at the `url`
  failure: function (err) { throw err; },
  // ??? (Function)
  progress: function() {},
  // Directly supply a Swagger spec directy for consumption (Object)
  spec: null,
  // Enable the client to return Q promises (Boolean)
  usePromise: null,
  // Request headers (String)
  swaggerRequestHeaders: 'application/json;charset=utf-8,*/*'
  // ??? (Function)
  defaultErrorCallback: null,
  // ??? (Function)
  defaultSuccessCallback: null,
  // ???
  parameterMacro: null,
  // ???
  modelPropertyMacro: null,
  // Use jQuery AJAX instead of Superagent (Boolean)
  useJQuery: null,
  // When false, jQuery will append a timestamp to the URL (Boolean)
  jqueryAjaxCache: null,
  // Whether to enable cookies (Boolean)
  enableCookies: null,
  // ??? (Array<String>)
  supportedSubmitMethods: [],
  // ???
  scheme: null,
}
```

**Comment by fehguy** [comment]
You can supply the spec as an object as well, but a URL is also required as there is a potential need to resolve remote references.

**Comment by fny** [comment]
Can you help me fill in the gaps for documenting the other initialization options? I can make a new PR if that would be easier.

**Comment by fehguy** [comment]
Hi @fny, a PR would be great, and yes, I will help you get that filled out.

I will close this and please send a PR against the README.md in master.
