### ISSUE TITLE
Windowless Testing Issues in React

### ISSUE THREAD

**Issue by cwbuecheler** [swagger-api/swagger-js#804]
Greets,

I'm using swagger-js to connect my actions to my API in a React app. Everything's working well now that the switch was made from jQuery to SuperAgent to resolve file uploading (thanks!), but I'm having some trouble with my unit tests. Because they're browser-less, I'm getting this error when I run Mocha:

`ReferenceError: window is not defined
    at SwaggerClient.initialize ([path to node-modules]/swagger-client/lib/client.js:128:8)`

The issue is this specific line:

`if(window && window.location) {`

When we were running the module locally, we changed it to `if(typeof(window) !== 'undefined' && window && window.location) {` and that worked fine. But I've switched to using the module from npm and don't really want to edit it manually if possible.

If this is an acceptable fix, I'm happy to make a quick PR, but I wanted to make sure you didn't have a better approach.

**Comment by fehguy** [comment]
Eeks, yes, please send a PR with that and I'll get it in.

**Comment by cwbuecheler** [comment]
No problem. Thanks for the speedy response.

**Comment by srl295** [comment]
@fehguy I see a similar issue on Node on Windows (not sure which version yet). Do you plan to issue a release?

**Comment by fehguy** [comment]
@srl295 just pushed 2.1.16 to npm.  Can you try that out?

**Comment by srl295** [comment]
Yes that works, alreaDy tested.
