### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by amcdnl** [swagger-api/swagger-js#809]
Would be nice to have TypeScript definitions for this project.

**Comment by wing328** [comment]
@amcdnl  As a workaround, you can use swagger codegen to generate TypeScript client (node, angular, angular2, fetch) as well as other API clients (e.g. Javascript, C#, Java, Ruby, Swift, etc) or server stubs (PHP Slim, C# Nancyfx, Java Spring, etc). Hope this helps.

**Comment by amcdnl** [comment]
Ya, but doesn't that kind of defeat the whole purpose of this project? lol

**Comment by wing328** [comment]
If using a dynamic client is a "MUST", then you've to wait for swagger-js team to come up with that (or you can contribute).

I just want to make sure you or people reading this is aware of the "workaround" using swagger codegen.

**Comment by amcdnl** [comment]
Gotcha, just making sure we are on the same page. I might get some time to contrib the TSD's.
