### ISSUE TITLE
How can I use of the "interceptors" in my angular.js application.

### ISSUE THREAD

**Issue by Kushi171987** [swagger-api/swagger-js#810]
Hi Team swagger-js,

   We are started using the swagger-js from few weeks onwards. You guys did a great job on this. But I need one small thing in it.  Not sure it it is already implemented or not, because we are using the 'interceptors' to modify the req & res objects. But after we using the swagger, this interceptors delegate methods for request & response are not called. So it became big pain for us because we are sending the authorization token in the header. Please let me know is there any thing I can use to simulate like interceptors. I think it related to #126.

Thanks In advance.

**Comment by fehguy** [comment]
Hi, this is supported as of 2.1.15--please see here for a test:

https://github.com/swagger-api/swagger-js/blob/master/test/client.js#L400

**Comment by Kushi171987** [comment]
Thank very much 👍  You save my day :)
