### ISSUE TITLE
ECMAScript 5 compatibility

### ISSUE THREAD

**Issue by hanouard** [swagger-api/swagger-js#818]
Hello,

Im having trouble with primitive type response like strings and booleans.
My app crashs with this trace:
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at /home/anouar/node_modules/my-app/swagger-client/lib/http.js:256:29

The problem is that Object.keys doesn't behave the same in ES5 and ES6.

```
Object.keys("foo");
// TypeError: "foo" is not an object (ES5 code)

Object.keys("foo");
// ["0", "1", "2"] (ES6 code)
```
[source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys)

Is using lodash Object.keys out of question?

**Comment by fehguy** [comment]
Thanks for the PR on this, i have merged it.
