### ISSUE TITLE
Add option to allow resolving non-200 responses

### ISSUE THREAD

**Issue by diosmosis** [swagger-api/swagger-js#820]
Currently, using `usePromise: true` will result in non-200 responses being rejected. When writing failure tests w/ a generator flow control library (like `co`), this can result in strange looking code, for example:

```
var client = // ... create Swagger client w/ usePromise: true

it('should respond w/ 404', function * () {
    var response;
    try {
        yield client.widgets.getWidget({ widgetId: 'unknown-id' });
    } catch (r) {
        response = r;
    }

    expect(response.status).to.equal(404);
});
```

It would be great if there was something like `request-promise`'s `simple: false` option that lets us get non-200 responses like so:

```
it('should respond w/ 404', function * () {
    var response = yield client.widgets.getWidget({ widgetId: 'unknown-id' });
    expect(response.status).to.equal(404);
});
```

**Comment by fehguy** [comment]
OK, I can see where that would be convenient but certainly not the default (like what you did suggest).  The behavior is to treat the error responses like _errors_ and require you to catch them.  I have added a couple tests to ensure this keeps working by default.

If you'd like to send a PR, we can set that option to allow _all_ responses to flow through the success `resolve`, and it can be handled like you're proposing.

I'll close this out when the tests are committed, and you can add a PR to give this option, assuming you have time.
