### ISSUE TITLE
Breaking changes from 2.0.x to 2.1.x

### ISSUE THREAD

**Issue by ruffrey** [swagger-api/swagger-js#824]
Hi and thanks to the maintainers for this great open source project.

It seems some public APIs for this library have breaking changes between 2.0.x and 2.1.x. Since it is an npm module, npm expects semver, meaning breaking changes should provide a major version bump. What has happened however is when you `npm install`, using a `^2.0.x` in `package.json`, npm will install 2.1.x which is not compatible.

My questions are:
- is this library intending to follow semver going forward?
- do you have a changelog somewhere from 2.0.x to 2.1.x ? (I looked for a bit but did not see one)

Thanks!

**Comment by fehguy** [comment]
We do our best to follow semver and I believe the API changes from 2.0.x and 2.1.x are purely optional, meaning you should be able to drop in 2.1.x without issue.  What are you seeing that is different?

All changes are listed in the release notes, which I agree are sometimes more verbose than what you're looking for specifically.

**Comment by chadxz** [comment]
When using 2.0.26, we had some code that was calling 

```
    swagger.authorizations.add(
      'basic-auth',
      new swagger.PasswordAuthorization(hostname, user, pass)
    );
```

in 2.1.17 `swagger.authorizations` is undefined

Additionally, in 2.0.26, we had some code referencing `client.apis.events.models`, but in 2.1.17, `client.apis.events` is undefined. `events` in this case was something that swagger-client was populating based on the swagger.json of our server. Upon investigating this, it looks like a great deal of the structure of the processed api definition has changed.

**Comment by fehguy** [comment]
@chadxz looks like you're right.  When the refactoring was done in the 2.1.x version, we tried to keep signatures the same, but it looks like those cases were not tested, and subsequently broke for you.

Suggest you use `~` and not `^` to keep on the compatible major.minor version, but as you said, we should do better to avoid breaking changes.
