### ISSUE TITLE
Unable to pass Empty Values in queryParam

### ISSUE THREAD

**Issue by rathishkumar89** [swagger-api/swagger-js#825]
Due to the migration of swagger installation method from npm to bower there is an issue we are facing in swagger.When we were using the previous method,we were able to modify the js to accept the empty queryParam. But now with the bower install route swagger gets downloaded on the air, due to this we were not able to edit the swagger script , swagger adds queryParam={queryParam} for empty queryParam.

Swagger is providing allowEmptyValue attribute for Optional fields when the "paramType" is "query". This attribute allows us to pass empty-valued parameters but there is no impact on the request it still holds the queryParam={queryParam}.Eventhough the allow-EmptyValue is set as true. We tried with the above feature, unfortunately it is not functional.

Is there any workaround? Or is there any other possible way to achieve this?.

**Comment by fehguy** [comment]
Can you please provide an example?

**Comment by rathishkumar89** [comment]
Hi Tony,

Here is the example web request 

Web-Request
{
"path": "/pets/getPet.do",
"operations": [{
"method": "GET",
"summary": "This API endpoint retrieves entire pets.",
"notes": "Returns the paginated list.",
"type": "void",
"nickname": "getPet.do",
"parameters": [{
"name": "petType",
"description": "Possible types",
"required": false,
"format": "string",
"in": "query"
}, {
"name": "test",
"description": "The value test.",
"required": true,
"format": "String",
"in": "query"
}]
}]
}

Output for above request:

/pets/getPet.do?test=dog

Expected output:

/pets/getPet.do?petType=&test=dog

So we introduced, allowEmptyValue : true for parameter "petType" to get expected output. But it is not functional. Can you please let us know the alternative to achieve the expected output

**Comment by fehguy** [comment]
Yes, `allowEmptyValue` is the right solution.  I'll make sure that's implemented.
