### ISSUE TITLE
Swagger API is not working on Internet explorer

### ISSUE THREAD

**Issue by amitkhese** [swagger-api/swagger-js#826]
My solution is working perfectly on chrome but we are facing an issue with Internet explorer. 
We can able see the API interface, but when trying to access login API, I got below error and after that page shows 401 exception.

Error:
**Unhandled exception at line 2, column 27219 in https://localhost/swagger/ui/swagger-ui-min-js
0x800a138f - JavaScript runtime error: Object.keys: argument is not an Object**

We are using swashbuckle swagger UI, but I think this is more related to swagger UI.As I observed swagger UI showing note about broken swagger with IE(See below image).
Can you please help me to resolve this issue ASAP.

- swagger-ui version : 2.0
- a swagger file reproducing the issue : swagger-ui-min-js

![image](https://cloud.githubusercontent.com/assets/9006300/17363429/0f18f072-5998-11e6-9369-0c3f33aed337.png)

**Comment by fehguy** [comment]
No idea who writes the Swagger UI for .NET but looking at the last published date (2012), you'd be wise to upgrade to swagger-ui directly.

**Comment by amitkhese** [comment]
We are not using swagger UI for .net anywhere in our project. I thought swashbuckle is using that internally.Thanks for confirm.
Do you think swashbuckle  upgrade can resolve this issue?

**Comment by webron** [comment]
Possibly, Swashbuckle does bundle swagger-ui in it, but not sure how up-to-date it is. You can always use swagger-ui directly without depending on it.
