### ISSUE TITLE
curl output does not match browser's actual request

### ISSUE THREAD

**Issue by centromere** [swagger-api/swagger-js#830]
I have a swagger file which specifies the following:

``` yaml
produces:
  - application/vnd.myApp
```

While the Accept header in the browser's request is set correctly, the curl output is not:

```
curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: application/json' 'https://...'
```

**Comment by fehguy** [comment]
https://github.com/swagger-api/swagger-js/commit/0bff27732e0d4bda23066f105ecd60cabaf5d5eb should fix this.
