### ISSUE TITLE
spec-converter.js:362 Uncaught TypeError: Cannot read property '$ref' of undefined

### ISSUE THREAD

**Issue by smadduri** [swagger-api/swagger-js#831]
Run time error while rendering the swagger UI.

Here is the swagger json that is being generated. I followed the instructions from here: https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5

and used the maven dependency approach to generate the json.

I see this error in the javascript console and cannot render the APIs.

Here is my swagger json:

`{
	"swagger": "2.0",
	"info": {
		"version": "1.0.0",
		"title": ""
	},
	"host": "localhost:8080",
	"basePath": "/api/v1",
	"tags": [{
		"name": "Itineraries"
	}, {
		"name": "ping"
	}],
	"schemes": ["http"],
	"paths": {
		"/itineraries": {
			"post": {
				"tags": ["Itineraries"],
				"summary": "Create Itinerary",
				"description": "",
				"operationId": "createItinerary",
				"consumes": ["application/json"],
				"produces": ["application/json"],
				"parameters": [{
					"name": "Authorization",
					"in": "header",
					"required": false,
					"type": "string"
				}, {
					"in": "body",
					"name": "body",
					"required": false,
					"schema": {
						"$ref": "#/definitions/ItineraryDTO"
					}
				}],
				"responses": {
					"200": {
						"description": "successful operation",
						"schema": {
							"$ref": "#/definitions/ItineraryDTO"
						}
					}
				}
			}
		},
		"/itineraries/users/{userID}": {
			"get": {
				"tags": ["Itineraries"],
				"operationId": "getItinerariesByUserId",
				"parameters": [{
					"name": "userID",
					"in": "path",
					"required": true,
					"type": "string"
				}],
				"responses": {
					"200": {
						"description": "successful operation",
						"schema": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/UserItineraryDTO"
							}
						},
						"headers": {}
					}
				}
			}
		},
		"/itineraries/{itinID}": {
			"get": {
				"tags": ["Itineraries"],
				"operationId": "getItineraryById",
				"parameters": [{
					"name": "itinID",
					"in": "path",
					"required": true,
					"type": "string"
				}],
				"responses": {
					"200": {
						"description": "successful operation",
						"schema": {
							"$ref": "#/definitions/ItineraryDTO"
						},
						"headers": {}
					}
				}
			}
		},
		"/itineraries/{itinID}/destinations": {
			"get": {
				"tags": ["Itineraries"],
				"operationId": "getDestinationsByItineraryId",
				"parameters": [{
					"name": "itinID",
					"in": "path",
					"required": true,
					"type": "string"
				}],
				"responses": {
					"200": {
						"description": "successful operation",
						"schema": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/Destination"
							}
						},
						"headers": {}
					}
				}
			}
		},
		"/ping": {
			"get": {
				"tags": ["ping"],
				"summary": "Health Check API",
				"description": "",
				"operationId": "sayPlainTextHello",
				"produces": ["text/plain"],
				"parameters": [],
				"responses": {
					"200": {
						"description": "successful operation",
						"schema": {
							"type": "string"
						}
					}
				}
			}
		}
	},
	"definitions": {
		"Comment": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer",
					"format": "int64"
				},
				"userId": {
					"type": "integer",
					"format": "int64"
				},
				"comment": {
					"type": "string"
				},
				"commentDate": {
					"type": "string",
					"format": "date-time"
				}
			}
		},
		"Destination": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer",
					"format": "int64"
				},
				"name": {
					"type": "string"
				},
				"itinerary": {
					"$ref": "#/definitions/Itinerary"
				},
				"latitude": {
					"type": "number",
					"format": "double"
				},
				"longitude": {
					"type": "number",
					"format": "double"
				},
				"googlePlaceId": {
					"type": "string"
				},
				"locations": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Location"
					}
				},
				"sequenceNum": {
					"type": "integer",
					"format": "int32"
				},
				"dayNum": {
					"type": "integer",
					"format": "int32"
				},
				"todos": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Todo"
					}
				}
			}
		},
		"Todo": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer",
					"format": "int64"
				},
				"todoDescription": {
					"type": "string"
				},
				"attraction": {
					"type": "string"
				}
			}
		},
		"TripHistory": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer",
					"format": "int64"
				},
				"itineraryId": {
					"type": "integer",
					"format": "int64"
				},
				"tripStartDate": {
					"type": "string",
					"format": "date-time"
				},
				"rating": {
					"type": "integer",
					"format": "int32"
				}
			}
		},
		"User": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer",
					"format": "int64"
				},
				"facebookHandle": {
					"type": "string"
				},
				"firstName": {
					"type": "string"
				},
				"lastName": {
					"type": "string"
				},
				"email": {
					"type": "string"
				},
				"password": {
					"type": "string"
				},
				"accountStatus": {
					"type": "string"
				},
				"accountType": {
					"type": "string"
				},
				"accountCreationDate": {
					"type": "string",
					"format": "date-time"
				},
				"lastLoginTime": {
					"type": "string",
					"format": "date-time"
				},
				"faqsAsked": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Faq"
					}
				},
				"faqsAnswered": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/FaqResponse"
					}
				},
				"itineraries": {
					"type": "array"
				},
				"likedItineraries": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/ItineraryLike"
					}
				},
				"tripHistory": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/TripHistory"
					}
				}
			}
		},
		"FaqResponse": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer",
					"format": "int64"
				},
				"answer": {
					"type": "string"
				}
			}
		},
		"ItineraryDTO": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"startDate": {
					"type": "string",
					"format": "date-time"
				},
				"endDate": {
					"type": "string",
					"format": "date-time"
				},
				"numOfDays": {
					"type": "integer",
					"format": "int32"
				},
				"id": {
					"type": "integer",
					"format": "int64"
				},
				"createdByUserId": {
					"type": "integer",
					"format": "int64"
				},
				"createdByUserEmail": {
					"type": "string"
				},
				"public": {
					"type": "boolean",
					"default": false
				}
			}
		},
		"UserItineraryDTO": {
			"type": "object",
			"properties": {
				"itineraryID": {
					"type": "integer",
					"format": "int64"
				},
				"itineraryName": {
					"type": "string"
				}
			}
		},
		"Faq": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer",
					"format": "int64"
				},
				"question": {
					"type": "string"
				},
				"answers": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/FaqResponse"
					}
				}
			}
		},
		"Itinerary": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer",
					"format": "int64"
				},
				"itineraryName": {
					"type": "string"
				},
				"startDate": {
					"type": "string",
					"format": "date-time"
				},
				"endDate": {
					"type": "string",
					"format": "date-time"
				},
				"numOfDays": {
					"type": "integer",
					"format": "int32"
				},
				"numOfAdults": {
					"type": "integer",
					"format": "int32"
				},
				"numofKids": {
					"type": "integer",
					"format": "int32"
				},
				"numofLikes": {
					"type": "integer",
					"format": "int64"
				},
				"numOfViews": {
					"type": "integer",
					"format": "int64"
				},
				"status": {
					"type": "string"
				},
				"createDate": {
					"type": "string",
					"format": "date-time"
				},
				"users": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/User"
					}
				},
				"itineraryLink": {
					"type": "string"
				},
				"comments": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Comment"
					}
				},
				"faqs": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Faq"
					}
				},
				"destinations": {
					"type": "array"
				},
				"public": {
					"type": "boolean",
					"default": false
				}
			}
		},
		"ItineraryLike": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer",
					"format": "int64"
				},
				"likeType": {
					"type": "string"
				},
				"itineraryId": {
					"type": "integer",
					"format": "int64"
				},
				"likedOnDate": {
					"type": "string",
					"format": "date-time"
				}
			}
		},
		"Location": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer",
					"format": "int64"
				},
				"name": {
					"type": "string"
				},
				"locationType": {
					"type": "string"
				}
			}
		}
	}
}`

**Comment by webron** [comment]
@smadduri - the problem is not with swagger-js but with swagger-core producing a malformed spec. Looking at your spec, I'm guessing you're using an old version of swager-core. Make sure to try it with the latest - 1.5.9. If you encounter this problem with 1.5.9 please open a ticket on swagger-core instead.

**Comment by smadduri** [comment]
Hmm. I didn't realize I was on an older version. I am using the swagger jersey 2.x version 1.5.0. I will try with the latest version tonight. Thanks for a pointer. And yes if I find the issue again, I will report it in swagger-core.

**Comment by webron** [comment]
1.5.0 had a major bug that exhibits exactly the issue you show in the spec. Updating to the latest should fix the issue.
