### ISSUE TITLE
WebCrypto usage in CustomRequestSigner seems impossible

### ISSUE THREAD

**Issue by centromere** [swagger-api/swagger-js#834]
My goal is to calculate a HMAC-SHA256 signature and pass it along with the request, similar to how AWS works. I am completely at a loss for how to do this with WebCrypto, given that all the return values are Promises.

**Comment by fehguy** [comment]
This may require a PR to support the signature generation in the requestInterceptor

**Comment by fehguy** [comment]
In order to do this, the interceptors would need to return a promise.  This just isn't possible with the current implementation but I'll leave this open so it can be stitched into the next

**Comment by char0n** [comment]
@fehguy, asynchronous flow is now supported inside `request` and `response` interceptors. For more information please have a look at [HTTP Client documentation](https://github.com/swagger-api/swagger-js/blob/master/docs/usage/http-client.md#request-interceptor).
