### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by darius-iko** [swagger-api/swagger-js#835]
Hi, does swagger-js support TypeScript language or TypeScript typings?

**Comment by wing328** [comment]
@darius-iko not that I'm aware of.

You can use [swagger codegen](https://github.com/swagger-api/swagger-codegen) to generate TypeScript client (node, angular, angular2, fetch) as well as other API clients (e.g. Javascript, C#< Java, Ruby, Swift, etc) or server stubs (PHP Slim, C# Nancyfx, Java Spring, etc)

**Comment by fehguy** [comment]
as @wing328 says, please consider the swagger-codegen

**Comment by darius-iko** [comment]
Thank you
