### ISSUE TITLE
JSON references are not url decoded

### ISSUE THREAD

**Issue by jeff9finger** [swagger-api/swagger-js#837]
It appears that the curly braces in the path json refs may not be compliant with the JSON spec. 
swagger-editor decodes encoded refs properly, but swagger-ui does not. Both swagger-editor and swagger-ui allow '{' and '}' chars, so it looks like these tools are not strictly enforcing the requirement (which is OK with me).

The issue is that swagger-ui ignores the json reference when it contains encoded characters. 

'''For example:
paths:
  /persons/{username}:
    $ref: 'persons.yaml#/paths/~1persons~1{username}'
```
Is dereferenced correctly. But
```
paths:
  /persons/{username}:
    $ref: 'persons.yaml#/paths/~1persons~1%7Busername%7D'
```

Is not dereferenced. It seems to be ignored.

https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03

The "$ref" string value contains a URI [RFC3986], which identifies
the location of the JSON value being referenced. It is an error
condition if the string value does not conform to URI syntax rules.
Any members other than "$ref" in a JSON Reference object SHALL be
ignored.

Curly braces aren't valid URI characters, so they have to be encoded.

**Comment by fehguy** [comment]
Please submit a test case in a PR and we can address this.
