### ISSUE TITLE
Calling a method fails if it has a parameter called "nodeType"

### ISSUE THREAD

**Issue by pavlos256** [swagger-api/swagger-js#839]
The problem happens because every jQuery form.find() call fails when there's an input with name="nodeType".

`submitOperation`

```
    form = $('.sandbox', $(this.el));
    error_free = true;
    form.find('input.required').each(function() {
```

jQuery tests form.nodeType but gets the child input element instead. Looks like it's a [known](https://bugs.jquery.com/ticket/12318) corner-case with no resolution.

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-JS 2.x is no longer under development. We'd be happy to consider any reports about Swagger-JS 3, though.

Closing as 2.x wontfix.
