### ISSUE TITLE
location.scheme should have priority over those declared in the spec.

### ISSUE THREAD

**Issue by c4milo** [swagger-api/swagger-js#841]
My swagger spec declares http and https, in that order.

When I access my app over over TLS, swagger-js attempts to use http and so the browser stops it from doing so. Can we make it so that it gives priority to location.scheme instead?

**Comment by c4milo** [comment]
This same issue may be causing this one too: https://github.com/swagger-api/swagger-ui/issues/1006

**Comment by edrex** [comment]
Downstream bug: https://github.com/swagger-api/swagger-ui/issues/1670
