### ISSUE TITLE
Default response code not shown

### ISSUE THREAD

**Issue by mex** [swagger-api/swagger-js#842]
Can anyone explain to me, why the default response code is being [removed](https://github.com/swagger-api/swagger-js/blob/a3363eb28ff4a17cd4e93b6c644bbc61390f8a03/lib/types/operation.js#L195) from the list of responses?

All I could find from the history was, that it was removed in [this commit](https://github.com/swagger-api/swagger-js/commit/394093b484a9f716cadebc0858de71b208d5e29b#diff-88377043a9027fc26aa964564c6b832bR439) due to some error in showing response messages in Swagger UI (https://github.com/swagger-api/swagger-ui/issues/602).

To me it makes sense to show all possible response codes (even the default).

**Comment by mex** [comment]
I'm already using a fork of this project, so I removed the specific check in my version. I was just wondering whether it was worth it to make a PR back to this repo, but I'll hold off. Let me know, if you want to change it at some point and I'll happily contribute.

**Comment by fehguy** [comment]
This will be addressed in the next major version of the library, since it's a breaking change for the behavior.
