### ISSUE TITLE
Tags must be present in the definition of operations

### ISSUE THREAD

**Issue by carlgustavjung** [swagger-api/swagger-js#844]
Hello,

Version is 2.1.18.
There will not be any defined operation in the SwaggerClient with a path like this one, unless the (optional) `tags` property is defined : 
```
paths:
  /emails:
    post:
      tags: <-- without this, no operation in the client
        - "emails"
      description: a description
      operationId: send
      parameters:
        - name: email
          in: body
          description: another description
          required: true
          schema:
            $ref: "#/definitions/EmailResponse"
      responses:
        "200": 
          description: Success
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
```
In `swagger-js/lib/client.js` at lines 361 and 380, it seems that the operations are defined by iterating the `operation.tags` array. No tags, no operation.
Once `tags` are set, the client works as expected. Maybe this could be added to the docs to avoid getting stuck on this.

Best.

**Comment by fehguy** [comment]
Hi, if a tag is not present, a tag named `default` will be created.
