### ISSUE TITLE
Fetching URL feature request

### ISSUE THREAD

**Issue by dmulter** [swagger-api/swagger-js#845]
I have an API that calls underlying services for separate resources. The underlying services expect an API key passed as either an HTTP header or as a query param. This creates the need for one of two possible changes in the context of my SwaggerUi. The change would actually be needed in this repo.

- When creating a SwaggerUi with url pointing to my Swagger endpoint, let me specify an X-Api-Key header sent in the request.

OR

- Allow suppression of any query parameters when rendering the "Fetching URL resource..." message. I would rather not expose the API key while you are fetching the Swagger JSON, and without headers I must pass it in the URL. This could be the default, or an option when creating SwaggerUi.

**Comment by fehguy** [comment]
Well that's easy-- you can create a request interceptor which will let you add any header or query parameter you like to any request, using your own logic.

Take a look at the tests, around here:

https://github.com/swagger-api/swagger-js/blob/master/test/request.js#L468

Please comment if that fit your need.

**Comment by dmulter** [comment]
Looks like it probably will, thanks for the help!

**Comment by fehguy** [comment]
please reopen if you need

**Comment by dmulter** [comment]
Sorry for the delay in getting around to my implementation, but I think the RequestInterceptor isn't the right way to go for my use case (though it's very cool). The key I need to provide is dynamic and only easy to get to in my Python app, not in my JavaScript. Some way to suppress the progress message URL portion is what I really need.
