### ISSUE TITLE
Array of ref in the get parameter not allow

### ISSUE THREAD

**Issue by gepeppe** [swagger-api/swagger-js#848]
Hello, I get a "not a valid parameter definition" when I try to add an array of refs in the get parameters, but I don't understand why it is not possible (If I use a string type instead of refs, it works correctly). Thanks

` 

    paths:
        /:
        get:
      parameters:
        - name: passengers
          in: query
          type: array
          items:
            $refs: '#/definitions/pax'
            #type: string             
      responses:
        200:
          description: OK

    definitions:
     pax:
      type: object
       properties:
      name:
        type: string
      familyname:
        type: string

 `

**Comment by fehguy** [comment]
You can have arrays of primitives or primitives but not anything with complex types in parameters.
