### ISSUE TITLE
Swagger-client does not adhere to HTTP header spec regarding header field name case-insensitivity

### ISSUE THREAD

**Issue by jvivs** [swagger-api/swagger-js#854]
We're using `swagger-client` internally and generally having pretty great results! Unfortunately we've run into some case sensitivity issues with headers across our various services. 

After doing a bit of research, we found that `swagger-client` is only passing through headers that exactly match the casing specified in the swagger spec. This results in some headers that should be sent (or passed through from an API to a service) not being sent.

Since the spec for headers defines field names as case-insensitive, we have attempted to add support for case-agnostic header params in `swagger-client` in #840 and refined a bit in #851.

Is there anything else we should be doing to move these PRs forward?

Thanks in advance!

**Comment by fehguy** [comment]
Fixed in #840

**Comment by jvivs** [comment]
@fehguy thank you!
