### ISSUE TITLE
Connection pooling disabled?

### ISSUE THREAD

**Issue by djMax** [swagger-api/swagger-js#862]
Right now, swagger-client uses the default superagent, which as far as I can tell has connection pooling off (because "agent" is set to false). Because swagger-client provides no way to manipulate the agent that superagent uses, there's no way to fix this. I'd propose that swagger-client should accept an agent and apply it to superagent when creating requests. Thoughts?

**Comment by fehguy** [comment]
The client accepts arguments when initializing it.  We could pass it in as an option and let the SuperAgent client choose to use it if it exists.  However, I'm not sure what that'll mean for headers, cookies, etc.  Seems like this needs to be considered very carefully.

**Comment by djMax** [comment]
It would need to be considered carefully by the user of the option, and I can see a clear argument it should be off by default. But the "good hygiene" case where cookies/etc are not stateful and keepalive is supported seems like it has to be a part of the lib. I guess it is now with "reimplement all HTTP" but ouch.

**Comment by djMax** [comment]
(is this even how superagent works? Would it re-send the cookies automatically? I didn't think it did that kind of thing)

**Comment by djMax** [comment]
Actually I wonder if we're falling victim to superagent's crap naming. request.agent is about cookies and all that. request().agent() sets the HTTP/S agent that the connection will use. That, I don't think, has anything to do with cookies or headers. I'm arguing that swagger-client should take an option for the latter.

**Comment by fehguy** [comment]
So in general, when constructing the swagger-client, passing a superagent client for reuse is just fine.  I'd just suggest sending a PR and we can check for existence of that client when calling the execute method against the SuperAgentHttpClient

**Comment by djMax** [comment]
This is fixed in master now - can we get a release?

**Comment by fehguy** [comment]
v2.1.23 has been published
