### ISSUE TITLE
Enhancing $ref to point to sub elements of a model

### ISSUE THREAD

**Issue by zamrokk** [swagger-api/swagger-js#868]
Hi,

I would like swagger ui to be able to point to a sub model element of a known model

like this : 
$ref: '#/definitions/client/valueProposition/strategicAlignment'

![image](https://cloud.githubusercontent.com/assets/2536368/18918372/dbbadaa4-859a-11e6-97da-b4ae4db001b9.png)

Is it possible ?

Thanks

ps : original post here : https://github.com/swagger-api/swagger-ui/issues/2428#issuecomment-250177842

**Comment by dolmen** [comment]
Swagger code generators (and swgger-ui) have special considerations for the name under `/definitions`: it is important (contrary to JSON Schema from which Swagger is derived).

I recommend to instead transform your schema '/definitions/client/value/valueProposition/strategicAlignment` into a named shema at `/definitions/StrategicAlignment` and point all your usages of this schema with `$ref`.

**Comment by webron** [comment]
@dolmen regardless what the tools do today, it is not technically illegal and should be supported. I agree with your recommendation, which easier to maintain.

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-JS 2.x is no longer under development. We'd be happy to consider any reports about Swagger-JS 3, though.

Closing as 2.x wontfix.
