### ISSUE TITLE
Can't make CookieAuthorization work

### ISSUE THREAD

**Issue by vvanmol** [swagger-api/swagger-js#873]
Hello, 

I'm struggling with the CookieAuthorization feature.  I've been checking the documentation and the swagger-js auth.js tests but I can't find a single example using it.

Basically I need to send a cookie with each requests sent through swagger-js.  I'm trying the following : 

```javascript
swaggerClient.clientAuthorizations.add('someCookieAuth', new SwaggerClient.CookieAuthorization('COOKIE_NAME=' + cookieValue + ';'));
```

But the cookie is never sent.  And I expected it to work as the similar approach works fine for a Header entry : 

```javascript
swaggerClient.clientAuthorizations.add('someApiAuth', new SwaggerClient.ApiKeyAuthorization('HEADER_NAME', 'headerValue', 'header'));
```

Could anyone please provide a basic example on how to add a CookieAuthorization to my client's authorizations ?  Or provide a fix to the example above ?

I'm using swagger-js 2.1.21 btw.

Many thanks !

**Comment by fehguy** [comment]
Since cookies are not supported by the spec, the client doesn't support them either.  I think this class is a remnant of a distant past.

Note, in 3.0 spec cookie parameters will be supported.
