### ISSUE TITLE
obj.body.keys is not a Function

### ISSUE THREAD

**Issue by Pchelolo** [swagger-api/swagger-js#877]
When POSTing form-data I'm getting `Uncaught TypeError: obj.body.keys is not a function` in 
Safari and certain versions of Chrome from this line: https://github.com/swagger-api/swagger-js/blob/master/lib/http.js#L248

The problem is that `FormData.prototype.keys()` doesn't exist in Safari, so it needs to be either polyfilled or removed.

**Comment by Pchelolo** [comment]
The fix doesn't actually fix anything. FormData.keys() is supposed to return an iterator, while _.keys returns an array, so the error just moves a little bit further.

**Comment by fehguy** [comment]
yep this slipped through.  The tests were using www-url-encoded so this was missed.  Thanks!
