### ISSUE TITLE
undefined property $ref on circular dependency (occurs in swagger-ui)

### ISSUE THREAD

**Issue by RobertPaasche** [swagger-api/swagger-js#888]
Related to: https://github.com/swagger-api/swagger-ui/issues/1646

The code with the undefined property is located in swagger-js, but the bug occurs in swagger-ui.

```
Resolver.prototype.resolveTo = function (property, objs) {

  // it is breaking here, because we don't have 
  // $ref in the property to the type = array.
  var ref = property.$ref;
```

**Comment by RobertPaasche** [comment]
Any progress?

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-JS 2.x is no longer under development. We'd be happy to consider any reports about Swagger-JS 3, though.

Closing as 2.x wontfix.
