### ISSUE TITLE
Uncaught TypeError: Cannot create property 'vendorExtensions' on string 'basic'(…)

### ISSUE THREAD

**Issue by mhawila** [swagger-api/swagger-js#892]
I get this error when I simply to instantiate a client using the code below.
```
var client = new SwaggerClient({
     url: 'valid url to swagger api spec',
     usePromise: true
})
```
Running this on the chrome console throws the exception, this happens after the http call has returned.
Swagger client version 2.1.23 and the [this line](https://github.com/swagger-api/swagger-js/blob/v2.1.23/lib/client.js#L314) is the one wrecking havoc!

**Comment by fehguy** [comment]
Can't reproduce--this must be from an older version of swagger-js.  Please re-test with 2.1.32 and reopen if you see an issue.

**Comment by psbrandt** [comment]
Hi @fehguy, here are the steps to reproduce the issue:

```
$ npm install swagger-client
$ node
> var SwaggerClient = require('swagger-client')
> var client = new SwaggerClient({ url: 'https://demo.openmrs.org/openmrs/module/webservices/rest/swagger.json', usePromise: true })
```

I'm using Node `v6.3.1`.

**Comment by psbrandt** [comment]
Reading the [**Security Definitions Object** spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityDefinitionsObject), it appears our OpenAPI JSON document is not valid, and we actually need something like:

```js
{
  swagger: "2.0",
  // stuff that probably isn't relevant
  securityDefinitions: {
    basic_auth: {
      type: "basic",
      description: "HTTP basic access authentication using OpenMRS username and password"
    }
  },
  // stuff that probably isn't relevant
}
```
Strangely, this was working before. I'll get work on getting our JSON up to spec.
