### ISSUE TITLE
handling undefined function calls in swagger

### ISSUE THREAD

**Issue by khieu** [swagger-api/swagger-js#896]
I'm using swagger-client on my project and I notice that in the success function, if the client make a call to an undefined operationId like `client.pet.getSth()` where `getSth` is not defined in the swagger file, no error was thrown and it fails silently. This behavior make debugging very hard because it just doesn't show any error message. I wonder if there's anyway to prevent this ?
I'm not sure if this is the right place to ask this question but any help is very much appreciated.
Thanks,
Hieu.

**Comment by fehguy** [comment]
My guess is that it _is_ failing, and because there is no operation, there is no success or failure to call.  It's probably dying in an async operation?  Perhaps you can share more details.

**Comment by khieu** [comment]
@fehguy yes it fails in an async operation. It basically looks like this: 

```
new Swagger(
  url:'http://example.com/pet',
  usePromise: true
)
.then(function clientHandler(client) {
   return client.pet.getPets()
})
.then(function resultHandler(result) {
   // do Sth with result.
})

```
In this case the only way to handle undefined `getPets` operation is to have an error handling function after resultHandler. Otherwise this chunk of code would fail silently without anything shown on console or network in the developer tools. I wonder if there's anyway to set it up so that it would automatically return a 404 or throw an error (without having to define an errorHandler func) like when an undefined function is called in python or java ?

Thank you so much !

**Comment by fehguy** [comment]
Yes, I think we can catch the absence of the `tags` attribute (`client.pet`) and the absence of the function, and return a proper error.

**Comment by fehguy** [comment]
Looked into this more.  We actually cannot catch access to undefined variables in the client.  That will be your job to do in your usage:

```
if(client.pet && client.pet.getPets) {
  // execute it
}
else {
  // handle gracefully
}
```

Not by lack of wanting, but it's just not possible in javascript
