### ISSUE TITLE
asCurl does not respect interceptor url changes

### ISSUE THREAD

**Issue by tyrsius** [swagger-api/swagger-js#903]
I was asked to [move this issue](https://github.com/swagger-api/swagger-ui/issues/2507) here

--------------
- swagger-ui version
2.2.6

I use a request interceptor to rewrite the URL for requests so that I can provide an Environment/Host selector to users. The interceptor is successful in changing the "Try It Out" requests, and in updating the *Request URL* section. However, the *CURL* section does not update.

Notice in the screenshot that the URL path starts with `/dev`  in CURL and `/prod` in the request URL.

![image](https://cloud.githubusercontent.com/assets/1187432/20441527/bd406876-ad79-11e6-89bd-38641ec11970.png)

It looks like this is due to the curl command [using the spec](https://github.com/swagger-api/swagger-ui/blob/2cd11efa9da0b8d489c4fa0bb286e47e83cb285a/src/main/javascript/view/OperationView.js#L783) for its url, instead of the request.

**Comment by fehguy** [comment]
This is a bug, working on it...
