### ISSUE TITLE
JQueryHttpClient error 'unable to parse JSON/YAML content' when response body contains image

### ISSUE THREAD

**Issue by kevinmreynolds** [swagger-api/swagger-js#906]
I'm using swagger-ui to call an API that uploads a file as part of a form, and then responds with a file (in my case, these are image files).  See https://github.com/swagger-api/swagger-ui/issues/2470 for more detail.

I'm running into a problem with the way the response body is processed. In http.js, in JQueryHttpClient.prototype.execute, we have the following:
```
    try {
      var possibleObj =  response.responseJSON || jsyaml.safeLoad(response.responseText);
      out.obj = (typeof possibleObj === 'string') ? {} : possibleObj;
    } catch (ex) {
      // do not set out.obj
      helpers.log('unable to parse JSON/YAML content');
    } 
```

What I'm seeing is that if the response is a PNG (or any non-text type?), then the responseText contains the PNG data, causing jsyaml.safeLoad to throw.  Thus, the response body is lost.

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-JS 2.x is no longer under development. We'd be happy to consider any reports about Swagger-JS 3, though.

Closing as 2.x wontfix.
