### ISSUE TITLE
Redundant Model.models property

### ISSUE THREAD

**Issue by Goldob** [swagger-api/swagger-js#908]
I was trying to browse the generated client through Node REPL and one thing that struck me was the unreadability of `client.models.{someModel}`. The cause of that is that next to model-specific properties, each `Model` object also contains `models` property ([right here](https://github.com/swagger-api/swagger-js/blob/abfff4786b43b3723dbe57da3d18fe820c372554/lib/types/model.js#L15)), which is excatly the same as `client.models`. I don't believe such a reference to be neccesary and as such, I suggest it to be removed.

I can do that myself, but I just wanted to consult the change beforehand, i.e. to be sure there isn't some nasty use case I'm missing.

**Comment by fehguy** [comment]
Yes, i believe this is a remnant of how it's used for rendering.  For example, you may get a reference to a single model which has a complex type.  Then for rendering, without a reference to top-level models, it's impossible to render complex properties.

This is not ideal!  But it's going away in an major rev of this library, which is coming soon.  So for now, this is used by swagger-ui, and shouldn't be removed.  It will be dramatically cleaned up, though.
