### ISSUE TITLE
map property doesn't render referenced model

### ISSUE THREAD

**Issue by dr3s** [swagger-api/swagger-js#909]
swagger-ui version 2.2.8
a swagger file reproducing the issue : https://gist.githubusercontent.com/anonymous/9ca4b9eeca273d64e2e3598aea458a08/raw/8a016825e15ec9fd3029c6be8575d46b64e474f9/test.json
itemViews is a map dataType that seems to match the spec yet it renders as an inline model. It is explicitly an object with additionalProperties ref of ItemView

ItemView is in the definitions but not rendered in the model for the Item.itemViews map

**Comment by dr3s** [comment]
#230

**Comment by fehguy** [comment]
Rendering is now in swagger-ui, so closing this.
