### ISSUE TITLE
How can I use `connectionAgent` to make every request go through a proxy

### ISSUE THREAD

**Issue by abhagupta** [swagger-api/swagger-js#910]
I am wondering how I can  use `connectionAgent` to send all the requests via a proxy. Say, my proxy is running at port `http://127.0.0.1:8442` . I send the request as below
```
var HttpProxyAgent = require('http-proxy-agent');
 mock.petstore(done,{
                url: 'http://localhost:8000/v2/petstore.yaml',
                connectionAgent: new HttpProxyAgent('http://127.0.0.1:8442')
                /*,swaggerRequestHeaders: 'application/yaml',*/
            }, function (petstore, server){
                sample = petstore;
                instance = server;
            });
```
This does not work.  If I create `connectionAgent ` as an object, with `agent` property, that does not work either.

Any suggestions?

**Comment by abhagupta** [comment]
seems like it is possible with latest version of `supergent` but a monkey patched request. Something like 
```if (proxyAgent) {
    var OrigRequest = request.Request;
    request.Request = function RequestWithAgent (method, url) {
      const req = new OrigRequest(method, url)
      req.agent(proxyAgent);
      return req;
    }
  }
```

as suggested by Superagent team here https://github.com/visionmedia/superagent/issues/1130.

Any plans of upgrading your `superagent` version?

**Comment by fehguy** [comment]
If you want to use a proxy, consider using `setHost('...')` against the client to point to the proxy, or to use a request interceptor.  There are examples in the tests

**Comment by abhagupta** [comment]
Thanks for replying on this but I am more looking into holistic approach in which I do not have to set up a setHost or a requestInterceptor for each request going on. I finally got the answer from 'superagent' team about how to do it but it needs superagent version 3. Are you guys planning to upgrade 'superagent' to 3?

**Comment by fehguy** [comment]
Happy to, please send a PR :)  Since our use of superagent is quite well tested and isolated.

Note, it's literally the exact same amount of work to call `setHost` one time for a proxy as it is to enable a custom agent and pass that.  but you have choices, as you pointed out.
