### ISSUE TITLE
Mask passwords in CURL example

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#917]

**Comment by DjLeChuck** [comment]
This modification introduces a problem. The passwords fields are not only hide on screen but also sent as ****** in the AJAX query.

**Comment by fehguy** [comment]
Right you are.  See https://github.com/swagger-api/swagger-js/issues/925, looks like this only applies to `www-form-urlencoded` passwords

**Comment by fehguy** [comment]
@DjLeChuck please pull master and retest

**Comment by DjLeChuck** [comment]
@fehguy yep, it's working now. Thank you for your reactivity!
