### ISSUE TITLE
Question regarding to boolean in-body params

### ISSUE THREAD

**Issue by seb0zz** [swagger-api/swagger-js#921]
Let's assume I have the following configuration for a `post` route:

```json
"tags": [
  "random"
],
"operationId": "randomOp",
"parameters": [
  {
    "name": "Authorization",
    "in": "header",
    "type": "string",
    "description": "Bearer web token"
  },
  {
    "name": "Accept-Language",
    "in": "header",
    "type": "string",
    "description": "User locale"
  },
  {
    "name": "id",
    "in": "path",
    "description": "Some id field",
    "required": true,
    "type": "string"
  },
  {
    "name": "randomBooleanField",
    "in": "body",
    "schema": {
      "type": "boolean"
    }
  }
],
``` 

No when I do the following in my javascript code:

```javascript
client.random.randomOp({
  Authorization: 'Bearer ey...',
  'Accept-Language': 'en',
  id: '123',
  randomBooleanField: true
});
```

The result is a `POST` HTTP request with the values for `Authorization` and `Accept-Language` successfully set as headers. With the `id` param successfully merged into the path. 

BUT an empty request body. After some debugging I found out that the body is not really empty but the client is trying to send the value `true`. Somehow the fetch API seems to make an empty request body out of that (I'm using a custom HTTP client).

Now my question is: Is this the desired behavior or might it be an issue either in my code or in the code of swagger-js?

**Comment by fehguy** [comment]
Strange but I may be misunderstanding. Can you send a PR with failing test?

**Comment by fehguy** [comment]
closing due to no response :(
