### ISSUE TITLE
Can't change the request url in swagger-ui version 2.2.8 

### ISSUE THREAD

**Issue by LuoPQ** [swagger-api/swagger-js#922]
I try to change the request URL by swaggerUi.api.setHost, and the property swaggerUi.api.host actually is changed, but when I click try it out, the request URL doesn't change.

swagger-ui version 2.2.8

**Comment by fehguy** [comment]
ok :)  Thank you for opening it here.  Digging in more, it is indeed isolated to swagger-ui, so I'm closing this out.  Sorry!
