### ISSUE TITLE
swagger-client uses http when the definition was loaded over https

### ISSUE THREAD

**Issue by ringmaster217** [swagger-api/swagger-js#931]
According to the specification, "If the schemes is not included, the default scheme to be used is the one used to access the Swagger definition itself."

The behavior of swagger-js and therefore swagger-ui is different from the behavior described above. If a schemes object is not included in the swagger definition, swagger-js will use the protocol used to load the web page (such as swagger-ui) instead of the protocol used to load the swagger definition. I believe the problem is caused here, on [line 349-352 of client.js](https://github.com/swagger-api/swagger-js/blob/b2c9f41ddec34fce2ab1d379fd7a6789a2be2a13/lib/client.js#L349). client.js appears to be going straight to window.location.protocol in the absence of a schemes object in the definition, which will use the protocol used to load the page. This may be different from the protocol used to load the swagger definition.

**Comment by fehguy** [comment]
Fixed by #932.  Yes this was a bug.
