### ISSUE TITLE
Cannot return a string JSON response

### ISSUE THREAD

**Issue by bowman** [swagger-api/swagger-js#933]
Commit: d84fc258d4631d5b3e4fd2474fd2e86e919d6a86

Explicitly ignores string JSON values:
```
           try {
             possibleObj = jsyaml.safeLoad(res.text);
+            // can parse into a string... which we don't need running around in the system
+            possibleObj = (typeof possibleObj === 'string') ? null : possibleObj;
           } catch(e) {
```

A results of `'"abc"\n'` should decode to an object `"abc"`,
perhaps using the API spec to resolve ambiguous cases.

I'm willing to patch and write tests if once an approach is agreed

**Comment by bowman** [comment]
Another instance, that seems inconsistent:
```
response.obj = (typeof possibleObj === 'object') ? possibleObj : null;
```
Wouldn't allow an array response?

**Comment by fehguy** [comment]
Well to the first issue, `response.obj` is reserved for an _object_, where as `"foo"` is a _string_.  So you will never get an object in there.

**Comment by fehguy** [comment]
Regarding arrays, recall:

```
var array = [1,2,3];
console.log(typeof array);
> "object"

Array.isArray(array);
> true
```

So unless I'm missing something, swagger-js is behaving correctly

**Comment by bowman** [comment]
fehguy@, sorry to be slow respond, it's been a hectic few months.

I'd like you to consider re-opening this issue, I can see my initial rushed post was unclear.

My starting point was the swagger spec.  A Response Object contains a Schema Object:

> The Schema Object allows the definition of input and output data types. These types can be objects, but also primitives and arrays. This object is based on the JSON Schema Specification Draft 4 and uses a predefined subset of it. On top of this subset, there are extensions provided by this specification to allow for more complete documentation.
http://swagger.io/specification/#schemaObject

This includes `type: string`, of course.  The petstore.yaml has an example:
https://github.com/swagger-api/swagger-editor/blob/master/spec-files/petstore_full.yaml#L390-L394

The behaviour of the generated node server is to return the JSON quoted string:
```
$ curl -sv -X GET --header 'Accept: application/json' \
   'http://localhost:8080/v2/users/login?username=u&password=p'   ; echo
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /v2/users/login?username=u&password=p HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.49.0
> Accept: application/json
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Fri, 03 Mar 2017 09:48:13 GMT
< Connection: keep-alive
< Content-Length: 7
< 
* Connection #0 to host localhost left intact
"aeiou"
```
So the "Hello World" example contains this

I expected that a Swagger aware client would handle the evaluation of all JSON results,
including primitives.  Indeed swagger-js does, but currently discards primitive results.
This means library users have to redo the evaluation and must fill in the gaps client side,
which is unfortunate for a client that could easily be universal and spec driven.
(Indeed, the benefits of a JS client "for free" after using Swagger on the server was
part of it's appeal).

We currently consume an API returning JSON strings (header and quotes) and would like to have
this supported upstream, rather than in a private fork if possible.

It seems that part of the original objection is that the field is called `obj` and thus
reserved for an object, but primitive responses are also allowed and for universality
ought to be supported.  The comment from ponelat@ is "can evaluate to a string,
which we don't need running around the system".  That would be reasonable
for application code, but for a general-purpose, specification driven client,
is inappropriately restrictive.  Postel's Law and all...
Perhaps `obj` is mis-named, or a second general result field could be included.
I'm sure there are other options you could suggest.

Thank you,

Brad

**Comment by freshtonic** [comment]
@fehguy a naked string (or any other primitive) is still a valid JSON document. Wrapping in an array or object is _not_ mandatory. Please re-open this.
