### ISSUE TITLE
How to handle keepalive ?

### ISSUE THREAD

**Issue by ffallah** [swagger-api/swagger-js#941]
Hi,
I am using swagger client in nodejs to trade on an online cryptocurrency exchange.
The problem is that when I try to send an order using swagger client, it takes 1-2 secs to initialize the HTTPS connection. My exchange states that they support 90 sec keepalive connections to their REST API server.
What is the proper way to keep the connection of swagger client alive to server in nodejs ?

Thanks

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-JS 2.x is no longer under development. We'd be happy to consider any reports about Swagger-JS 3, though.

Closing as 2.x wontfix.
