### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'window.location.host')

### ISSUE THREAD

**Issue by ankitpopli1891** [swagger-api/swagger-js#942]
It seems like location is `undefined` [here](https://github.com/swagger-api/swagger-js/blob/2cdccc05c787cf551ffe2ac7f0f5223e26c9598d/lib/types/operation.js#L56)

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-JS 2.x is no longer under development. We'd be happy to consider any reports about Swagger-JS 3, though.

Closing as 2.x wontfix.

**Comment by zhujingxing** [comment]
request origin: "http://localhost:8081", origin not be window.location.host, or somewhere not be window.location.host
