### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prop' of undefined

### ISSUE THREAD

**Issue by ankitpopli1891** [swagger-api/swagger-js#943]
Uncaught TypeError: Cannot read property 'prop' of undefined

The error occurs while building the client using `SwaggerClient.buildFromSpec` API.

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-JS 2.x is no longer under development. We'd be happy to consider any reports about Swagger-JS 3, though.

Closing as 2.x wontfix.
