### ISSUE TITLE
Client does not allow for asynchronous authorizations

### ISSUE THREAD

**Issue by maseb** [swagger-api/swagger-js#946]
Feature request. :) 

An increasing number of REST APIs (including those offered by large cloud providers who are organizationally aligned behind Swagger internally and externally) make use of [signed requests][signed-requests] (or similar), which is a "proof of possession" rather than "proof by possession" (e.g., cookies) auth mechanism. Part of what's making this possible is native crypto accessible in the browser via the WebCrypto APIs. 

However, the WebCrypto API for `sign` is asynchronous (Promise-based). Given this, it's impossible to leverage WebCrypto in combination with swagger-js, since swagger-js assumes synchronous application of authorization materials to the request. 

This limits our ability to use swagger-js (and, indeed, _many_ of the other open source Swagger libraries). The alternative is build our own (which we do), and aim to open source them (which we hope to), but there are organizational overheads (read: lawyers) and philosophical/practical concerns (read: fragmentation, developer adoption) that make this less than desirable. 

In an ideal world, each public extension point of the swagger-js client would allow for async operation. This enables a lot of interesting use cases while not significantly increasing the complexity of the client. 

[signed-requests]:https://tools.ietf.org/html/draft-cavage-http-signatures-06

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-JS 2.x is no longer under development.

Version 3 does move to a Promise-based interface, and has plug points for implementing something like this.

Closing as 2.x wontfix.
