### ISSUE TITLE
cURL percentage encoding seems inappropriate for json/xml data

### ISSUE THREAD

**Issue by louisburton** [swagger-api/swagger-js#947]
Form encoding is expected when the content-type is for form data. I don't think it's correct when the body is not of this type.
I believe @fehguy switched from the unicode escaping to this approach here:
https://github.com/swagger-api/swagger-js/commit/e81b5f97556f2f4b2c173d3331ade7746ace1dd3#diff-e9afd75580721a5b884cc82272c23984L985

Behaviour can be observed using the PetStore sample from swagger-ui (https://github.com/swagger-api/swagger-ui/).
Try creating a user with the following JSON:
```
{
  "id": 123,
  "username": "louis@mytenant",
  "surname": "O'Burton"
}
```

It will generate a cURL command like so:
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \ 
   "id": 123, \ 
   "username": "louis%40mytenant", \ 
   "surname": "O%27Burton" \ 
 }' 'http://petstore.swagger.io/v2/user'
```

When issuing this from Linux bash I receive:
`{"code":400,"type":"unknown","message":"bad input"}`

I also believe that the server will unmarshal the JSON with string values that include the literal percentage encodings, which does not seem the desired or expected behaviour to me. I can see that there are tests asserting this however (https://github.com/swagger-api/swagger-js/blob/master/test/request.js#L352), which confuses me.
I can work around it by hacking some post processing into our version of swagger-ui, which is not very desirable. Something like the following, but ideally just for the data part of the curl command:
```
      if (contentType === 'application/json' || contentType === 'application/xml') {
        curlCommand = curlCommand.replace(/%27/g, '\\u0027').replace(/ \\ \n /g, '\n').replace(/%40/g, '@');
      }
```

Apologies if I'm missing something with cURL or missing some prerequisite of using this command.

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-JS 2.x is no longer under development. We'd be happy to consider any reports about Swagger-JS 3, though.

Closing as 2.x wontfix.
