### ISSUE TITLE
File formData not working in cURL commands

### ISSUE THREAD

**Issue by louisburton** [swagger-api/swagger-js#948]
This commit by @fehguy is handling arrays for type `multi` in collections of form data.
https://github.com/swagger-api/swagger-js/commit/12dc4de84b5b89a7b7e91f7ed5bc37f76154cb9d

I think inadvertently however, this may have regressed the support for when the parameter is of type 'file'. In changing `obj.body.get(parameter.name)` to `obj.body.getAll(parameter.name)`, the return type becomes an array, and the subsequent `paramValue.name` reference is not appropriate for the array (but is fine for the first element of the array).
https://github.com/swagger-api/swagger-js/blame/master/lib/types/operation.js#L1119

As a result, file params don't correctly end up in the cURL command.

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-JS 2.x is no longer under development. We'd be happy to consider any reports about Swagger-JS 3, though.

Closing as 2.x wontfix.
