### ISSUE TITLE
Need assistance @fehguy

### ISSUE THREAD

**Issue by neumond** [swagger-api/swagger-js#957]
Resolver.js seems to be very dirty bit of code, I constantly find new and new bugs there which block my own work with swagger ui. And everything is related to such simple mechanism like $ref resolving. Having more than 900 lines of code here doesn't look good, with all this heavy raw string processing.

$refs are slightly complex thing to work with: they allow recursive/cyclic referencing. Strictly speaking, you can't just completely unwrap jsonschema eliminating all the refs. But you can use ability of dynamically typed languages to make "pointer" with simple assigning:

```javascript
a = {b: 3};
a.c = a;  // here a.c works exactly like $ref to a
```

This prevents infinite consumption of memory to store the scheme.

But downloading and storing the scheme/specification doesn't seem to be the only operation resolver.js does. It has some fragile and unspecified logic of gathering model descriptions. I want to spend some time refactoring resolver.js, but I need kind of specification for these custom operations it does. Would be much better to separate simple downloading the spec and it's modifying/aggregating. Please help me there, @fehguy.

**Comment by fehguy** [comment]
DID YOU REALLY CALL MY CODE DIRTY AT THE SAME TIME AS ASKING FOR HELP?  WHAT IS THIS WORLD COMING TO


In all honest, and hurt feelings aside, I can save you trouble.  Wait for the end of the month and this code will be replaced with something written by better developers. (sniff)

**Comment by neumond** [comment]
Oh, so dramatic. Sorry, I didn't want to hurt you in any way, but I still consider this file quite dirty-written. There're many reasons why people may write things coarsely, it's pretty understandable, I don't blame you for that. But put yourself in my position for a moment, swagger ui breaks on every "non-trivial" (but valid!) $ref used in specification, and the more bugs I fix, the more I find new ones. I offer you _my_ help in first place (possibly almost complete rewrite of resolver). But I need to understand better area of responsibility of Resolver object, better described API and this thing with models. If you don't need such help or you think this code is perfect, it's ok, I'll just close this issue and stop working on this.

**Comment by fehguy** [comment]
Nah, I think it's ugly code.  I'm just trying to say, this code is 100% getting recycled so I wouldn't worry about redoing it right now, unless you must patch things.

What _is_ well done are the tests against the resolver, so if you make any changes, it should catch your issues.

**Comment by neumond** [comment]
Hmm.. I can PR you couple of tests then. Got it.
