### ISSUE TITLE
"See more at" string in UI's info block (info_url) can't fetched the translated one

### ISSUE THREAD

**Issue by eduardtibet** [swagger-api/swagger-js#961]
As mentioned in https://github.com/swagger-api/swagger-ui/blob/master/CONTRIBUTING.md seems this bug is related to the swagger-js rather than the UI itself.

Swagger UI version 2.2.8
When turning on translation files (any from dist/lang folder) by uncommenting / adding string, i.e.
`<script src='lang/ru.js' type='text/javascript'></script>`
for some unknown reasons the string:  **See more at** doesn't translated at all despite the  `data-sw-translate ` value mentioned within tag in **swagger-ui.js** file.

It is irrelevant to the translation file used.

Steps to reproduce for English speaking people:

1. Turn on English translation (dist/lang/en.js) by adding / uncommenting
`<script src='lang/en.js' type='text/javascript'></script>`

2. Change the translated (second one) `"See more at":"See more at"` in **en.js** file  to any arbitrary value i.e. 
`"See more at":"TEST english translation"`

3. Reload UI with any json.

4. You will see **See more at** but not **TEST english translation**

**Comment by shockey** [comment]
Thanks for the report! Unfortunately, Swagger-UI 2.x is no longer under development. We'd be happy to consider any reports about Swagger-UI 3, though.

Closing as 2.x wontfix.
