### ISSUE TITLE
Cross domain request error

### ISSUE THREAD

**Issue by kchauhan-muhimbi** [swagger-api/swagger-js#962]
I am trying to call API using swagger-client but getting following error:

"The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'null' is therefore not allowed access."

Please note that our API is configured to allow Cross Domain requests. It returns following headers,

name="Access-Control-Allow-Origin" value="*" 
name="Access-Control-Allow-Headers" value="Content-Type, Authorization, API_Key" 
name="Access-Control-Allow-Methods" value="GET, POST, PUT, DELETE, OPTIONS"

The issue is that when I make request, it adds extra header "Access-Control-Allow-Origin" with value "(star)". So we have one header with same value ("star").

Any help would be appreciated.

**Comment by lyssdod** [comment]
Hi,

What backend are you using?

**Comment by kchauhan-muhimbi** [comment]
The WCF service is hosted on Azure web app. It is developed using asp.net.

**Comment by kchauhan-muhimbi** [comment]
Hi,

I extracted swagger-client.js file and found that it adds “Access-Control-Allow-Origin” header to make sure request is accepted by the API server. If you comment that code then request goes through without issues.

Any reason for adding this header value?

**Comment by webron** [comment]
@kchauhan-muhimbi which version of swagger-js do you use?

**Comment by kchauhan-muhimbi** [comment]
@webron  - I am using v2.1.32.

**Comment by webron** [comment]
@ponelat any thoughts on that?

**Comment by ponelat** [comment]
I imagine the issue stems from the two headers ( the one you're adding and then one we're adding ) having two different cases. Such that both headers are being added, resulting in `*, *` in the final browser request.

I don't see any explicit mention of those headers in swagger-js@2.x ( nor 3.x)  but I imagine it could come from some third party. @kchauhan-muhimbi would you mind pointing out the line you commented out? it would help debug this.. thanks.

**Comment by kchauhan-muhimbi** [comment]
This is fixed. I did some changes in the API and I am now able to call the API. I have another issue "#1017" regarding error while making api request.
