### ISSUE TITLE
Please provide "Upgrade from 2.x to 3.x" instructions

### ISSUE THREAD

**Issue by louisremi** [swagger-api/swagger-js#969]
Hello there,

I tried upgrading from 2.x to 3.x and this proved to be a terrible idea. Nothing works any more, as far as I can tell.
It'd be great to have some docs to help us make the transition :-)

**Comment by webron** [comment]
We're working on those, thanks for your patience :)

**Comment by webron** [comment]
Take a look at https://github.com/swagger-api/swagger-js/blob/master/docs/MIGRATION_2_X.md. Note that we're working on additional changes, and will make sure to update as we introduce those.
