### ISSUE TITLE
3.x authorizations are applied to operation, not client

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-js#971]
This was an unintended change from the 2.x series for swagger-js, we should be able to authorize a _client_ and have it apply them to operations as needed.  Instead, we have to apply them to each operation, every time.

**Comment by ponelat** [comment]
see: https://github.com/swagger-api/swagger-ui/issues/2793

**Comment by webron** [comment]
@ponelat does #975 cover this and the issue can be closed or is something else needed?

**Comment by ponelat** [comment]
Yup that solves this issue. It doesn't solve the issue of adding auth to _fetching the spec_. That's tracked elsewhere.

**Comment by jasongonzales23** [comment]
Hi, I got here from the FAQs, and it looks like you've changed how authorizations worked. If that is correct, perhaps we should document this. Happy to help, BTW, but perhaps someone with more experience with the project can do it better than I.

**Comment by komasoftware** [comment]
I have a Swagger 2.0 spec with following security definition 
```
securityDefinitions:
    jwt:
        type: apiKey
        name: Authorization
        in: header
```
But I have a hard time getting the swagger-js 3.0 client to pass the credentials. 
This is what I am doing 
```
            let authorizations = {
                jwt: { token: { access_token: "jwtvalue goes here" } }
            };
            return new SwaggerClient({
                url: 'specURL goes here',
                authorizations: authorizations
            })
                .then(client => {
               .....

```
Can I even use the swagger-js 3.0 client against a swagger 2.0 spec ?
The only documentation I could find was in the migration doc ...

**Comment by vukee** [comment]
Same issue here. I can add whatever I want into 'authorizations', nothing is passed with the request.

Is there somewhere a full documentation for swagger-js? Or some examples how to use authorizations? Would be really helpful.

**Comment by bearer-syntaxerror** [comment]
From the documentation I'm having a pretty tough time understanding how to add the following header to my requests:
`authorization: bearer {token}`

Any tips?
