### ISSUE TITLE
Global ajax event handlers with swagger client 2.x

### ISSUE THREAD

**Issue by malinthaprasan** [swagger-api/swagger-js#973]
Hello,

I have tried using ajaxComplete() global event handler (https://api.jquery.com/ajaxComplete) with Swagger client (2.x). It seems it is not getting executed after every request. Is that the default behavior? What I am trying is to do some validations for every response coming into swagger client from the server. Is there any other way I can do it globally? (instead of doing this in each and every place swagger client is used)

**Comment by fehguy** [comment]
Try the responseInterceptor support. That will enable exactly what you're describing

**Comment by malinthaprasan** [comment]
@fehguy Thank you for the response. That would suit my requirement!

**Comment by malinthaprasan** [comment]
Quick question, we need to always configure the swagger client whenever we need a responseInterceptor right? There isn't a way we can configure a global response/requestInterceptor which would be hit by any SwaggerClient object we create without configuring each one?

**Comment by shockey** [comment]
Unfortunately, Swagger-JS 2.x is no longer under development. We'd be happy to consider any reports about Swagger-JS 3, though.

Closing as 2.x wontfix.
