### ISSUE TITLE
Observable support

### ISSUE THREAD

**Issue by vincent-cm** [swagger-api/swagger-js#982]
Any plan to support observable which introduced by Rxjs, typescript, angular HTTP...?

**Comment by vincent-cm** [comment]
@buunguyen The plugin instance now can be initiated by Promise
`return new Promise<any>(resolve => {
      if (swagger != null && swagger.template != null) {
        resolve(swagger);
      } else {
        swagger = new SwaggerClient({
          url: URL,
          enableCookies: true,
          success: function (data: any) {
            swagger = this;
            resolve(this);
          }
        });
      }//else
    });`

Can this be supported by converting Promise to Observable?
[http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html)

**Comment by buunguyen** [comment]
Is there a specific use case that you want to achieve with SwaggerClient that can only be done via the observable interface? Also, if you have to consume observable, can you simply [convert it](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/frompromise.md) from a promise? 

This is unrelated, but unless I misunderstood, the code you show looks a bit complicated. `SwaggerClient()` returns a promise that resolves to the client object. So you might just do this:

```js
if (swagger && swagger.template) return Promise.resolve(swagger);
else return new SwaggerClient(...)
```

**Comment by vincent-cm** [comment]
@buunguyen Yes, some cases like only Observables can achieve, please see [https://blog.thoughtram.io/angular/2016/01/06/taking-advantage-of-observables-in-angular2.html](https://blog.thoughtram.io/angular/2016/01/06/taking-advantage-of-observables-in-angular2.html)

**Comment by shockey** [comment]
Observables are currently in [TC39 stage 1](https://github.com/tc39/proposals), and would be a breaking change to our top-level interface.... so this is not likely to happen soon.

However, I'd be excited to see a compatibility layer that consumes our promise interface and exposes an Observable interface.

**Comment by FallenRiteMonk** [comment]
I havent exactly looked at your use cas but you can create a obsevable from a promise using rxjs fromPromis funktion:
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/frompromise.md

**Comment by char0n** [comment]
@vincent-cm this library revolves around native [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). As @shockey pointed out it is possible  to create an `observable interface` by consuming our `Promise interface`. The only problem can be the cancel-ability of observables, as promises are non cancel-able and immutable concept. The only way this interface can IMHO be implemented is using `userFetch` (more in [our docs](https://github.com/swagger-api/swagger-js/blob/master/docs/SUMMARY.md)) override and create promises that are cancel-able. It can be achieved by using [AbortController](https://davidwalsh.name/cancel-fetch) and passing it as a signal property of the `Request`.

**Comment by char0n** [comment]
I'm closing this for now, due to inactivity. If there is an attempts of this observable interface, please make RxJS a `peerDependency`.
