### ISSUE TITLE
Incorrect method used for given operationId

### ISSUE THREAD

**Issue by srihakum** [swagger-api/swagger-js#991]
I am trying to load a swagger and invoke a particular operationId (createAccount) which is a POST operation on the path /accounts. However when I run this code I get the result of GET on /accounts operation. Is there something I am doing wrong?
Test code:

```
var Swagger = require('swagger-client');
Swagger({"url":"https://staging.cloud-elements.com/elements/api-v2/elements/44/docs"}).then(function (client) {
    client.apis.zohocrm.createAccount({"Authorization":"","body":{"Account Name":"XYZ"}})
        .then(function(response){
            console.log(response);
        })
        .catch(function (error) {
            console.log(error);
        });
}).catch(function (error) {
    console.log(error);
});
```
I have not provided Authorization for security reasons. Hence the response would be 401.

**Comment by webron** [comment]
Which version of swagger-js do you use?
Can you share the spec?

**Comment by srihakum** [comment]
I am using 3.0.3 version. Spec is available here https://staging.cloud-elements.com/elements/api-v2/elements/44/docs. After deeper understanding it seems that there is no mention of schemes in the spec, so it looks to default to http. However the server was responding with 301 where the URL was retained as per location header and method was defaulted to GET. This redirection causes POST to be converted to GET.

**Comment by webron** [comment]
Thanks for the analysis. We're aware of issues when `schemes`, `host` or `basePath` are missing and working to resolve those.

**Comment by srihakum** [comment]
@webron Thanks for acknowledging the issue. Any timelines on when we can expect this to be available. We are currently blocked to use this in our code because of this issue. Any help here is much appreciated.

**Comment by webron** [comment]
This is a very high priority for us, but I don't have an ETA for the fix.

**Comment by webron** [comment]
This should be fixed in master/latest release.
