### ISSUE TITLE
CORS cookies

### ISSUE THREAD

**Issue by lyssdod** [swagger-api/swagger-js#993]
Hi, there's hardcoded parameter of `credentials: same-origin` in `execute.js`, how can I change it to `credentials: include` during init? Is it possible? Thanks!

**Comment by buunguyen** [comment]
For now there's no easy way to change it. You might need to pass in `requestInterceptor` fn and modify `req.credentials`.

**Comment by shockey** [comment]
Closing; `requestInterceptor` is the best way to do this, and I don't think adding another interface _just_ for this would be worth the overhead.
