### ISSUE TITLE
Should default to `consumes[0]` if no `requestContentType` provided

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-js#995]
The final order of setting the `Content-Type` header should be as follows..

- if `has no req.body, no req.form` add nothing.
- else if `requestContentType`, use that.
- else if `has consumes` use `consumes[0]`
- else if `has a "type: file"` parameter` use multipart/form-data`
- else if `has "in: formData"` use `application/x-www-form-urlencoded`
- else add nothing.

**Comment by dwilson6** [comment]
I've run into this as well. Is someone already working on this? If not, I can take a crack at it. I've already implemented part of it in my own requestInterceptor function.  

Also related, I've noticed that if I have a POST endpoint with a json parameter in the body and I call that operation with the tags interface like `client.apis.default.operation({param_name: {}})` (I explicitly set the Content-Type header to application/json), I get an error `unexpected token o in JSON at position 1...` so I have to serialize the value of the param explicitly `client.apis.default.operation({param_name: JSON.stringify({})})`.  Would it be reasonable to automatically stringify if the content type is application/json and it has an "in: body" parameter and the value is an object? I can create a separate issue for this if you'd like.

**Comment by webron** [comment]
@dwilson6 we're always looking for community contributions. Nobody has started working on this issue yet.

As for the other thing you bring up, please open a separate ticket. I don't really follow what you're saying, but there are better developers than me on the project who will ;)

**Comment by dwilson6** [comment]
I was going to look at this today but it looks like @bodnia has it almost done

**Comment by ponelat** [comment]
UPDATE:
Changed the order, to respect the user override `requestContentType`

**Comment by bodnia** [comment]
@ponelat when we  do not have any content and (`body`/`form`) we should add a content-type for thing that we do not pass, is this correct?

**Comment by ponelat** [comment]
you're right.
If the user _does_ feel like overriding this, they should use an explicit header. `requestContentType` does only make sense for when the client has a body.

**Comment by bodnia** [comment]
fixed https://github.com/swagger-api/swagger-js/pull/1016
